- lib/mayaUsd/ufe/StagesSubject.cpp
* Added special case for "Active" metadata sending Ufe notif.
> MAYA-121600 - Refresh issue with deactivation of USD Prims

- plugin/al/plugin/AL_USDMayaTestPlugin/py/testCommands.py
- plugin/al/plugin/AL_USDMayaTestPlugin/test_data/cube_displayColor.usda
- plugin/al/usdmayautils/AL/usdmaya/utils/MeshUtils.cpp
This is a fix for a crash occurring in case a varying `displayColor` and a constant `displayOpacity` was authored.
The code assumed that `displayColor` and `displayOpacity` would have arrays of equal sizes. Furthermore it was asserting the size of these arrays way too late (and asserting wasn't the best option anyway).
I've enforced the check earlier and added the possibility to combine a constant opacity primvar.
As it stands, with this change, the export of a prim with varying `displayColor` and constant `displayOpacity` will result in a varying `displayOpacity` primvars if the `compaction` wasn't enabled during export.
> Varying display colour bug

- lib/mayaUsd/commands/Readme.md
- plugin/pxr/doc/README.md
- test/lib/usd/plugin/CMakeLists.txt
- test/lib/usd/plugin/plugInfoSiteSpecificConfig.json
- test/lib/usd/translators/CMakeLists.txt
- test/lib/usd/translators/testUsdImportExportSiteSpecificConfig.py
> MAYA-114977 Updated documentation + unit test

- lib/mayaUsd/render/vp2RenderDelegate/draw_item.h
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateSelection.py
If we discover they haven't changed then don't set the values into Maya.
> MAYA-121303 Setting the instance colors or transforms into Maya is expensive. 

- lib/mayaUsd/commands/PullPushCommands.cpp
- lib/mayaUsd/commands/PullPushCommands.h
- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/python/wrapPrimUpdaterManager.cpp
- lib/mayaUsd/undo/OpUndoItems.cpp
- lib/mayaUsd/undo/OpUndoItems.h
- test/lib/mayaUsd/fileio/testDiscardEdits.py
- test/lib/mayaUsd/fileio/testEditAsMaya.py
- test/lib/mayaUsd/fileio/testMergeToUsd.py
On edit as Maya, Maya object is selected.  On merge to USD, USD prim is selected.  On discard edits, USD prim is selected.  All implementations correctly support undo / redo.
> Proper selection for edit as Maya, merge to USD, and discard Maya edits.

- lib/mayaUsd/resources/scripts/cacheToUsd.py
- lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
- lib/mayaUsd/resources/scripts/mayaUsdOptions.py
- test/lib/mayaUsd/fileio/testCacheToUsd.py
- Add convertOptionsTextToDict function.
- Save and load the cache-to-USD options from an option var.
- Make the menu options values separate from the localized labels.
- Fill the cache-to-USD UI from the saved options.
> MAYA-121545 persist cache-to-USD options

- lib/mayaUsd/resources/scripts/CMakeLists.txt
- lib/mayaUsd/resources/scripts/mayaUsdMergeToUsd.py
- lib/mayaUsd/resources/scripts/mayaUsdUtils.py
- plugin/adsk/scripts/mayaUSDRegisterStrings.mel
- plugin/adsk/scripts/mayaUsdMenu.mel
- Refactor code to detect if a pulled path is a maya reference.
- Use refactored code to detect maya reference when building the menu.
- Use different label for Maya reference when discarding edits.
> MAYA-121814 change label to cancel maya ref edit

- lib/mayaUsd/ufe/UsdUndoDuplicateCommand.cpp
- lib/mayaUsd/ufe/UsdUndoInsertChildCommand.cpp
- lib/mayaUsd/ufe/UsdUndoRenameCommand.cpp
- lib/mayaUsd/utils/CMakeLists.txt
- lib/mayaUsd/utils/loadRules.cpp
- lib/mayaUsd/utils/loadRules.h
- test/lib/ufe/testGroupCmd.py
- test/lib/ufe/testRename.py
Added code to preserve the loaded or unloaded state of a prim when grouped, reparented or renamed. Note that we don't remove the old rules when duplicating since the source prim still exists.
- Refactor the existing load-state preservation code in reusable functions.
- Use them in the duplicate, rename, and reparenting commands.
- Add unit tests for grouping and renaming, which also covers parenting since grouping reparents.
> MAYA-114593 preserve load state of prims

- lib/mayaUsd/undo/OpUndoItems.cpp
- lib/mayaUsd/undo/OpUndoItems.h
Minor simplification to avoid going through a string representation of an MDagPath for undo / redo purposes.  MDagPath is robust in the face of node delete and reparent, so is appropriate to use for undo / redo.
> Use MDagPath in lock undo item.

- lib/mayaUsd/render/vp2RenderDelegate/draw_item.h
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.h
new topology to the old. Only do the topology updates if the old and new typologies are different. Save the adjacency calculation used to compute normals.
> MAYA-113944 If USD reports that the topology is dirty compare the

- lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
- lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
* Two small renaming.
* Collapse some sections by default (only for cache).
* enable/disable based on radio button selection.
> MAYA-121837: Maya Reference: Clean up 'Cache to USD' UI options

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
As per title, if prim visibility changed, invalidate the bbox cache so that the bbox on screen can be kept up to date.
> [al] Fixed a bug where bbox did not recalculate if prims visibilities changed

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- lib/mayaUsd/render/vp2RenderDelegate/material.h
and uvScaleOffset and re-used correctly when hitting a texture in the cache.
> MAYA-121882 Share the cached HdVP2TextureInfo between all materials so that isSRGB

- lib/mayaUsd/commands/PullPushCommands.cpp
- lib/mayaUsd/fileio/jobs/jobArgs.cpp
- lib/mayaUsd/fileio/jobs/jobArgs.h
- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/python/wrapPrimUpdaterManager.cpp
- lib/mayaUsd/python/wrapUtil.cpp
- lib/mayaUsd/resources/scripts/cacheToUsd.py
- lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
- lib/mayaUsd/resources/scripts/mayaUsdMergeToUSDOptions.py
- lib/mayaUsd/resources/scripts/mayaUsdOptions.py
- lib/mayaUsd/utils/util.cpp
- plugin/adsk/plugin/exportTranslator.cpp
- plugin/adsk/scripts/mayaUsdMenu.mel
- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
- plugin/pxr/maya/lib/usdMaya/exportTranslator.cpp
- test/lib/mayaUsd/fileio/CMakeLists.txt
- test/lib/mayaUsd/fileio/testCustomRig.py
- test/lib/mayaUsd/fileio/testMayaUsdOptions.py
- Add animation, startTime, endTime, frameStride and frameSample to the users args dictionary.
- This allows passing these user options to merge-to-USD and cache-to-USD.
- Split translating text-format to a dictionary from extracting the time sample range.
- This allows passing only a dictionary for all user options instead of having additional separate options for the time samples.
- Adapt users of JobArgs to use the new pure-dictionary internal API.
- In particular, mergeToUsd and duplicate now use these dictionary options.
- Add animation data check-box in cache-to-USD options UI.
- Add animation data check-box in merge-to-USD options UI.
- Improve the text to dict conversion in Python to respect the historical format for options containing list of items.
- In particular, some use …
>  MAYA-121626 Automatically set the animation option

- lib/mayaUsd/resources/scripts/mayaUsdAddMayaReference.py
- lib/mayaUsd/ufe/UsdUndoRenameCommand.cpp
- test/lib/ufe/testRename.py
MAYA-121937 - Renaming 2 usd items with illegal characters will cause Maya to crash
* Validate the name before making it unique.
> MAYA-121937 - Renaming 2 prims w/illegal chars will crash Maya

- lib/mayaUsd/resources/scripts/cacheToUsd.py
- plugin/adsk/scripts/mayaUSDRegisterStrings.mel
- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
- test/lib/usd/translators/testUsdExportNurbsCurve.py
Using the existing filtering mechanism.
> MAYA-121808 Add curve filtering option in UI

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/ufe/Utils.cpp
- lib/mayaUsd/ufe/Utils.h
- test/lib/mayaUsd/fileio/testDuplicateAs.py
- Add isMayaRootPath helper function.
- Use the destination path when duplicating as Maya.
- Add a unit test.
> MAYA-122014 support duplicate to Maya to non root

- lib/usd/ui/layerEditor/mayaSessionState.cpp
- lib/usd/ui/layerEditor/mayaSessionState.h
- Extract the path of the node immediately instead of doing it later on idle.
- In some scenarios, the object is no longer valid on idle.
> MAYA-122122 void crash when editing as maya

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/fileio/translators/translatorMayaReference.cpp
- lib/mayaUsd/fileio/translators/translatorUtil.cpp
- lib/mayaUsd/fileio/translators/translatorUtil.h
- lib/mayaUsd/python/CMakeLists.txt
- lib/mayaUsd/python/module.cpp
- lib/mayaUsd/python/wrapTranslatorUtil.cpp
- lib/mayaUsd/undo/OpUndoItems.h
- lib/mayaUsd/utils/editRouter.cpp
- lib/usd/translators/mayaReferenceReader.cpp
- lib/usd/translators/mayaReferenceUpdater.cpp
- lib/usd/translators/mayaReferenceUpdater.h
- test/lib/mayaUsd/fileio/testCacheToUsd.py
- test/lib/mayaUsd/fileio/testCustomRig.py
Design wants all attributes except transform attributes to be locked on the Maya transform node stand-in which is created for the Maya reference prim on pull.  There might be other attributes that we will decide we don't want to lock, so this may evolve after we gain experience.
> Locked attributes on Maya reference prim transform stand-in.

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/resources/scripts/mayaUsdUtils.py
When a Maya ref is under a xofrm and that xform is edited-as-maya, show the proper menu for the maya ref and handle the cancel-edit correctly.
- Detect the Maya ref for the context menu using the USD_typeName.
- Refactor the code that use the USD_typeName attribute in the prim update manager.
- Use the new common code in merge-to-USD, edit-as-Maya, discard edits and orphaned edits.
> MAYA-121877 cancel edit on maya ref under an xform

- lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.cpp
Fixes up some test failures after removing GL from HdxPickTask
> Add glBindVertexArray to UsdMayaGLBatchRenderer::_TestIntersection.

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_TransformMatrix.cpp
This PR changed the floating point comparison to be GfIsClose() with float type epsilon (1e-7), this is good enough to judge the floating point difference, otherwise AL_USDMaya might write out redundant xformOps thus dirty the edit layer, then could cause the stage recomposing and viewport redrawing unnecessarily.
> [al] Reduce floating point comparison precision to avoid making edit layer dirty

- lib/mayaUsd/listeners/notice.cpp
- lib/mayaUsd/nodes/CMakeLists.txt
- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/nodes/proxyShapeLoadRules.cpp
- lib/mayaUsd/nodes/proxyShapeLoadRules.h
- lib/mayaUsd/nodes/proxyShapePlugin.cpp
- lib/mayaUsd/utils/CMakeLists.txt
- lib/mayaUsd/utils/loadRules.h
- lib/mayaUsd/utils/loadRulesAttribute.cpp
- lib/mayaUsd/utils/loadRulesText.cpp
- test/lib/mayaUsd/utils/CMakeLists.txt
- test/lib/mayaUsd/utils/main.cpp
- test/lib/mayaUsd/utils/testLoadRules.cpp
Load rules conversions
- Add functions to convert the USD stage load rules into text and back.
- Add function to save/load load rules on a dynamic Maya attribute.
- Add unit tests for the text conversions.
- Only run load rules unit test on Windows.
- Other platforms have linker or run-time link problems with Cg and OpenMaya.
Load rules persistence
- Add a class to handle the persistence.
- It keeps a list of proxy shape that need to be updated before being saved
- Listen to kBeforeSave Maya message and transfers the load rules to the proxy stage.
- Each proxy shape registers with this class.
- The proxy shape applies the persisted load rules on load if present.
- Implemented the persistence using dynamic attributes.
- Since there won't be a ton of them, use MEL as it is more robust and …
> MAYA-114603 persist USD payload state

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- Fixed a bug where a folded constant was mistook for a renamed variable
- Fixed a bug where constant nodes had incorrect input name
- Cleaned up unnecessary MaterialX data copied by addInputFromNodeDef
> Fix MaterialX not working with AMD material lib

- lib/mayaUsd/ufe/Utils.cpp
The function used to try to convert a UFE path to a USD prim prints assertion when the path is not to a USD prim. Caller need to check if the prim is valid anyway, so don't cause spurious, unconditional errors to get printed.
> MAYA-122124 avoid errors in marking menu

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
Changes for this PR:
- Mark geometry dirty explicitly otherwise bbox won't move
- Fix GetOutputTime() to return the correct time code
> [al] Mark outTime attribute dirty to force updating Maya bbox; fix incorrect time code for bbox

- lib/usd/hdMaya/adapters/spotLightAdapter.cpp
If I understand correctly starting with Pixar USD 21.05 we should use UsdLuxTokens for spot light parameters instead of HdLightTokes
From 21.05 release notes:
"UsdLux Shadow and Shaping APIs are now connectable. All attributes on these APIs have been given the "inputs:" prefix."
In our "hdRPR" render delegate we use these "inputs" prefixes but it does not work with MtoH without such fixes.
> Use USDLuxTokens for spot light

- lib/mayaUsd/utils/loadRulesAttribute.cpp
Use the correct mel command to querythe existence of an attribute. The new code avoids errors being printed in teh MEL console when the attribute does not exists.
> MAYA-114603 use correct way to query attribute

- plugin/pxr/maya/lib/usdMaya/AEpxrUsdReferenceAssemblyTemplate.py
The AETemplate for the pxrUsdReferenceAssembly node is not built due to syntax errors in maya 2022 and above
> Fix for attribute editor in 2022 due to changes to callcustom in editorTemplate

- lib/mayaUsd/render/MaterialXGenOgsXml/CMakeLists.txt
- lib/mayaUsd/render/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
- lib/mayaUsd/render/MaterialXGenOgsXml/GlslFragmentGenerator.h
- lib/mayaUsd/render/MaterialXGenOgsXml/OgsFragment.cpp
- lib/mayaUsd/render/MaterialXGenOgsXml/OgsFragment.h
- lib/mayaUsd/render/MaterialXGenOgsXml/OgsXmlGenerator.cpp
- lib/mayaUsd/render/MaterialXGenOgsXml/libraries/mx_lighting_maya_none.glsl
- lib/mayaUsd/render/MaterialXGenOgsXml/libraries/mx_lighting_maya_v3.glsl
- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
MaterialX has multiple options for specular environment sampling. They
will be exposed as optionVars.
string MxMayaEnvironmentMethod (none, prefiltered, fis)
- Defaults to fis in V3, prefiltered otherwise
int MxMayaEnvironmentSamples (any reasonable value, default 64)
- only valid in FIS mode
string MxMayaEnvironmentAlbedoMethod (analytic, montecarlo)
- only valid in FIS mode
> Adds optionVars for controlling specular lighting options

- CMakeLists.txt
- cmake/compiler_config.cmake
- plugin/al/plugin/AL_USDMayaTestPlugin/py/testTranslators.py
- plugin/al/tutorials/endToEndMaya/tutorial_scripts/add_set_to_s00.py
- plugin/al/tutorials/endToEndMaya/tutorial_scripts/prep_anim_shot_s00_01.py
+ Change a few compiler flags to be at par with Maya
+ Fix some easy Python 3 issues.
> MAYA-122250 UFE 3 build as Universal Binary 2 (x86_64 + arm64)

- lib/mayaUsd/ufe/UsdUIInfoHandler.cpp
- lib/mayaUsd/ufe/UsdUIInfoHandler.h
Fix a crash that happened when a prim was deactivated in the outliner while the MEL console was docked and MEl history options "show all commands" was on. It was due to recursive paint event corrupting the Qt internal paint engine.
> MAYA-122640 fix crash with deactivate and console

- lib/usd/utils/MergePrims.cpp
- test/lib/mayaUsd/fileio/testMergeToUsd.py
- test/testUtils/usdUtils.py
When targeting a higher layer than where a prim is defined, the merge would fail to create the proper USD hierarchy. That was due to SdfCopySpec not creating automatically the missing parents.
> MAYA-122369 fix missing edit after merge

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- test/lib/mayaUsd/fileio/testEditAsMaya.py
Make can-edit-as-Maya return false if the prim is already edited or an ancestor of an edited prim.
> MAYA-121938 prevent recursive edit as Maya

- plugin/al/plugin/AL_USDMayaTestPlugin/test_translators_CameraTranslator.cpp
- plugin/al/translators/Camera.cpp
Set readAnimatedValues attribute True on Camera translator import
> Enable readAnimatedValues attribute on Camera translator import

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
Proper script call to fetch polymesh active color for Maya 2022 and below
> MAYA-121599 - Active Selection Highlighting color doesn't work in Maya 2022 with USD

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.h
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/points.cpp
GetRenderTag is a function defined in HdRprim, but the callsite has been
moved from classes derived from HdRprim to a different parent class.
Pass the render tag into the _SyncSharedData from the HdRprim derived
classes to fix the build
> Fix build for USD versions past 21.11

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
This PR removes the events registered in service of non-UFE proxy shape callbacks for refresh stages and pre/post selection from `MayaUsdProxyShapeBase` and `Ufe::Global`. As suggested in PR [`Autodesk/maya-usd#1855`](https://github.com/Autodesk/maya-usd/pull/1855), these were no longer be required and are superseded by UFE observability.
> Removed proxy shape pre/post selection events notification

- lib/mayaUsd/resources/scripts/mayaUsdAddMayaReference.mel
- lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
- lib/mayaUsd/utils/editRouter.cpp
Also fixes MAYA-122127 and MAYA-122135: remove tooltip from Deinf In and makre vairiant the default when creating a ref when Maya prefs are empty.
> MAYA-122123 make Define In options enabled

- lib/mayaUsd/ufe/ProxyShapeHierarchy.cpp
- lib/mayaUsd/ufe/ProxyShapeHierarchy.h
- lib/mayaUsd/ufe/PulledObjectHierarchy.cpp
- lib/mayaUsd/ufe/PulledObjectHierarchy.h
- lib/mayaUsd/ufe/UsdHierarchy.cpp
- lib/mayaUsd/ufe/UsdHierarchy.h
- test/lib/ufe/testChildFilter.py
- test/lib/ufe/testContextOps.py
- test/testUtils/ufeUtils.py
Some code paths were ignoring deactivated children when they should not because hasChildren() was ignoring deactivated children.
> MAYA-122218 showing dactivated children

- lib/mayaUsd/resources/scripts/mayaUsdOptions.py
The defaults were not parsed properly when a list with a single item was given as teh default as it could not determine if it was a text or floating-point values.
> MAYA-122128 NURBS defaut to off when caching

- lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.mel
- lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
- lib/mayaUsd/utils/editRouter.cpp
- Disable the Binary/ASCII drop-down when the file format only supports one type.
- Properly enforce the selected type otherwise.
> MAYA-122361 enforce cache file format

- lib/mayaUsd/ufe/UsdTransform3dSetObjectMatrix.cpp
- lib/mayaUsd/ufe/UsdTransform3dSetObjectMatrix.h
- test/lib/ufe/testRotatePivot.py
Setting the rotate or scale pivot on a prim with a matrix (a.k.a. transform) transform op immediately creates a Maya fallback matrix stack, because pivot values are not supported by the single matrix data model.  When this occurs, a UsdTransform3dSetObjectMatrix wrapper Ufe::Transform3d interface is created to wrap the Maya fallback matrix stack.  This wrapper did not forward the pivot accessors to the wrapped Maya fallback stack, now fixed.
> Implement pivot accessors for wrapped matrix ops.

- plugin/al/usdmayautils/AL/usdmaya/utils/DgNodeHelper.cpp
- plugin/al/usdmayautils/AL/usdmaya/utils/DgNodeHelper.h
We have the function `DgNodeHelper::setFloatAttrAnim`() for float type attributes but missing similar functions for `int` and `bool` types, this PR is for that case.
> [al] Added support for importing animated bool and int type attributes

- plugin/al/mayautils/AL/maya/utils/PluginTranslatorOptions.cpp
- plugin/al/mayautils/AL/maya/utils/PluginTranslatorOptions.h
- plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/test_DiffPrimVar.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/test_translators_MeshTranslator.cpp
- plugin/al/translators/CommonTranslatorOptions.cpp
- plugin/al/translators/CommonTranslatorOptions.h
- plugin/al/translators/Mesh.cpp
- plugin/al/usdmayautils/AL/usdmaya/utils/DiffPrimVar.cpp
- plugin/al/usdmayautils/AL/usdmaya/utils/DiffPrimVar.h
- plugin/al/usdmayautils/AL/usdmaya/utils/MeshUtils.cpp
- plugin/al/usdmayautils/AL/usdmaya/utils/MeshUtils.h
This PR mainly contains two features for exporting:
- Default RGBA value (RGB = 0.18, A =1.0) so that the value is always meaningful
- Optionally accept color "threshold", the UI is also extended to support custom precision to allow displaying high precision of floating point numbers, defaults to 1e-5 which should be enough for color.
> [al] Add support for default rgba values and color threshold for exporting

- lib/usd/hdMaya/delegates/sceneDelegate.cpp
Adding a check into M2H scene delegate to not translate DAG nodes coming from UFE/USD runtime. This avoids object duplication as those objects are already hadled by USD Imaging delegate
> MAYA-123100 - Suppress UFE-proxy lights in Maya Scene Delegate to avoid lights duplication

- lib/mayaUsd/ufe/CMakeLists.txt
- lib/mayaUsd/ufe/UsdShaderAttributeDef.cpp
- lib/mayaUsd/ufe/UsdShaderAttributeDef.h
- lib/mayaUsd/ufe/UsdShaderNodeDef.cpp
- lib/mayaUsd/ufe/UsdShaderNodeDef.h
- lib/mayaUsd/ufe/UsdShaderNodeDefHandler.cpp
- lib/mayaUsd/ufe/UsdUndoCreateFromNodeDefCommand.cpp
- lib/mayaUsd/ufe/UsdUndoCreateFromNodeDefCommand.h
- test/lib/ufe/testContextOps.py
- test/lib/ufe/testShaderNodeDef.py
Ufe 0.4.8 has multiple changes to improve NodeDef discovery:
NodeDef:
- Expose read-only interface to query node classifications (allows
sorting them in a node picker)
- Expose read-only metadata API (limited to known USD metadata tags at
the moment)
- Remove internally kept data. Everything is built on-the-fly from the
SdrShaderNode information
- Expanded the port API to allow name discovery and single port queries
AttributeDef:
- The base class in Ufe is now a full interface. Added an implementation
for USD that returns the information directly from the associated
SdrShaderProperty
- Expose read-only metadata API (limited to known USD tags at the
moment)
> Ufe 0.4.8: Add classifications and metadata to def

- lib/usd/translators/nurbsCurveWriter.cpp
- test/lib/usd/translators/testUsdExportNurbsCurve.py
This PR aims to continue the alignment between the AL and ADSK plugins' export functionality, updating the ADSK plugin's NURBS curve export of `knots` to avoid adding extra knots in non-wrapping curves (i.e. do not copy the first and last knots in the exported vector). The PR also adds a simple implementation for the `widths` attribute as lifted from the AL plugin's NURBS curve export translator in favour of just authoring a constant `widths` vector of `[1]`.
> Updated NURBS curve export for widths and knots attributes

- lib/mayaUsd/render/mayaToHydra/plugin.cpp
- lib/mayaUsd/render/mayaToHydra/renderOverride.cpp
- lib/mayaUsd/ufe/Utils.cpp
Some resources used by the Hydra renderer are cached in the Hydra engine task context. The shutdown of the Maya-to-Hydra render override destroyed many Hydra-related objects, but the Hydra engine itself is kept by value and is never destroyed. We ended-up having data in teh task context that still referred to deleted objects and that led to a crsh if the Hydra render override was initialized and used again.
Arguably, the bug is in Hydra itself, where the texture handles (HdStTextureHandle) keep a raw pointer to the texture registry (HdSt_TextureHandleRegistry) instead of a smart pointer. That raw pointer is taken from the HdRenderIndex, which does keep its pointer to the registry as a shared_ptr.
OTOH, semi-shutting-down Hydra like our render override does is probably not correct. These …
> MAYA-122541 fix hydra crash with skydome

- lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
MAYA-122923 - cache to USD dialog: description text causes big empty space to appear below the options
* Made the Description frame non-collapsable (to follow standard in Maya).
* Added logic to collapse sections which fixes the blank space at bottom.
> MAYA-122923 - Cache to USD dialog: empty space below options

- lib/mayaUsd/resources/scripts/mayaUsdMergeToUSDOptions.py
* Made window/form/scroll layout changes to make it similar to a normal Maya option box with the same size/spacing.
> MAYA-122928 - merge to USD dialog window height - cannot scroll down

- lib/mayaUsd/nodes/layerManager.cpp
- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/utils/utilSerialization.cpp
- lib/mayaUsd/utils/utilSerialization.h
- lib/usd/translators/mayaReferenceUpdater.cpp
- lib/usd/ui/layerEditor/layerTreeItem.cpp
- lib/usd/ui/layerEditor/pathChecker.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/cmds/LayerCommands.cpp
When re-saving a modified layer, follow the current ASCII / Binary format selected in the layer editor.
Notes:
- USD SdfLayer does not have a Save() function taking the desired format. The only option we have is to use Export().
- The choice of binary / ASCII is in a sub-menu and is global to all layers and all stages. That may not be convenient for the user: changing it will affect all stages and all layers. Beware!
> MAYA-123013 obey file-format choice in layer editor

- plugin/al/lib/AL_USDMaya/AL/usdmaya/cmds/ProxyShapeCommands.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorContext.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorContext.h
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.h
- plugin/al/plugin/AL_USDMayaTestPlugin/py/testTranslators.py
- plugin/al/plugin/AL_USDMayaTestPlugin/test_data/resync_root.usda
- plugin/al/plugin/AL_USDMayaTestPlugin/test_data/resync_sublayer.usda
USD hierarchy might become invalid after resync (managed by translators that are not in AL_USDMaya's scope), this PR fixed the issue that irrelevant translators were removed on resync, if the registered prim is not a child of requested resync path, keep the translator and do nothing (leaving it handled by its own translator).
> [al] Fixed issue that resync prim would cause irrelevant translators being removed

- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TransformTranslator.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/test_translators_TransformTranslator.cpp
This PR is a follow up of https://github.com/Autodesk/maya-usd/pull/2218 which:
- Fixed the computation of local transformation matrix (Maya is post-multiplied)
- Added verification in unit test to check if the exported matrix can match Maya
> [al] Fixed incorrect computing local transformation matrix when exporting to USD

- lib/mayaUsd/ufe/StagesSubject.cpp
Exception can be thrown by the notified objects or function. Do not let it out as it will crash Maya as nothing else above catches the exceptions.
> MAYA-123016 catch exceptions during notifications

- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/ufe/UsdLight.h
- lib/mayaUsd/ufe/UsdObject3d.cpp
- lib/mayaUsd/utils/util.cpp
- lib/mayaUsd/utils/util.h
Add Maya-specific camera extents to the USD UFE bounding box calculation
> MAYA-122146 - Selecting a camera and framing it with "f" shows the origin instead of the camera

- lib/mayaUsd/fileio/primUpdaterManager.cpp
When locking nodes, it also locks topological modifications. Explicitly re-enable it afterward.
> MAYA-123332 allow topological modifications

- lib/mayaUsd/utils/stageCache.cpp
When a prim is shown in the outliner and  the outliner gets collapsed, then the outliner still keeps the reference to the prim. But because it is collapsed it does not update when the selection changes. On the other hand, stages only go away when a new Maya scene is created since they are cached. Also, UFE notifications are based on UFE paths.
So if a USD file was staged, a prim selected and shown in the AE, then the AE gets collapsed, then a new Maya scene gets created and the same USD file is staged, then selecting the same prim and modifying (say, translating it), it would send a UFE notification with the same UFE path, but the prim in the AE is the prim in the old stage that no longer exists.
We now reset the outliner when clearing the stage cache for this reason.
> MAYA-123016 stage clear now resets the outliner

- lib/mayaUsd/commands/PullPushCommands.cpp
- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/undo/OpUndoItems.cpp
- lib/mayaUsd/undo/OpUndoItems.h
The undoable execution items were not returning the success/failure status from the convenience static execute function, preventing the validation of correct execution.
Fix this by making the execute function of PythonUndoItem and FunctionUndoItem return a boolean success flag, received from the redo function. Use this flag during pull and pull to validate that key steps executed correctly.
In our case, the authoring of metadata on an instance prototype is forbidden by USD and was failing, but that fact was lost. So no pull information was written, which entirely broke the pull/push workflow.
Many other convenience functions of undo items (select and lock) were not returning errors. Now they return a success flag and callers verify it.
> MAYA-123419 add execution validation during pull/push

- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/nodes/proxyShapeBase.h
- plugin/pxr/maya/lib/usdMaya/proxyShape.cpp
Allow derived classes to opt out of authoring loadRules attributes on
proxyShapes in order to prevent clutter within Pixar Usd Reference
Assemblies.
> Don't author the loadRules attribute for Pxr reference assemblies

- lib/mayaUsd/ufe/UsdShaderNodeDefHandler.cpp
Using GetShaderNodeByIdentifier resolves issues where there is more than
one node sharing the same name with two different versions.
See Pixar Issue #1873 about version parsing failure in usdMtlx.
> Fix issues between two versions of standard_surface

- lib/mayaUsd/nodes/proxyShapeBase.cpp
We were running into null pointer crashes when trying to load invalid
stages. This was hit internally when dealing with Usd Scene Assemblies -
I'm unsure if this is a problem in a pure UFE environment
> Guard against a NULL Usd Stage when rendering

- test/lib/ufe/CMakeLists.txt
- test/lib/ufe/testPixelMoveCmd.py
- test/testUtils/mayaUtils.py
This change tests the new UFE support in the pixelMove command.  This addresses
https://github.com/Autodesk/maya-usd/issues/2234
> Test pixelMove UFE support.

- lib/mayaUsd/fileio/jobs/readJob.cpp
- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/nodes/proxyShapeBase.h
- lib/mayaUsd/nodes/stageNode.cpp
- lib/mayaUsd/python/wrapStageCache.cpp
- lib/mayaUsd/utils/stageCache.cpp
- lib/mayaUsd/utils/stageCache.h
- plugin/pxr/maya/lib/usdMaya/referenceAssembly.cpp
- plugin/pxr/maya/lib/usdMaya/translatorModelAssembly.cpp
- test/lib/mayaUsd/nodes/testProxyShapeBase.py
- test/lib/testMayaUsdPythonImport.py
- Add two new stage caches for unshared stages.
- These are necessary to be able to find unshared stages when toggling between shared and unshared.
- Do *not* pass an explicit sesssion layer when opening a stage unless unshared stage is explicitly desired.
- That is because the cache takes into consideration the session layer if given as an argument, which would unshare layers unintetionally.
- In particular, choosing to target the session layer (which is UI consideration) would indirectly make the stage unshared.
- Properly reload unshare stage and toggle between shared and unshared stage by transferring the content of the session layer.
- Clarify with comments the design and behaviour of the stage proxy shape.
- Adapted AL code to conform to the new API.
- Add unit test for session …
> MAYA-123361 fix unshared stage toggling and loading

- lib/mayaUsd/fileio/jobs/readJob.cpp
- lib/mayaUsd/fileio/jobs/writeJob.cpp
- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/fileio/shading/shadingModeExporter.cpp
- lib/mayaUsd/utils/CMakeLists.txt
- lib/mayaUsd/utils/progressBarScope.cpp
- lib/mayaUsd/utils/progressBarScope.h
- plugin/adsk/plugin/exportTranslator.cpp
- plugin/adsk/plugin/importTranslator.cpp
- plugin/adsk/scripts/mayaUSDRegisterStrings.mel
* New progress bar utility file with classes: ProgressBarScope/ProgressBarLoopScope.
* Use these new classes in read/write job import/export translator, prim updater manager and shadingModeExporter to display a progress bar for the various workflows.
* Track the number of steps advanced and output message if it doesn't equal number set.
* Added env var "MAYAUSD_ENABLE_PROGRESSBAR" (default true) which can be used to disable progress bar display.
> MAYA-114724/MAYA-114039 - Progress bar for import/export/push/pull

- test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegatePerInstanceInheritedData.py
- test/testUtils/mtohUtils.py
to match the default values in Maya 2023 so we don't have to update images.
> MAYA-122511 Set the color and specular roughness on the default standard surface 

- lib/mayaUsd/fileio/shaderWriterRegistry.cpp
- lib/mayaUsd/fileio/shading/shadingModeRegistry.cpp
- lib/mayaUsd/fileio/shading/shadingModeRegistry.h
- lib/mayaUsd/fileio/shading/shadingModeUseRegistry.cpp
Currently, there is no way to register a shader writer that handles all
connected plugs to the shader. For example, the writer might handle file
nodes connected to the shader, but useRegistry shading mode will invoke
FileTextureWriter unconditionally. It will write out a UsdUVTexture
shader, which useRegistry won't be able to connect to the shading network.
> Respect prim writer ShouldPruneChildren when shading mode is useRegistry

- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/nodes/proxyShapeBase.h
- test/lib/mayaUsd/nodes/testProxyShapeBase.py
When the proxy stage is recompute with an unsaved root layer, the attribute keeping the root layer name would be empty. A new root layer would be created each time, losing any previous content.
This attribute only gets set once the stage gets saved.
Fix this by re-using the same anonymous root layer when the stage has not been saved yet.
Also, as a bonus, this fix change teh code so that the same code path for newly created stage is used, which means that if the user ahas set the option var to target the session layer, it will also be honored for newly-created stages. It will also re-use any pre-existing stage, so we also avoid creating stages repeatedly for the same unsaved proxy stage node every time an attribute get sets.
> MAYA-114376 preserve unsaved root layer

- lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
UI element fixes to read the "Prepend/Append" menu correctly.
> MAYA-123877 Prepend reference/payload doesn't work in Caching Maya Ref

- lib/mayaUsd/resources/scripts/mayaUsdDuplicateAsMayaDataOptions.py
- lib/mayaUsd/resources/scripts/mayaUsdMergeToUSDOptions.py
Make sure the default options contain all the possible options so that when using the defaults to reset options, all options get reset.
> MAYA-123903 reset all merge and duplicate options

- test/lib/mayaUsd/fileio/testComponentTags.py
- test/lib/usd/translators/testUsdExportUVSetMappings.py
- test/lib/usd/translators/testUsdExportUVSets.py
Provide explicit values for export options in open source tests even if
they match defaults. This allows tests to pass in environments which
run with site-specific export option overrides
> Provide explicit export options in tests

- CMakeLists.txt
CMAKE_OSX_DEPLOYMENT_TARGET set as in Maya, 11.0 for UB2 otherwise10.14
> MAYA-124244 MacOS: mayausd doesn't load on older Mac systems. (10.15.7)

- lib/mayaUsd/fileio/shading/shadingModeExporter.cpp
If -materialCollectionsPath is empty, an appropriate path is selected
to hold the material bindings. But the control flow ends there, which
looks unintentional.
> Fix handling of empty materialCollectionsPath

- lib/mayaUsd/ufe/UsdShaderNodeDef.cpp
The identifier could be namespaced. Make sure the nodedef type is the
namespaced identifier instead of the non-namespaced "name".
When creating a node, make sure the node name is sanitized, because the namespace separator is an illegal character for USD names.
> Fix discovery and creation of namespaced nodes

- lib/mayaUsd/ufe/UsdAttribute.cpp
- lib/mayaUsd/ufe/UsdAttribute.h
- lib/mayaUsd/ufe/UsdConnectionHandler.cpp
- test/lib/ufe/testConnections.py
- When unauthored attributes get connected, they must become authored.
- When Material outputs are connected, we need to check the render context of the source node and use the right render context
> Fix attribute creation on connect

- lib/mayaUsd/fileio/shading/shadingModeUseRegistry.cpp
- test/lib/mayaUsd/fileio/testDuplicateAs.py
Unchecking all material export options should result in no materials
in the USD file.
> Skip Material export if not conversion was selected

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
Make sure to track display layers that were loaded before the creation of Proxy Render Delegate
> Fixing a visibility update issue when USD data and display layer is saved to Maya file

- lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
Removed the code which disabled this field. Just leave the field enabled all the time.
> MAYA-124458 - When caching to USD, 'Prim Name' is disabled when Define in Variant is selected

- lib/mayaUsd/fileio/translators/translatorRfMLight.cpp
- test/lib/usd/translators/testUsdImportRfMLight.py
Keep translator code in sync with the usdLux schema and args file.
Ideally we wouldn't need to keep these in sync manually, so we're
considering a future change to use Sdr to do this for us.
> Author normalization attribute when exporting RfM Lights

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.h
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/points.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
- Support for display layer's 'template' attribute
- Update render prims on color space change + proper color space conversion for "lead" selection color
- Fixing rendering issues in points
> MAYA-123143 - As a user, I'd like my prims to be templated in a Display Layer

- lib/mayaUsd/utils/editRouter.cpp
- lib/mayaUsd/utils/variants.h
- lib/usd/translators/mayaReferenceUpdater.cpp
- test/lib/mayaUsd/fileio/testCacheToUsd.py
- Need to find and temporarily switch to the variant that contains the Maya Reference.
- Since variant set and variant name are under the user control, we need an explicit search.
- Copy only the transform and properly handle the case of the source and destination not being variants.
Second version added:
- Move the copying of the Maya Reference transform to the edit router.
- Go back to using mergePrim to do the work.
- Properly handle the case teh destination is in a variant.
- Cleanup the edit router code by refactor common code and common code patterns.
- Read all expected context arguments in one go, makes it easeier to understand what argument are expected.
- Move inner lambda function to a separate function for code clarity.
- Avoiding having such a function within a function makes …
> MAYA-124418 copy transform to the correct variant.

- test/lib/mayaUsd/fileio/testDisplayLayerSaveRestore.py
- test/lib/ufe/testDisplayLayer.py
* editDisplayLayerMembers command was made opt-in for Ufe objects.
> MAYA-124484: Display Layers

- lib/mayaUsd/ufe/Utils.cpp
ufePathToPrim would TF_VERIFY when failing to resolve the provided path,
which reports a TF_CODING_ERROR. Since this isn't actually a result of a
coding error, downgrade this to a TF_WARN.
> Use TF_WARN when passed an invalid Path

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- lib/mayaUsd/render/vp2RenderDelegate/material.h
- lib/mayaUsd/render/vp2RenderDelegate/render_delegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/render_delegate.h
This makes sure textures and shaders are freed before VP2 shuts down.
> Flush all resource caches on exit

- lib/mayaUsd/ufe/StagesSubject.cpp
- lib/mayaUsd/ufe/UsdConnectionHandler.cpp
- If we can not find a shader source type, assume the user knows what he
is doing.
- If trying to connect a node graph output to surface, dig into the node
graph in case we find a shader source type by traversing the
connections.
> Improve connecting to surface experience

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
A MaterialX shader graph can be transitively in a bad state while being
edited. Make sure it does not cause a crash is a NodeDef is missing.
> Fix MaterialX conversion crash with invalid graphs

- cmake/gulrak.cmake
This PR fixes issue #2420.
Perhaps @hinton-mgi can test this fix?
Minor note: I am submitting this PR as an individual. I have signed and sent in my Individual CLA form accordingly.
> Fix configuration error when GULRAK_SOURCE_DIR is specified on Windows

- lib/mayaUsd/ufe/MayaUIInfoHandler.cpp
- test/lib/mayaUsd/fileio/CMakeLists.txt
- test/lib/mayaUsd/fileio/testEditAsMaya.py
- test/lib/ufe/testUIInfoHandler.py
* Set icon disabled with Maya object is orphaned.
* Added unit test for tree view cell info and icon in this orphaned case.
> MAYA-123044: As a user, I'd like to see orphaned objects' icons dimmed

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- lib/mayaUsd/render/vp2RenderDelegate/material.h
- lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
Happens when the shader topology changes, and requires a mesh update to push the latest MShaderInstance.
Thanks to William Krick and Huidong Chen for the code. I only needed to enable it for TopoChanged material updates.
> Mark primitives as dirty if the shader has been rebuilt

- lib/usd/translators/shading/usdFileTextureWriter.cpp
This changes the behaviour of the texture prim writer to **always** write the colorSpace attribute, whereas currently they are elided if they match the default.
This is important for us, and other software vendors, who have software that needs to ingest data from a multitude of pipelines with different defaults. This means we currently have to apply heuristics to figure out the default for a given texture, but it would be most ideal to be able to just always write out the intended color space into the file.
I think this would be a beneficial default for Maya USD in general, because even in a film studio, we might share assets between shows that have different OCIO defaults, so it's beneficial to know that information up front as much as possible.
> Always write color space to usd texture prims

- lib/mayaUsd/utils/util.cpp
GetDictionaryFromArgDatabase would error on doubles being passed in, like frameStride etc...
I've added support for doubles and improved the error message to mention which flag is failing. I would also recommend changing it from TF_CODING_ERROR to a warning, but I didn't want to do that for this PR incase it was preferable for it to stay as an error.
> Add support for doubles to GetDictionaryFromArgDatabase

- lib/mayaUsd/ufe/UsdContextOps.cpp
- lib/mayaUsd/ufe/private/Utils.cpp
- test/lib/ufe/testContextOps.py
Also fix a bug in the allow check when dealing with variant: it was refusing even when the allow-stronger-layer flag was on and in a stronger layer.
> MAYA-113642 disallow switching variants in a weaker layer.

- lib/mayaUsd/ufe/Utils.cpp
- test/lib/ufe/testAttributeBlock.py
- test/testSamples/attributeBlock/root.usda
- test/testSamples/attributeBlock/subB.usda
- test/testSamples/attributeBlock/subBRef.usda
- test/testSamples/attributeBlock/subC.usda
- test/testSamples/attributeBlock/subCRef.usda
- test/testSamples/attributeBlock/sublayerOfSubB.usda
This PR is for addressing the issue discussed in here https://github.com/Autodesk/maya-usd/discussions/2212. In short, at Animal Logic, we found `isAttributeEditAllowed` function in UFE a bit confusing and was blocking our pipeline so we updated its logic in our internal code base. This PR is to promote our internal solution.
> Allowing a new prim spec to be written in edit target layers

- lib/mayaUsd/ufe/UsdConnectionHandler.cpp
See https://github.com/PixarAnimationStudios/USD/issues/2013
I do hope to get a better workaround either in the issue comments or on
this USD-interests thread:
https://groups.google.com/g/usd-interest/c/5LZT-IOaOTU/m/XwLzFTq7AgAJ
But, in the meantime, creating a dummy prim under the material is enough to
cause the resync to happen... Feel free to revoke my coding license.
This is ugly.
> Workaround for USD Issue 2013

- CMakeLists.txt
- build.py
- cmake/googletest.cmake
- cmake/googletest_download.txt.in
- cmake/googletest_src.txt.in
- cmake/utils.cmake
* Added support for Microsoft Visual Studio 2019/2022.
* Created helper for general external project settings. Includes OSX UB2 and Linux CXX11_ABI.
> MAYA-124107 - MayaUSD: build as Universal Binary 2 (x86_64 + arm64)

- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeLiveSurface.py
Otherwise, the test failed when run locally. The new method to retrieve the 3D view is more robust.
> Change how the active 3D view is retrieved in the test

- lib/mayaUsd/fileio/jobs/jobArgs.cpp
- lib/mayaUsd/fileio/jobs/jobArgs.h
- lib/mayaUsd/fileio/jobs/readJob.cpp
- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/python/wrapPrimReader.cpp
- test/lib/mayaUsd/fileio/testEditAsMaya.py
- Preserve the timeline start/end and min/max after editing a Maya reference.
- Add a unit test that checks the timeline preservation.
- Corrected two tests that had their named swapped.
> MAYA-124106 preserve timeline during edit-as-Maya

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.h
- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- lib/mayaUsd/render/vp2RenderDelegate/material.h
- lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.h
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.h
- lib/mayaUsd/render/vp2RenderDelegate/points.cpp
- lib/mayaUsd/render/vp2RenderDelegate/points.h
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
- lib/mayaUsd/render/vp2RenderDelegate/tokens.h
- Introducing support for two simultaneous compiled material networks in HdVP2Material: Full and Untextured. Before, only one one network might be compiled at a time.
- Fixing mixed multi-viewport styles, which were broken lately, all the while keeping the optimal performance.
- Adding a separate representation for Untextured draw style with support from meshes, curves and points
- Supporting display layer's "texturing" attribute
> MAYA-123181 - As a user, I'd like my prims to be in untextured mode when in a Display Layer

- lib/usd/ui/layerEditor/mayaSessionState.cpp
- lib/usd/ui/layerEditor/mayaSessionState.h
When a Maya namespace is renamed, we now update the stages proxy shape names that are managed by the layer manager.
> MAYA-125054 - Fix namespace renaming

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.h
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/points.cpp
- lib/mayaUsd/ufe/UsdAttributes.cpp
- properly handle display layer's attribute "enable"
- fixing an issue with bound box dimensions when a display layer is switched to bound box mode in multi-viewport
- fixing an issue with visibility when a display layer is switched into invisible state while in multi-viewport
- fixing an issue with enabling all required material primvars from both networks: full and untextured
> MAYA-125149 - When "Enable Overrides" is unchecked for a Display Layer USD Data still uses Bounding Box

- lib/mayaUsd/resources/scripts/mayaUsdMergeToUSDOptions.py
- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
MAYA-124951: Duplicate as USD Data timeline options don't show what is currently applied
* Do not auto-update the animation start/end to the playback range as it doesn't actually reflect the values used by the options other than export (edit as maya, merge to maya).
> MAYA-124951: Duplicate as USD Data timeline options don't show what is currently applied

- lib/mayaUsd/render/mayaToHydra/utils.cpp
This is a small PR to show the correct render name for MtoH in the UI. This doesn't help mtoh work better on mac yet, but it does help my OCD slightly.
This API exists on USD 20.02 and higher. Hopefully that's fine for the current USD versioning being used for Maya USD
> Show correct render backend name

- plugin/al/schemas/AL/usd/schemas/maya/tests/CMakeLists.txt
- plugin/al/usdtransaction/AL/usd/transaction/tests/CMakeLists.txt
Sorry I didn't catch it earlier but one of the changes in https://github.com/Autodesk/maya-usd/pull/2456 , i.e., linking the boost python's library to the test executables, breaks our builds.
As I'm not across the reason for the removal in the first place, I reintroduce it here so we can discuss the best approach to get builds up and running.
> Broken AL_USDMaya and AL_USDTransaction builds (AL)

- cmake/googletest.cmake
- cmake/googletest_download.txt.in
- cmake/googletest_src.txt.in
* Minor changes to settings used when compiling googletest required for building with gcc 11.
> MAYA-125364 - MayaUsd: Maya master blessing failing (Linux only)

- lib/mayaUsd/fileio/orphanedNodesManager.cpp
- lib/mayaUsd/fileio/orphanedNodesManager.h
- lib/mayaUsd/fileio/primUpdaterManager.cpp
- test/lib/mayaUsd/fileio/CMakeLists.txt
- test/lib/mayaUsd/fileio/testDiscardEdits.py
As per MAYA-123378, discarding edits on an orphaned Maya node whose USD ancestor is unloaded causes an error.
Added a unit test for this case.  Without the fix, the test fails, with the fix, the test succeeds.
> Fix orphaned node discard edits with unloaded ancestor.

- lib/mayaUsd/fileio/orphanedNodesManager.cpp
- lib/mayaUsd/ufe/UsdStageMap.cpp
- test/lib/mayaUsd/fileio/testHideOrphanedNodes.py
When undoing the deletion of an ancestor of a USD prim with variant which had some of its children edited as Maya, we need to validate that the correct set of variant is active before showing the edited Maya data.
Also, when going down the items of the trie that contains the UFE path component, we need to properly handle the points where we cross run-times (currenly there is only Maya and USD). When crossing runtimes, we must create a new segment.
>  MAYA-125101 Correct handling of display list vs variants

- CMakeLists.txt
- cmake/compiler_config.cmake
- cmake/googletest.cmake
- cmake/modules/FindMaya.cmake
- Support for RHEL8 with new ABI. If Maya was built with new ABI then MayaUsd must also be.
- Detect if Maya was built with UB2 and issue warning if MayaUsd is UB2, but Maya is not.
> MAYA-125649 - Build MayaUsd on RHEL8 with new ABI when Maya switches

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/fileio/primUpdaterManager.h
When a USD object is edited as Maya and the Maya scene is saved, if Maya is restarted and teh scene reloaded, the edited USD object cannot be manipulated again. That was due to internal non-saved state not being set properly when restarting Maya.
Avoid the problem by not using non-persistent state.
> MAYA-125867 fix edit-as-Maya on fresh Maya session

- plugin/adsk/scripts/AEmayaUsdProxyShapeBaseTemplate.mel
Inside the AE template of mayaUsdProxyShape, a code segment from the AEdependNodeTemplate function is copied to avoid calling it. Probably to avoid creating Node Behavior layout. This commit adds the line which allows mayaUsdProxyShape to be assigned custom UI via callbacks -hook "AETemplateCustomContent".
> Allow custom UI hooks for mayaUsdProxyShape

- lib/mayaUsd/ufe/wrapUtils.cpp
- test/lib/ufe/testPythonWrappers.py
MAYA-111420 was entered to ensure that getAllStages() would not return stages whose proxy shape was deleted.  This bug was fixed by previous code, so simply added a test to demonstrate the fix, with undo and redo.
> Added test for getAllStages() versus delete.

- lib/mayaUsd/render/mayaToHydra/utils.cpp
We are already using the pxr namespace via the directive in this file, and the explicit namespacing breaks internal builds at Pixar.
> Removing unnecessary explicit 'pxr' namespacing

- lib/mayaUsd/nodes/proxyShapeBase.cpp
- test/lib/mayaUsd/nodes/testProxyShapeBase.py
Currently, we reproduce the FPS (frames-per-second) of the shared root layer to the
newly-created unshared root layer so that the animation playback speed stays consistent.
> MAYA-125895 transfer state from root layer when toggling shareable stage

- lib/mayaUsd/ufe/UsdUndoDuplicateCommand.cpp
- lib/mayaUsd/ufe/Utils.cpp
- lib/mayaUsd/ufe/Utils.h
- test/lib/ufe/testDisplayLayer.py
* Use new MayaUsd::ufe::ReplicateExtrasToUSD helper class to perform dupication of Display Layer (USD -> USD).
* Added unit test.
> MAYA-123716 - Duplicated prim to be on the Display Layer that the source prim was on

- lib/mayaUsd/ufe/UsdContextOps.cpp
- lib/mayaUsd/ufe/UsdSceneItemOps.cpp
- lib/mayaUsd/ufe/UsdSceneItemOps.h
- lib/mayaUsd/ufe/UsdUndoAddNewPrimCommand.cpp
- lib/mayaUsd/ufe/UsdUndoAddNewPrimCommand.h
- lib/mayaUsd/ufe/UsdUndoAttributesCommands.cpp
- lib/mayaUsd/ufe/UsdUndoAttributesCommands.h
- lib/mayaUsd/ufe/UsdUndoInsertChildCommand.cpp
- lib/mayaUsd/ufe/UsdUndoInsertChildCommand.h
Signed-off-by: Patrick Hodoul [Patrick.Hodoul@autodesk.com](mailto:Patrick.Hodoul@autodesk.com)
The pull request improves some existing code to provide an access to commands (without being executed). The aim is to enable command aggregation so the execution can be one single composite command (instead of several undoable commands).
Being in that code area, the pull request also adds extra information to the commands so, the DCC undoable queue can log meaningful information when undoing a command for example. Please refer to the `Ufe` pull request [#302](https://git.autodesk.com/media-and-entertainment/ufe/pull/302).
The pull request implements the `Ufe` pull request [#309](https://git.autodesk.com/media-and-entertainment/ufe/pull/309).
As the changes only consists to slightly refactor …
> LOOKDEVX-606 - Improve undo/redo capabilities

- lib/mayaUsd/fileio/transformWriter.cpp
- lib/mayaUsd/fileio/transformWriter.h
- test/lib/mayaUsd/fileio/testCacheToUsd.py
- test/testSamples/rhino_rig/anim_001.ma
When a complex rig controls geometry, it is possible that the USD exporter will author a given transform operation (for example, translate) multiple times on a single USD trasformable geometry. The old exporter code would try to create the same USD transform operation, which would fail. Instead, we now detect that a transform operation already has an instance and create new ones with a suffix for each extra duplicate op.
A limit of 1000 instances of a given transform op has been set. It seems unlikely that any single geometry will have more than 1000 direct operations applied to it at the same times. (This number does not count indirect transform from parents.)
> MAYA-125897 support duplicate xform ops

- lib/mayaUsd/nodes/proxyShapeBase.cpp
- test/lib/mayaUsd/nodes/testProxyShapeBase.py
Tramsfer the timecodes-per-second when flipping shared flag on a stage.
> MAYA-125895 Handle timecodes-per-second when flipping shared state

- lib/mayaUsd/commands/baseImportCommand.cpp
- lib/mayaUsd/commands/baseImportCommand.h
- test/lib/usd/translators/UsdImportSessionLayerTest/Cubes.usda
- test/lib/usd/translators/testUsdImportSessionLayer.py
- Add a new -primVariant (-pv) flag to the mayaUSDimport command.
- Takes three argument: prim path, variant name, variant selection.
- Can be repeated.
- Extended an existing unit test to test it.
> MAYA-125954 USD import command support prim variants

- lib/mayaUsd/ufe/ProxyShapeSceneSegmentHandler.cpp
- lib/mayaUsd/ufe/ProxyShapeSceneSegmentHandler.h
- test/lib/ufe/testSceneSegment.py
Implement filtered version of `Ufe::SceneSegmentHandler::findGatewayItems()`.
Allows `findGatewayItems()` to filter the returned Selection by the specified nested runtime ID. For example, `findGatewayItems(path, usdRtid)` will only search for MayaUSD proxy shapes.
The according changes to UFE can be found in [this PR](https://git.autodesk.com/media-and-entertainment/ufe/pull/310).
> MAYA-125747 Implement filtered version of findGatewayItems().

- lib/usd/ui/layerEditor/layerTreeView.cpp
- lib/usd/ui/layerEditor/layerTreeView.h
- lib/usd/ui/layerEditor/qtUtils.cpp
- lib/usd/ui/layerEditor/qtUtils.h
When the layer manager model is rebuilt, preserve the state of the layer view (currently, only the expanded state of each layer) so that it can be restored once the model rebuilt is done.
- Add a LayerViewMemento to preserve the view state.
- Provide a preserve() and restore() method to save and restorethe state.
- Provide an empty method to avoid losing state when multiple calls to About-to-reset are made.
- Preserve befor ethe model reset, restore after.
- Note that, yes Qt emits the signal multiple times when the model is reset, so we have to take that into accouunt.
> MAYA-125275 preserve the layer manager expanded layers

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
This PR is related to this post: https://github.com/Autodesk/maya-usd/discussions/2516. In short, we recently found in our production in Animal Logic that, in some cases, `StagesSubject::onStageSet()` was called when `fStageListeners` was not empty which was causing verification message  being emitted constantly in Maya script editor:
```
// Error: Failed verification: ' g_StageMap.isDirty() ' // 
// Error: Failed verification: ' fStageListeners.empty() ' // 
```
We found `StagesSubject::onStageSet()` is triggered by `MayaUsdProxyStageSetNotice`, and `fStageListeners` is cleared out in
https://github.com/Autodesk/maya-usd/blob/dev/lib/mayaUsd/ufe/StagesSubject.cpp#L415-L442 which is called in `StagesSubject::onStageInvalidate()` https://github.com/Autodesk/maya-usd/blob/dev/lib/mayaUsd/ufe …
> Clearing out stage listeners before creating new ones

- lib/mayaUsd/ufe/UsdUndoAddNewPrimCommand.cpp
- lib/mayaUsd/ufe/UsdUndoAddNewPrimCommand.h
- test/lib/ufe/testContextOps.py
- Remove the restriction when creating a new prim.
- Add a unit test that validate we can create the new prim.
> MAYA-126141 allow creating prims in weaker layers.

- lib/mayaUsd/fileio/jobs/readJob.cpp
- test/lib/usd/translators/testUsdImportSessionLayer.py
- test/testUtils/usdUtils.py
Importing a USD file should not be able to affect staged USD files. Avoid such problem by not using any cache when importing.
> MAYA-126368 make import *not* use the shared stage cache

- lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.h
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
- test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateDisplayLayers.py
1. Introducing display layer cache in vp2RenderDelegate to drastically optimize Syncing of massive amounts of render items/instances
2. Explicitly disable display layers for point instancers until we figure out exactly what to do with them
> MAYA-126117 - Point instancer: performance drop on point instanced selection.

- lib/mayaUsd/fileio/transformWriter.cpp
- lib/mayaUsd/fileio/transformWriter.h
The code and structure were using "opName" to mean different things. In some cases it was the name of the Maya transform attribute, in other cases it was the suffix of the USD transform attribute. They sometimes corresponded, but sometimes not, which made the code intent harder to understand.
This change is made in preparation to supporting parent-offset-matrix, to avoid polluting that PR with these pure nomenclature changes.
- Renamed the cases where "opName" is a a Maya attribute to "mayaAttrName".
- Renamed "parentName" to "mayaAttrName".
- Renamed the cases where "opName" is a USD suffix to "suffix".
- Renamed the "setOpName" flag to "useSuffix".
> MAYA-124097 anim channel code clarification

- lib/mayaUsd/ufe/UsdSceneItemOps.cpp
- lib/mayaUsd/ufe/UsdSceneItemOps.h
- lib/mayaUsd/ufe/UsdUndoDuplicateCommand.cpp
- lib/mayaUsd/ufe/UsdUndoDuplicateCommand.h
- lib/mayaUsd/ufe/UsdUndoRenameCommand.cpp
- lib/mayaUsd/ufe/UsdUndoRenameCommand.h
- test/lib/ufe/testBatchOpsHandler.py
- test/lib/ufe/testDuplicateCmd.py
- test/lib/ufe/testRename.py
> LOOKDEVX-991 Improve usability of NoExec commands

- lib/usd/hdMaya/delegates/sceneDelegate.cpp
- lib/usd/hdMaya/delegates/sceneDelegate.h
When rendering, with some options, the renderer adds atemporary light to the scene, then removes it as soon as the render ends. The Maya scene delegate receives scene addition notifications, but in this case by the time the consequences if the notifications are processed, the light has already been deleted and the delegate access freed memory.
Make the scene delegate also listen to scene item removal notifications to remove items that have been deleted before they can be processed.
> MAYA-122481 fix rendering crash with MtoH

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/ufe/UsdUndoDuplicateCommand.cpp
- lib/mayaUsd/ufe/Utils.cpp
- lib/mayaUsd/ufe/Utils.h
This PR fixes a bug in the original code by introducing a code to properly replace USD prefixes when copying to USD.
> MAYA-123716 - As a user, I'd like my duplicated prim to be on the Display Layer that the source prim was on

- lib/mayaUsd/ufe/UsdAttribute.h
The connection API requires being able to cast to UfeAttribute, the UsdAttributeFilename class was the only one not allowing that. This makes the code uniform.
> Allow connecting filename attributes.

- lib/mayaUsd/render/vp2RenderDelegate/draw_item.cpp
- lib/mayaUsd/render/vp2RenderDelegate/draw_item.h
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
Reimplement shared VP2 render item counter to avoid using MRenderItem::setCustomData method, which causes a huge performance regression in Maya
> MAYA-126504 - Performance Issue: AntiquesMall Scene now takes 20+ minutes to load in Maya

- lib/mayaUsd/ufe/UsdShaderAttributeDef.cpp
Arnold stores these in the "hints" data, which is as valid as storing them in "metadata", so we update Ufe getMetadata to also look at hints on shader port attributes.
> Allow retrieving Arnold "uimin" metadata.

- lib/mayaUsd/ufe/UsdUndoDuplicateSelectionCommand.cpp
- lib/mayaUsd/ufe/UsdUndoDuplicateSelectionCommand.h
- test/lib/ufe/testDuplicateCmd.py
Fixes: Two items that would resolve to the same path after name conflict resolution actually end up being duplicated into the same name.
So duplicating "bob1" and "bob2" in the same selection would result in a single "bob3" and a missing "bob4".
The code now creates and executes sub-duplication tasks in the main loop to make sure the name conflict resolution sees the complete picture.
> Fix duplication of homonyms

- lib/mayaUsd/fileio/primUpdaterContext.cpp
- lib/mayaUsd/fileio/primUpdaterContext.h
- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/python/wrapPrimUpdater.cpp
- lib/mayaUsd/ufe/CMakeLists.txt
- lib/mayaUsd/ufe/EditAsMayaCommand.cpp
- lib/mayaUsd/ufe/EditAsMayaCommand.h
- lib/mayaUsd/ufe/SetVariantSelectionCommand.cpp
- lib/mayaUsd/ufe/SetVariantSelectionCommand.h
- lib/mayaUsd/ufe/UsdContextOps.cpp
- lib/mayaUsd/ufe/Utils.cpp
- lib/mayaUsd/undo/OpUndoItemList.h
- lib/mayaUsd/undo/OpUndoItems.cpp
- lib/mayaUsd/undo/OpUndoItems.h
- lib/usd/translators/mayaReferenceUpdater.cpp
- test/lib/mayaUsd/fileio/testAddMayaReference.py
- test/lib/mayaUsd/fileio/testCacheToUsd.py
- test/lib/mayaUsd/fileio/testPrimUpdater.py
- test/lib/ufe/testContextOps.py
This required many fixes and improvements.
The main challenges were:
- The fact that a given prim is a Maya reference is the knowledge of custom prim update manager.
- Some things were not available as UFE commands.
- It is possible to edit multiple Maya Ref at the same time in a single edit session (for example two ref as child of an edited prim)
- Many small bugs or limitations that had to be fixed.
The first item was addressed by having the possibility for prim updater to add extra work to be done once an operation (edit-as-Maya, merge-to-USD, etc) is done successfully:
- Add a composite UFE command to the prim updater context.
- This command contains sub-commands that are executed at the end of a prim updater operation.
- The prim updater customization classes can thus add final work …
> MAYA-125918 auto re-edit when merging a Maya Ref

- lib/mayaUsd/resources/scripts/mayaUsdMergeToUsd.py
When two variants contain prim with the same name, editing one prim in one variant then switching to the other variant would still show the "Merge Maya Edits to USD" menu item enabled due to the confusion of still having a prim with the same name.
Augment the code to properly detect that the prim has no pull information and disable the merge-to-USD menu item.
> MAYA-125036 correctly disable merge to USD

- lib/mayaUsd/fileio/shading/shadingModeExporterContext.cpp
- lib/mayaUsd/fileio/utils/meshWriteUtils.cpp
- lib/mayaUsd/fileio/utils/writeUtil.cpp
- lib/mayaUsd/fileio/utils/writeUtil.h
- test/lib/usd/translators/testUsdExportUVSetMappings.py
The export options -remapUVSetsTo and -preserveUVSetNames are now correctly handled when exporting materials.
> Fix material export when preserving UVset names

- test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegatePrimPath.py
A change in how Maya reacts to some UFE notification preserves the selection in more cases instead of clearing it. This test was affected by the Maya change.
> MAYA-000000 fix test

- lib/mayaUsd/ufe/UsdUndoMaterialCommands.cpp
- test/lib/ufe/testContextOps.py
When using "Assign New Material", a new material gets created in the default materials scope. This scope is usually called "mtl". In the previous implementation, there was a bug where materials got created in *any* scope that starts with "mtl". If, for example, there was a scope called "mtlFoo", and no scope called "mtl", the new material got created in "mtlFoo". However, the expected behaviour in this example is to create a scope called "mtl" and to create the new material in there.
This is the expected behaviour in a more general sense: If the default materials scope name (usually "mtl") is available, create the new material in a scope with this name. If the default materials scope name is not available i.e., there is already something that is not of type "Scope" that is using that name …
> MAYA-126483 Fix a bug where materials got created in the wrong scope.

- lib/mayaUsd/ufe/UsdAttributes.cpp
- test/lib/ufe/testAttributes.py
With this PR, when deleting a compound attribute, the associated connections are also deleted. 
Fixes [issue 126871](https://jira.autodesk.com/browse/MAYA-126871).
I updated the existing `testAttributes.py` adding the test `testRemoveCompoundAttribute`.
> Maya-126871 Delete compound attributes does not remove their connections.

- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
When working in an Arnold or RenderMan shading workflow, it is perfectly normal that there is no VP2 materials to be found. Remove the warning since the code correctly handles the situation by using the fallback shader.
> Remove frequent warning in Arnold/RenderMan shading workflows

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
Loading a MaterialX stage with cubic texture sampling does not work with UDIMs.
The default range for LOD values in OpenGL is -1000 to 1000.
The default range for Dx11 is 0 to 16.
The minLOD parameter in MSamplerStateDesc is unsigned int.
Leave the values as initialized by the API to prevent breaking the UDIM texture queries.
> UDIM: Use default LOD values in anisotropic mode

- cmake/modules/FindUFE.cmake
* Temporary setting of UFE_PREVIEW_VERSION_NUM while we transition to UFE v4.0.0.
> MAYA-127074 - MayaUSD : Bump UFE version to 4.0

- lib/mayaUsd/ufe/CMakeLists.txt
- lib/mayaUsd/ufe/UsdAttribute.cpp
- lib/mayaUsd/ufe/UsdCamera.cpp
- lib/mayaUsd/ufe/UsdLight.cpp
- lib/mayaUsd/ufe/UsdTransform3dMatrixOp.cpp
- lib/mayaUsd/ufe/UsdTransform3dUndoableCommands.cpp
- lib/mayaUsd/ufe/UsdTransform3dUndoableCommands.h
- lib/mayaUsd/ufe/UsdUndoAttributesCommands.cpp
- lib/mayaUsd/ufe/UsdUndoAttributesCommands.h
- lib/mayaUsd/ufe/UsdUndoableCommand.cpp
- lib/mayaUsd/ufe/UsdUndoableCommand.h
- test/lib/ufe/testCamera.py
Implemeted the UFE commands necessary to set values on a camera via UFE.
Extended the available base classes to implement UFE commands that modify USD data. Make each base class do one thing only, to clarify the purpose of each.
Add UsdUndoCapture class:
- It captures the changes to USD data within a UFE command.
- Its sub-classes only need to implement executeImplementation() and optionally setImplementation().
- It provides executeWithUndoCapture to do the command execution implementation while capture USD changes.
- Same for setWithUndoCapture.
- Provides undoUsdChanges() to undo all changes that were capture.
- Same with redoUsdChanges, to redo the changes.
Refactor UsdUndoableCommand class:
- Make UsdUndoableCommand use UsdUndoCapture class.
- Add templated variable-arguments …
> MAYA-109455 UFE USD camera commands

- lib/mayaUsd/fileio/orphanedNodesManager.cpp
- lib/mayaUsd/fileio/orphanedNodesManager.h
- lib/mayaUsd/fileio/pullInformation.cpp
- lib/mayaUsd/utils/CMakeLists.txt
- lib/mayaUsd/utils/primActivation.cpp
- lib/mayaUsd/utils/primActivation.h
- lib/usd/translators/mayaReferenceUpdater.cpp
- test/lib/mayaUsd/fileio/CMakeLists.txt
- test/lib/mayaUsd/fileio/testAddMayaReference.py
- test/lib/mayaUsd/fileio/testDiscardEdits.py
When a Maya reference is edited, its USD prim is deactivated to hide it in the outliner. If its parent prim is then deactivated, the edit is orphaned. At that point the Maya Ref prim and its parent are both deactivated. If the edit is cancelled while the parent is deactivated, the code could not activate the Maya Ref USD prim because children of deactivated prims cannot be modified. We needed to fix this.
The fix is to add code to temporarily reactivate ancestors prims when trying to activate a prim. The design actually provides a class to temporarily activate all ancestors of a prim, for any possible edits.
- Add PrimActivation class to temporarily make a prim accessible even when its ancestors are deactivated.
- It works by activating all inactive ancestors by authoring opinions in the …
> MAYA-122927 interaction between deactivation and cancel edit

- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/python/wrapDiagnosticDelegate.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.h
- lib/mayaUsd/render/pxrUsdMayaGL/shapeAdapter.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/utils/diagnosticDelegate.cpp
- lib/mayaUsd/utils/diagnosticDelegate.h
- test/lib/mayaUsd/utils/testDiagnosticDelegate.py
- test/lib/ufe/testAttribute.py
- test/lib/ufe/testAttributes.py
- test/lib/ufe/testConnections.py
- test/lib/usd/translators/testUsdExportStripNamespaces.py
Improve the message batching to be usable for errors too. Also, remove
hard-coded crash when we can. We should never explicitly choose crash Maya
under the user's feet just because of some-sub-system is unhappy. Errors are
fine for those cases.
Unfortunately, there are some messages that comes from OGS and which require a
Maya fix to avoid flooding the script editor, those cannot be fixed in the
plugin. (Well, it would need investigation why the VP2 delegate does what it
does and causes those OGS errors.)
- Always accumulate and coalesce messages.
- Use a thread to periodically write messages.
- Only write messages if there are some pending and at least a second has passed.
- For low-volume messages, this will print all messages.
- For high-volumes messages, this avoids a flood of …
> MAYA-104552 improve diagnostics

- lib/mayaUsd/fileio/pullInformation.cpp
- lib/mayaUsd/fileio/pullInformation.h
- lib/mayaUsd/python/wrapPrimUpdaterManager.cpp
- lib/mayaUsd/resources/scripts/mayaUsdMergeToUsd.py
- lib/mayaUsd/ufe/MayaUIInfoHandler.cpp
Also fixes MAYA-126891
- Provide a function to explicitly determine if an edited prim is orphaned.
- Provide the function in Python too.
- Use it both to build the context menu and do the outliner item rendering.
> MAYA-125036 correctly identify orphaned edited prims

- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
- lib/mayaUsd/ufe/UsdAttributeHolder.cpp
- test/lib/ufe/testAttribute.py
Some attribute names use namespaces that are copies of the schema name. When displaying UI names we want to strip that redundant information.
> Shorten nice names by trimming schema name

- lib/mayaUsd/sceneIndex/CMakeLists.txt
- lib/mayaUsd/sceneIndex/plugInfo.json
* The plugInfo specified as part of https://github.com/Autodesk/maya-usd/pull/2805 incorrectly included an absolute path.
> MAYA-126175: fix plugInfo to use relative path

- lib/mayaUsd/ufe/Utils.cpp
Minor changes in UFE utility `vtValueFromString()`:
- If the input string is empty, the functors stored in the converter map for int,float,double numeric types now return an empty variant value. 
- The change prevents throwing of exceptions when `std::stoi/f/d` fail.
> LOOKDEVX-1084 - Prevent string conversions to throw exceptions with empty value

- lib/mayaUsd/ufe/UsdUndoInsertChildCommand.cpp
- test/lib/ufe/testParentCmd.py
MAYA-127045 Add reparenting rules for UsdShadeShader, UsdShadeNodeGraph and UsdShadeMaterial.
Users are able to reparent USD items in the Outliner. However, in some cases, reparenting does not make sense and can lead to problematic situations in LookdevX. The following rules are established, when a user tries to reparent items in the Outliner:
- UsdShadeShader can only have UsdShadeNodeGraph/UsdShadeMaterial as parent.
- UsdShadeNodeGraph can only have a UsdShadeNodeGraph/UsdShadeMaterial as parent.
- UsdShadeMaterial cannot have UsdShadeShader/UsdShadeNodeGraph/UsdShadeMaterial as parent.
If one of the rules is broken, reparenting is prevented.
> MAYA-127045 Add reparenting rules for Shaders, NodeGraphs and Materials.

- lib/mayaUsd/ufe/UsdShaderAttributeHolder.cpp
- The goal is to notify the user when a property of any shader lacks a default value.
- The properties that lack a default value will start to log a warning when the user interacts with them in the editor (that involves the `get()` of the property value).
- Known attributes are maintained in a list (`std::unordered_set`) to avoid being too verbose for properties we have already printed on Console.
> LOOKDEVX-1091 - Add Ufe log on console to notify shader attribute without a default value

- test/lib/ufe/testAttribute.py
UFE attribute metadata API was introduced in UFE 3. The new testAttributeNiceNames should be disabled if the API is now available (UFE 2 and earlier)
> Skip new test if UFE attribute metadata not available

- test/lib/usd/translators/testUsdExportUVSetMappings.py
This fixes this test for environments with remapUVSetsTo defaults configured
> Fix empty values for remapUVSetsTo

- lib/mayaUsd/resources/scripts/mayaUsdOptions.py
- The materials scope name is only modifiable with the environment variable.
- OTOH, the options used for duplicate, merge and cache to USD are all saved in options vars.
- This resulted in that the environment variable value was saved in options vars and would persists even when the env var was no longer set.
- This changes cleans up the option vars of the value that were set by the env var.
- It is a bit unfortunate that the materials scope choice was designed this way but now we are too close to release to re-design it.
> MAYA-126515 clean options of materials scope name

- lib/mayaUsd/utils/utilSerialization.cpp
When an invalid extension string is provided, USD fails to relocate the file when trying update the cached stage layers and will return a TfNullPtr which results in crash. The fix is to check and update the file path prior to passing to layer export and load operations.
> Fixes an issue on layer editor save dialog, where an invalid extension could cause a crash. The fallback is .usd.

- lib/mayaUsd/ufe/UsdUndoDuplicateSelectionCommand.cpp
- test/lib/ufe/testBatchOpsHandler.py
The post-duplicate cleanup would delete an unconnected port knowing that it would still survive via the shader node definition.
However NodeGraphs do not have an underlying definition, so we need to preserve those unconnected ports even though they might not have a value at this point in time.
> Preserve NodeGraph boundaries on duplicate.

- lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.cpp
* Pixar added support for instances inside of usd imaging stage scene index.
* Enable instance in non empty stage in preparation for next usd release
> MAYA-127233: enable instances to determine non empty stage in preparation for USD v23

- plugin/adsk/scripts/mayaUSDRegisterStrings.py
- plugin/adsk/scripts/mayaUsd_USDRootFileRelative.py
MAYA-127119 - Save USD root file relative to scene file
MAYA-127352 - Save USD root file relative to scene file using Bulk Save
MAYA-127358 - Load my USD root file relative to scene file using 'Create Stage from File'
MAYA-127353 - Load my USD root file relative to the scene file
* Small update to UI string for checkbox (with new tooltip).
> MAYA-127119 - Save USD root file relative to scene file

- lib/mayaUsd/render/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
Shading graphs containing closures would fail to work with MaterialX 1.38.5.
> Adding a MaterialX v1.38.5 update for closures

- lib/mayaUsd/ufe/UsdConnectionHandler.cpp
- lib/mayaUsd/ufe/UsdUndoConnectionCommands.cpp
A workaround was created for
https://github.com/PixarAnimationStudios/USD/issues/2013 which was fixed in USD 23.02 via https://github.com/PixarAnimationStudios/USD/pull/2017/commits/e3b963b4ee622d2d07ae5f60ce9c5684f0d4966f
This makes sure the workaround ends once we reach that USD version.
> Add a version upper bound on Hydra workaround

- lib/mayaUsd/resources/scripts/CMakeLists.txt
- lib/mayaUsd/resources/scripts/mayaUsdAddUSDReference.mel
- lib/mayaUsd/ufe/UsdContextOps.cpp
- lib/mayaUsd/utils/utilFileSystem.cpp
- lib/mayaUsd/utils/utilFileSystem.h
- plugin/adsk/scripts/mayaUSDRegisterStrings.py
- plugin/adsk/scripts/mayaUsd_USDRootFileRelative.py
- plugin/adsk/scripts/mayaUsd_pluginUICreation.mel
- Refactor the Python helper to handle the relative-path UI in file dialogs.
- Make it more generic by abstracting to which file the path will be relative to, the label of the UI and the option var used.
- Add makePathRelativeTo function to UsdMayaUtilFileSystem to make any file path relative to a given directory.
- Add requireUsdPathsRelativeToEditTargetLayer function to verify if USD ref paths should be relative.
- Make the USD context menu use the new relative ref UI and functions.
- Refactor its code a bit to make reading the generated scripts easier.
> MAYA-127393 allow USD ref to be relative

- lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.cpp
As per
https://groups.google.com/g/usd-interest/c/PuZud-IQ6gE/m/TZJ2BOtYBQAJ
the legacy UsdImaging scene delegate flattens the USD scene. Moving to the new Hydra 2.0 scene index framework requires adding an explicit flattening filtering scene index.
> mayaUsd scene hierarchies need flattening scene index filter.

- lib/mayaUsd/nodes/layerManager.cpp
When doing a bulk-save of layers when saving a Maya scene for the first time, the multiple-parts of the saving process could end-up using stale data. That is because there is a first batch-save delegate (customizable callback) that can do a partial save, then a fallback save is done for any layer that did not get saved.
When a stage has just been created, it contains an anonymous root layer which gets replaced by a non-anonymous by the batch save delegate. When the root layer is swapped, the stage proxy shape is updated by setting its stage name attribute.  Unfortunately, the USD stage object was being cached and the attribute change was thus not use immediately. Thus the 2nd part fallback-save thought that the root layer was still anonymous.
The fix is to refresh the cached USD stages by …
> MAYA-127478 fix bulk save of root layer filename

- lib/mayaUsd/ufe/UsdTransform3dCommonAPI.cpp
- lib/mayaUsd/ufe/UsdTransform3dCommonAPI.h
Like the other implementations, call the rotate pivot function. This fixes the visual position of the scale pivot in Maya when using the scaling tool.
> MAYA-124897 implement scale pivot for common API

- lib/mayaUsd/ufe/Utils.cpp
When an operation cannot proceed because it would need to modify multiple layers at the same time, use a different error message. Do not tell the user to switch layer.
> MAYA-125340 improve error messages

- test/lib/ufe/testDisplayLayer.py
Additional testing for USD to USD duplication with display layers. This case covers the bug found by QA during the original feature testing
> MAYA-126541 - Create a more extensive unit test for display layer support during USD to USD duplication 

- lib/mayaUsd/listeners/stageNoticeListener.cpp
- lib/mayaUsd/listeners/stageNoticeListener.h
- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/nodes/proxyShapeBase.h
- lib/mayaUsd/nodes/proxyShapeStageExtraData.cpp
- lib/mayaUsd/nodes/proxyShapeStageExtraData.h
- lib/mayaUsd/utils/CMakeLists.txt
- lib/mayaUsd/utils/targetLayer.cpp
- lib/mayaUsd/utils/targetLayer.h
- test/lib/mayaUsd/nodes/testProxyShapeBase.py
- test/lib/mayaUsd/utils/CMakeLists.txt
- test/lib/mayaUsd/utils/testTargetLayer.cpp
- When saving a Maya scene, the current target layer of USD stage get saved in an attribute on the proxy shape.
- When loading a scene, when creating the USD stage, set the target layer to the one that was saved.
- The target layer is persisted as a text attribute containing the USD layer identifier.
- Listen to edit target change to save the attribute when the target is set to avoid losing it if the proxy shape gets recomputed.
- Add a unit test,
> MAYA-114188 save the target layer

- plugin/pxr/maya/lib/usdMaya/testenv/testUsdExportPackage.py
The test expects that the temp folder be devoid of certain files, but it sometimes happens that files matching the pattern existed before the test started and are undeletable. (Locked by an other process or owned by another user?)
Record the list of pre-existing files and ignore them.
> MAYA-000000 Reduce testUsdExportPackage failures

- lib/mayaUsd/nodes/layerManager.cpp
- lib/mayaUsd/utils/utilSerialization.cpp
- lib/mayaUsd/utils/utilSerialization.h
- lib/usd/ui/layerEditor/batchSaveLayersUIDelegate.cpp
- lib/usd/ui/layerEditor/layerTreeModel.cpp
- lib/usd/ui/layerEditor/saveLayersDialog.cpp
- lib/usd/ui/layerEditor/saveLayersDialog.h
- Record from which stage the saved layer are from.
- Update the edit target to the new layer of the stage if the old layer was the edit target.
- Adjust save dialog callers to track and pass the necessary info.
> MAYA-127808 update edit target when saving an anonymous layer

- lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.h
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.h
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/tokens.h
- Adding 'untextured' override support to instanced geometry
- Fixing a bug with slection highlight of mods
> MAYA-125725 - Implement display layer's untextured mode for instanced geometry

- lib/mayaUsd/ufe/UsdUndoDuplicateCommand.cpp
- lib/usd/utils/util.cpp
- lib/usd/utils/util.h
- test/lib/ufe/testDuplicateCmd.py
- test/testSamples/cubeRef/cube-root.usda
- test/testSamples/cubeRef/cube.usda
The concept of layer from within the USD API is confusing relative to the high-level concept of layers. When talking about layers at a high-level, what is meant are the root and session layers and their sub-layers. OTOH, in the API, the layers are also used for references.  A reference is kept in a layer object (SdfLayer), but is not part of the stage layer stack!
In the case of duplication, we use SdfCopySpec to do the heavy lifting, and that takes a source path and source layer. But these are low-level layers, not high-level layers. in particular, if the source prim is in a reference, we must use the reference layer as the layer and the path must be relative to reference, not the stage root!
So, change the duplicate code to handle references correctly.
- Add a helper function to …
> MAYA-124737 improve duplicate command

- lib/usd/translators/shading/shadingTokens.h
- lib/usd/translators/shading/usdFileTextureWriter.cpp
The logic for writing our `sourceColorSpace = "raw"` in the USD files was based on looking to see if the colorSpace was set to `Raw`.
However, if you're using OCIO colorspaces, `Utility - Raw` is also another valid option based on the [standard ocio config](https://github.com/colour-science/OpenColorIO-Configs/blob/master/aces_1.2/config.ocio) .
This also adds a case for that scenario. It would be the most common Raw setup in OCIO based studios unless they diverge from the base config.
Unfortunately, I do not know if your CI supports OCIO colorspace configs, so I didn't add a test for this. Please let me know how you'd like to handle that.
> Write sourceColorSpace=raw when using Utility - Raw

- lib/mayaUsd/ufe/UsdContextOps.cpp
Unfortunately, USD stage's SetLoadRules function does not optimize the change notifications it sends out. Its Load and Unload functions do optimize the notifications they send out. Normally, this is an implementation details inside USD that we should not have to rely on. Pragmatically though, using the functions which send out the most narrow notification is better. So even though calling SetLoadRules is simpler and more precise, it is less efficient.
> MAYA-124922 use Load/Unload for payload

- lib/usd/ui/importDialog/USDImportDialogCmd.cpp
- plugin/adsk/scripts/mayaUsdTranslatorImport.mel
- Add a flag to the UsdImportDialog command to specify the parent window name.
- Use that flag when invoking the command from the import panel.
- Use the flag in the command to find the parent window.
> MAYA-106352 keep hierarchy window on top of import window

- lib/mayaUsd/ufe/UsdSceneItem.cpp
- lib/mayaUsd/ufe/UsdUIInfoHandler.cpp
- lib/mayaUsd/ufe/UsdUndoRenameCommand.cpp
- Protect UsdSceneItem against invalid prims.
- Protect USD UI info handler against invalid prims.
- These can happen for example when we're in the middle of a rename and the outliner gets updated or redrawn.
- Fix the rename command to send rename notifications to all proxy shape that share the same stage.
- At the same time, refactor the redo/undo code that was 99% identical.
> MAYA-127427 fix rename when staged multiple times

- lib/mayaUsd/ufe/ProxyShapeCameraHandler.cpp
Verify that the UFE item has been successfully created before using it.
> MAYA-127959 avoid crash when world node has an unexpected name

- lib/mayaUsd/python/wrapUtil.cpp
- plugin/adsk/scripts/mayaUSDRegisterStrings.py
- plugin/adsk/scripts/mayaUsd_USDRootFileRelative.py
- plugin/adsk/scripts/mayaUsd_layerEditorFileDialogs.mel
* Added two path preview fields with logic to update them on any change to path/file from save/load dialog where the relative path is used.
* Added python wrapper for util ensureUSDFileExtension()
> MAYA-127370 - Preview of my relative path (resolved and unresolved)

- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
Fixes the crash when multiple instances of the same stage file are being rotated / scaled simultaneously.
> Removed an artifical crash in transform operations and replaced it with a asserts.

- lib/mayaUsd/ufe/UsdAttributeHolder.cpp
- test/lib/ufe/testAttributes.py
This PR fixes [Jira MAYA-128001](https://jira.autodesk.com/browse/MAYA-128001):  If we try to clear a Compound attribute, we get the error: "Cannot clear metadata. 'metadataName' is not registered as valid metadata for spec type SdfSpecTypeAttribute." and the attribute metadata is not cleaned.
> MAYA-128001 - clearMetadata doesn't work for UsdShadeNodeGraph attribute.

- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/ufe/UsdUndoDeleteCommand.cpp
- lib/mayaUsd/ufe/UsdUndoInsertChildCommand.cpp
- lib/mayaUsd/ufe/UsdUndoInsertChildCommand.h
- lib/mayaUsd/ufe/UsdUndoRenameCommand.cpp
- lib/mayaUsd/ufe/UsdUndoRenameCommand.h
- lib/mayaUsd/ufe/UsdUndoReorderCommand.cpp
- lib/mayaUsd/ufe/Utils.cpp
- lib/mayaUsd/utils/CMakeLists.txt
- lib/mayaUsd/utils/layers.cpp
- lib/mayaUsd/utils/layers.h
- lib/mayaUsd/utils/util.cpp
- lib/mayaUsd/utils/util.h
- lib/usd/ui/layerEditor/layerTreeModel.cpp
- test/lib/ufe/testDeleteCmd.py
- test/lib/ufe/testGroupCmd.py
- test/lib/ufe/testRename.py
- test/lib/ufe/testReorderCmd.py
Keep opinions in the session layer in sync when a prim is renamed while targeting another layer. Do the same for insert child, group delete and reorder commands.
Provide helper functions to deal with the session layer and enhance the various commands to allow them when the session layer contains opinions, by using these helper functions.
Allow authoring in session layer: detect that the target is in the session layer and allow edits there if it is the strongest session opinion.
- Move many layer-related helpers into their own file.
- Refactor code that used the old functions to use the new functions.
- Add applyToAllPrimSpecs and applyToAllLayersWithOpinions helper functions.
- Add applyToSomeLayersWithOpinions helper function to apply a change to a subset of layers.
- Use …
> MAYA-126128 sync session layer for various commands

- lib/usd/hdMaya/adapters/proxyAdapter.h
Hello !
Could we add a getter for usd imaging delegate in proxy adapter?
We are making production render feature in our plugin with our hydra render delegate (RadeonProRender hdRPR) and we try reuse as much code as possible from MtoH.
Thank you!
> Add a getter for usdimaging delegate in proxy adapter

- lib/mayaUsd/ufe/Utils.cpp
* Removed TF_WARN - it is not appropriate for low-level utility function.
> MAYA-124715: Error: Failed verification: on File > New

- lib/mayaUsd/ufe/UsdUndoConnectionCommands.cpp
* I have found "isDisconnected  not used" treated as error that if PXR > v0.23 is used
> MAYA-128040: isDisconnected local variable treated as error if pxr > v0.23

- lib/mayaUsd/ufe/UsdAttributeHolder.cpp
- lib/mayaUsd/ufe/UsdTransform3d.cpp
- lib/mayaUsd/ufe/UsdTransform3dCommonAPI.cpp
- lib/mayaUsd/ufe/UsdTransform3dMatrixOp.cpp
- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.h
- lib/mayaUsd/ufe/UsdUndoVisibleCommand.cpp
- lib/mayaUsd/ufe/Utils.cpp
- lib/mayaUsd/ufe/Utils.h
- test/lib/ufe/testBlockedLayerEdit.py
- test/lib/ufe/testGroupCmd.py
Make the transform commands propagate the errors they encounters instead of just logging them. This is necessary to make UFE composite commands work properly: they need to know that a sub-command failed and stop execution. Otherwise they just keep going and pretend they worked when they didn't, corrupting the state of USD or Maya.
- Add helper functions to enforce blocked attribute edits by throwing exception with a clear message when edits are not allowed.
- Make all transform commands enforce the blocked edits.
- This fixes the group, ungroup and parenting UFE composite commands when a subset of items cannot be modified.
> MAYA-126128 transform command error reporting

- modules/alUSD_Win.mod.template
- modules/mayaUSD_Win.mod.template
- modules/pxrUSD_Win.mod.template
Discussed in https://github.com/Autodesk/maya-usd/issues/2859
Paths added to the dll search list are not necessarily searched in order, so this change makes sure that PXR_USD_WINDOWS_DLL_PATH is defined in any .mod files for Windows so we don't get .dll clashes.
I changed all 3 windows mod files, because (I'm guessing) that Pixar and Animal Logic aren't using Windows, and those are there only for completeness. Plus anybody that looks to those files as an example of an alternative setup should probably have that variable set.
> Add PXR_USD_WINDOWS_DLL_PATH to all of the windows module templates.

- cmake/test.cmake
Add cmake test fixes to go with .mod file changes made here:
https://github.com/Autodesk/maya-usd/pull/2867
> Add cmake test fixes to go with .mod file changes made recently

- lib/usd/ui/layerEditor/loadLayersDialog.cpp
- lib/usd/ui/layerEditor/loadLayersDialog.h
- plugin/adsk/scripts/mayaUsd_layerEditorFileDialogs.mel
- Add UI to load-layer file dialog to make the file path relative, in MEL.
- Modify the overall load-layer dialog to support relative sub-layers.
> MAYA-127737 allow loading relative sub layers

- lib/mayaUsd/ufe/UsdUndoRenameCommand.cpp
* When sending notif use the new prim.
> MAYA-128044: Outliner: Renaming prims changes icon to def

- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/nodes/proxyShapeBase.h
- lib/mayaUsd/utils/layers.cpp
- lib/mayaUsd/utils/layers.h
- lib/mayaUsd/utils/targetLayer.cpp
- lib/mayaUsd/utils/targetLayer.h
The problem is recursive interactions between multiple actors.
First actor: the ProxyAccessor class.
This class is only vaguely documented, that is there is a mechanical description but not an explanation of why it needs to exists nor why it is written as it is. It's mechanical purpose, as I understand it from its docs, is to copy input plugs into the proxy shape to stage data and copy stage data to output plugs. For some reason which are not explained, it writes its data to the session layer. To do so, it temporarily sets the target layer to the session layer.
Second actor: the ProxyShapeBase class.
The class is the representation of the USD stage as a Maya node. As part if its computation, it creates the stage. It holds multiple attributes to do so:
- The root layer
- The session layer …
> MAYA-128407 fix edit-target loops in proxy shape compute

- plugin/al/translators/tests/testTranslators.py
- plugin/al/usdmayautils/AL/usdmaya/utils/MeshUtils.cpp
We found a logical error in multiple color sets exporting from Maya to USD in AL_USDMaya where vertex colours were written wrong. This PR addresses the said issue.
> [al]Fixing multiple colour sets export from Maya to USD

- lib/mayaUsd/ufe/UsdTransform3d.cpp
- lib/mayaUsd/ufe/UsdTransform3dCommonAPI.cpp
- lib/mayaUsd/ufe/UsdTransform3dMatrixOp.cpp
- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.h
- lib/mayaUsd/ufe/Utils.h
The creation of transform command cannot throw exception because Maya is not ready to handle them. Since we cannot change Maya at this point revert to the old behaviour of returning a null command.
> MAYA-128463 transform command return null.

- lib/mayaUsd/nodes/CMakeLists.txt
- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/nodes/proxyShapeBase.h
- lib/mayaUsd/nodes/proxyShapeUpdateManager.cpp
- lib/mayaUsd/nodes/proxyShapeUpdateManager.h
- test/lib/ufe/testContextOps.py
- test/lib/ufe/testUINodeGraphNode.py
A renderer now only has to track the "updateid" and "resyncid" attributes of the stage to know if something significant happened.
All UINodeGraphNodeAPI notifications were suppressed.
> Add smart signaling for renderers.

- lib/mayaUsd/commands/baseImportCommand.cpp
- lib/mayaUsd/commands/baseImportCommand.h
- lib/mayaUsd/fileio/importData.cpp
- lib/mayaUsd/fileio/importData.h
- lib/mayaUsd/fileio/jobs/jobArgs.cpp
- lib/mayaUsd/fileio/jobs/jobArgs.h
- lib/mayaUsd/fileio/translators/translatorSkel.cpp
- lib/mayaUsd/fileio/translators/translatorXformable.cpp
- plugin/adsk/plugin/importTranslator.cpp
- test/lib/usd/translators/CMakeLists.txt
- test/lib/usd/translators/testUsdImportEulerFilter.py
It has proven useful to allow the Euler filtering of rotational animation on import as well as export. This P/R adds a flag `aef/applyEulerFilter` flag to `mayaUSDImport` that applies Euler filtering for transform and skeletal animation data.
> Added applyEulerFilter to import

- lib/mayaUsd/nodes/proxyAccessor.cpp
- lib/mayaUsd/nodes/proxyAccessor.h
- lib/mayaUsd/nodes/proxyAccessor.py
- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/nodes/proxyShapeBase.h
Add a custom attribute "combinedVisibility" to proxy accessors to output combined visibility to maya pulled prims
> MAYA-114041 - As a user, I'd like my pulled Maya object to inherit visibility

- lib/mayaUsd/nodes/proxyShapeUpdateManager.cpp
This is needed for the calls to std::once_flag and std::call_once
> Adding missing <mutex> include

- lib/mayaUsd/nodes/proxyShapeUpdateManager.cpp
- lib/mayaUsd/utils/layers.cpp
This will restrict namespace edits to your current usd stage. This avoids the issue of spanning references and inherits, etc, which will often be illegal operations. This addresses the issue I posted here:
https://github.com/Autodesk/maya-usd/issues/2953
> Restrict namespace edits to current stage

- lib/mayaUsd/nodes/proxyShapeUpdateManager.cpp
- lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.cpp
In most recent USD, Populate is called from within SetStage, so there is no need to callsites to call it explicitly
> Remove explicit call to sceneIndex::Populate

- lib/mayaUsd/nodes/layerManager.cpp
- lib/mayaUsd/utils/util.cpp
- lib/mayaUsd/utils/util.h
- lib/mayaUsd/utils/utilSerialization.cpp
- lib/mayaUsd/utils/utilSerialization.h
- lib/usd/ui/layerEditor/layerTreeItem.cpp
The problem was that when saving an anonynous layer, the stage changes since the root layer changes identity. We need to set the target layer, but not on the current stage, but on the new computed stage.
Also, I added error messages when a save operation fails.
- Add a helper function to retrieve the proxy shape node from its node name.
- Pass the new layer to the helper function that sets the new proxy path of the proxy shape.
- Make sure that all layer info contain the proxy shape path since it is needed to update the target layer when a target anonymous layer is saved.
- Renamed the saveRootLayer function to updateRootLayer since it is not saving the layer, it is updating the proxy shape.
> MAYA-128199 fix error on save

- lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.cpp
Came as a result of this
https://github.com/Autodesk/maya-usd/pull/2983
Implicit Populate was only added as part of patch version 2305, the code was added here
https://github.com/PixarAnimationStudios/USD/commit/3091ceaecd6d6dfc574199c2500594bade84939c
The PXR_VERSION used is incorrect it will break versions predating the patch version 2305.
https://github.com/PixarAnimationStudios/USD/blob/3091ceaecd6d6dfc574199c2500594bade84939c/cmake/defaults/Version.cmake
Should be fixed like this
```
#if PXR_VERSION <= 2305
// In most recent USD, Populate is called from within SetStage, so there is no need to callsites to call it explicitly
_usdImagingStageSceneIndex->Populate();
#endif
```
> HYDRA-300: Update proxyShapeSceneIndexPlugin.cpp

- doc/EditRouting.md
- lib/mayaUsd/python/wrapEditRouter.cpp
- lib/mayaUsd/ufe/UsdAttributeHolder.cpp
- lib/mayaUsd/ufe/UsdObject3d.cpp
- lib/mayaUsd/ufe/UsdUndoDuplicateCommand.cpp
- lib/mayaUsd/ufe/UsdUndoInsertChildCommand.cpp
- lib/mayaUsd/ufe/UsdUndoVisibleCommand.cpp
- lib/mayaUsd/ufe/UsdUndoVisibleCommand.h
- lib/mayaUsd/utils/CMakeLists.txt
- lib/mayaUsd/utils/editRouter.cpp
- lib/mayaUsd/utils/editRouter.h
- lib/mayaUsd/utils/editRouterContext.cpp
- lib/mayaUsd/utils/editRouterContext.h
- test/lib/ufe/testEditRouting.py
Add a context classes that reuse previous edit routing before doing a new edit routing.
- One is OperationEditRouterContext, used to route commands.
- The other is AttributeEditRouterContext, used to route attribute modifications.
- This is done by keeping track of edit routing contexts higher in the call stack.
- Remove the EditTargetGuard class since it was doing the same work as USD UsdEditContext class.
- Add documentation about how to route a custom composite command.
Modified the commands that were routing edits to use the new EditRoutingContext. This makes the code using them clearer.
- Fetch the current edit target via the stage, not the context, since the context may not have a target layer if the operation was not routed.
Correctly support absence of edit router. This happens …
> MAYA128513 edit routing of composite commands

- test/lib/ufe/testUINodeGraphNode.py
An issue was introduced in the `UINodeGraphNode` test with #2966. This fixes this issue.
> LOOKDEVX-1112 - Fix UINodeGraphNode test

- lib/mayaUsd/ufe/UsdShaderNodeDef.cpp
- lib/mayaUsd/ufe/UsdShaderNodeDef.h
- lib/mayaUsd/ufe/UsdUndoMaterialCommands.cpp
- lib/mayaUsd/utils/util.cpp
- lib/mayaUsd/utils/util.h
- plugin/adsk/plugin/adskMaterialCommands.cpp
- plugin/adsk/plugin/adskMaterialCommands.h
- test/lib/ufe/testAttribute.py
- test/lib/ufe/testShaderNodeDef.py
- Utility function `UsdMayaUtil::GetSurfaceShaderNodeDefs()` for getting vetted surfaces as well as those with "shader/surface" role (adds afew arnold ones, potentially more)
- `UsdShaderNodeDef::definitions` can now be queried for surface definitions only in order to access them through UFE
- `UsdShaderNodeDef::createNodeCmd` will implicitly create a material if given a valid material scope
- `UsdUndoAddNewMaterialCommand` will only attempt to connect surface nodes to material output
- UI specific string requirements have been pushed to `UsdMayaUtil::prettifyName` for consistency
> MAYA-128779 - Improvements for surface shader querying and handling

- plugin/adsk/plugin/adskMaterialCommands.cpp
Bug fix for my earlier PR https://github.com/Autodesk/maya-usd/pull/2958.
For some reason, certain node types report their first ancestor as the same name as the node type itself. This threw off the logic in my original implementation, so this fix makes sure we check against at least one actual ancestor type.
> MAYA-128934 - Bug fix: Prevent right click-material assignment for physics-related nodes

- lib/mayaUsd/fileio/utils/jointWriteUtils.cpp
- test/lib/usd/translators/CMakeLists.txt
- test/lib/usd/translators/testUsdExportSkin.py
If an artist uses polyReduce (or other node that changes the vertex count) after a skinCluster has been applied, the Usd exporter tries to compare the weights of the original vertex count with the assigned weights of the reduced vertex count. This results in an out-of-bounds access to the MDoubleArray that holds the weights.
This P/R checks for that condition and throws an exception if encountered (this occurs in a part of the plugin that is not using `MStatus` to signal success/failure/error).
> Check skin cluster weights

- cmake/test.cmake
* Add Maya location to LD_LIBRARY_PATH for executable tests.
> MAYA-128070 - Update for USD v23.02

- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/nodes/proxyShapeBase.h
- lib/mayaUsd/utils/utilSerialization.cpp
- lib/usd/ui/layerEditor/mayaSessionState.cpp
- plugin/adsk/scripts/AETemplateHelpers.py
- plugin/adsk/scripts/mayaUSDRegisterStrings.py
- plugin/adsk/scripts/mayaUsd_USDRootFileRelative.py
- plugin/adsk/scripts/mayaUsd_createStageFromFile.mel
When saving/loading root layer as relative to Maya scene file, if Maya scene file doesn't exist, we update the appropriate file path in a postponed fashion, when Maya scene is saved
> MAYA-128504 - As a user, I'd like to load my USD root file as relative before I save my scene file

- lib/usd/ui/layerEditor/layerTreeItem.cpp
Dont' use an invalid pointer when checking if a layer is muted.
> MAYA-128598 fix crash when deleting a stage

- lib/mayaUsd/ufe/Global.cpp
- lib/mayaUsd/ufe/StagesSubject.cpp
- lib/mayaUsd/ufe/UsdAttribute.cpp
- lib/mayaUsd/ufe/UsdAttributeHolder.cpp
- lib/mayaUsd/ufe/private/UfeNotifGuard.h
- test/lib/ufe/testAttribute.py
- test/lib/ufe/testUINodeGraphNode.py
Setting the value of a USD property that previously had the default value for that property creates a USD property-spec, which trigger a USD notification about a property being added. In reality, it is not that a new custom property is added, just that an opinion about a property that is being set.
The attribute editor handled the addition of a property by recreating the UI entirely.
To differentiate between a real property being added and a property getting a non-default value, we now add a guard in the various places where we are setting a value to allow the notification handler to know the difference.
> MAYA-128764 fix AE refresh

- lib/mayaUsd/commands/layerEditorCommand.cpp
Added save / restore to preserve object selection after Undoing Remove SubLayer
> Added save / restore to preserve object selection after Undoing Remove SubLayer

- lib/mayaUsd/ufe/UsdMaterial.cpp
- lib/mayaUsd/ufe/UsdMaterial.h
- test/lib/ufe/testMaterial.py
Extends the UFE Material Interface, mainly intended for internal use in the LookdevX team
- implements `hasMaterial` query that is being introduced in the UFE abstract interface
> MAYA-128783 - Material api: hasMaterial implementation

- lib/mayaUsd/nodes/proxyAccessor.cpp
- lib/mayaUsd/nodes/proxyAccessor.h
- lib/mayaUsd/nodes/proxyAccessor.py
When handling the combined visibility of the edited prim, the code did not work when the prim was directly under the stage.
More precisely, the ProxyAccessor design did not support accessing properties of the absolute root node of a stage. Normally, this would not be a problem since that prim does not have attributes, but for Edit-as-Maya, the combined visibility assumed it could create a SdfPath to the associated property, which is impossible for the root prim.
The solution is to modify the ProxyAccessor code to avoid creating the SdfPath to the property and instead keep the prim path and property name separate in the code. Unfortunately, the way the ProxyAccessor works is by encoding the full path of the property ("prim.property") in the Maya attribute name. So we "cheat" by creating …
> MAYA-129047 allow editing prims directly under the stage

- lib/mayaUsd/nodes/proxyAccessor.cpp
- lib/mayaUsd/utils/utilFileSystem.cpp
- lib/mayaUsd/utils/utilFileSystem.h
- lib/mayaUsd/utils/utilSerialization.cpp
- lib/mayaUsd/utils/utilSerialization.h
- lib/usd/ui/layerEditor/saveLayersDialog.cpp
- test/lib/mayaUsd/utils/CMakeLists.txt
- test/lib/mayaUsd/utils/testUtilsFileSystem.cpp
- Added helper functions to extract and manipulate the numbered suffix of a file name.
- Added a helper function to ensure a filename is unique on-disk.
- Added a helper function to generate the layer file name.
- Use the new function when saving layers.
> MAYA-129186 clearer layer file names

- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/meshViewportCompute.cpp
Updated to use the vertex adjacency API directly to build the vertex adjacency table instead of using Storm specific shared builder computations.
This simplifies the code sightly while avoiding a dependency on API that is being moved from imaging/hd to imaging/hdSt.
Not using a version guard here since the interface we're switching to has been available for a long time.
> Use Hd_VertexAdjacency API directly

- lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.cpp
This should have been an exclusive version check not an inclusive one.
Otherwise, we can't compile against 23.5
> USD 23.5 compatibility: Fix USD version check 

- lib/mayaUsd/ufe/UsdShaderNodeDef.cpp
- lib/mayaUsd/ufe/UsdUndoAddNewPrimCommand.cpp
- lib/mayaUsd/ufe/UsdUndoAddNewPrimCommand.h
- lib/mayaUsd/ufe/UsdUndoMaterialCommands.cpp
- lib/mayaUsd/ufe/UsdUndoMaterialCommands.h
In UsdUndoMaterialCommands, factor out the code related to materials scopes into separate commands and functions. This will allow reusing them and is required by future work (MAYA-128151).
Also, make `UsdUndoAddNewPrimCommand` derive from `SceneItemResultUndoableCommand`. This allows UFE clients to access the newly created prim by calling `SceneItemResultUndoableCommand::sceneItem()`.
> MAYA-129061 - Refactor material commands.

- lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp
Do not call an instances functions when not an instance.
> MAYA-129295 prevent primInfo errors

- lib/mayaUsd/nodes/layerManager.cpp
- lib/mayaUsd/nodes/layerManager.h
- lib/usd/ui/layerEditor/mayaSessionState.cpp
- lib/usd/ui/layerEditor/mayaSessionState.h
- lib/usd/ui/layerEditor/stageSelectorWidget.cpp
- Add a selected stage attribute on the LayerManager Maya node.
- Add functions on the LayerManager node and its internal LayerDatabase class to set and get the currently selected stage.
- Add functions to save and load the selected stage from the attribute.
- Add functions to the Maya session state to retrieve the selected stage from the LayerManager node.
- Add protection to avoid clobbering the selected stage during load, while the UI is being built.
- Make the stage selection widget use the selected stage from the session state when initializing.
- Support selecting the stage via its parent xform.
> MAYA-129309 save and restore selected stage

- lib/mayaUsd/ufe/UsdStageMap.cpp
The error was printed from a utility function to map from a DAG object to a USD stage. Utility functions should not warn, the caller should warn if it realyl thinks it is an error. Here, we are responding to a notification sent in the middle of DAG object deletion, so it is expected that the object is not valid. This shows that printing an error in this case is incorrect.
> MAYA-128939 remove error message on deleting a stage

- lib/mayaUsd/ufe/UsdUINodeGraphNode.cpp
MAYA-129420 - Fix a bug where `UsdUINodeGraphNode::hasPosOrSize()` returned the wrong value.
`hasPosOrSize()` was returning true, even if the underlying `VtValue` was not holding a value.
> MAYA-129420 - Fix a bug where `UsdUINodeGraphNode::hasPosOrSize()` returned the wrong value.

- lib/mayaUsd/utils/utilFileSystem.cpp
- lib/mayaUsd/utils/utilFileSystem.h
- lib/mayaUsd/utils/utilSerialization.cpp
- lib/mayaUsd/utils/utilSerialization.h
- lib/usd/ui/layerEditor/saveLayersDialog.cpp
- lib/usd/ui/layerEditor/saveLayersDialog.h
- plugin/adsk/scripts/mayaUsd_layerEditorFileDialogs.mel
Ability to bulk-save layers with relative paths
> MAYA-129141 - As a user, I'd like to set my anonymous layers as relative in Bulk Save's 'Save As' dialog

- lib/mayaUsd/fileio/schemaApiAdaptor.cpp
- lib/mayaUsd/fileio/schemaApiAdaptor.h
- lib/mayaUsd/fileio/utils/adaptor.cpp
- lib/mayaUsd/fileio/utils/adaptor.h
- lib/mayaUsd/fileio/utils/writeUtil.cpp
- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/python/wrapAdaptor.cpp
- lib/mayaUsd/ufe/UsdAttributeHolder.cpp
- lib/mayaUsd/ufe/Utils.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/fileio/export_misc.cpp
- test/lib/usd/translators/testUsdMayaAdaptor.py
This API change will take effect with the next USD release - 23.08.
> Use new UsdPrimDefintionAPI with latest USD

- lib/mayaUsd/commands/Readme.md
updating readme.md to include Arbitrary Attributes to export options
> MAYA-129268: Update Readme.md

- lib/mayaUsd/ufe/CMakeLists.txt
- lib/mayaUsd/ufe/UsdUndoCreateStageWithNewLayerCommand.cpp
- lib/mayaUsd/ufe/UsdUndoCreateStageWithNewLayerCommand.h
- lib/mayaUsd/ufe/wrapUtils.cpp
- plugin/adsk/scripts/mayaUsd_createStageWithNewLayer.py
- test/lib/ufe/testPythonWrappers.py
Add an undoable command that creates a stage with a new layer.
The new command is a C++ implementation of the existing [mayaUsd_createStageWithNewLayer.py](https://github.com/Autodesk/maya-usd/blob/329d37d0b584b0428b9c43d1f63828cdc04e39b5/plugin/adsk/scripts/mayaUsd_createStageWithNewLayer.py) Python script. The command enables the creation of stages from within the C++ code, which  will be required by future work (MAYA-128151) and might also be generally useful.
This commit also adds a Python binding for the stage creation command, which is used in mayaUsd_createStageWithNewLayer.py to replace the current implementation.
> MAYA-129059 - Add command to create stages.

- lib/mayaUsd/nodes/layerManager.cpp
- lib/usd/ui/layerEditor/mayaLayerEditorWindow.cpp
- lib/usd/ui/layerEditor/mayaSessionState.cpp
- lib/usd/ui/layerEditor/mayaSessionState.h
- Make the Maya session state resgister and unreguster its Maya notification on creation and deletion.
- No longer de-regiuster the notifictions whne the layer manager window is created or closed.
- That was causing the session state to not save the pinned stage because the layer manager would get destroyed before the pinned stage was saved and the notifications would no longer be received.
- When switching pinned stage, mark the Maya scene as dirty.
> MAYA-129309 fixing saving the pinned stage

- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/wrapTranslatorBase.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/wrapTranslatorContext.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/wrapLayerManager.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/wrapProxyShape.cpp
This macro will be removed in USD 23.08. It was only needed to workaround a bug in Visual Studio 2015, which USD no longer supports as of 22.08.
> Deprecate use of TF_REFPTR_CONST_VOLATILE_GET

- lib/mayaUsd/commands/baseExportCommand.cpp
Only use the export roots if no node were specified on the export command-line. Otherwise, it is impossible to export a subset of nodes when usinfg the export roots flag.
> MAYA-128511 fix export roots behaviour

- lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.cpp
Fix for prims not being captured by MayaHydra when a new prim is added to an empty USD Stage in MayaUSD
> HYDRA-318 Fix for prims not being added to empty USD Stage

- lib/mayaUsd/ufe/UsdUndoMaterialCommands.cpp
- lib/mayaUsd/ufe/Utils.cpp
- lib/mayaUsd/ufe/Utils.h
Move `isMaterialsScope()` to a shared location, so that it can be reused by LookdevX.
> MAYA-129682 - Move `isMaterialsScope()` into Utils.

- lib/mayaUsd/fileio/orphanedNodesManager.cpp
After editing-as-Maya and then deleting the stage, the menu for discard edit would not show up or would do nothing. Fix this by correctly updating the pulled information on the Maya node.
- Correctly compute the new pulled path in the case where the stage proxy node no longer exists.
- This happens because as part of deletion, Maya reparents child nodes before deleting them.
- Refactor some common code to extract the list of UFE components from a trie node full path.
> MAYA-127770 missing discard edits

- plugin/adsk/scripts/mayaUsdMenu.mel
When calling the context menu and the mouse is over an object in a set, Maya returns the set instead of the object. Fix this by finding what is under the mouse in the outliner.
> MAYA-126887 fix context menu when in a set

- test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
This test was failing due to our usd export configuration. This change adds the explicit option that was needed to ensure the expected result was produced.
> Add options to UsdExport in new test

- lib/usd/utils/MergePrims.cpp
- test/lib/mayaUsd/fileio/testMergeToUsd.py
Behaviour of the function mergePrims in MergePrims.cpp was changed: 
Before, the function SdfJustCreatePrimInLayer was called for the prim's parent. This way the required "overs" were created up to the prim's parent and therefore the prim itself was created as "def"
Now, we call SdfJustCreatePrimInLayer for the prim itself. This way we create all required "overs" including the prim itself, which is the right behaviour.
> EMSUSD-85 - As a user, I'd like my 'Merge as USD' edits to be specified as overs when authoring to a stronger layer

- lib/mayaUsd/resources/scripts/CMakeLists.txt
- lib/mayaUsd/resources/scripts/mayaUsdClearRefsOrPayloadsOptions.mel
- lib/mayaUsd/resources/scripts/mayaUsdClearRefsOrPayloadsOptions.py
- lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
- lib/mayaUsd/resources/scripts/mayaUsdOptions.py
- lib/mayaUsd/ufe/UsdContextOps.cpp
- plugin/adsk/scripts/mayaUsd_pluginUICreation.mel
- Add command to clear payloads.
- Make commands to clear refs and payloads be undoable.
- Improve Python options utility helpers functions to deal with dictionaries directly.
- Implement clear dialog UI in Python.
- Remember user choices between invocations.
> MAYA-102168 clear payloads

- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
- lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
- plugin/adsk/scripts/CMakeLists.txt
- plugin/adsk/scripts/mayaUSDRegisterStrings.py
- plugin/adsk/scripts/mayaUsdMenu.mel
- plugin/adsk/scripts/mayaUsd_USDRootFileRelative.py
- plugin/adsk/scripts/mayaUsd_imageFileDialogs.mel
- Added an Attribute Editor control template for image assets.
- Added a function to detect that a UFE attribute is an asset.
- Added MEL callback trampolines to Python for the image file dialog.
- Added a usdImageRelativeToEditTargetLayer class to handle the file dialog UI, reusing code for other relative path handling.
- Simplified the layout of the relative file options.
- Don't auto-add the USD extension when browsing for image files.
- Auto-show the image preview in the dialog.
- Select the "All Files" filter by default.
> EMSUSD-109 allow textures to be relative

- doc/codingGuidelines.md
- lib/mayaUsd/fileio/orphanedNodesManager.cpp
- lib/mayaUsd/fileio/primUpdater.cpp
- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/ufe/UsdConnections.cpp
- lib/mayaUsd/ufe/UsdContextOps.cpp
- lib/mayaUsd/ufe/UsdContextOps.h
- lib/mayaUsd/ufe/UsdLight.h
- lib/mayaUsd/ufe/UsdPathMappingHandler.cpp
- lib/mayaUsd/ufe/UsdRotatePivotTranslateUndoableCommand.h
- lib/mayaUsd/ufe/UsdSceneItemOps.h
- lib/mayaUsd/ufe/UsdShaderAttributeDef.cpp
- lib/mayaUsd/ufe/UsdShaderAttributeHolder.cpp
- lib/mayaUsd/ufe/UsdShaderNodeDef.cpp
- lib/mayaUsd/ufe/UsdStageMap.cpp
- lib/mayaUsd/ufe/UsdTransform3d.cpp
- lib/mayaUsd/ufe/UsdTransform3d.h
- lib/mayaUsd/ufe/UsdTransform3dCommonAPI.cpp
- lib/mayaUsd/ufe/UsdTransform3dFallbackMayaXformStack.cpp
- lib/mayaUsd/ufe/UsdTransform3dMatrixOp.cpp
- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
- lib/mayaUsd/ufe/UsdTransform3dReadImpl.cpp
- lib/mayaUsd/ufe/Utils.cpp
- lib/mayaUsd/ufe/XformOpUtils.cpp
- lib/usdUfe/ufe/UsdCamera.h
- lib/usdUfe/ufe/UsdHierarchy.h
- lib/usdUfe/ufe/private/Utils.cpp
- lib/usdUfe/undo/UsdUndoStateDelegate.cpp
We should strive to reduce the number of scenarios under which Maya crashes. Instead, when possible, we should report an error to user and abort the operation. MayaUSD has extensive undo/redo capabilities now and code is able to undo partially done operations. Given this, errors should be reported and propagated back.
The macros TF_AXIOM and TF_FATAL_ERROR cause crashes when their conditions are not met, even in release builds. Remove TF_AXIOM and TF_FATAL_ERROR, replacing them with:
- TF_WARN when the situation was not an error but an unusual situation.
- TF_VERIFY when it still warrant an error message to the user, for example during error handling.
- Simple if/else, with an error return value when not a hard error.
- Simple if when the condition was trivial, like an empty node when …
> MAYA-127095 remove usage of macros leading to fatal exits

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- test/lib/mayaUsd/fileio/testEditAsMaya.py
USD will refuse anyway, so better to prevent showing the option to the user.
> EMSUSD-40 prevent editing instance proxy.

- lib/mayaUsd/ufe/UsdUndoDeleteCommand.cpp
- lib/usdUfe/utils/usdUtils.cpp
- lib/usdUfe/utils/usdUtils.h
- test/lib/ufe/testDeleteCmd.py
- test/testSamples/tree/treeMat.usda
Similar to what is done on Rename, we traverse the scene and clean up any reference, target, or connection that will become invalid once the prim is removed.
> LOOKDEVX-1592 - Clean up references, targets, and connections on delete

- lib/usdUfe/ufe/UsdUndoAddRefOrPayloadCommand.cpp
- Only warn when referencing a mesh with a non mesh.
- The other cases are actually fine.
- Don't prevent referencing, onyl warn.
> Reduce the reference warning

- lib/mayaUsd/utils/util.cpp
- test/lib/usd/translators/CMakeLists.txt
- test/lib/usd/translators/testUsdExport8BitNormalMap.py
When exporting file nodes from Maya to Usd and the file node is referenced, the export code does not recognize that the Maya attributes for scale/bias are not set properly despite these values being correct in the referenced Maya scene. This seems to be because the exporting code is using MPlug::getSetAttrCmds and checking the result to see if it is empty to determine if the values need to be written.
This P/R checks the Dependency node to see if it is from a referenced file, then uses MPlug::isDefaultValue to determine if the plug values need to be authored on the exported Usd data.
Note:
In my past testing, Plug::isDefaultValue seemed unreliable, and I suspect it remains so based on the code using MPlug::getSetAttrCmds, so if there is a better approach, please advise. …
> Referenced shader attributes issue

- lib/mayaUsd/ufe/UsdUndoCreateStageWithNewLayerCommand.cpp
- lib/mayaUsd/ufe/UsdUndoCreateStageWithNewLayerCommand.h
- test/lib/testMayaUsdCreateStageCommands.py
- Do not keep reference to temporarily created DAG modifiers.
- Capture the undo item by using a undo item list and undo recorder.
- Don't hide potential unrelated exceptions.
- Add a unit test for the command.
> EMSUSD-189 fix undo of the stage creation command

- lib/mayaUsd/base/api.h
This was getting picked up implicitly via the include in pxr/base/arch/defines.h but that is getting removed in usd 23.08
> Include pxr header

- lib/usd/ui/layerEditor/saveLayersDialog.cpp
- lib/usd/ui/layerEditor/saveLayersDialog.h
EMSUSD-255 Fixes an issue in Layer Editor where Save All icon was not functioning properly.
The issue occurred due to Qt UI layout changes. The solution is to keep track of the SaveLayerPathRow data separately so that it can be iterated over when saving all layers.
> EMSUSD-255 Fixes an issue in Layer Editor where Save All icon was not functioning properly.

- lib/mayaUsd/ufe/UsdAttribute.h
- lib/mayaUsd/ufe/UsdShaderAttributeHolder.cpp
- test/lib/ufe/testAttribute.py
Allows a downstream client to access the USD data wrapped in a UFE Attribute class.
Also updates core and tests in case MaterialX starts remembering default values for matrix33 inputs.
> LOOKDEVX-1547 - Allow introspecting UsdAttribute UFE class

- lib/mayaUsd/fileio/primReaderRegistry.cpp
If a prim reader doesn't already exist in the registry, the Find function will try to load the "provider" plugin, but was not returning the reader if it was registered during this process. This changes the behavior to return the newly registered reader.
> Return Prim Readers that are loaded in Find

- plugin/al/translators/NurbsCurve.cpp
- plugin/al/translators/tests/testTranslators.py
- plugin/al/usdmayautils/AL/usdmaya/utils/NurbsCurveUtils.cpp
Previously, AL USDMaya was exporting maya NurbsCurves as-is but USD's NurbsCurve spec is different from maya's. From USD's doc, we can see it uses a different knot spec than Maya does:
https://graphics.pixar.com/usd/release/api/class_usd_geom_nurbs_curves.html#details
Also, in Maya's [MFnNurbsCurve](https://help.autodesk.com/view/MAYAUL/2022/ENU/?guid=Maya_SDK_cpp_ref_class_m_fn_nurbs_curve_html) API doc, it says:
```
Managing different knot representations in external applications
Note that some third party applications use a different format for knots, where the number of knots required for a curve is M+2N+1 rather than M+2N-1 as used in Maya. Both knot representations are equivalent mathematically. To convert from one of these external representations into the Maya representation, …
```
> [al]Updating AL USDMaya's NurbsCurve static import export to use USD's curve spec

- lib/mayaUsd/ufe/UsdLight.cpp
- lib/mayaUsd/ufe/UsdLightHandler.cpp
Create USD light from USD will cause the bug. The root cause is that those shadow attributes are never added to the USD created lights. So create Shadow attributes at first query if the attribute is not created
> EMSUSD-77 - Newly created USD Lights can't cast shadows

- lib/mayaUsd/fileio/primWriter.h
- lib/mayaUsd/fileio/primWriterRegistry.cpp
- lib/mayaUsd/fileio/primWriterRegistry.h
- lib/mayaUsd/fileio/shaderWriter.h
- lib/mayaUsd/fileio/shaderWriterRegistry.cpp
- lib/mayaUsd/fileio/shaderWriterRegistry.h
- lib/mayaUsd/fileio/shading/symmetricShaderWriter.cpp
- lib/mayaUsd/fileio/utils/adaptor.cpp
- lib/mayaUsd/fileio/writeJobContext.cpp
- lib/mayaUsd/fileio/writeJobContext.h
- lib/mayaUsd/python/wrapPrimWriter.cpp
- lib/usd/pxrUsdPreviewSurface/usdPreviewSurfaceWriter.cpp
- lib/usd/translators/shading/mtlxBaseWriter.cpp
- lib/usd/translators/shading/mtlxSymmetricShaderWriter.cpp
- lib/usd/translators/shading/usdDisplacementShaderWriter.cpp
- lib/usd/translators/shading/usdFileTextureWriter.cpp
- lib/usd/translators/shading/usdMaterialWriter.cpp
- test/lib/mayaUsd/fileio/testPrimWriter.py
- test/lib/mayaUsd/fileio/testShaderWriter.py
- Add `CanExport` function to primWriter for overriding default primWriter
- Overload the Register function for backward support
- Add `Poke `function for cases when only wants to check for plugin register but not really find a primWriter
> EMSUSD-101 Override primWriter

- lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.cpp
The inputArgs to the HdFlatteningSceneIndex now map names of data sources to HdFlattenedDataSourceProvider. An implementation of such a provider can implement different policies.
> Use new HdFlattenedDataSourceProvider

- lib/mayaUsd/resources/scripts/mayaUsdAddMayaReference.mel
- lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.mel
- lib/mayaUsd/ufe/MayaUsdContextOps.cpp
- plugin/adsk/scripts/mayaUsd_USDRootFileRelative.py
- Prepare the current edit target before showing the file dialog.
- Make the function used for this preparatio clearer by naming the flag passed to disable the option for using the scene file as the relative root. When making things relative to the edit target, we don't want to accidentlly use the scene as the root when no saved layer exist.
- Make the code creating the dialog for Maya ref use the code to make the path relative.
- Change the label of the seperator in the file dialog.
- Refactor the common Python code to avoid passing around some options and at teh same time make the function override have the same parameters. Having the same paarmeters is necessary since differnt classes will end-up calling different functions with the same parameters.
- Split the code that create the …
> EMSUSD-256 allow Maya ref to be relative to the layer.

- plugin/adsk/scripts/mayaUSDRegisterStrings.mel
- plugin/adsk/scripts/mayaUsdTranslatorImport.mel
- Embed import options in subheading
- Change the style from progressive disclosure to Maya style (grey out children options when parent unselected)
> EMSUSD-278 - Embed import options in subheadings 

- lib/usd/translators/shading/shadingTokens.h
- plugin/adsk/scripts/mayaUSDRegisterStrings.mel
- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
> EMSUSD-279 - Change the export options to be consistent with import options

- lib/usdUfe/ufe/UsdUndoAddRefOrPayloadCommand.cpp
- test/lib/ufe/testReferenceCommands.py
If a reference or payload does not contain a default prim, let the reference or payload loading fail instead of selecting the first prim of the file. Remove the related test.
> EMSUSD-306 don't use a random default prim

- lib/mayaUsd/base/tokens.h
- lib/mayaUsd/resources/ae/usdschemabase/custom_image_control.py
- lib/mayaUsd/resources/scripts/cacheToUsd.py
- lib/mayaUsd/resources/scripts/mayaUsdAddMayaReference.mel
- lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
- lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
- lib/mayaUsd/resources/scripts/mayaUsdUtils.py
- lib/mayaUsd/ufe/MayaUsdContextOps.cpp
- lib/mayaUsd/utils/layers.cpp
- lib/mayaUsd/utils/layers.h
- lib/mayaUsd/utils/mayaEditRouter.cpp
- lib/usd/translators/mayaReferenceEditRouter.md
- lib/usdUfe/utils/layers.cpp
- lib/usdUfe/utils/layers.h
- plugin/adsk/scripts/mayaUsd_USDRootFileRelative.py
- test/lib/mayaUsd/fileio/testCacheToUsd.py
- Move the Python function getCurrentTargetLayerDir to the mayaUsdUtils file for reuse.
- Change section label to "Author Cache File to USD".
- Combine description text to improve the layout spacing.
- Add UI to make the cache file relative to the targeted layer.
- Add a new cache edit router parameter to control if the cache file is relative.
- Document the new edit router parameter in the user documentation.
- Modify the Python createCacheCreationOptions to allow specifying if we want relative paths.
- Pass the parameter when caching from the caching file dialog.
- Refactor C++ functions to get the edit target file path and folder to be reusable.
- Use the new C++ functions in the context menu and caching code.
- In the Maya reference edit router, add the cache payload or reference to …
>  EMSUSD-259 relative Maya ref cache

- lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
- lib/mayaUsd/resources/scripts/mayaUsdMayaReferenceUtils.py
Adding the required tooltip to the LoadPayload checkbox
> EMSUSD-308 - USD reference/Payload: "Load Payload" on the browser dialog should have a tooltip.

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/resources/scripts/cacheToUsd.py
- plugin/adsk/plugin/exportTranslator.cpp
- plugin/adsk/scripts/mayaUSDRegisterStrings.mel
- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
- Add the option menu for relative textures in the export UI-builder.
- Add the code to fill and extract the selected option to and from the UI.
- Add the required labels and tool-tips.
- Fix the problem that the export code was never able to export relative paths when goign through the UI becuase the output file argument was never set in merge-to-USD, cache-to-USD and duplicate.
> EMSUSD-263 export relative textures UI

- lib/usdUfe/ufe/Global.cpp
- lib/usdUfe/ufe/Global.h
- lib/usdUfe/ufe/UsdContextOps.cpp
- lib/usdUfe/ufe/Utils.cpp
- lib/usdUfe/ufe/Utils.h
1. Fixed usdUfe context ops to toggle the visibility. The visibility we want to toggle is the _computed_ visibility, not the authored visibility.
2. Exposed isRootChild as a an optional DCC function. Previous behavior kept as default (assumes more than one UFE runtime active, i.e. the maya case).
> EMS-310 Usd Context Ops, fixed toggle visibility to used computed visibile + expose isRootChild as a DCC function.

- lib/mayaUsd/base/tokens.h
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.h
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- Added optionVar "mayaUsd_ShowDisplayColorTextureOff" to toggle display mode
- The optionVar will be add to user Pref once the feature is ready. 
- To view the change in real time, run `ogs -reset`. This command will be added to the user pref call as well, so the user can see the difference when toggle the optionVar
> EMSUSD-121 - Use display color when texture mode is disabled

- CMakeLists.txt
- build.py
Following the move to enable MaterialX as default introduced in PR #2979, this enables the same option for people building using CMake directly.
> Enable MaterialX support in CMake

- lib/usdUfe/ufe/StagesSubject.cpp
- lib/usdUfe/ufe/UsdUndoAddNewPrimCommand.cpp
- test/lib/ufe/testDeleteCmd.py
- test/lib/ufe/testObservableScene.py
Fixed bad notification translation. See comments in PR. 
(also see https://forum.aousd.org/t/what-are-inert-prims/330)
Also fixed a thrown exception when object add fails for whatever reason.
> EMSUSD-266 Fixed bad USD/UFE notifications

- lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.cpp
- lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.h
To support USD Animation, like SceneDelegate, we need to set Time to SceneIndex for Hydra Viewport.
To do that, we add changes below:
1.React on the Maya timeChanged event.
2.Set current Time from proxy node to USDImagingStageSceneIndex on initialization or time was changed
> connect Maya Time to USD Imaging SceneIndex

- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
* Fix for broken template with different Ufe versions.
> EMSUSD-596 - AE: broken templates on older maya versions

- lib/mayaUsd/utils/utilFileSystem.cpp
- lib/usd/ui/layerEditor/loadLayersDialog.cpp
- plugin/adsk/scripts/mayaUsd_USDRootFileRelative.py
- plugin/adsk/scripts/mayaUsd_layerEditorFileDialogs.mel
- Fix helper functions when the layer folder is empty.
- Don't use the current directory when there is no file path.
- Register the necessary callbacks.
- Simplified code logic in Python relative file code to be more linear.
> EMSUSD-311 fix load sub-layer file preview.

- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
Some error checking logging was confusing for the user. Some failures were reported as the cryptic: "Failed verification: ' result == MStatus::kSuccess '".  This leads users to think we are reporting a success. (Technically we were reporting failure to succeed, but the message was worded confusingly.)
Change those failure verification messages to use explicit warning messages instead. This provides clearer failure diagnostics.
> EMSUSD-59 make error messages more clear

- lib/mayaUsd/fileio/translators/translatorMesh.cpp
- lib/usd/translators/meshReader.cpp
- test/lib/usd/translators/testUsdImportInstances.py
- When in a prototype, do not create an extra transform node.
- Adjust the related import tests, which were already mentioning those extra nodes.
> EMSUSD-80 avoid creating an extra transform when in a prototype

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/ufe/Global.cpp
- lib/mayaUsd/ufe/UsdAttributes.cpp
- lib/mayaUsd/ufe/Utils.cpp
- lib/mayaUsd/ufe/Utils.h
- lib/usdUfe/python/wrapUtils.cpp
- lib/usdUfe/ufe/Global.cpp
- lib/usdUfe/ufe/Global.h
- lib/usdUfe/ufe/Utils.cpp
- lib/usdUfe/ufe/Utils.h
- test/lib/ufe/testContextOps.py
- test/lib/ufe/testDuplicateCmd.py
- test/lib/ufe/testPythonWrappers.py
* Added optional DCC function for uniqueChildName() and override the UsdUfe one with Maya version: uniqueChildNameMayaStandard().
* Split out numerical suffix handling in UsdUfe::uniqueName() into separate helper function.
* When creating new unique name take into account length of numerical suffix (when padded with 0's).
* Added new unit tests to testDuplicateCmd to test all these naming rules.
> EMSUSD-533 - Incremental naming doesn't take zero into consideration

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- test/testSamples/MaterialX/ShadedPyramid.usda
The MaterialX topological node list was in need of an update:
For MaterialX 1.38.7:
"dot" nodes are now topological.
Via https://github.com/AcademySoftwareFoundation/MaterialX/pull/1152
For upcoming MaterialX 1.38.8:
"dot" node no longer elided (except for filenames) "switch" node no longer elided
Via https://github.com/AcademySoftwareFoundation/MaterialX/pull/1522
> EMSUSD-612 - Update topo node list

- lib/mayaUsd/commands/layerEditorCommand.cpp
- lib/mayaUsd/utils/layerMuting.cpp
- lib/mayaUsd/utils/layerMuting.h
- test/lib/mayaUsd/fileio/testAddMayaReference.py
- test/testUtils/usdUtils.py
- Add a global functionality to hold onto muted layers.
- This is to work around the fact that OpenUSD will not keep muted layers in memory.
- Make sure to clean up the list of muted layers when a new Maya scene is created.
- Use the muted layer holder in the MuteLayer command.
- The base class of the command was trying to hold onto layer, but when the undo stack is cleared, so would be the anonymous layers.
- In particular, when unloading a Maya Reference, Maya always clears the undo stack.
- Add a test that check if muted anonymous layers are lost when editing a Maya Reference.
- The test fails without my fix, works with it.
- Improved test helper functions to enable creating anonymous sub-layers.
> EMSUSD-277 fix lost muted anonymous layers

- test/lib/mayaUsd/utils/testMaterialCommands.py
- test/lib/ufe/testUIIcons.py
- test/testSamples/material/materialAssignment.usda
UsdSkelPackedJointAnimation is deprecated and can safely be removed from tests
> Add versioning to tests that use UsdSkelPackedJointAnimation 

- lib/mayaUsd/nodes/proxyShapeStageExtraData.cpp
- lib/mayaUsd/nodes/proxyShapeStageExtraData.h
- lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.cpp
- lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.h
Maya crashes when the MayaUsdProxyShapeSceneIndex tries to access MayaUsdProxyShape which is no longer valid.  This event happens for example in the case seen here in the reivew code to set time on the USD Stage. In this situation a Maya callback registered for "timechanged" event was also triggered on "New Scene" event but the USD and Hydra resources were deleted by then on which the callback tried to set the time and hence the crash.
The fix involves adding new API to MayaUsdProxyShapeStageExtraData which is a container of sorts for MayaUsdProxyShapeBase. The API allows to check if the proxy shape requested is valid.
> HYDRA-496: Fix for crash on new scene with a USD Stage inside the Maya scene

- lib/mayaUsd/utils/utilFileSystem.cpp
- lib/usd/ui/layerEditor/loadLayersDialog.cpp
When no parent layer exists, use the project folder by default instead of the current directory.
> EMSUSD-623 use project folder by default

- CMakeLists.txt
- build.py
- cmake/modules/FindMaya_Qt.cmake
- lib/mayaUsd/CMakeLists.txt
- lib/usd/CMakeLists.txt
- lib/usd/ui/CMakeLists.txt
- lib/usd/ui/importDialogDemo/CMakeLists.txt
- plugin/adsk/plugin/CMakeLists.txt
* New logic in build.py (during configure stage) to "setup Maya Qt" by looking for Qt headers in Maya devkit. If not found, extract either just the header from "qt*-include.zip" for Qt5 or the entire zipfile for Qt6.
* Deprecated the "--qt-location" flag from build.py.
* New cmake module "FindMaya_Qt" used for Qt5.
* Use versionless Qt targets.
This will solve issue #1070 by finding and building with Qt from Maya devkit for all supported versions of Maya.
> EMSUSD-282 - MayaUsd: build with Qt directly from Maya devkit/runtime

- lib/mayaUsd/resources/ae/usdschemabase/custom_image_control.py
- lib/usd/ui/layerEditor/layerEditorWidget.cpp
- lib/usd/ui/layerEditor/saveLayersDialog.cpp
- lib/usd/ui/layerEditor/stringResources.h
- plugin/adsk/scripts/CMakeLists.txt
- plugin/adsk/scripts/mayaUSDRegisterStrings.mel
- plugin/adsk/scripts/mayaUSDRegisterStrings.py
- plugin/adsk/scripts/mayaUsd_USDRootFileRelative.py
- plugin/adsk/scripts/mayaUsd_pluginUICreation.mel
- plugin/adsk/scripts/mayaUsd_pluginUIDeletion.mel
- plugin/adsk/scripts/mayaUsd_preferenceTab.mel
- plugin/adsk/scripts/usdFileSaveOptions.mel
* New MEL file "mayaUsd_preferenceTab.mel" containing the USD preference dialog code. Added when mayaUsdPlugin is loaded.
* Removed "saving usd files" options from LayerEditor and move them to USD preferences.
* New optionVar for Image relative.
* For LE bulk saveas, set the initial state of relative checkboxes from optionVars.
* In LE fixed initial dialog size.
> EMSUSD-287 - Setup preference section

- lib/usdUfe/ufe/StagesSubject.cpp
When undoing a visibility command, UsdNotice::ObjectsChanged does not produce a path for Info Change but still generates a path for Re-sync Change which has the Visibility token. The special case is added to refresh when in the latter path.
> EMSUSD-490 Fixes outerliner not refreshing when performing a UsdUndoVisibleCommand

- build.py
The Qt6 archive in the Maya devkit was renamed. Adapt to that rename, supporting both old and new names.
> Qt6 archive in Maya devkit was renamed.

- lib/mayaUsd/ufe/UsdTransform3dMatrixOp.cpp
- lib/usdUfe/ufe/UsdUndoInsertChildCommand.cpp
- lib/usdUfe/utils/layers.cpp
- lib/usdUfe/utils/layers.h
- test/lib/ufe/testParentCmd.py
- test/testSamples/relativeSubLayer/root.usda
- test/testSamples/relativeSubLayer/sublayer.usda
There were multiple problems that triggered each others to cause a crash when using relative sub-layers. The problems were:
- The relative sub-layer was not found.
- This cause the code that applies the reparenting to all layers to do no work.
- This would cause the prim to vanish.
- This would cause the transform command to crash because it did not check that the scene item was valid.
The corrections done are:
- Fix the getAllSubLayers helper function to use FindRelativeToLayer to find sub-layers, in case they are relative to their parent. Otherwise it would fail to find sub-layers.
- Modify the applyToAllPrimSpecs, applyToAllLayersWithOpinions and applyToSomeLayersWithOpinions helper functions to return the number of layers that were affected.
- This allows the caller to detect if no …
> EMSUSD-489 fix reparenting crash

- lib/mayaUsd/ufe/MayaUsdContextOps.cpp
- lib/mayaUsd/utils/utilFileSystem.cpp
- plugin/adsk/scripts/mayaUSDRegisterStrings.py
- plugin/adsk/scripts/mayaUsd_USDRootFileRelative.py
This also fixes [EMSUSD-634] - Error when attempting to add a Maya Reference.
> EMSUSD-644 - As a user, I'd like to add a relative payload/ref on a anonymous layer

- lib/mayaUsd/resources/scripts/mayaUsdUtils.py
EMSUSD-630 Enabled Load Payload By Default On Add Payload UI
> EMSUSD-630 Enabled Load Payload By Default On Add Payload UI

- test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateDisplayLayers.py
- test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateUSDPreviewSurface.py
Certain baselines assume Y-up. Explicitly set this so tests pass in various environments
> Explicitly set UpAxis in tests

- lib/mayaUsd/python/wrapUtil.cpp
- lib/mayaUsd/resources/ae/usdschemabase/custom_image_control.py
- lib/mayaUsd/resources/scripts/mayaUsdAddMayaReference.mel
- lib/mayaUsd/resources/scripts/mayaUsdAddMayaReference.py
- lib/mayaUsd/utils/utilFileSystem.cpp
- lib/mayaUsd/utils/utilFileSystem.h
- plugin/adsk/scripts/mayaUSDRegisterStrings.py
Postponed processing of relative asset paths assigned to anonymous layers
> EMSUSD-645 - As a user, I'd like to add a relative file dependency on a anonymous layer

- lib/mayaUsd/fileio/shading/shadingModeUseRegistry.cpp
When exporting prims to USD that have Lambert materials , some extra nodes were being exported that would later cause a crash due to the mismatch between input nodes and uv sets. This fixes the issue by changing to depth first when traversing the node graph and only exporting nodes that are supposed to be part of the graph.
> EMSUSD-549 Fixes unneeded nodes getting exported on materials

- lib/mayaUsd/nodes/proxyShapeBase.cpp
For details and discussions please see this github issue: https://github.com/Autodesk/maya-usd/issues/3243
The idea is to check if the cache is actually connected (for example bifrost graph), if not this is not actually an incoming stage
> EMSUSD-499 - Dirty layers don't get saved in Maya files

- plugin/adsk/scripts/USDMenuProc.mel
We must create the pop-up menu explicitly, otherwise the menu fails to show in some circumstances.
> EMSUSD-715 fix context menu in viewport

- lib/usdUfe/python/wrapCommands.cpp
- lib/usdUfe/ufe/UsdUndoClearDefaultPrimCommand.cpp
- lib/usdUfe/ufe/UsdUndoClearDefaultPrimCommand.h
- lib/usdUfe/ufe/UsdUndoSetDefaultPrimCommand.cpp
- lib/usdUfe/ufe/UsdUndoSetDefaultPrimCommand.h
- lib/usdUfe/ufe/Utils.cpp
- lib/usdUfe/ufe/Utils.h
- plugin/adsk/scripts/AETemplateHelpers.py
- plugin/adsk/scripts/AEmayaUsdProxyShapeBaseTemplate.mel
- test/lib/ufe/CMakeLists.txt
- test/lib/ufe/testDefaultPrimCmds.py
- test/lib/ufe/testGroupCmd.py
- test/lib/ufe/testParentCmd.py
- test/lib/ufe/testRename.py
- test/testSamples/defaultPrimInSub/root.usda
- test/testSamples/defaultPrimInSub/sub.usda
- Add a applyRootLayerMetadataRestriction helper function to enforce not modifying the root layer metadata when not targeting the root layer.
- The only restriction applied is about the default prim.
- Call it from within the applyCommandRestriction helper function.
- Call it from within the default prim commands.
- Add unit tests for the rename, parent and group default prim restrictions.
- Add tests for the default prim commands.
> EMSUSD-632 prevent root metadata changes when not targeting root

- plugin/adsk/scripts/USDMenuProc.mel
EMSUSD-772 - Fixes Edit-As-Maya Option Dialog Not Executing Action 
EMSUSD-740 - Updates the "Apply" button's logic to conform with the new design. It should also execute the action.
> EMSUSD-772 - Fixes Edit-As-Maya Option Dialog Not Executing Action

- lib/mayaUsd/ufe/MayaUsdContextOps.cpp
- lib/mayaUsd/ufe/MayaUsdContextOps.h
- lib/mayaUsd/ufe/UsdUndoMaterialCommands.cpp
- lib/usdUfe/ufe/UsdContextOps.cpp
- lib/usdUfe/ufe/UsdContextOps.h
- test/lib/ufe/testContextOps.py
EMSUSD-626: As a layout artist, I'd like to toggle visibility of multiple prims
* Added bulk edit menu support to base UsdContextOps class.
* Override in MayaUsdContextOps to add Maya specific menu items.
* Assign New Material / Assign Existing Material - both of these now only work on single prim if context item is not in selection.
* Fix contextOps unit test because of spec change with material context menu items and selection.
* Added unit test for bulk edit contextOps.
> EMSUSD-626: As a layout artist, I'd like to toggle visibility of multiple prims

- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
The export types checkboxes will follow the options the user made last time, instead of always checking to true. For example, if the user chose to export mesh only last time, then the next time export window opens up, only "Mesh" will be set to true
> EMSUSD-732 - USD Export Options are always set to "on"

- lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
- lib/mayaUsd/resources/scripts/mayaUsdMayaReferenceUtils.py
- Disable to code that auto-fills the prim path when creating a ref or payload.
- We are keeping the code because we think we likely will put it back in the next release under an advance option.
- Update the tooltip to be clearer and remove text about auto-filling.
> EMSUSD-254 disable the default prim auto-filling.

- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
Disable the material section when user excludes Meshes from export. Currently the material is attached to the mesh so when the mesh is not exported, the material can not be exported either.
> EMSUSD-550 - Disable Material section when Mesh type is excluded from export

- lib/usdUfe/ufe/StagesSubject.cpp
- test/lib/ufe/testObject3d.py
Previously we fixed the Undo command that wasn't triggering a visibility update on the Outliner.
This change is about fixing the Re-do which is a different attribute event.
> EMSUSD-490 Fixes Redo Visibility Visual Update in Outliner

- lib/mayaUsd/commands/abstractLayerEditorWindow.h
- lib/mayaUsd/nodes/layerManager.cpp
- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/utils/utilSerialization.cpp
- lib/usd/ui/layerEditor/mayaLayerEditorWindow.cpp
- lib/usd/ui/layerEditor/mayaLayerEditorWindow.h
- lib/usd/ui/layerEditor/mayaSessionState.cpp
- lib/usd/ui/layerEditor/mayaSessionState.h
- test/lib/mayaUsd/nodes/testProxyShapeBase.py
The interaction between how the stage were initially open or created and how they were updated did not match. This caused the code that attempted to update the stage cache when saving anonymous layers to fail to achieve its goal. This led to the proxy shape next compute to fail to find the original session layer. This caused the information about edited-as-Maya prim to be lost. This resulted in the stage being in a weird state where a Maya reference prim was edited but the stage had forgotten about it.
Fix the code so that the way the stage os open in the proxy shape and in the function that update the stage cache match.
- Changed how the proxy shape open the USD stage by always initially not loading payloads.
- Also, do not pass an explicit resolver as it would affect which stage could …
> EMSUSD-749 fix how stages are updated when saved

- cmake/compiler_config.cmake
* USD v23.11 was updated to C++ 17
* Boost fix for older Maya versions with USD v23.11
> EMSUSD-675 - Support for USD v23.11

- lib/mayaUsd/render/MaterialXGenOgsXml/CMakeLists.txt
- lib/mayaUsd/render/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
- lib/mayaUsd/render/MaterialXGenOgsXml/OgsFragment.cpp
- lib/mayaUsd/render/MaterialXGenOgsXml/OgsFragment.h
- lib/mayaUsd/render/MaterialXGenOgsXml/OgsXmlGenerator.h
- lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.cpp
- lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.h
- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- test/lib/mayaUsd/utils/CMakeLists.txt
- test/lib/mayaUsd/utils/materialx_test_data/Channel1_topo.mtlx
- test/lib/mayaUsd/utils/materialx_test_data/Channel4_topo.mtlx
- test/lib/mayaUsd/utils/materialx_test_data/Interface2_topo.mtlx
- test/lib/mayaUsd/utils/materialx_test_data/MultiOut6_topo.mtlx
- test/lib/mayaUsd/utils/materialx_test_data/topology_tests.mtlx
- test/lib/mayaUsd/utils/test_ShaderGenUtils.cpp
Implements a topo neutral graph generator. This allows detecting that two native MaterialX shading graphs are topologically equivalent, generate universal shading code, and provide the right mapping to find the original node name corresponding to a renamed node.
Also adds proper exports to allow rebuilding the old MaterialX Maya surface node using this new functionnality. This also requires fixing the generated code to properly handle the "texcoord" nodes variables used in the shader.
> LOOKDEVX-2124 - MaterialX Topo Handler

- lib/mayaUsd/nodes/layerManager.h
- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/nodes/proxyShapeBase.h
- test/lib/ufe/CMakeLists.txt
- test/lib/ufe/testDuplicateProxyShape.py
The crash occurred in deeply nested callbacks-within-callbacks. There were attributes being set which triggered dirtynes, which triggered computation, which triggered atribute updates, which triggered proxy accessor, etc. In the end, some code accessed the proxy shape Maya node while it was not in a valid state to be accessed.
The ultimate cause was that, surprinsingly, never during the duplication of a node does the node has its final name, in any of the usual callbacks. During the postConstruct callback, it doesn't have a name. During the copyInternal callback, it does not have a name. But the proxy shape wants to know its ownname when it registers some callbacks. The end-result was that during save, the node was discovering that it had a new name and it brought the house down.
The fix …
> EMSUSD-604 fix crash when duplicating a proxy shape

- lib/mayaUsd/fileio/primReaderRegistry.h
This include is required for the Usd Type reader registry definition. The include was being picked up at the callsite
> Add missing include

- test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateMaterialX.py
* Disabled test that is failing with USD 23.11 because of problem in Usd. https://github.com/PixarAnimationStudios/OpenUSD/issues/2800
> EMSUSD-675 - Build USD v23.11 with Python 3.11/OSD 3.6 and update ecg-maya-usd

- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
- lib/usdUfe/ufe/UsdUndoToggleActiveCommand.cpp
- lib/usdUfe/ufe/UsdUndoToggleInstanceableCommand.cpp
- test/lib/ufe/testContextOps.py
(This also covers EMSUSD-790.)
- Make the internal commands used to toggle activation or instanceable flag enfore edit restrictions.
- Make the corresponding code in the attribute editor also use these commands.
- Add unit tests for the new restrictions.
> EMS-789 apply restrictions for activation and instanceable

- lib/mayaUsd/fileio/writeJobContext.cpp
- lib/mayaUsd/utils/util.cpp
- lib/mayaUsd/utils/util.h
- test/lib/mayaUsd/fileio/testCacheToUsd.py
- The issue is caused by transforms merged to parent node, which will cause a mismatch between SDF and DAG paths and ultimately cause clashes. We should only write to the node's parent node when it a shape node.
- Removed the `channel1` part of the unity test because that attribute is created because of the bug above. I compared the cache to usd result to a normal export and the files matches (there's no `channel1 ` in normal export usd files)
> EMSUSD-603 - Errors when trying to cache a rig with merge transforms ON and namespaces OFF

- lib/usdUfe/ufe/StagesSubject.cpp
There are cases where we need a subtree invalidate (see comment). We are not able parse the entries and know when we do or not... be safe and always invalidate if no notification is sent.
> EMSUSD-796 Send subtree invalidate on undo mark instanceable.

- lib/mayaUsd/nodes/layerManager.cpp
When Maya copies a Maya node, it actually export the selected nodes into a temporary file. When the node is a MayaUSD node, this export automatically prompt the user to save the dirty USD files. To avoid this, we now detect that we are exporting due to a copy operation and force saving the USD layer into the temporary Maya scene file.
> EMSUSD-647 fix copying the proxy shape node

- lib/mayaUsd/ufe/MayaUsdUIInfoHandler.cpp
- lib/mayaUsd/ufe/MayaUsdUIInfoHandler.h
- lib/usdUfe/ufe/UsdUIInfoHandler.cpp
Allows any renderer like Arnold, VRay, or RenderMan to provide outliner icons for their custom nodes.
> LOOKDEVX-2260 - Add a third party naming convention for shader outliner icons

- lib/usdUfe/ufe/Utils.cpp
- lib/usdUfe/utils/layers.cpp
- test/lib/ufe/CMakeLists.txt
- test/lib/ufe/testVariant.py
- test/testSamples/variantInRef/layout/assets/asset.usda
- test/testSamples/variantInRef/layout/assets/geo_variants.usda
- test/testSamples/variantInRef/layout/layout.usda
- test/testSamples/variantInRef/shot.usda
- Fix getStrongestLayer to find layers relative to their parent layer.
- Fix the reporting of unknown layers with a clearer message.
- Add a unit test for switching a variant in a sub-layer.
- Add a unit test for switching a variant in a sub-layer when the variant is in a reference.
> EMSUSD-126 fix finding strongest layer.

- lib/usd/ui/layerEditor/layerTreeItem.cpp
- lib/usd/ui/layerEditor/layerTreeView.cpp
Relevant change is the removal of the call to isReadOnly(). I refactored the function to avoid nested if and complex conditional that are hard to understand. Also commented on what each condition aims to do.
> EMSUSD-852 allow saving locked layers

- cmake/modules/FindUFE.cmake
* Temporary setting of UFE_PREVIEW_VERSION_NUM while we transition to UFE v5.0.0.
> EMSUSD-875 - MayaUSD : Bump UFE version to v5.0

- lib/mayaUsd/ufe/Global.cpp
- lib/mayaUsd/ufe/MayaUsdContextOps.cpp
- lib/usdUfe/ufe/CMakeLists.txt
- lib/usdUfe/ufe/Global.cpp
- lib/usdUfe/ufe/Global.h
- lib/usdUfe/ufe/UsdContextOps.cpp
- lib/usdUfe/ufe/UsdUndoLongDurationCommand.cpp
- lib/usdUfe/ufe/UsdUndoLongDurationCommand.h
- lib/usdUfe/ufe/Utils.cpp
- lib/usdUfe/ufe/Utils.h
- Add a USD UFE long-duration command to wrap other commands that may take a long time to run.
- Add two DCC-specific functions to start and stop the wait cursor.
- Add start/stop helper functions.
- Add a wait cursor class to automatically start and top the wait cursor.
- Wrap the load and unload payload commands in a long-duration command.
- Adjust existing commands that used a wait cursor to use the global helper class instead.
> EMSUSD-65 use wait cursor for payload commands

- README.md
this is a small change to improve the find-ability  of the release page to point users to the installers location.
> Update README.md with a link to the release page

- lib/usdUfe/ufe/UsdContextOps.cpp
* Set the bulk menu header as a header item (using metadata). Newer Maya versions will detect this metadata and draw the item as a header.
> EMSUSD-799: See the bulk menu look modern and up to date with VXD

- lib/usdUfe/ufe/UsdUndoInsertChildCommand.cpp
- test/lib/ufe/testParentCmd.py
Adjust the parenting UFE command to allow parenting under a prim defined in a lower layer.
Add a unit test to validate the fix. Failed before the fix, now works.
> EMSUSD-756 allow parenting under a stronger layer

- lib/mayaUsd/utils/utilSerialization.cpp
Fixes USDZ extension not being accepted in prim hierarchy view.
> EMSUSD-761 - Fixes USDZ extension not being accepted in prim hierarchy view

- lib/mayaUsd/nodes/proxyShapeBase.cpp
- test/lib/mayaUsd/nodes/ProxyShapeBaseTest/CubeModel.usda
- test/lib/mayaUsd/nodes/testLayerManagerSerialization.py
- test/lib/mayaUsd/nodes/testProxyShapeBase.py
When reloading a scene that contained layers serialized directly in the scene, sub-layers would be lost because they were anonymous layers but on reload that status was lost and the sub-layer would be lost whenever the stage got recomputed.
Fix this by remembering that the sub-layer are anonymous on reload.
Add unit test to verify lost layer fix
- Add comments to the layer manager serialization test and fix the layer being targeted.
- Refactor common code in proxy shape saving tests.
- Add more checks in the proxy shape saving test to verify that the contents are correct after reload and after recompute.
> EMSUSD-671 fix reloading scene with layers saved in the Maya scene

- lib/mayaUsd/fileio/shaderReader.h
This was implicitly included via sdf/allowed.h, but has been removed from that header.
> Add explicit boost/optional include

- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
- lib/mayaUsd/resources/ae/usdschemabase/attribute_custom_control.py
- lib/mayaUsd/resources/ae/usdschemabase/custom_enum_control.py
- lib/mayaUsd/resources/ae/usdschemabase/custom_image_control.py
* Use tooltip cleaning method similiar to UsdView to remove leading whitespace from multi-line doc strings.
* Added tooltips to all attributes.
> EMSUSD-181: Tooltips are not formatted correctly

- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/nodes/proxyShapeBase.h
- lib/mayaUsd/python/CMakeLists.txt
- lib/mayaUsd/python/module.cpp
- lib/mayaUsd/python/wrapLoadRules.cpp
- lib/mayaUsd/utils/loadRules.h
- lib/mayaUsd/utils/loadRulesAttribute.cpp
- lib/usdUfe/utils/loadRules.h
- lib/usdUfe/utils/loadRulesText.cpp
- plugin/adsk/scripts/AETemplateHelpers.py
- plugin/adsk/scripts/mayaUsd_createStageFromFile.mel
- test/lib/mayaUsd/nodes/testProxyShapeBase.py
Instead, we will always use the existing payload rules dynamic attribute.
- Remove the "loadPayloads" attribute from the proxy shape.
- Add Python binding to new functions to set and retrieve if all payloads are loaded or not.
- Split-up existing load-rules helper functions to give more fined-grained access to the saved load rules in order to support the Python API.
- Use the new Python helper functions when creating or loading a stage.
- Adjust one unit test.
> EMSUSD-671 Remove the load payloads proxy shape attribute

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/ufe/UsdUndoDuplicateCommand.cpp
- lib/mayaUsd/ufe/Utils.cpp
- lib/mayaUsd/ufe/Utils.h
- lib/mayaUsd/utils/traverseLayer.cpp
- lib/usdUfe/ufe/Utils.cpp
- lib/usdUfe/ufe/Utils.h
The goal is to solve problems with duplicating Maya node to USD when using the Arnold configuration. The main problem is that Arnold authors the materials used by the prim corresponding to the duplicated Maya node outside of the USD prim. The duplicate code was expecting to copy a single prim and its children.
To solve this, we add code to follow relationships and connections inside the new prim and also copy the targets of these relationships and connections.
Improve the traverseLayer function:
- Avoid infinite recursion by tracking which path have already been traversed.
- Correctly traverse relationships and not stop at first non-prim item.
- It worked for the original use case (prim updater) because that use case always pruned the traversal under each prim, avoiding traversal of …
> EMSUSD-804 duplicate-to-USD support relationship targets

- lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.cpp
The shadergen can recover from benign errors. Let it try to complete generation instead.
> LOOKDEVX-2331 - Do not bail out after a failed validate call

- lib/usd/ui/layerEditor/layerTreeView.cpp
New layer items in the Layer Editor are now in the collapsed state by default when found for the first time, instead of expanded by default.
> EMSUSD-838 new layers collapsed

- lib/usd/ui/layerEditor/layerTreeView.cpp
- lib/usd/ui/layerEditor/layerTreeView.h
When holding shift while clicking the expand or collapse button, expand or collapse all items in the layer editor.
> EMSUSD-840 expand and collapse all layer items

- lib/mayaUsd/ufe/UsdAttribute.cpp
Fixes a bug with UsdAttributeEnumString that have token values. We discovered a case where this was possible and needed to handle it.
> EMSUSD-934 - Fixes a bug with UsdAttributeEnumString that have token

- lib/mayaUsd/render/MaterialXGenOgsXml/CMakeLists.txt
- lib/mayaUsd/render/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
- lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaTransformNormalNodeGlsl.cpp
- lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaTransformNormalNodeGlsl.h
- lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaTransformPointNodeGlsl.cpp
- lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaTransformPointNodeGlsl.h
- lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaTransformVectorNodeGlsl.cpp
- lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaTransformVectorNodeGlsl.h
A transform node with empty space values will cause the shadergen to crash. This has been fixed in future MaterialX 1.38.9 by introducing ShaderPort::getValueString() in https://github.com/AcademySoftwareFoundation/MaterialX/pull/1560
We have backported that fix in local copies of the transform node C++ implementations in order to prevent crashing with the current versions of MaterialX.
> LOOKDEVX-2354 - Fix the transform nodes crash

- plugin/adsk/scripts/mayaUSDRegisterStrings.mel
- plugin/adsk/scripts/mayaUsd_createStageFromFile.mel
* Removed duplicate string resource.
> EMSUSD-956: Resource Identifier warning on first launch of MayaUSD

- plugin/adsk/scripts/mayaUsd_preferenceTab.mel
* Fix cancel case and optimize when to call 'ogs -reset'
> EMSUSD-717: USD Prefs: "Use Display Color" preferences are maintained when user cancels change

- test/lib/ufe/testParentCmd.py
Verify that the parent command with a single argument wil parent to the selection. Only works in future Maya versions.
> EMSUSD-134 unit test for parent to selection

- lib/mayaUsd/ufe/UsdAttribute.cpp
- lib/mayaUsd/ufe/UsdAttribute.h
- lib/mayaUsd/ufe/UsdAttributeHolder.cpp
- lib/mayaUsd/ufe/UsdAttributes.cpp
- test/lib/ufe/testConnections.py
When creating NodeGraph/Material inputs and outputs, allow passing the native type as a string instead of "Generic" when creating a port that can only be wrapped in UFE as an UfeAttributeGeneric.
This allows LookdevX to display the expected port type when promoting ports on inner nodes.
> LOOKDEVX-2403 - Allow creating custom types at NodeGraph boundaries

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
- lib/mayaUsd/ufe/Global.cpp
- lib/usdUfe/ufe/Utils.h
When a command may trigger a long viewport update, set a flag so that the proxy render delegate shows the wait cursor while it is updating the viewport data. We make the assumption that long-duration commands will generally cause long-duration viewport updates. This is done via the already-existing LongDurationCommand base class and wait cursor functions.
- Modify the WaitCursor helper class to take a flag to control if the cursor is shown or not.
- This allows conditionally showing the wait cursor based on a condition.
- Add a function to tell the render delegate that it should expect its update to take a long time.
- Make the wait cursor function used by long-duration commands tell the render delegate to expect a long update.
> EMSUSD-65 wait cursor during long VP2 updates

- lib/usd/ui/layerEditor/layerTreeItem.cpp
- plugin/adsk/scripts/mayaUSDRegisterStrings.mel
- plugin/adsk/scripts/mayaUsdMenu.mel
Layer Editor's "Revert to File" menu item is renamed to "Reload"
Additionally, The action no longer requires the layer to be dirty and the menu item is shown as long as the layer is not an anonymous layer.
> EMSUSD-964 - Layer Editor's "Revert to File" menu item is renamed to "Reload"

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/utils/traverseLayer.cpp
The code was not creating the necessary missing parent prims and was not detecting relationships correctly, among other smaller things.
- Add a helper to create the missing parent prims, trying to replicate the same prim type found in the temporary source stage, without actually copying those prims.
- Add a lot of debug logging to help investigate issues with duplicate-to-USD.
- Keep track of each prim that gets brought in by each prim that gets copied, recursively, so that we copy all necessary prims.
- Keep recursing into prims that have already been copied indirectly via SdfCopySpec so that their relationships can be detected too.
- This happens for example if one copies a Maya sphere than contained a Maya cube.
- Correctly detect relationships. The old way was detecting relational …
> EMSUSD-804 fix copying node with Arnold material.

- lib/mayaUsd/resources/ae/usdschemabase/attribute_custom_control.py
EMSUSD-971 - HTML code is displayed for tooltip of USD prim Attributes
* Use rich text for tooltip, instead of html tags.
EMSUSD-969 - USD Prim transform attributes have empty tooltips
* Handle empty doc string case.
> Fix AE tooltip and status bar message

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/python/CMakeLists.txt
- lib/mayaUsd/python/module.cpp
- lib/mayaUsd/python/wrapCopyLayerPrims.cpp
- lib/mayaUsd/utils/CMakeLists.txt
- lib/mayaUsd/utils/copyLayerPrims.cpp
- lib/mayaUsd/utils/copyLayerPrims.h
- test/lib/mayaUsd/fileio/CMakeLists.txt
- test/lib/mayaUsd/fileio/testCopyLayerPrims.py
The goal is to make the duplication more testable.
Some scenarios would require the Arnold plugin to be present and we want to avoid depending on it. So instead, the code refactor split the duplication into finer-grained functions that can be tested by using custom-made temporary layers to reproduce the behavior of Arnold.
The refactor also makes the code clearer and more correct by having smaller functions. Multiple subtle problems were discovered and fixed with this strategy, related to complex cases of renaming and inter-prim relationships.
- Move code to copy temporary prims to a layer out of PrimUpdaterManager.
- This makes the code testable with pre-fabricated temp layers to test specific scenarios.
- This also lighten a bit the prim updater manager source code, which is very large. …
> EMSUSD-972 refactor duplication code

- lib/mayaUsd/utils/copyLayerPrims.cpp
- test/lib/mayaUsd/fileio/testCopyLayerPrims.py
The test revealed a flaw in the code that follows relations and connections. Fixed the code to not go into an infinite loop when there are circular relationships or connections.
- Fix infinite recursion when relations or connections form a circle.
- Added many test for connections, similar to those for relations.
- Refactored the test code to allow testing relations or connections.
- Added tests for circular targets.
- Added test for mix or relationships and connections.
> EMSUSD-972 add unit test for circular relationships

- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/nodes/proxyShapeBase.h
- lib/mayaUsd/ufe/UsdStageMap.cpp
Maya scene load without any USD data is slower when the MayaUSD plugin is loaded.
The reason behind the bad performance is that the UsdStageMap class constantly rebuilds itself because it thinks it is out of date. The reason is that its UsdStageMap::proxyShape() function assumes that it is always called to retrieve an existing proxy shape. So when it fails to find the requested proxy shape, it assumes its mapping between UFE paths and DAG paths must be stale. Those assumptions are false.
The culprit is the following sequence:
- Adding Maya nodes cause a UFE AddObject notification to be sent.
- The Maya outliner UI wants to know if this object might be a UFE gateway node.
- It asks UFE if is a gateway node.
- This ends-up being routed to MayaUSD.
- …
> MAYA-132438 fix slow scene load performance

- lib/mayaUsd/resources/ae/CMakeLists.txt
See Python [PEP 420](https://peps.python.org/pep-0420/) for details.
Should allow other Maya modules to also declare an attribute editor template for their own UFE datamodels.
> LOOKDEVX-2254 - Enable "Implicit Namespace Packages" feature

- lib/mayaUsd/fileio/primWriterRegistry.cpp
- lib/mayaUsd/fileio/primWriterRegistry.h
- lib/mayaUsd/fileio/writeJobContext.cpp
https://github.com/Autodesk/maya-usd/issues/3502
What MayaUsd used to do is using a map to remember if a primWriter has been used for this maya object type. However, with our _CanExport()_ feature available, the user may want to inspect each object and see which writer to use, so call Find() to inspect and find the best primWriter to use if there are multiple primWriters available for this maya object type
> EMSUSD-957 - Call CanExport() per object instead of per export

- lib/mayaUsd/fileio/jobs/readJob.cpp
Editing as Maya an instanced object and then undoing the edit-as-Maya would crash. That was because when editing an instance, Maya nodes were briefly created for the prototype, registered as newly-created nodes, then immediately deleted. When undoing, the undo was trying to delete those non-existing nodes.
Fix by removing the deleted node from the map of created Maya nodes.
> EMSUSD-987 undo edit prototype

- lib/mayaUsd/utils/CMakeLists.txt
- lib/mayaUsd/utils/mayaNodeObserver.cpp
- lib/mayaUsd/utils/mayaNodeObserver.h
- lib/mayaUsd/utils/mayaNodeTypeObserver.cpp
- lib/mayaUsd/utils/mayaNodeTypeObserver.h
Add new classes to observe Maya nodes of a given type or a given Maya node. The observer forward changes to registered listeners. The goal is to standardize how a node is observed and to share the notification between multiple listeners.
This will be used by multiple classes in a subsequent pull request: MayaUsdProxyShapeBase, UsdStageMap and MayaSessionState.
The MayaNodeTypeObserver allows listening to new nodes being created or removed. The MayaNodeObserver allows listening to the node being renamed or reparented. Many use cases need to track the DAG path, UFE path or USD path of objects, mostly the USD stage itself.
> EMSUSD-988 Maya node observer classes

- lib/mayaUsd/nodes/layerManager.cpp
- test/lib/mayaUsd/fileio/CMakeLists.txt
- test/lib/mayaUsd/fileio/testSaveMutedAnonLayer.py
Fix that muted anonymous layers are lost when saved within the Maya scene file. The culprit was that UsdStage::GetLayerStack() did not return muted layers. The new code use an alternative method to retrieve the list of layers.
> EMSUSD-1001 lost muted layer

- cmake/modules/FindMaya.cmake
- test/testUtils/mayaUtils.py
Remove code (currently not used) that detected this.
> Maya is no longer using a Preview Release number

- lib/mayaUsd/nodes/layerManager.cpp
- lib/mayaUsd/nodes/layerManager.h
- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/utils/layerMuting.cpp
- lib/mayaUsd/utils/layerMuting.h
- test/lib/mayaUsd/fileio/testSaveMutedAnonLayer.py
- Allow retrieving a mapping of renamed layers from the LayerManager Maya node that keeps track of USD layers saved inside a Maya scene.
- Pass that map of layer names to the function that restore layer muting.
- Make sure muted layers are not lost by adding them to the set of retained muted layers.
- This is especially important for anonymous layers, as nothing else refer to them.
> EMSUSD-1007 fix layers not muted on reload

- plugin/adsk/plugin/CMakeLists.txt
The mayaUsdAPI library is not directly needed by the mayaUsd plugin. However, there is no way currently for other plugins that need it to know where to locate it on mac/linux through rpaths. By linking it it will be preloaded like the other dynamic libs.
> EMSUSD-1016 - Link against mayaUsdAPI to preload it for other plugins

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/nodes/layerManager.cpp
- lib/mayaUsd/nodes/layerManager.h
Avoid starting to edit-as-Maya in the middle of saving because some of the state necessary to keep track of the edit would not make it to the saved file.
> EMSUSD-1003 Keep Maya Ref valid after saving

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp
- lib/mayaUsd/render/vp2RenderDelegate/points.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
Call the Usdimaging function to retrieve all instance prim path at once instead of one-by-one, which optimizes many internal details.
- Use the same faster code in a few other similar places.
- Add a convenience function to retrieve all the prim paths when the instance ID are consecutive.
- Use it in a few places.
> EMSUSD-708 fix performance of instanceable prims

- lib/mayaUsd/commands/Readme.md
- lib/mayaUsd/commands/abstractLayerEditorWindow.h
- lib/mayaUsd/commands/layerEditorCommand.cpp
- lib/mayaUsd/commands/layerEditorWindowCommand.cpp
- lib/mayaUsd/utils/CMakeLists.txt
- lib/mayaUsd/utils/layerLocking.cpp
- lib/mayaUsd/utils/layerLocking.h
- lib/usd/ui/layerEditor/abstractCommandHook.h
- lib/usd/ui/layerEditor/layerEditorWidget.cpp
- lib/usd/ui/layerEditor/layerTreeItem.cpp
- lib/usd/ui/layerEditor/layerTreeItem.h
- lib/usd/ui/layerEditor/layerTreeItemDelegate.cpp
- lib/usd/ui/layerEditor/layerTreeModel.cpp
- lib/usd/ui/layerEditor/layerTreeView.cpp
- lib/usd/ui/layerEditor/mayaCommandHook.cpp
- lib/usd/ui/layerEditor/mayaCommandHook.h
- lib/usd/ui/layerEditor/mayaLayerEditorWindow.cpp
- lib/usd/ui/layerEditor/mayaLayerEditorWindow.h
- lib/usd/ui/layerEditor/saveLayersDialog.cpp
- lib/usd/ui/layerEditor/stringResources.h
- plugin/adsk/scripts/mayaUsdMenu.mel
- test/lib/testMayaUsdLayerEditorCommands.py
The system lock is a severity of locking a layer where it cannot be undone using UI. It is meant to be controlled through script or programmatically to prevent a user from editing or saving a layer.
The locking can be performed using the mayaUsdLayerEditor command with the lockLayer parameter:
- `lockLayer 0` is unlocked 
- `lockLayer 1` is locked: Sets the PermissionToEdit to false
- `lockLayer 2` is system locked: Sets both the PermissionToEdit and PermissionToSave to false
Example of System Locking:
In the above example:
- (1) asdf.usda is system locked, No Save, No Edit
- As a result of the system lock, the anonymous layers (2), (3) cannot be saved since saving them will cause a change in asdf.usda. The anonymous layers can still be edited.
- qwerty.usda changes can be saved since it …
> EMSUSD-872 - Adds the ability to System-lock a layer

- lib/mayaUsdAPI/CMakeLists.txt
- lib/mayaUsdAPI/utils.cpp
- lib/mayaUsdAPI/utils.h
This will remove the need for LookdevX to link directly to `mayaUsd` and `mayaUsdUtils` with a couple of exceptions that will be sorted out  at a later time.
> EMSUSD-1066 - Minimal API needed by LookdevX to decouple from mayaUsd

- lib/usd/ui/layerEditor/abstractCommandHook.h
- lib/usd/ui/layerEditor/layerTreeView.cpp
- lib/usd/ui/layerEditor/mayaCommandHook.cpp
- lib/usd/ui/layerEditor/mayaCommandHook.h
When reverting multiple USD layers, reverting the first layer would trigger the UI to update, thus making the the element holding the other layers invalid before they were processed.
To avoid this, add a mechanism to delay the execution of commands in the command-hook so that all item can be processed before the first command is executed.
In the Maya implementation of the command hook, the MEL and Python commands are accumulated when the commands are delayed and executed once the delayed commands are triggered.
> EMSUSD-1017 Fix reverting multiple files

- lib/mayaUsd/commands/layerEditorCommand.cpp
- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/nodes/proxyShapeBase.h
- lib/mayaUsd/utils/layerLocking.cpp
- lib/mayaUsd/utils/layerLocking.h
- test/lib/testMayaUsdLayerEditorCommands.py
- test/testSamples/layerLocking/layerLocking.usda
- If a layer has a LayerLock_Locked status, the status is saved into a proxy shape attribute named "lockedLayers" (brief name: lockla) and is stored in the maya file.
- Moved the core of locking mechanism into layerLocking .h and .cpp
> EMSUSD-871 - Locked layer status persists between Maya sessions

- .github/workflows/maya-usd-new-issues.yml
- .github/workflows/maya-usd-preflight-launcher.yml
I noticed this in the checks after running a preflight:
For details as to why see https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
I updated this in the past from Node12 to Node16 in #3291
> Update github actions to node20 (node16 is out of support)

- lib/mayaUsd/nodes/proxyShapeBase.cpp
Fixes the issue where the lock state isn't applied from Maya file when the layer is both locked and muted.
> EMSUSD-1087 - Fixes the issue where the lock state isn't applied from Maya file when the layer is both locked and muted.

- lib/mayaUsd/render/vp2RenderDelegate/colorManagementPreferences.cpp
- lib/mayaUsd/render/vp2RenderDelegate/colorManagementPreferences.h
- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
This prevents spamming the error log with evey single image node using a unsupported color space.
> EMSUSD-1071 - Remember unknown color spaces

- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/proxyDrawOverride.cpp
When computing bounding boxes and transforms for ProxyShape nodes, apply the root-to-prim transforms defined within the referenced Usd stage for the specified prim for imaging and selection
> Apply root-to-prim transforms

- lib/mayaUsd/commands/layerEditorCommand.cpp
- lib/usdUfe/python/wrapUtils.cpp
- lib/usdUfe/ufe/Utils.cpp
- lib/usdUfe/ufe/Utils.h
- test/lib/testMayaUsdLayerEditorCommands.py
Targets the session layer when no other layers are modifiable
> EMSUSD-885 - Targets the session layer when no other layers are modifiable

- plugin/adsk/scripts/mayaUsd_createStageFromFile.mel
- test/lib/testMayaUsdCreateStageCommands.py
EMSUSD-1120 - Stage loading problems using MEL proc
* Make sure to init the optionvars used by the MEL command.
> EMSUSD-1120 - Stage loading problems using MEL proc

- lib/mayaUsd/nodes/layerManager.cpp
This makes the Maya file backward compatible with older MayaUSD plugins that did not have that attribute. This is particularly good when a Maya scene does not use USD at all.
> Clear the selected stage layer database attribute when no stage selected

- lib/usdUfe/ufe/UsdUndoAddNewPrimCommand.cpp
When the user tries to add a prim under a prim that is deactivated, they will see an error in the console such as:
```
Failed to create new prim type: Capsule
ValueError: Cannot append null item pointer to selection.
```
However, upon reactivating the prim that was deactivated, they will see that the prim was in fact added. This PR addresses this problem by removing the invalid prim that gets created in such a situation.
> EMSUSD-591: Remove lingering invalid prims after adding prim under prim that is deactivated

- lib/usd/utils/MergePrims.cpp
When updating to USD v24.03 the test `testMergeToUsd.py` would segfault and crash. I found its because of a `const TkToken&` being stored in a struct which is then passed around. Not sure why with 24.03 this changed, but my suspicion was that token was being released elsewhere and this the ref in the struct not valid. There is no reason to store a ref in the struct. TfTokens are lightweight objects which are ref counted.
> EMSUSD-1073 - Update for USD v24.03

- lib/mayaUsd/render/MaterialXGenOgsXml/libraries/1.38.3/mx_lighting_maya_v3.glsl
- lib/mayaUsd/render/MaterialXGenOgsXml/libraries/1.38.7/mx_lighting_maya_v3.glsl
- lib/mayaUsd/render/MaterialXGenOgsXml/libraries/mx_lighting_maya_v3.glsl
MaterialX 1.38.9 has incorporated this commit (https://github.com/AcademySoftwareFoundation/MaterialX/commit/eae062a038bcd8f8172b1725e93e35641dc73f61) that causes a conflict with a similar change that is inside Maya USD resulting in Pixel shader compilation errors;
```
ERROR: 0:1092: Function 'mx_latlong_compute_lod' redefines an existing function
```
This PR resolves that by renaming the Maya one to a non-conflicting name. This seemed easiest rather than trying to detect the MaterialX version and handling it accordingly.
Without this PR, Maya fails to generate any MaterialX based shaders.
> Fix conflict in shaders with MaterialX 1.38.9

- plugin/adsk/scripts/mayaUsdMenu.mel
* When over the Dopesheet the panel type returned is not compatible with OutlinerEditor command.
> MAYA-133210: Dope Sheet : Error when right-click on channel set if USD plugin installed

- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
- lib/mayaUsdAPI/utils.cpp
- lib/mayaUsdAPI/utils.h
An image UsdShade node that never had its filename attribute set would fail the isImageAttribute test. Allow the image code since a filename in a shader is always an image.
> LOOKDEVX-2358 - Fix image file attribute detection

- lib/mayaUsd/resources/ae/usdschemabase/custom_image_control.py
- lib/mayaUsd/utils/utilFileSystem.h
EMSUSD-993: When opening a file dependency in the AE, the dialog doesn't open to the location of the file
* If we can resolve path to absolute, open the file dialog on that path.
* Fix spelling mistakes
> EMSUSD-993: When opening a file dependency in the AE, the dialog doesn't open to that path

- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
When there is no custom root prim name entered, disable the root prim type drop-down button. Also, don't add the empty root prim name to the available root prims.
> EMSUSD-1187 disable root prim type UI

- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
- plugin/adsk/scripts/mayaUsdTranslatorImport.mel
When an export plugin has no option UI, the option button must not show up. When the plugin was disabled and nothing was exported, we got into a state where the option button would still show up.
- Add a function to update all option buttons of each export plugin.
- Call it when setting up the initial UI.
- Do the same fixes for teh import plugins.
> EMSUSD-1193 hide unwanted export plugin options

- lib/mayaUsd/commands/layerEditorCommand.cpp
- lib/usd/ui/layerEditor/mayaCommandHook.cpp
- test/lib/testMayaUsdLayerEditorCommands.py
- test/testSamples/layerLocking/layerLockingSubLayer.usda
- test/testSamples/layerLocking/layerLockingSubSubLayer.usda
- When unlocking recursively, do not unlock sub-layers that are system-locked.
- Correctly check that the *request* was for system lock when undoing a lock command.
- Add more lock tests to cover more cases, like having sub-layers and system-locked layers.
> EMSUSD-1149 prevent unlocking system-locked layer when unlocking parents

- lib/usdUfe/ufe/Utils.cpp
- test/lib/ufe/testPayloadCommands.py
- test/lib/ufe/testReferenceCommands.py
- Apply the same logic as for references.
- Add test for deletion of a prim containing a payload or a ref.
> EMSUSD-1067 allow deleting prims carrying a loaded payload

- lib/usd/ui/layerEditor/layerTreeItem.cpp
- lib/usd/ui/layerEditor/layerTreeItemDelegate.cpp
- lib/usd/ui/layerEditor/qtUtils.cpp
- lib/usd/ui/layerEditor/resources.qrc
Correctly define the scaling icon and don't try to calculate the DPI in the plugin, let the pixmap creation do the maths. In that scheme, the default 100% scaling pixamp does not have a DPI suffix, so fix the resource names.
> EMSUSD-1142 layer editor icon scaling

- lib/usd/translators/meshWriter_BlendShapes.cpp
- test/lib/usd/translators/testUsdExportBlendshapes.py
When exporting maya blendshapes to usd, it's used the name of the mesh shape. However, the Maya's shape editor lists the name of the parent node to drive the blendshape weights. 
This PR it's an improvement so that the default USD blendshapes are created with proper names.
> EMSUSD-1180 Fix blendshape names

- lib/mayaUsd/commands/layerEditorCommand.cpp
- lib/mayaUsd/python/__init__.py
- lib/usd/ui/layerEditor/layerTreeView.cpp
- lib/usd/ui/layerEditor/layerTreeView.h
- lib/usdUfe/python/wrapUICallback.cpp
- lib/usdUfe/utils/uiCallback.cpp
- lib/usdUfe/utils/uiCallback.h
- test/lib/testMayaUsdLayerEditorCommands.py
- Support having multiple callbacks for a given UI callback.
- Support having multiple callbacks from Python.
- Support unregistering a callback.
- Register a UI callback for the onRefreshSystemLock"" notification in the layer view.
- Repaint when receiving that notification.
> EMSUSD-1092 fix layer editor refresh when reloading from AE

- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
- lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
- Added a new material custom control for the attribute editor (AE).
- It creates text fields for the material path, inherited material and ancesto prim path.
- If the material is directly on the prim, the inherited and ancestor fields are hidden.
- If the material is inherited, the material path is set to "inheriting".
- All fields are not editable.
- The direct or inherited material is found by using the ComputeBoundMaterial function from the USD material binding API.
- Added a button to go to the prim from which the material is inherited.
- Don't show the material section for materials themselves.
- Show the direct material when there is one even though an inherited material over-rides it.
- Show tooltip explaining how inherited material affect the prim in the assigned material field. …
> EMSUSD-208 Material custom control for AE

- plugin/al/MIGRATION_GUIDE.md
- plugin/al/README.md
- Added Migration guide moving from AL_USDMaya plugin to Autodesk's MayaUSD plugin
- Updated `plugin/al/README.md` to point to the migration guide doc
> Migration guide from AL_USDMaya to Autodesk's MayaUSD

- lib/mayaUsd/resources/ae/CMakeLists.txt
- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
- lib/mayaUsd/resources/ae/usdschemabase/material_custom_control.py
- lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
- Move the custom control class to its own file.
- Add an option menu to control the material binding strength in the attribute editor (AE).
- Change the binding strength when the user select a new value in the option menu.
- Hide the menu when the material in inherited and there is no direct material.
- Disable the menu when there is a stronger inherited material and a direct material.
- Show a tooltip that explain why it is disabled.
- Update children when material strength is changed.
- Don't change selection when going to the prim from which the material in inherited.
- Don't use italics.
> EMSUSD-204 Material binding strength in AE

- lib/mayaUsd/ufe/UsdUndoDeleteCommand.cpp
- lib/usdUfe/base/tokens.h
- lib/usdUfe/python/wrapEditRouter.cpp
- lib/usdUfe/ufe/Utils.cpp
- lib/usdUfe/utils/editRouter.cpp
- lib/usdUfe/utils/editRouter.h
- test/lib/ufe/testDeleteCmd.py
Hi, in our pipeline, we have a tool in Maya to delete prims from a specified layer using USD's native API, and we are using the `delete` key as the hotkey to run the tool. In order the make the prim deletion behaviour consistent between our tool and in Maya viewport (so that users could hit the `delete` key either with the tool or viewport in focus and get the same result), we'd like to map the `delete` key in Maya to our prim deletion tool, but we learned that the `delete` key executed in viewport cannot be remapped and it has been reserved to Maya's `cmds.delete()` command which has its own logic to delete the selected prims from the layers retrieved based on its own logic. `cmds.delete()` calls `UsdUndoDeleteCommand` internally and it doesn't support `EditRouter` to get an edit target …
> Support EditRouter in delete command

- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
- lib/mayaUsd/resources/ae/usdschemabase/material_custom_control.py
- lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
- test/lib/testAttributeEditorTemplate.py
- Detect if the LookdevX plugin is loaded. Everything else is turned off when not loaded.
- Add a button to graph the material in a LookdevX tab.
- Use a named tuple to hold text field info.
- Refactor the code to show buttons and update the associated commands.
- Use the lookdevXGraph command to open the tab.
- Add a utility function to build a UFE path from a USD path.
- Fixed that the AE would not update when assigning an existing material.
- Add a popup menu to the graph material buttons.
- Allow creating a new tab or re-using an existing tab.
- The material types is always USD since these are USD materials.
> EMSUSD-209 graph the material in LookdevX

- lib/mayaUsd/ufe/UsdPointInstanceModifierBase.h
- lib/mayaUsd/ufe/UsdPointInstanceOrientationModifier.cpp
- lib/mayaUsd/ufe/UsdPointInstanceOrientationModifier.h
- lib/mayaUsd/ufe/UsdPointInstancePositionModifier.cpp
- lib/mayaUsd/ufe/UsdPointInstancePositionModifier.h
- lib/mayaUsd/ufe/UsdPointInstanceScaleModifier.cpp
- lib/mayaUsd/ufe/UsdPointInstanceScaleModifier.h
- lib/mayaUsd/ufe/UsdSetXformOpUndoableCommandBase.cpp
- lib/mayaUsd/ufe/UsdSetXformOpUndoableCommandBase.h
- lib/mayaUsd/ufe/UsdTransform3dBase.cpp
- lib/mayaUsd/ufe/UsdTransform3dBase.h
- lib/mayaUsd/ufe/UsdTransform3dCommonAPI.cpp
- lib/mayaUsd/ufe/UsdTransform3dMatrixOp.cpp
- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.h
- lib/mayaUsd/ufe/UsdTransform3dPointInstance.cpp
- lib/mayaUsd/ufe/UsdTransform3dPointInstance.h
- lib/usdUfe/base/tokens.h
- lib/usdUfe/python/wrapEditRouter.cpp
- test/lib/ufe/testEditRouting.py
Add helpers to support permissions and routing:
- Provide a helper function to check permission-to-edit in the base class of the USD implementation of the UFE 3D Transform interface.
- The helper ensures that the correct edit context is used when checking permissions.
Use helpers in transforms and commands:
- Use those helper functions to check for permission to edit in command creation.
- Use those helper functions to do the edits, in command execution.
- Add edit routing context in all transform-related edits function.
- This context queries and sets where the edits should be routed.
- In particular, it is used in the execute, undo, redo and set functions of the command base class.
- Properly check permissions for matrix commands.
- The common API, 3d Matrix Op, point instances and Maya …
> EMSUSD-1111 Edit routing for transform commands

- lib/mayaUsd/ufe/UsdUndoDeleteCommand.cpp
- lib/usdUfe/utils/editRouter.cpp
The new code for doing edit routing using an edit target directly was not supporting the usual use-case of providing the target by the layer identifier or layer handle.
It also always allowed stronger opinions, even though we only need it if the target is within a reference or payload.
This fixes both issues: delete can now be routed like other commands by ID or layer handle and will only allow stronger opinions when targeting a non-local layer.
Extending using an edit target directly in all other commands will be done separately in the future.
> EMSUSD-1258 extend the delete cmd edit routing

- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
Fix the position of the Maya manipulators when USD pivot are used instead of (or in addition to) Maya pivots.
> EMSUSD-1046 manip pivot position

- lib/usdUfe/python/CMakeLists.txt
- plugin/adsk/scripts/mayaUsd_preferenceTab.mel
- test/lib/ufe/testClipboard.py
* cmake mistake caused missing python binding
> EMSUSD-1272 - CopyPaste: MayaUSD clipboard error messages when opening up preferences window

- CMakeLists.txt
* When building UsdUfe standalone with Ufe containing clipboard support (which requires C++17) we must disable it USD version and C++ version don't match.
> EMSUSD-1192 - UsdUfe: create standalone builds for MaxUsd

- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
- test/lib/ufe/testCenterPivot.py
- test/testSamples/pivot/cube-far-pivot.usda
When there is a mix of Maya-style and USD-style pivot, handle the translate rotate pivot command differently.
> EMSUSD-26 fix center pivot command

- lib/mayaUsd/render/MaterialXGenOgsXml/OgsFragment.cpp
Handle the case where a shader input has no path, yet is a valid parameter of that node. This is a behavior that was changed in MaterialX 1.38.10.
> LOOKDEVX-2903 - Update for a change in MaterialX 1.38.10

- lib/usd/translators/shading/mtlxFileTextureWriter.cpp
- lib/usd/translators/shading/usdFileTextureWriter.cpp
- test/lib/usd/translators/testUsdExportTexture.py
Fixes #3766 .
Adds support for environment variable expansions found in `file.fileTextureName` attributes at export, thanx to `MRenderUtil::exactFileTextureName`.
A more conservative surgical change would  be to use `MString::expandEnvironmentVariablesAndTilde`.  I opted for `exactFileTextureName` as it  aligns with file node logic, supporting other resolution options like `dirmap` and `MPxFileResolver` plugins, although it might introduce more side effects.
> Add support for env var expansions in file node writers

- lib/usdUfe/ufe/UsdClipboardCommands.cpp
- lib/usdUfe/ufe/UsdClipboardCommands.h
- lib/usdUfe/ufe/UsdClipboardHandler.cpp
- lib/usdUfe/ufe/UsdUndoSelectAfterCommand.h
- test/lib/ufe/testClipboard.py
* Proper undo/redo support for selection of pasted prims.
> EMSUSD-1121 - Pasted prims should be selected

- lib/mayaUsd/ufe/UsdTransform3dFallbackMayaXformStack.cpp
- lib/mayaUsd/ufe/UsdTransform3dFallbackMayaXformStack.h
- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.h
- test/lib/ufe/testRotateCmd.py
Force the prim to have a three-axis rotation when creating a rotation command.
The fallback transform implementation derives from the Maya one, but wants the old behavior of not changing how the ops work. So we add a virtual function to detect this.
Add a unit test that test the situation.
> EMSUSD-1260 fix rotation when prim already single-axis rotation

- lib/mayaUsd/commands/baseExportCommand.cpp
- lib/mayaUsd/fileio/jobs/jobArgs.cpp
- lib/mayaUsd/fileio/jobs/jobArgs.h
- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/fileio/shading/shadingModeExporterContext.cpp
- lib/mayaUsd/fileio/shading/shadingModePxrRis.cpp
- lib/mayaUsd/fileio/shading/shadingModeUseRegistry.cpp
- lib/mayaUsd/fileio/writeJobContext.cpp
- lib/mayaUsd/render/mayaToHydra/shadingModeExporter.cpp
- plugin/adsk/plugin/exportTranslator.cpp
- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
- plugin/adsk/scripts/mayaUsd_exportHelpers.py
- plugin/pxr/maya/lib/usdMaya/exportTranslator.cpp
- test/lib/usd/translators/CMakeLists.txt
- test/lib/usd/translators/testUsdExportMaterialsOnly.py
- Add the full list of Maya objects that were selected in the export job export arguments.
- Pass the full object list when creating the UsdMayaJobExportArgs in the base export command, prim updater manager and export translator.
- In specific material exporter, don't skip if the assignments are empty, since we are now exporting materials independently of meshes.
- Avoid errors when filling the default prim UI since some objects in the selections might not be DAG objects.
- Don't disable exporting materials UI when meshes are disabled since they are now independent.
- Add isExportingMeshes, isExportingCameras and isExportingLights functions to UsdMayaJobExportArgs.
- Use them instead of custom code during export.
- When exporting selected, only include materials that are selected or used …
> EMSUSD-1005 export materials without meshes

- lib/usdUfe/ufe/UsdClipboard.cpp
- lib/usdUfe/ufe/UsdClipboard.h
- lib/usdUfe/ufe/UsdClipboardCommands.cpp
- lib/usdUfe/ufe/UsdClipboardCommands.h
- lib/usdUfe/ufe/UsdClipboardHandler.cpp
- test/lib/ufe/testClipboard.py
* Added selection observer to UsdClipboard to track when to reset the "paste as sibling".
* Fixed bug with cut command which wasn't removing the cut item from selection. Added unit test for this.
* New logic in paste command (for regular prims only) to paste as a sibling of the copy rather than into the paste target if the selection wasn't changed between copy and paste.
* Overrode the paste command execute to set a selection guard since the paste command selects newly pasted prims.
* New unit test for pasting multiple times to test paste as sibling.
> EMSUSD-1122 - As a user, I'd like to copy and then paste a prim as a sibling

- lib/usdUfe/ufe/UsdClipboardCommands.cpp
- lib/usdUfe/ufe/UsdClipboardHandler.cpp
- test/lib/ufe/testClipboard.py
* Added a few nullptr checks to clipboard commands.
* Added cut restriction checks to cut command creation. Only allow cut (copy + delete) of items which can be cut. Will return empty command if no items in selection can be cut.
* Added new unit test for cut restrictions.
* Added new unit test for cut/copy/paste error conditions.
> EMSUSD-1126 - Cut a prim and not have it paste if the cut is restricted

- lib/mayaUsd/nodes/layerManager.cpp
- test/lib/mayaUsd/nodes/testLayerManagerSerialization.py
When there are no USD stages in the scene, don't create an empty LayerManager node that would require the MayaUSD plugin to load the Maya scene.
> EMSUSD-1266 don't depend on MayaUSD if not using it

- cmake/googletest.cmake
- cmake/googletest_download.txt.in
- cmake/gulrak.cmake
- lib/mayaUsd/fileio/jobs/readJob.cpp
- lib/usd/translators/shading/mtlxFileTextureReader.cpp
- lib/usd/translators/shading/mtlxFileTextureWriter.cpp
- lib/usd/translators/shading/mtlxImageReader.cpp
* Set C++ version when building googletest and use shallow clone (no history is needed).
* Update gulrak version from 1.5.6 to 1.5.14.
* Remove unneeded filesystem include.
> Update googletest & gulrak (filesystem)

- lib/usd/translators/jointWriter.cpp
- test/lib/usd/translators/testUsdExportSkeleton.py
We were exporting the rest transform as the inverse of the bind transform. 
This was causing issues for bones that weren't bound to any skin cluster.
With this pr, we will use the inverse of the joint's transform as the rest transform.
https://openusd.org/dev/api/_usd_skel__a_p_i__intro.html#UsdSkel_API_WritingSkels
This PR fixes #2857 and #3765
> EMSUSD-1359 Export of Maya skeleton as USD comes in as a stage in the wrong place.

- lib/mayaUsd/base/tokens.h
- lib/mayaUsd/fileio/chaser/importChaserRegistry.h
- lib/mayaUsd/nodes/proxyStageProvider.h
- lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.h
- lib/mayaUsd/undo/OpUndoItems.h
- lib/usd/ui/layerEditor/abstractCommandHook.h
- lib/usd/ui/layerEditor/layerTreeItem.h
* As per our coding standard, all included public header files from outside and inside the project should be included using angle brackets. Only the associated header (to the .cpp) can be included with double quotes and no path.
> EMSUSD-1351 - MayaUsd: Code cleanup

- test/lib/usd/pxrUsdPreviewSurface/testPxrUsdPreviewSurfaceExport.py
- test/lib/usd/translators/testUsdExport8BitNormalMap.py
- test/lib/usd/translators/testUsdExportAssignedMaterials.py
- test/lib/usd/translators/testUsdExportCustomConverter.template.py
- test/lib/usd/translators/testUsdExportDefaultPrim.py
- test/lib/usd/translators/testUsdExportDisplacement.py
- test/lib/usd/translators/testUsdExportFannedOutFileNodesMaterial.py
- test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
- test/lib/usd/translators/testUsdExportImportUDIM.py
- test/lib/usd/translators/testUsdExportMaterialScope.py
- test/lib/usd/translators/testUsdExportMaterialsOnly.py
- test/lib/usd/translators/testUsdExportMultiMaterial.py
- test/lib/usd/translators/testUsdExportRfMShaders.py
- test/lib/usd/translators/testUsdExportRoots.py
- test/lib/usd/translators/testUsdExportShadingInstanced.py
- test/lib/usd/translators/testUsdExportShadingModePxrRis.py
- test/lib/usd/translators/testUsdExportTexture.py
- test/lib/usd/translators/testUsdExportUVSetMappings.py
- test/lib/usd/translators/testUsdExportUVTransforms.py
- test/lib/usd/translators/testUsdExportUsdPreviewSurface.py
- test/lib/usd/translators/testUsdExportUsdzPackage.py
This allows tests to pass within environments with specified default export behavior
> Explicitly setting legacyMaterialScope arg in tests

- lib/mayaUsd/render/px_vp20/glslProgram.h
* According to our coding standard we should not use reserved identifiers, like underscore followed immediately by an uppercase letter or double underscore.
> EMSUSD-1351 - MayaUsd: Code cleanup - never use reserved identifiers

- lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/SurfaceNodeMaya.cpp
This light is the only one that has a specular contribution that differs from the diffuse one, in order to create a fast square-shaped specular.
Problem is this is not a correct physical light and MaterialX expects lights to behave identically in th diffuse and specular domains.
So, we were already using the diffuse light direction at the top of the light loop, so the only change is to use the diffuseI multiplication factor at the bottom. This produces better results with aiAreaLight.
> LOOKDEVX-2937 - Fix diffuse lighting with aiAreaLight

- lib/mayaUsd/commands/PullPushCommands.cpp
- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/python/wrapPrimUpdaterManager.cpp
- lib/mayaUsd/ufe/MayaUsdContextOps.cpp
- lib/mayaUsd/ufe/UsdUndoCreateStageWithNewLayerCommand.cpp
- lib/mayaUsd/ufe/UsdUndoCreateStageWithNewLayerCommand.h
- lib/mayaUsd/ufe/UsdUndoRenameCommand.cpp
- lib/mayaUsd/ufe/wrapUtils.cpp
- lib/mayaUsdAPI/utils.h
- plugin/adsk/scripts/mayaUsd_createStageWithNewLayer.py
- test/lib/mayaUsd/fileio/testDiscardEdits.py
- test/lib/mayaUsd/fileio/testDuplicateAs.py
- test/lib/mayaUsd/nodes/testLayerManagerSerialization.py
- test/lib/mayaUsd/nodes/testProxyShapeBase.py
- test/lib/mayaUsd/undo/testOpUndoItem.py
- test/lib/mayaUsd/undo/testOpUndoItemList.py
- test/lib/mayaUsd/undo/testUsdUndoManager.py
- test/lib/testMayaUsdCreateStageCommands.py
- test/lib/ufe/testBatchOpsHandler.py
- test/lib/ufe/testClipboard.py
- test/lib/ufe/testDeleteCmd.py
- test/lib/ufe/testGroupCmd.py
- test/lib/ufe/testLegacyDeleteCmd.py
- test/lib/ufe/testObject3d.py
- test/lib/ufe/testParentCmd.py
- test/lib/ufe/testPythonWrappers.py
- test/lib/ufe/testRename.py
- test/lib/ufe/testReorderCmd.py
MAYA-131348 - Nothing prevents users from naming nodes "world", which breaks USD workflow
* Incorrect to create Ufe::Path for Maya (hidden) world node using Ufe::PathString::path().
* Let DuplicateCommand accept empty destination path which means Maya (hidden) world node.
* Let CreateStageWithNewLayer command accept null input parent which means Maya world node.
* Use ufe.PathString.string() instead of str()
> MAYA-131348 - Adapt to Maya Ufe world node change

- lib/mayaUsd/nodes/layerManager.cpp
- lib/mayaUsd/nodes/layerManager.h
- lib/usd/ui/layerEditor/batchSaveLayersUIDelegate.cpp
- lib/usd/ui/layerEditor/batchSaveLayersUIDelegate.h
- lib/usd/ui/layerEditor/layerTreeModel.cpp
- lib/usd/ui/layerEditor/saveLayersDialog.cpp
- lib/usd/ui/layerEditor/saveLayersDialog.h
- lib/usd/ui/layerEditor/stringResources.h
- Change the labels on headers and buttons when exporting.
- Propagate the fact we are exporting from the layer manager down to the UI.
> EMSUSD-1389 save before export

- lib/mayaUsd/python/wrapPrimWriter.cpp
- test/lib/mayaUsd/fileio/CMakeLists.txt
- test/lib/mayaUsd/fileio/testExportChaser.py
- test/lib/mayaUsd/fileio/utils/CMakeLists.txt
- test/lib/mayaUsd/nodes/CMakeLists.txt
- test/lib/mayaUsd/undo/CMakeLists.txt
- test/lib/mayaUsd/utils/CMakeLists.txt
- test/lib/mayaUsdAPI/CMakeLists.txt
- test/lib/ufe/CMakeLists.txt
- test/lib/usd/pxrUsdPreviewSurface/CMakeLists.txt
- test/lib/usd/translators/CMakeLists.txt
This PR fixes https://github.com/Autodesk/maya-usd/issues/3809 :
- Fixed accessing those TfToken type arguments in Python
- Extended unit test to cover other TfToken arguments
Note: Many other CMakeLists.txt files are also touched to align with other unit tests for the correct runtime env (`LD_LIBRARY_PATH`)
> Fixed accessing JobExportArgs TfToken arguments in Python

- test/lib/testMayaUsdCreateStageCommands.py
MAYA-131348 - Nothing prevents users from naming nodes "world", which breaks USD workflow
* Add unit test to verify Maya fix.
> MAYA-131348 - Nothing prevents users from naming nodes "world"

- lib/mayaUsd/python/__init__.py
- lib/mayaUsd/ufe/Global.cpp
- lib/usdUfe/python/wrapEditRouter.cpp
- lib/usdUfe/utils/editRouter.cpp
- lib/usdUfe/utils/editRouter.h
- test/lib/ufe/testEditRouting.py
If two Python edit routers were written in the Maya script editor using the same function name, then the first one would no longer be held in memory and would crash when called. Fix this by increasing the Python reference count when registering and decreasing it when unregistering.
Make the cleanup of registered Python routers safer during exit. Make the clearAllEditRouters function accessible from Python.
Add a unit test to cover this problem.
> EMSUSD-1361 Same-name Python edit routers

- lib/mayaUsd/ufe/trf/UsdTransform3dMayaXformStack.cpp
- lib/mayaUsd/ufe/trf/UsdTransform3dMayaXformStack.h
- test/lib/ufe/CMakeLists.txt
- test/lib/ufe/testCenterPivot.py
- test/lib/ufe/testPivotConversion.py
- test/testSamples/pivot/cube-usd-pivot.usda
Multiple tools require the use of Maya-style pivots. The difference between Maya-style and USD-style is that Maya has two separate pivots for rotation and scaling while USD has a single pivot for both. In addition, Maya has pivot-compensation attributes.
When there is already a USD-style pivot authored, we need to convert it to the Maya-style pivots when these tools try to modify the object. We detect that such a conversion is needed and adjust the values when they are read and do the conversion the first time a tools tries to write the values.
Fix center pivot test to take into account the new behaviour. Add new unit test for pivot conversion.
> EMSUSD-1160 improve Maya pivot support

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- lib/mayaUsd/utils/selectability.cpp
These were getting included transitively via the Tf library in Usd.
> Add required includes explicitly

- lib/mayaUsd/fileio/jobs/jobArgs.cpp
- lib/mayaUsd/fileio/jobs/jobArgs.h
- lib/mayaUsd/fileio/jobs/writeJob.cpp
- test/lib/mayaUsd/fileio/testSchemaApiAdaptor.py
- test/lib/usd/pxrUsdPreviewSurface/testPxrUsdPreviewSurfaceExport.py
- test/lib/usd/translators/testUsdExport8BitNormalMap.py
- test/lib/usd/translators/testUsdExportCustomConverter.template.py
- test/lib/usd/translators/testUsdExportDisplacement.py
- test/lib/usd/translators/testUsdExportEmptyXforms.py
- test/lib/usd/translators/testUsdExportFannedOutFileNodesMaterial.py
- test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
- test/lib/usd/translators/testUsdExportImportUDIM.py
- test/lib/usd/translators/testUsdExportMaterialScope.py
- test/lib/usd/translators/testUsdExportMaterialX.py
- test/lib/usd/translators/testUsdExportMultiMaterial.py
- test/lib/usd/translators/testUsdExportRfMShaders.py
- test/lib/usd/translators/testUsdExportRoots.py
- test/lib/usd/translators/testUsdExportSchemaApi.py
- test/lib/usd/translators/testUsdExportShadingInstanced.py
- test/lib/usd/translators/testUsdExportShadingModePxrRis.py
- test/lib/usd/translators/testUsdExportSkeleton.py
- test/lib/usd/translators/testUsdExportTexture.py
- test/lib/usd/translators/testUsdExportUVSetMappings.py
- test/lib/usd/translators/testUsdExportUVTransforms.py
- test/lib/usd/translators/testUsdExportUsdPreviewSurface.py
- test/lib/usd/translators/testUsdExportUsdzPackage.py
- test/testSamples/twoSpheres/sphere.usda
Change when the default prim is selected when the export job has no default prim explicitly given. It is now chosen at the beginning the export. This change allows the material scope to know that it must be placed under that default prim.
Take into account root prim and export roots. When the root prim or export roots are explicitly given, use them as the default prim if no explicit default prim was given.
Fix all unit tests affected by the change to where the material scope is placed. Some tests are fixed by explicitly requested that no default prim be used, some are fixed by changing where the material scope is checked to be. These two variations allow testing the new behaviour without having to write new unit tests.
> EMSUSD-1357 material scope when no default prim given

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- test/lib/mayaUsd/fileio/testMergeToUsd.py
Editing a USD prim as Maya should not author the prim kind on the prim when merging back. Doing so can block subsequent merging if the kind is not compatible with the edits. We should not decide the root prim kind behind the back of the user.
> EMSUSD-867 don't set kind when editing as Maya

- lib/mayaUsdAPI/CMakeLists.txt
* Add missing define when building with clipboard support.
> EMSUSD-1410 - MayaUsdAPI - enhance with missing functions required for LookdevX

- lib/mayaUsd/render/MaterialXGenOgsXml/libraries/lookdevKit.mtlx
- lib/mayaUsd/render/MaterialXGenOgsXml/libraries/usd_utilities.mtlx
- lib/mayaUsd/ufe/UsdShaderNodeDef.cpp
- lib/usdUfe/base/tokens.h
- lib/usdUfe/ufe/StagesSubject.cpp
- lib/usdUfe/ufe/UsdAttributeHolder.cpp
- lib/usdUfe/ufe/UsdShaderAttributeDef.cpp
- lib/usdUfe/ufe/Utils.cpp
- lib/usdUfe/utils/Utils.cpp
- test/lib/testAttributeEditorTemplate.py
- test/lib/ufe/testAttribute.py
- Prettify UI names provided by USD that are identical to the family name (for MaterialX shader nodes)
- Do more corrections in the prettifyName function based on observations on the MaterialX library
- Store known USD metadata using Sdf keys instead of Sdr metadata
> LOOKDEVX-3214 - Improve UI name generation

- lib/usdUfe/ufe/UsdUndoInsertChildCommand.cpp
- lib/usdUfe/ufe/trf/UsdTransform3dUndoableCommands.cpp
- lib/usdUfe/utils/editRouterContext.cpp
- test/lib/ufe/testEditRouting.py
- test/lib/ufe/testParentCmd.py
The parenting code was not copying the data correctly. Changed to use the similar code as in the duplicate command. The duplicate command could not be used because the parenting command targets an arbitrary destination.
Added a unit test that exercises the case where a prim is in multiple layers and targeting the session layer. The old code would lose data.
Nested edit router failed to route to the correct layer and would result instead in an infinite loop.
Improve edit routing unit test to test deeper routing nesting.
> EMSUSD-1467 fix multi-layer parenting

- lib/mayaUsd/commands/PullPushCommands.cpp
- lib/mayaUsd/fileio/jobs/jobArgs.h
- lib/mayaUsd/fileio/jobs/writeJob.h
- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/fileio/primUpdaterManager.h
- lib/mayaUsd/fileio/shading/shadingModeExporter.cpp
- lib/mayaUsd/fileio/writeJobContext.h
- lib/mayaUsd/python/wrapPrimUpdaterManager.cpp
- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
- test/lib/mayaUsd/fileio/testDuplicateAs.py
- Keep track of the exported material paths in the write job and write job context.
- No longer disable material UI when not exporting meshes in duplicate mode.
- Add the exported material to the write job in the shading engine.
- Cleanup the result of the export in the prim updater manager.
- When copying to USD, make sure we don't use legacy mode and have no default prim.
- Make the duplicate command and function return the list of duplicated destinations.
- This fixes the problem that the destination of duplicating without meshes cannot be known in advance.
- Add unit test for duplication without meshes but with materials.
> EMSUSD-1432 duplicate materials without meshes

- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
Materials options were not being retained on the final export windows when the user had selected a plugin configuration.
> EMSUSD-1554 Fix materials options retention

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/utils/copyLayerPrims.cpp
- lib/mayaUsd/utils/copyLayerPrims.h
- plugin/adsk/scripts/mayaUsdMenu.mel
- test/lib/mayaUsd/fileio/testDuplicateAs.py
- Add an option to the copyLayerPrims function to merge the top USD scope instead of creating new ones.
- This allows copying multiple prims with a common root tree without adding new branch every time.
- This is useful when duplicating materials only because each one creates a "mtl" scope to contain itself. With this change, all material will be under a common "mtl" scope instead of having a different scope for each.
- Make use of that mode in the duplicate code. Also, make sure we set the export selected flag so that it only duplicate materials in the selected Maya nodes.
- Modify the duplicate menu handler to parse the whole selection if the clicked object is in the selection.
- Add a unit test.
> EMSUSD-1527 support selection in duplicate to USD

- test/lib/mayaUsd/fileio/CMakeLists.txt
- test/lib/mayaUsd/fileio/testExportChaserJobContext.py
Create a unit test that register two export job context each with its own chaser and verify that they each get called.
> EMSUSD-1477 unit test for multi export chasers with multi job contexts

- lib/mayaUsd/fileio/jobs/jobArgs.cpp
The VRay plugin provides the chaser name by the user arguments instead of returning it in the plug-in job-context callback. (How they inject the chaser name in the arguments is still a mystery.)
The code used to overwrite such user arguments with the job-context arguments. (By calling VtDictionaryOver.) Now we instead merge the dictionaries with code refactored from the code used to merge job context arguments.
Do the same for the import context.
> EMSUSD-1477 merge job context arguments with user arguments

- lib/mayaUsd/nodes/layerManager.cpp
- lib/mayaUsd/utils/utilSerialization.cpp
- lib/mayaUsd/utils/utilSerialization.h
- lib/usd/translators/stageWriter.cpp
- lib/usd/ui/layerEditor/mayaSessionState.cpp
The problem was that the fact that the stage root layer was a relative path was lost when saved mid-export. Change the code so that the knowledge of the user's choice is always correctly preserved. Then the exported stage can correctly detect that the file path is relative.
- Add a function to check if a proxy shape is holding the file path as relative.
- Modify the setNewProxyPath function to take a flag to control if the new path is relative or not, including optionally following the mode selected in a option var or in the proxy shape.
- Use that new parameter when saving anonymous layers based on the known information that is passed when saving that anonymous layer, in the saveAnonymousLayer function.
- Use that new parameter when converting anonymous layers to saved layers.
- Use that …
> EMSUSD-1496 export stages as relative references

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/ufe/Utils.cpp
- plugin/adsk/scripts/mayaUsdMenu.mel
- test/lib/mayaUsd/fileio/testDuplicateAs.py
- Return the correct path of the copied object from the duplicate function.
- Don't try to process the virtual root prim path.
- Prepare the correct export options.
- Add a unit test for duplicate grouped meshes.
> EMSUSD-1629 fix copying grouped meshes

- test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateMaterialX.py
* Disable failing test with USD v24.08 because of issue with the custom OpenEXR code.
> EMSUSD-1550 - Build USD v24.08 (with oneTBB)

- lib/mayaUsd/fileio/jobs/readJob.cpp
- lib/mayaUsd/fileio/jobs/readJob.h
- lib/mayaUsd/fileio/primReaderContext.cpp
- lib/mayaUsd/fileio/primReaderContext.h
- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/fileio/translators/translatorXformable.cpp
- plugin/pxr/maya/lib/usdMaya/readJobWithSceneAssembly.cpp
- plugin/pxr/maya/lib/usdMaya/readJobWithSceneAssembly.h
As https://github.com/Autodesk/maya-usd/pull/3861 mentioned, this change seems breaking workflows.
Reverting the changes for now
> EMSUSD-986 - Revert edit as maya changes

- lib/usd/ui/layerEditor/layerTreeModel.cpp
- lib/usd/ui/layerEditor/layerTreeView.cpp
- lib/usd/ui/layerEditor/layerTreeView.h
- Don't use clear() to empty the layer tree model because it causes recursive Qt notifications.
- Remember the position of the scroll bars when updating the layer manager model.
- Don't allow recursive caching the layer manager state.
- Properly get rid of the cached state once restored.
> EMSUSD-1610 layer manager flicker

- lib/usd/ui/layerEditor/layerTreeView.cpp
- lib/usd/ui/layerEditor/layerTreeView.h
- lib/usd/ui/layerEditor/mayaLayerEditorWindow.cpp
When removing multiple layers the removal must not be delayed. This is due to the low-level implementation of layer removal: it uses the parent layer and the index of the sub-layer to be removed instead of its name. When commands are delayed, the index would become incorrect. By not delaying command, the index is properly calculated.
> EMSUSD-1619 fix removal on multiple layers

- lib/mayaUsd/fileio/orphanedNodesManager.cpp
- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/fileio/utils/CMakeLists.txt
- lib/mayaUsd/fileio/utils/proxyAccessorUtil.cpp
- lib/mayaUsd/fileio/utils/proxyAccessorUtil.h
- lib/mayaUsd/nodes/proxyAccessor.py
- test/lib/mayaUsd/fileio/CMakeLists.txt
- test/lib/mayaUsd/fileio/testEditAsMaya.py
- test/lib/testMayaUsdProxyAccessor.py
Hello,
This PR addresses an issue where pulled Maya objects transform and visibility were disconnected from the USD stages after renaming or reparenting a USD ancestor of the pulled prim. Our artists very frequently have multiple pulled objects in the same stage while re-structuring the hierarchy.
Before this fix:
Ater this fix:
Changes included in this PR:
- Added the ability to cleanly reparent a DAG to a USD item using `mayaUsd.lib.proxyAccessor`, ensuring it does not leave disconnected proxyAccessor outputs, potentially accessing invalid prims: a25dcd60cb84981e69d2bb5f64a6625a3e45a59b and unit-test 415dcb653db407229cf07991a623c5379230326f.
- Small refactoring of `PrimUpdaterManager` to mutualize the `mayaUsd.lib.proxyAccessor.parent` python call: …
> Fix reparenting/renaming of pulled objects USD ancestor

- lib/mayaUsd/render/pxrUsdMayaGL/proxyDrawOverride.cpp
- lib/usd/hdMaya/adapters/dagAdapter.cpp
- plugin/pxr/maya/lib/usdMaya/translatorModelAssembly.cpp
Hi, I just have some small fixes when compiling with MSVC 2022 and targetting an older Hydra API (USD 23.02).
First commit has the compiler fixes (changing operator notation `and` to `&&` and `not` to `!`) and the second commit has the comma fix for old hydra APIs.
I used these fixes for `release/v0.29.0` but I thought I'd target the `dev` branch for upstreaming.
Cheers
> MSVC 2022 compiler fixes + minor correction for older Hydra APIs

- lib/mayaUsd/utils/progressBarScope.cpp
Only issue warning if progress() returns a valid value
> Fix Progress Bar warnings

- lib/mayaUsd/render/MaterialXGenOgsXml/OgsFragment.cpp
- lib/mayaUsd/render/MaterialXGenOgsXml/OgsFragment.h
- lib/mayaUsdAPI/render.cpp
- lib/mayaUsdAPI/render.h
This will expose the MaterialX path of a library definition containing hardcoded image paths, allowing clients to fetch the relevant data required to populate those shader inputs.
> LOOKDEVX-3222 - Expose hardcoded texture paths

- lib/mayaUsd/fileio/jobs/writeJob.cpp
Since the default prim logic was needed to determine the parent scope of materials in the current material scope behavior, it isn't needed if using the legacy material scope strategy
> Use legacy DefaultPrim logic if using legacy material scopes

- test/lib/ufe/testReferenceCommands.py
- test/testSamples/twoSpheres/sphere_ext.usda
- test/testSamples/twoSpheres/spheres_ref.usda
Modifying a test file that is used in multiple tests is causing issues in our test framework. This change splits the file that is overwritten during the testReferenceCommands test to avoid corrupting other tests that are trying to use the same test file
> Copy a test file for use in overwrite testing

- lib/usd/schemas/plugInfo.json.in
- test/lib/mayaUsd/fileio/UsdCustomRigSchema/plugInfo.json
This still allows aliases as identifiers as a backup
> USD 24.11 adds explicit schemaIdentifier fields

- test/lib/ufe/testLight.py
EMSUSD-1654 Fixed Test a typo in testLight's testUsdVolumeLights that causes the test to fail when there's no `Light_v5_5` attribute defined.
> EMSUSD-1654 Fixed Test a typo in testLight's testUsdVolumeLights

- README_DOC.md
- lib/mayaUsd/commands/Readme.md
- lib/mayaUsd/commands/baseImportCommand.cpp
- lib/mayaUsd/commands/baseImportCommand.h
- lib/mayaUsd/fileio/doc/How-to-add-new-option.md
- lib/mayaUsd/fileio/jobs/jobArgs.cpp
- lib/mayaUsd/fileio/jobs/jobArgs.h
- lib/mayaUsd/fileio/jobs/readJob.cpp
- lib/mayaUsd/fileio/jobs/readJob.h
- lib/mayaUsd/python/wrapPrimReader.cpp
- plugin/adsk/scripts/mayaUSDRegisterStrings.mel
- plugin/adsk/scripts/mayaUsdTranslatorImport.mel
- test/lib/usd/translators/CMakeLists.txt
- test/lib/usd/translators/UsdImportUpAxisTests/UpAxisY.usda
- test/lib/usd/translators/testUsdImportUpAxis.py
- test/lib/usd/translators/testUsdImportXforms.py
- Add -upAxis (-upa) and -axisAndUnitMethod (-aum) flags to the base import command.
- Document the new flags in the import command read-me file.
- Add upAxis and axisAndUnitMethod tokens to the import job args tokens.
- Add the rotateScale, addTransform and overwritePrefs tokens to the import job args token.
- Add the upAxis and axisAndUnitMethod data to the UsdMayaJobImportArgs structure.
- Handle parsing the new user args to build the UsdMayaJobImportArgs.
- Expose the upAxis and axisAndUnitMethod data to Python.
- Add the new UI related to upAxis and axisAndUnitMethod in the import UI.
- Add documentation about how to add a new import or export option.
Implement import rotation
- Add axis conversion helper to the UsdMaya_ReadJob class.
- Determine the Maya up-axis and USD up-axis.
- …
> EMSUSD-946 axis in import UI and command

- lib/mayaUsd/fileio/chaser/exportChaser.cpp
- lib/mayaUsd/fileio/chaser/exportChaser.h
- lib/mayaUsd/fileio/jobs/jobArgs.cpp
- lib/mayaUsd/fileio/jobs/jobArgs.h
- lib/mayaUsd/fileio/jobs/writeJob.cpp
- lib/mayaUsd/fileio/jobs/writeJob.h
- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/python/wrapExportChaser.cpp
- lib/mayaUsd/python/wrapPrimWriter.cpp
- test/lib/mayaUsd/fileio/testExportChaserJobContext.py
When "Duplicate as Usd data" is select from the context ops menu on a maya object, we only translate to Usd the selected maya object.
This can be a problem when there are extra prims created by a chaser, for example. Those would be discarded.
With those changes, we allow the users to register the path for those extra prims created so that it can be queried when merging the maya object into Usd.
> EMSUSD-1555 Duplicating a Physical Sky to USD using Arnold options is missing data

- lib/mayaUsd/render/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
- lib/mayaUsd/render/MaterialXGenOgsXml/OgsXmlGenerator.cpp
Does not affect USD since geompropvalue should be used instead for accessing vertex color streams.
> LOOKDEVX-2640 - Fix compilation error when using geomcolor nodes

- lib/mayaUsd/commands/Readme.md
- lib/mayaUsd/commands/baseImportCommand.cpp
- lib/mayaUsd/commands/baseImportCommand.h
- lib/mayaUsd/fileio/jobs/jobArgs.cpp
- lib/mayaUsd/fileio/jobs/jobArgs.h
- lib/mayaUsd/fileio/jobs/readJob.cpp
- lib/mayaUsd/fileio/jobs/readJob.h
- lib/mayaUsd/fileio/jobs/writeJob.cpp
- lib/mayaUsd/python/wrapPrimReader.cpp
- lib/mayaUsd/utils/util.cpp
- lib/mayaUsd/utils/util.h
- plugin/adsk/scripts/mayaUSDRegisterStrings.mel
- plugin/adsk/scripts/mayaUsdTranslatorImport.mel
- test/lib/usd/translators/CMakeLists.txt
- test/lib/usd/translators/UsdImportUnitsTests/UnitsMillimeters.usda
- test/lib/usd/translators/testUsdImportUnits.py
- Add -unit (-unt) option to the import command.
- Document it.
- Add unit option to the job import argument structure.
- Parse the unit option.
- Expose it to Python.
- Add check-box UI to the import UI.
- Add private structure to the import read job class to hold all conversion info.
- Remove old warning about unit conversion not being implemented.
- Refactor the code for up-axis conversion to also handle the units conversion.
- Change prefs for units if requested and needed.
- Add unit tests.
> EMSUSD-947 units conversion for USD import

- test/lib/mayaUsd/fileio/testDuplicateAs.py
- test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateUSDPreviewSurface.py
- test/lib/usd/translators/testUsdImportXformAnim.py
Pixar's configuration will use Z-up for USD stages by default, but Maya defaults to Y-up. This was causing objects to get rotated on import/export, which caused test failures. Disable this translation for these tests
> Disable upAxis translation on import/export in tests

- lib/mayaUsd/ufe/UsdUndoMaterialCommands.cpp
- lib/mayaUsd/ufe/UsdUndoMaterialCommands.h
- lib/mayaUsd/ufe/UsdUndoRenameCommand.cpp
- test/lib/ufe/testContextOps.py
Fix crash when trying to assigned a material to a prim in a locked layer. The code was failing to check for null in a critical place.
- Check for null item or stage when renaming prim.
- Check for null after creating a scope.
- Properly sequence undo vs undo-block when the execution fails.
- Add a unit test to verify the crash fix.
> EMSUSD-1682 assign material to lock layer

- lib/mayaUsd/fileio/translators/translatorBlendShape.cpp
- lib/mayaUsd/fileio/translators/translatorSkel.cpp
- lib/mayaUsd/fileio/utils/meshWriteUtils.cpp
- lib/mayaUsd/fileio/utils/meshWriteUtils.h
- lib/usd/translators/meshWriterBlendShapes.cpp
- test/lib/usd/translators/testUsdExportBlendshapes.py
- test/lib/usd/translators/testUsdImportBlendShapes.py
Describing the issue:
When importing an USD asset with blendshapes and then re-exporting it, the blendshapes on the re-exported asset seem incorrect.
Solution:
Looking at the connections node after import, there were some connections not correctly made in maya.
This PR fix those connects as well as tries to match the node namings to closer to what it was before what it was exported.
This pr fixes #3921
> EMSUSD-1712 Reimport blendshape issues

- lib/mayaUsd/fileio/jobs/readJob.cpp
- lib/mayaUsd/utils/dynamicAttribute.cpp
- lib/mayaUsd/utils/dynamicAttribute.h
- test/lib/usd/translators/testUsdImportUnits.py
- test/lib/usd/translators/testUsdImportUpAxis.py
- Change the dynamic attribute APi to allow controlling the attribute flags.
- Make the up-axis and units attributes be visible.
> EMSUSD-1700 make up-axis and units attribute visible

- lib/usdUfe/ufe/UsdUndoAddNewPrimCommand.cpp
- lib/usdUfe/ufe/Utils.cpp
- lib/usdUfe/ufe/Utils.h
- lib/usdUfe/undo/UsdUndoBlock.cpp
- lib/usdUfe/undo/UsdUndoBlock.h
- lib/usdUfe/undo/UsdUndoManager.cpp
- lib/usdUfe/undo/UsdUndoManager.h
- test/lib/ufe/testContextOps.py
- Refactor the USD undo block and undo manager to support extending an undo item with new undos.
- Add a helper function to cleanup the session layer of a given prim data, capturing the removal in an undo item.
- Make the add-prim command use the session clean-up helper.
- Add unit test.
> EMSUSD-1613 clean session layer when undoing add prim

- lib/mayaUsd/fileio/jobs/readJob.cpp
- lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
When the USD import needs to change the Maya units preferences, we need to close the preferences window, otherwise it will overwrite the preferences when closed.
> EMSUSD-1718 automatically close prefs when changing units

- lib/mayaUsd/utils/utilSerialization.cpp
Don't try to set the units and up-axis metadata on layers that are not editable.
> EMSUSD-1222 no metadata on read-only layers

- lib/mayaUsd/nodes/layerManager.cpp
- lib/mayaUsd/nodes/layerManager.h
- lib/mayaUsd/nodes/proxyShapeBase.cpp
- test/lib/CMakeLists.txt
- test/lib/testMayaUsdCreateStageInMayaRef.py
When loading a Maya scene containing a stage, possibly through other Maya reference, find the correct layer manager node for the stage. Each layer manager node is specific to the scene or reference.
- Add an optional parameter to some layer manager function to specify the Maya reference that should contain the information.
- Pass the correct Maya reference, if any, when computing the proxy shape node layers.
- Add a unit test to load a stage in a Maya reference.
> EMSUSD-1722 find the correct layer manager node

- test/lib/mayaUsd/fileio/testSaveLockedAnonLayer.py
- test/lib/mayaUsd/fileio/testSaveUpAxisAndUnits.py
Two tests were using the same scene file names. Maybe they were randomly overwriting each other when run in parrallel.
> Make unit test scene file names unique

- lib/mayaUsd/render/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
- lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaShaderGraph.cpp
- lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaShaderGraph.h
This PR is an attempt to back port the following MaterialX PR for MayaUsd: https://github.com/AcademySoftwareFoundation/MaterialX/pull/2076.
This PR makes it possible to have defaultgeomprop values on nodegraph inputs as opposed to only on nodedef inputs.
> Adds support for defaultgeomprop values on nodegraph inputs.

- lib/mayaUsd/commands/layerEditorCommand.cpp
- lib/mayaUsd/python/__init__.py
- lib/mayaUsd/resources/ae/usdschemabase/Attribute-Editor-Template-Doc.md
- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
- lib/mayaUsd/resources/ae/usdschemabase/attributeCustomControl.py
- lib/usdUfe/python/wrapUICallback.cpp
- lib/usdUfe/ufe/UsdContextOps.cpp
- lib/usdUfe/utils/uiCallback.cpp
- lib/usdUfe/utils/uiCallback.h
* Added new `triggerUICallback` function and removed `getUICallbacks`
* Updated AE doc on how to use new AE custom callback.
* New custom callback section in AE template giving clients ability to add to AE template.
* New attribute nice name callback to give clients ability to inject function into attribute nice name.
> EMSUSD-1630: Support custom callback for primitives AE template

- lib/mayaUsd/fileio/jobs/jobArgs.cpp
- lib/mayaUsd/fileio/jobs/jobArgs.h
- lib/mayaUsd/fileio/jobs/writeJob.cpp
- plugin/adsk/scripts/mayaUSDRegisterStrings.py
- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
- test/lib/usd/translators/testUsdExportUnits.py
- test/testUtils/transformUtils.py
- Add "dm" in the supported units in the export command.
- Add a Decimeters entry in the drop-down menu for units in export.
- Add unit tests for all export units.
- Adjust precision of comparison because comparison would fail for feet.
> EMSUSD-1724 add support for decimeters in export

- lib/mayaUsd/resources/ae/usdschemabase/Attribute-Editor-Template-Doc.md
- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
- lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
- test/lib/testAttributeEditorTemplate.py
- Accumulate all schemas and their attributes before creating any UI for them.
- Re-ordered schemas according to the design.
- Renamed Xformable to Transforms.
- Made all sections be collapsed by default except the prim type section, Light and Light type
- Removed the "Applied Schemas" section.
- Add a unit test and fix some tests that assumed sections would be expanded.
> EMSUSD-1521 modify AE section order

- lib/mayaUsd/nodes/layerManager.cpp
- lib/usdUfe/utils/layers.cpp
- lib/usdUfe/utils/layers.h
- test/lib/usd/translators/UsdExportStagesAsRefsTest/sceneWithStage.ma
- test/lib/usd/translators/testUsdExportStagesAsRefs.py
- Add an helper function to check if a stage is dirty.
- Do not save dirty layers when exporting to USD.
- Instead, warn about anonymous or dirty stages.
- Add a unit test.
> EMSUSD-1455 no save during export

- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
- plugin/adsk/scripts/mayaUsdTranslatorImport.mel
- plugin/adsk/scripts/mayaUsd_createStageFromFile.mel
Make it offset 8 pixel from parent. Yes, it only requires 2 pixels offset, due to internal margins, etc.
> EMSUSD-1766 adjust axis and units section indent

- lib/mayaUsd/nodes/layerManager.cpp
- lib/mayaUsd/nodes/layerManager.h
- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/nodes/proxyShapeBase.h
- lib/mayaUsd/utils/util.cpp
- lib/mayaUsd/utils/util.h
- lib/usd/ui/layerEditor/mayaSessionState.cpp
- test/lib/testMayaUsdCreateStageInMayaRef.py
- Pass the proxy node to the layer manager so it can determine which layer manager corresponds to the proxy node.
- We keep track of the association by connecting a new proxy shape attribute to the layer manager so that we can traverse the connection to find the layer manager.
- Fix a crash in MayaSessionState when the proxy shape has been deleted before the on-idle callback is run.
- This can happen in scripts that creates scene, a stage and clear the scene in one go, before an on-idle callback is run.
- Make the test more similar to the script in the ticket.
> EMSUSD-1722 fix node origin detection

- lib/mayaUsd/fileio/jobs/writeJob.cpp
- test/lib/usd/translators/testUsdExportDefaultPrim.py
Properly filter the default prim argument to convert it in the same way we convert DAG paths while exporting.
Add a unit test to cover exporting a mesh inside a namespace and set as the default prim.
> EMSUSD-1777 namespace in USD default prim export argument

- lib/mayaUsd/fileio/jobs/writeJob.cpp
- lib/mayaUsd/utils/util.cpp
- lib/mayaUsd/utils/util.h
- test/lib/usd/translators/testUsdExportDefaultPrim.py
- Add a helper function to convert a DAG path to a valid prim name.
- Properly create the default prim name using that function.
- Add a unit test for the export roots without default prim case.
> EMSUSD-1745 fix export roots when no default prim is specified

- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
- test/lib/testAttributeEditorTemplate.py
- Add the custom callback to teh list of section to add.
- Create a unit test that verify it works.
> EMSUSD-1813 fix custom AE callbacks

- lib/mayaUsd/ufe/CMakeLists.txt
- lib/mayaUsd/ufe/MayaUsdContextOps.cpp
- lib/mayaUsd/ufe/MayaUsdHierarchyHandler.cpp
- lib/mayaUsd/ufe/MayaUsdHierarchyHandler.h
- lib/mayaUsd/ufe/ProxyShapeHierarchy.cpp
- lib/usdUfe/ufe/UsdContextOps.cpp
- lib/usdUfe/ufe/UsdHierarchy.cpp
- lib/usdUfe/ufe/UsdHierarchyHandler.cpp
- lib/usdUfe/ufe/Utils.cpp
- lib/usdUfe/ufe/Utils.h
- test/lib/ufe/testChildFilter.py
- test/testSamples/classPrims/class-prims.usda
- Add a getUsdPredicate helper function to UsdUfe to create the USD predicate corresponding to a list of UFE filters.
- Add the "Class Prims" filter to the list of USD filters in the hierarchy handler.
- Use the helper to create the USD predicate.
- Rely on the USD predicate having a correct predicate for inactive prim instead of using an explicit flag.
- Adjust the context menu for class prims.
- Add a unit test for the class prims filter.
Work around the problem that Maya does not correctly handle UFE filters. Maya only handles one UFE filter. If there are more than one filters, only one is handled.
To work around this issue, we manually ask the outliner what are the desired settings and use these settings as the default values for the filters. When the outliner fails to handle multiple …
> EMSUSD-1570 add a class-prims filter to USD UFE

- lib/mayaUsd/resources/ae/CMakeLists.txt
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/__init__.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/widget.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/__init__.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/list.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/persistentStorage.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/resizable.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/theme.py
- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
- lib/mayaUsd/resources/ae/usdschemabase/lightCustomControl.py
- test/lib/testAttributeEditorTemplate.py
Initial iteration of the new light attributes:
* Added a new attribute to Usd Lights
* Lists of included and excluded prims to the light collection
* Ability to "Include all" which sets the `includeRoot` light attribute
The main new file is the `widget.py` under the collection folder. The common folder are for inheriting different Qt classes and themes.
> EMSUSD-1518 As an artist, I want the ability to determine whether a collection includes all objects by default or not

- lib/mayaUsd/fileio/orphanedNodesManager.cpp
- lib/mayaUsd/fileio/utils/proxyAccessorUtil.cpp
- lib/mayaUsd/nodes/proxyAccessor.py
This PR addresses a crash that occurs when renaming a USD prim with descendant prims edited as Maya, while the Attribute Editor is visible and displaying the prim being renamed. I observed the issue on Maya 2023 and 2025 on Linux. It occurs since PR #3861.
The crash can be reproduced using this [maya scene](https://github.com/user-attachments/files/17546929/crash_ae_on_ufe_rename.zip). To trigger the issue, open the AE, select and rename a prim such as `/Root1`. This should result in a hard crash within `TPSdatabase::doRebuild`, typically producing the following stack trace:
```
TPSdataNode::typeName(bool) const
TPSdatabase::generateUI(QLayout*, TPSdataNode*, bool)
TPSdatabase::generateUI(QLayout*, TdependNode*, bool)
TPSdatabase::doRebuild(Tevent const&) …
```
> Fix crash in Attribute Editor when renaming a prim with pulled descendants

- lib/usdUfe/ufe/UsdUndoCreateGroupCommand.cpp
- lib/usdUfe/ufe/Utils.cpp
- lib/usdUfe/ufe/Utils.h
- test/lib/ufe/testGroupCmd.py
- test/lib/ufe/testUngroupCmd.py
When grouping USD items, make the group name more unique vs other existing group names. This avoid having a chain of group with names almost all the same.
We don't do this for other prims, because too much code, especially unit tests related to materials, assume that the names will have specific pattern.
- Add a new utility function is UsdUfe to make a name relatively unique.
- Use that function to prepare the group name.
- Add a new unit test.
- Adjust a ungroup unit test that assumed things about the group name.
> EMSUSD-1490 make group names more unique

- lib/usd/translators/lightReader.cpp
As discussed, disable the editAsMaya for now instead of writing light reader/writers
> EMSUSD-1625 - Disable EditAsMaya for cylinder, disk and dome light

- lib/mayaUsd/commands/layerEditorCommand.cpp
- test/lib/testMayaUsdLayerEditorCommands.py
On `refreshSystemLock`, the stage's editTarget could be improperly set to the session layer when our callback unlocks a layers which is non-writable on disk. In such cases, in-memory layer editions should still be allowed without enforcing the session layer. We are encountering this issue in production and we need the editTarget selection to be preserved in such case.
Additionally, the editTarget update did not account for new locks that could be introduced by `onRefreshSystemLock` callbacks.
- Changed the timing of `updateEditTarget` calls within the `refreshSystemLock` command: https://github.com/jufrantz/maya-usd/commit/33e48e2f24af0e1ea61352381abae2a2f73996c5
- Added unit tests to validate `refreshSystemLock` behavior across various callback scenarios: …
> Improve stage edit target updates with refreshSystemLock callbacks

- CMakeLists.txt
* Boost is not needed when building UsdUfe only.
> EMSUSD-1770 - Initial support for USD v24.11

- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
- lib/mayaUsd/resources/ae/usdschemabase/lightCustomControl.py
- test/lib/testAttributeEditorTemplate.py
Apply the collection widget to all collections on prims, not just lights.
> EMSUSD-1856 make the collection widget support all collections

- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
A previous change broke which attributes are added to the extra attributes section. That is because the default function to create an attribute UI returns None and was interpreted as no UI being created.
This is a unfortunate consequence of the design: the return value is interpreted as success or failure of creating a UI and then, on success, custom callbacks are connected to that UI. But for the default fallback, those callbacks must not be added, so it returns None, which was interpreted as failure. Given that it is the final fallback, that had no consequences, but a code change made registering the attribute as being handled was no longer done properly.
Restore the old code, which was adding the attribute to the list of known, handled attributes. Also, don't add suppressed attributes …
> Fix AE extra attribute section.

- lib/mayaUsd/resources/ae/CMakeLists.txt
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/includeExcludeWidget.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/filteredStringListModel.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/filteredStringListView.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/list.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/resizable.py
- Add a FilteredStringListModel class.
- Use that model in the collection string list widgets.
- Add a text edit widget to enter the search text
- Connect the search changed signal to the filtered model.
- Add a button to clear the search filter.
- Add a flag on the filtered model to remember if it was entirely filtered out.
- Properly re-filter the model when a new list of text is given.
- Moved the filtered view in its own file.
- Give the resizable lists a sensible default size.
> EMSUSD-1856 Add filtering search to the collection widget

- lib/mayaUsd/ufe/UsdLight.cpp
- test/lib/ufe/testLight.py
- test/testSamples/light/SimpleLight.usda
- Don't create light attributes when reading them.
- Make all set function create the attribute if it does not exists.
- Add a unit test for loading stage with lights not being dirty.
> EMSUSD-1891 Don't dirty stage when loading

- lib/usdUfe/utils/Utils.cpp
- Ui Nodegraph Node -> Ui
Example: Ui Nodegraph Node Pos -> Ui Pos
Justification: the section is already titled Node Graph Node
- Translate Scale/Rotate Pivot -> Scale/Rotate Pivot
Example: Translate Scale Pivot -> Scale Pivot
Justification: pivot are always translations, no need to say it, it is implicit in being a pivot.
- Translate Scale/Rotate Pivot Translate -> Rotate/Scale Pivot Translate
Example: Translate Scale Pivot Translate -> Scale Pivot Translate
> EMSUSD-968 shorter nice names

- test/lib/ufe/testLight.py
For some reasons, USD 24.11 reports the root layer as being modified even though dumping the layer as string shows the data is not modified. Will need to be investigated further.
> EMSUSD-1912 disable new light test on USD 24.11

- lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.cpp
- lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.h
- lib/mayaUsdAPI/render.cpp
- lib/mayaUsdAPI/render.h
- test/lib/mayaUsd/utils/test_ShaderGenUtils.cpp
Allows quickly reducing a graph to only a surface for when the viewport is in "untextured" mode.
> MAYA-133671 - Add textured mode handling to topo grapher

- lib/mayaUsd/nodes/layerManager.cpp
The `MayaUsd::utils::saveLayerWithFormat` function uses two approaches to save USD data, depending on the layer file format:
- **Matching file format:**
If the layer file's format matches the user's preferences, the function calls `SdfLayer::Save()`. By default, Save() does not overwrite the file unless the layer has been modified.
- **Mismatched file format:**
If the file format differs from the user's preferences, the function uses `SdfLayer::Export()` to save the layer to the file. Unlike Save(), Export() always writes to the file, even if the layer hasn’t been modified in memory, potentially overwriting more recent changes on disk.
With this PR, `LayerDatabase::saveUsdToUsdFiles` now performs a "dirty" check to ensure that only modified layers are saved (exported). This change is …
> LayerManager: Prevent unintended overwriting of unmodified USD layers at Maya save.

- lib/mayaUsd/utils/diagnosticDelegate.cpp
When aborting the process due to a fatal error (for example TF_CODING_ERROR or setting the environment variable TF_FATAL_VERIFY to 1), MayaUSD would get in a deadlock. Fix this by avoiding trying to unregister the diagnostic delegate when logging a fatal error.
> Fix fatal error exit

- lib/mayaUsd/python/wrapPrimReader.cpp
- lib/mayaUsd/python/wrapPrimWriter.cpp
The PrimReaderWrapper<T> and PrimWriterWrapper<T> helper classes ignored the template parameter when deriving from TfPyPolymorphic. This caused unexpected duplicate entries in boost::python's type conversion table. boost::python silently accepted this, but the new pxr_boost::python in OpenUSD 24.11 flagged this with an assert in debug mode.
The wrappings for ShaderReaderWrapper and ShaderWriterWrapper incorrectly specified PrimReaderWrapper<> and PrimWriterWrapper<> as their bases. For example, this meant that passing an instance of a ShaderReader to a a Python-wrapped C++ function that takes a UsdMayaPrimReader would fail. This doesn't show up in practice since clients aren't expected to create their own instances of these types but it seemed good to fix anyway.
> Fix UsdMayaPrimWriter and UsdMayaPrimReader Python Wrappings

- test/lib/ufe/testLight.py
Now that we have a fix in Maya, we can re-enable the test.
> EMSUSD-1912 Re-enable light test for USD 24.11

- lib/mayaUsd/commands/layerEditorCommand.cpp
No longer change the selection in the lock layer command.
> EMSUSD_1917 lock layer should preserve the selection

- lib/mayaUsd/python/wrapPrimWriter.cpp
- test/lib/mayaUsd/fileio/testPrimWriter.py
Some export job arguments were not exposed to Python code. We now expose them and verify that they are accessible in a unit test.
> EMSUSD-1919 expose export job args to Python

- cmake/modules/FindUSD.cmake
- lib/usdUfe/CMakeLists.txt
- lib/usdUfe/ufe/UsdUndoInsertChildCommand.cpp
- test/lib/ufe/testGroupCmd.py
If a prims has a reference the normal reparent algorithm would flatten the reference. In the frequent case where the prim only has opinion on a single layer and grouping in the same layer, we can instead rename the prim. This requires support for namespace edits in USD.
- Detect this common case and use namespace edits when available.
- Add a unit test to validate this.
> EMSUSD-1949 better support for grouping prims with references

- lib/mayaUsd/fileio/jobContextRegistry.cpp
- lib/mayaUsd/fileio/jobContextRegistry.h
- test/lib/usd/plugin/nullApiExporter.cpp
- Change the job context registration macro to be order-independent.
- Change unit test to verify that the macro are order-neutral by registering UI first.
> EMSUSD-1971 Make job context UI registeration be order-neutral

- lib/mayaUsd/resources/ae/CMakeLists.txt
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/expressionRulesMenu.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/expressionWidget.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/includeExcludeWidget.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/widget.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/filteredStringListModel.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/filteredStringListView.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/stringListPanel.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/theme.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/data/__init__.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/data/collectionData.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/data/stringListData.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/usdData/__init__.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/usdData/usdCollectionData.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/usdData/usdCollectionStringListData.py
Separate data from UI:
- Add data and usdData modules.
- Add collectionData and stringData to the data module as abstract interface to read and modify collection data.
- Add usdCollectionData and usdCollectionStringListData to usdData, for USD implementation.
- This also avoids business logic referring to UI labels and such.
- This also automatically updates the data source for the UI since the model is the data source.
- Allow setting the collection on the usdCollectionData.
- Fix the default value for the include-all flag.
- Still need to derive a Maya implementation to host picking and undo/redo.
- Make all UI use the collectionData and stringListData classes to hold and modify data instead of having business logic in UI.
Refactor UI code:
- Rename list.py to stringListPanel.py to …
> EMSUSD-1519 refactor collection UI

- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/expressionRulesMenu.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/includeExcludeWidget.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/filteredStringListView.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/theme.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/data/collectionData.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/usdData/usdCollectionData.py
- lib/mayaUsd/resources/ae/usdschemabase/lightCustomControl.py
- Add to the data classes a function to remove all includes and excludes.
- Add to the UI a menu item to remove all includes and excludes.
- Make the UI call the data when triggered.
- Make menu item separators show up even as first item.
- Fix place holder text in list view.
- Fix non-light collections.
> EMSUSD-1519 Collections: remove all includes and excludes

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
MayaUSD should use a copy of the HdStorm MaterialX library in order to optimize it without affecting any Storm based render delegate.
> EMSUSD-2000 - Do not contaminate HdStorm libraries with lobe pruning

- lib/mayaUsd/resources/ae/CMakeLists.txt
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/expressionWidget.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/widget.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/host.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/usdData/usdCollectionData.py
- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
- lib/mayaUsd/resources/ae/usdschemabase/collectionCustomControl.py
- lib/mayaUsd/resources/ae/usdschemabase/collectionMayaHost.py
- plugin/adsk/plugin/plugin.cpp
- Added methods on the Host class to create the data used by the UI.
- Host create USD collection and string list by default.
- Use the Host to create the data in the UI classes.
- UsdCollectionData uses Host to create its string lists.
- Make the expression widget update itself on USD data changed notification even when there is no expression attribute.
- Rename the light linking custom control to be collection custom control.
- Move the Maya host class to its own file.
- Implement Maya-specific collection data with all needed setters.
- Add a _UsdUndoBlockContext class to capture all USD changes into undo items and later transfer them to a Maya command.
- Add a _UsdUndoBlockCommand that transfer the captured undo items into itself for future undo and redo.
- Add a _UndoItemHolder class …
> EMSUSD-1657 light linking undo and redo

- lib/usdUfe/ufe/StagesSubject.cpp
- test/lib/ufe/testSelection.py
This handles the case where we receive a prim deleted message outside of a maya command, which results in the removal of a selected prim. In this case, we trigger a subtree invalidated notice so that the global selection list will be updated.
> Update change processing code

- lib/mayaUsd/resources/ae/CMakeLists.txt
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/expressionWidget.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/widget.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/filteredStringListView.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/resizable.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/stringListPanel.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/theme.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/data/collectionData.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/data/stringListData.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/usdData/usdCollectionData.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/usdData/usdCollectionStringListData.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/usdData/validator.py
- Fix setting a new prim and collection on an existing collection widget.
- Remove obsolete list item delegate and unused painters from the list view widget.
- Remove unused painter function from the Theme class.
- Make the data setter return true or False if the data was set or not.
- (This will potentially make possible to not add an undo for do-nothing actions.)
- Add validation of the prim and collection to avoid printing stack traces to the user.
- Update the check condition to change include all.
- Don't change focus of the expression widget on enter.
- Don't allow pasting text with formatting (bold, etc)
- Making the resizing of the list widgets more robust.
- Added an error message when setting the expression causes an exception.
- Avoid submitting the expression when it has not …
> EMSUSD-0 bring light linking changes from the shared repo

- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/widget.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/theme.py
- lib/mayaUsd/resources/ae/usdschemabase/collectionCustomControl.py
- lib/mayaUsd/resources/ae/usdschemabase/collectionMayaHost.py
- Make tabs be themeable by the Theme class.
- Create a MayaTheme to theme the tab to look right in Maya.
- Make the collection widget theme its tab using the Theme class.
- Only inject Host and Theme once.
> EMSUSD-1984 collection tab look

- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/includeExcludeWidget.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/menuButton.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/theme.py
Adjust the spacing in the include/exclude header buttons.
> EMSUSD-1997 adjust collection UI spacing

- lib/usdUfe/ufe/UsdSceneItem.cpp
- test/lib/testAttributeEditorTemplate.py
Give def a base type so that the Maya AE machinery can find the AE template, which assumes that the prim ultimately has UsdSchemaBase as a base type.
Added a unit test.
> EMSUSD-1890 show Def in AE

- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/usdData/validator.py
- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
- Make the validator function decorator catch the exceptions raised within the USD collection data classes to handle the case where the USD version does not support some API.
- Make the special code used to handle multi-apply schemas in USD prior to 22.3 correctly list the collection attribute itself.
> EMSUSD-2132 fix collections for Maya 2023

- build.py
* Catch when test run fails and re-run only failed tests.
> EMSUSD-2124 - MayaUsd: rerun failed tests to make random failures more stable

- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/expressionWidget.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/includeExcludeWidget.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/warningWidget.py
Was trusting the icon visibility as being equal to the conflicted state, but when the UI is not visible on-screen, the the icon might be invisible due to not be on-screen rather than due to being hidden. So we now keep an explicit flag instead.
> EMSUSD-1674 fi warning icon not disappearing

- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
- Python 3.9 treat static methods vs self differently than newer Python version.
- USD 22.11 did not list the base collection schema in the list of attributes.
> EMSUSD-2111 support the collection UI in Maya 2023.

- lib/mayaUsd/render/mayaToHydra/utils.h
- lib/mayaUsd/render/px_vp20/utils.cpp
- lib/mayaUsd/render/px_vp20/utils.h
- lib/mayaUsd/render/pxrUsdMayaGL/proxyDrawOverride.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
This PR skips MayaUsd handling of USD data when Hydra is being used, to avoid unnecessary processing and data loading. The change essentially rehabilitates an existing fix, but also updates it for the new MayaHydra render override prefix.
The changes will only take effect in viewports using MayaHydra; this should address the concerns raised in the previous attempt at solving this issue : https://github.com/Autodesk/maya-usd/pull/4060#issuecomment-2579789457. We only block rendering and selection, as they are both handled by MayaHydra.
I ran MayaHydra unit tests and all passed (except `testMaterialXOnNative` as I did not have LookdevX installed).
> HYDRA-1347 : Fix double texture loading when using Hydra

- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
- test/lib/testAttributeEditorTemplate.py
- Check both suppressed and already-added attributes when creating section to avoid adding attributes twice to the AE.
- Support schemas without Python support.
> EMSUSD-1932 applied schemas in AE

- lib/mayaUsd/fileio/primUpdaterManager.cpp
If there are no entries corresponding to the source DAG path in the map, try to use one of the extra prims as the source root path.
> MTOA-2265 duplicate material to USD with Arnold

- lib/mayaUsd/fileio/shading/shadingModeExporter.cpp
This was caused by an out-of-range vector access.
> ShadingModeExporter: Fix potential crash when exporting collection-based material bindings.

- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/expressionWidget.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/includeExcludeWidget.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/filteredStringListModel.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/filteredStringListView.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/data/stringListData.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/usdData/usdCollectionStringListData.py
- lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/usdData/validator.py
Also addresses: EMSUSD-2168, EMSUSD-2169, EMSUSD-2171, EMSUSD-2167, EMSUSD-2151
Fix validation error:
- Make the convertToCollectionString return the cause of any error.
- Make the validator only handle the attribute error exception caused by the absence of expression support in old USD, not all exceptions.
Fix list editor:
- Replace ad-hoc code with QCompleter and QItemDelegate to edit the list items.
- This fixes multiple interaction bugs.
- Mark the filtered string list model items as being editable.
- Make sure the list view gets focus after edit.
- Make sure the new item can be added before deleting the old item in replaceStrings.
- Simplify how the stage prims are gathered for suggestions.
> EMSUSD-2171 Fix multiple collection UI issues

- lib/mayaUsd/fileio/shading/shadingModeExporterContext.cpp
- test/lib/usd/translators/CMakeLists.txt
- test/lib/usd/translators/UsdExportUVSetsSwitchTest/UsdExportUVSwitchTest.ma
- test/lib/usd/translators/testUsdExportUVSetsSwitch.py
The uvLink command can return nothing if it cannot determine the UV link of the shader node. This would break assumptions in the export code and lead to a crash when accessing missing data. Handle the case where the uvLink command returns nothing to prevent that crash.
Add a unit test that reproduced the crash and now no longer crashes.
> EMSUSD-1896 avoid crash when shader has no uvLink

- lib/usdUfe/python/wrapUICallback.cpp
Using Py_IncRef() / Py_DecRef() to ensure the python callback will be alive.
> EMSUSD-2224 - usdUfe.registerUICallback can crash with python lambdas

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/undo/OpUndoItems.cpp
- lib/mayaUsd/undo/OpUndoItems.h
When editing as Maya a `mayaReference` prim, we noticed that `allowTopologyMod` attributes were being force-enabled on all referenced meshes, cluttering the reference edits list and preventing these attributes from being disabled up-front if needed. 
This PR skips these forced edits unless allowTopologyMod was really disabled by the preceding LockNodeUndoItems execution.
> PrimUpdaterManager: Avoid spurious `allowTopologyMod` reference edits

- lib/mayaUsd/ufe/ProxyShapeSceneSegmentHandler.cpp
- lib/mayaUsd/ufe/UsdStageMap.cpp
- lib/mayaUsd/ufe/UsdStageMap.h
- lib/mayaUsd/ufe/Utils.cpp
- lib/mayaUsd/ufe/Utils.h
- test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateCameras.py
EMSUSD-2199 - Fixes a performance issue regarding findGatwayItems() / cameras
This change addresses some of the performance issues mentioned in https://github.com/Autodesk/maya-usd/issues/4125
- Created methods to check / get the list of stages without having to re-generate / update the stage map cache.
- Added an early out in findGatwayItems to avoid unnecessary looping.
> EMSUSD-2199 - Fixes a performance issue regarding findGatwayItems() / cameras

- lib/mayaUsd/nodes/proxyAccessor.h
- test/lib/testMayaUsdProxyAccessor.py
EMSUSD-2222: [Github #4142] Duplicating a ProxyStage and hiding the duplicate causes Maya to Crash
* When duplicating the node we don't need to create the forceCompute attribute (the dup'd node will already have it from original).
> EMSUSD-2222: Duplicating a ProxyStage and hiding the dup causes crash

- lib/usdUfe/ufe/StagesSubject.cpp
- test/lib/ufe/testAttribute.py
We currently changed the initial AttributeAdded inside a UFE SetValue into a AttributeValueChanged.
We now do the same for the final ArreibuteRemoved.
> Properly handle deleted attributes

- lib/mayaUsd/ufe/ProxyShapeSceneSegmentHandler.cpp
This prevents a hang we are experiencing when duplicating a ProxyShape. During the duplication process, a path with a ':' prefix is found in 'allStagesPaths' but this does not correspond to a valid scene item. A simple null check prevents the issue
> Check that the stagePath points to a valid Ufe item

- lib/mayaUsd/ufe/Utils.cpp
This update the getProxyShape() util function to avoid rebuilding cache by default.
> EMSUSD-2232 - Avoids rebuilding cache when trying to getProxyShape

- lib/mayaUsd/render/pxrUsdMayaGL/shapeAdapter.cpp
Hydra was applying alpha values to the wireframe representation of meshes, which was causing issues with selection highlighting. A new draw mode was added and adopted in Pixar's batch renderer
> Use new wireframe draw modes

- lib/usd/ui/importDialog/ItemDelegate.cpp
- lib/usd/ui/importDialog/USDImportDialog.cpp
- lib/usd/ui/layerEditor/layerTreeItem.cpp
- lib/usd/ui/layerEditor/layerTreeItemDelegate.cpp
- lib/usd/ui/layerEditor/layerTreeViewStyle.h
The maya_open_source Qt code already has version checks for Qt 6,
but we need to follow the v6 branch when we are building with 5.15
deprecation turned on. Adding this define to the checks as a minimal
way to get this to compile internally with deprecation turned on,
without changing the code in a way that makes it hard to merge
updates from upstream.
> Fixes for building with QT_DISABLE_DEPRECATED_BEFORE

- lib/mayaUsd/fileio/shading/shadingModeExporterContext.cpp
- lib/usd/translators/shading/mtlxMaterialXSurfaceShaderWriter.cpp
- test/lib/usd/translators/CMakeLists.txt
- test/lib/usd/translators/UsdExportMaterialXSurfaceShader/ImageWithoutGeomProp.mtlx
- test/lib/usd/translators/testUsdExportMaterialXSurfaceShader.py
Add geomprop node when exporting MaterialX containing images not connected to a geomprop node.
Surface up the texcoord attribute to the material to allow the _UVMappingManager to connect the proper UV channel.
> EMSUSD-2265 : Mtlx-USD export should add ND_geompropvalue node to the image node during convertion

- lib/usd/translators/shading/mtlxMaterialXSurfaceShaderWriter.cpp
Fix crash : the input might not always be part of a node.
> EMSUSD-2524 : Crash if the file port is promoted to the top level of the graph

- lib/usd/translators/shading/mtlxMaterialXSurfaceShaderWriter.cpp
- test/lib/usd/translators/UsdExportMaterialXSurfaceShader/RelativePath.mtlx
- test/lib/usd/translators/testUsdExportMaterialXSurfaceShader.py
Add relative path support for texture file while exporting MaterialX stack.
> EMSUSD-2295 : Texture paths are not saved as relative when exporting an object with MaterialX Document

- lib/lookdevXUsd/CMakeLists.txt
- lib/lookdevXUsd/LookdevXUsd.cpp
- lib/lookdevXUsd/ProxyShapeLookdevHandler.cpp
- lib/lookdevXUsd/ProxyShapeLookdevHandler.h
- lib/lookdevXUsd/UsdMaterialHandler.cpp
To decouple form USD, LookkdevX wants to move out any remaining USD dependencies. 
This PR moves the `ProxyShapeLookdevHandler` and its associated command `MayaUsdCreateLookdevEnvironmentCommand` to MayaUSD. This was missed when moving LookdevXUsd to MayaUSD: The `ProxyShapeLookdevHandler` is registered against the Maya runtime and, thus, resided in a different folder.
Unfortunately, there are no Python bindings for the `LookdevXUfe::LookdevHandler` yet, so I'm not sure if the test can be moved over right now. I logged another ticket to add bindings and move the test. 
This PR also makes a small change to `LookdevXUfe::UsdMaterialHandler`. See comment below.
> LOOKDEVX-4467 - Move ProxyShapeLookdevHandler to MayaUSD.

- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
* NodeDefHandler was only added in Ufe v4
> EMSUSD-2578: Material prims break AE on Maya 2023 / 2022

- test/lib/ufe/testAttribute.py
The assertion that the doc metadata should exist is no longer valid
> API doc is no longer included schema's "doc" field

- lib/mayaUsd/render/MaterialXGenOgsXml/GlslOcioNodeImpl.h
- lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaTransformVectorNodeGlsl.h
- lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/TexcoordNodeMaya.h
Fixes API broken by removing GlslImplementation class in MaterialX PR 2409
> Updates for MaterialX 1.39.4

- lib/usd/ui/CMakeLists.txt
- tutorials/import-export-plugin-c++/CMakeLists.txt
* Qt targets are ALIAS targets in newer Qt.
> EMSUSD-2663 - MayaUsd: Maya blessing broken after Qt 6.8.3 update

- lib/mayaUsd/ufe/CMakeLists.txt
- lib/mayaUsd/ufe/MayaUsdUndoRenameCommand.cpp
- lib/mayaUsd/ufe/MayaUsdUndoRenameCommand.h
- lib/mayaUsd/ufe/UsdSceneItemOps.cpp
- lib/mayaUsd/ufe/UsdUndoCreateStageWithNewLayerCommand.cpp
- lib/mayaUsd/ufe/UsdUndoDuplicateCommand.cpp
- lib/mayaUsd/ufe/UsdUndoMaterialCommands.cpp
- lib/mayaUsd/ufe/Utils.cpp
- lib/mayaUsd/ufe/Utils.h
- lib/usdUfe/ufe/CMakeLists.txt
- lib/usdUfe/ufe/UsdUndoDeleteCommand.cpp
- lib/usdUfe/ufe/UsdUndoDeleteCommand.h
- lib/usdUfe/ufe/UsdUndoInsertChildCommand.cpp
- lib/usdUfe/ufe/UsdUndoRenameCommand.cpp
- lib/usdUfe/ufe/UsdUndoRenameCommand.h
- lib/usdUfe/ufe/Utils.cpp
- lib/usdUfe/ufe/Utils.h
* Moved these two commands from MayaUsd to UsdUfe.
* Created MayaUsdUndoRenameCommand to overload virtual method for sending Ufe rename notif.
* Moved helper function createSiblingSceneItem().
> EMSUSD-2648/2648 - UsdUfe: move delete and rename commands from MayaUsd

- lib/mayaUsd/render/MaterialXGenOgsXml/CMakeLists.txt
- lib/mayaUsd/render/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
- lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaShaderGraph.cpp
- lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaShaderGraph.h
- test/lib/mayaUsd/utils/test_ShaderGenUtils.cpp
- test/lib/usd/translators/testUsdExportMaterialX.py
The code should stop being active if we are using the version they were backported from.
Targets 2 backports: PR #3968 and PR #3795.
Also fix some unit test failures that could happen with USD 25.08 and MaterialX 1.39.4.
> Bracket code backported from MaterialX 1.39.X

- lib/mayaUsd/render/pxrUsdMayaGL/sceneDelegate.cpp
This obviates the need to explicitly add new cache entries when new Hd Camera attributes are added
> Initialize PxrGL HdCamera attr value cache

- lib/mayaUsd/commands/layerEditorCommand.cpp
Areas that will be affected by setting the `MAYAUSD_LAYEREDITOR_DISABLE_AUTOTARGET` env variable are:
- Mute layer
- Lock layer
- System lock layer
> EMSUSD-2783 - Adds an envionment variable to disable layer auto targeting

- plugin/adsk/plugin/exportTranslator.cpp
- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
* Remove duplicated options from default string.
* Strip float string down to just int part.
> EMSUSD-1221: Unknown warning when selecting USD export option

- lib/lookdevXUsd/UsdSoloingHandler.cpp
- Issue was introduced by prettifying th output of shader node def top classification.
- Fixed forever by removing hardcoded strings and discovering the top classification at init time.
> Fix soloing handler issue
