Autodesk/maya-usd

build.py
=> add missing spaces in build.py help

build.py
Just a convenience to easily see build output on the console
=> add a verbosity arg to build.py

plugin/pxr/maya/plugin/pxrUsdPreviewSurface/CMakeLists.txt
=> [pxr] fix for building with PXR_VALIDATE_GENERATED_CODE

lib/render/vp2RenderDelegate/mesh.cpp
https://github.com/Autodesk/maya-usd/issues/126 ProxyShape plays only once for animated USD mesh
The performance optimization was to avoid repetitive calls into
MPxSubSceneOverride::setGeometryForRenderItem() but unfortunately
it brought regression because the API call has a side effect to
trigger consolidation/instancing update.
=> Fix regression due to avoiding repepetive MPxSubSceneOverride::setGeometryForRenderItem() call

lib/render/vp2RenderDelegate/proxyRenderDelegate.cpp
Fixing https://github.com/Autodesk/maya-usd/issues/105
=> MAYA-102267 selection highlight when multiple proxy shapes are selected

lib/render/vp2RenderDelegate/material.cpp, lib/render/vp2RenderDelegate/material.h, lib/render/vp2RenderDelegate/mesh.cpp, lib/render/vp2RenderDelegate/mesh.h
See https://github.com/Autodesk/maya-usd/pull/91 for the original review.
I only change part of VP2RenderDelegate code (excluding instancer code because it looks to me we need to refactor that class in a larger scale at some point).
=> MAYA-102285 minor code refinement from previous review

plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp, plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.h, plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeUI.cpp
...instead of old display*Guide attrs
=> update to use new draw*Purpose attrs from base class

CMakeLists.txt, build.py, cmake/defaults/CXXDefaults.cmake, cmake/defaults/msvcdefaults.cmake, lib/CMakeLists.txt, plugin/al/CMakeLists.txt, plugin/al/lib/AL_USDMaya/CMakeLists.txt, plugin/al/schemas/AL/usd/schemas/maya/CMakeLists.txt, plugin/al/schemas/AL/usd/schemas/mayatest/CMakeLists.txt, plugin/pxr/cmake/macros/Private.cmake
Merge pull request #196 from Autodesk/donnels/MAYA-102389/python_binding_dont_work_in_debug
=> MAYA-102389 - MayaUsd.ufe python bindings don't work in Maya Debug (Win)

lib/fileio/writeJobContext.cpp, lib/fileio/writeJobContext.h, lib/usd/translators/instancerWriter.cpp, plugin/pxr/maya/plugin/pxrUsdTranslators/CMakeLists.txt, plugin/pxr/maya/plugin/pxrUsdTranslators/testenv/InstancerExportTest/InstancerExportTest.ma, plugin/pxr/maya/plugin/pxrUsdTranslators/testenv/testPxrUsdTranslatorsInstancer.py
Also added tests for instancer / namespaced instancers
=> [pxr] fix for export of namespaced point instancers

lib/fileio/shading/shadingModeExporterContext.cpp, lib/render/pxrUsdMayaGL/batchRenderer.cpp, lib/render/pxrUsdMayaGL/hdRenderer.cpp, lib/render/pxrUsdMayaGL/sceneDelegate.cpp, lib/render/pxrUsdMayaGL/usdProxyShapeAdapter.cpp, lib/render/vp2RenderDelegate/material.cpp, plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeUI.cpp
I made needed to get compilation working for 19.07 for some comparisons I was doing, and AL said they needed 0.19.07 support... so here it is!
=> fixes for usd < 19.11 compilation (dev branch)

lib/fileio/shading/shadingModeExporterContext.cpp, lib/render/mayaToHydra/renderGlobals.cpp, lib/render/mayaToHydra/renderOverride.cpp, lib/render/mayaToHydra/renderOverride.h, lib/render/mayaToHydra/utils.cpp, lib/render/pxrUsdMayaGL/batchRenderer.cpp, lib/render/pxrUsdMayaGL/hdRenderer.cpp, lib/render/pxrUsdMayaGL/sceneDelegate.cpp, lib/render/pxrUsdMayaGL/usdProxyShapeAdapter.cpp, lib/render/vp2RenderDelegate/material.cpp, lib/usd/hdMaya/adapters/materialAdapter.cpp, lib/usd/hdMaya/adapters/materialNetworkConverter.cpp, lib/usd/hdMaya/delegates/delegate.h, lib/usd/schemas/CMakeLists.txt, plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeUI.cpp, plugin/al/schemas/AL/usd/schemas/maya/tests/CMakeLists.txt
I made needed to get compilation working for 19.07 for some comparisons I was doing, and AL said they needed 0.19.07 support... so here it is!
This PR is for support against refactoring_sandbox - it depends on https://github.com/Autodesk/maya-usd/pull/213 and https://github.com/Autodesk/maya-usd/pull/215, which should both be merged first
=> fixes for usd < 19.11 compilation (refactoring_sandbox branch)

test/lib/CMakeLists.txt
This is a follow-up change from feedback on #217.
=> replace path/pythonPath variable handling with separate_argument_list() utils function

build.py
=> [build] missing space meant CMAKE_MACOSX_RPATH wasn't being properly set

lib/fileio/utils/readUtil.cpp
I was reading this code and noticed a "copy-paste-error".
=> Fix copy paste error

doc/build.md, lib/fileio/shaderWriter.cpp, lib/fileio/shaderWriter.h, lib/fileio/shading/shadingModeUseRegistry.cpp, lib/fileio/utils/adaptor.cpp, lib/render/mayaToHydra/CMakeLists.txt, lib/render/mayaToHydra/renderOverride.cpp, lib/render/mayaToHydra/renderOverride.h, lib/render/px_vp20/utils.cpp, lib/render/pxrUsdMayaGL/batchRenderer.cpp, lib/render/pxrUsdMayaGL/batchRenderer.h, lib/render/pxrUsdMayaGL/sceneDelegate.cpp, lib/render/vp2RenderDelegate/proxyRenderDelegate.cpp, lib/ufe/UsdAttribute.cpp, lib/ufe/UsdAttributes.cpp, lib/usd/hdMaya/adapters/constantShadowMatrix.h, lib/usd/translators/fileTextureWriter.cpp, lib/usd/translators/fileTextureWriter.h, plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.cpp, plugin/pxr/maya/plugin/pxrUsdPreviewSurface/usdPreviewSurfaceWriter.cpp, plugin/pxr/maya/plugin/pxrUsdPreviewSurface/usdPreviewSurfaceWriter.h, test/lib/usd/schemas/testMayaUsdSchemasMayaReference.py
In particular, this PR absorbs the following core USD commits:
https://github.com/PixarAnimationStudios/USD/commit/055b8532b86f4e327fdca68536bf686d13b88ff3
https://github.com/PixarAnimationStudios/USD/commit/340759c4ef0f3c1588718acf48809e6f5dc44a57
https://github.com/PixarAnimationStudios/USD/commit/d204a531c93281f8210d53de9482a97c8fd32c50
https://github.com/PixarAnimationStudios/USD/commit/5d30f6e6ad0d12ed403dc55eaa0e75fa04d4cb92
https://github.com/PixarAnimationStudios/USD/commit/daa2d3b2e20211fe986c66f9c3d99102d5bde5f1
https://github.com/PixarAnimationStudios/USD/commit/3b0c7c90f9779f955e9751c21873b637f660cd5f
https://github.com/PixarAnimationStudios/USD/commit/287e977efd199f0c7e8f8eadd2396d85d0f27507
https://github.com/PixarAnimationStudios/USD/commit/0a8a2587db9592372ccb39deccec93f29c …
=> apply updates based on recent core USD dev branch commits

lib/fileio/translators/translatorMayaReference.cpp
Separate PR to address following suggestions from #255 
https://github.com/Autodesk/maya-usd/pull/255#discussion_r378591553
https://github.com/Autodesk/maya-usd/pull/255#discussion_r378591806
https://github.com/Autodesk/maya-usd/pull/255#discussion_r378592716
This PR doesn't address following suggestion, explanation will be added in comments
https://github.com/Autodesk/maya-usd/pull/255#discussion_r378589393
=> Improve performance based on suggestions in PR255

cmake/jinja.cmake
=> MAYA-103731 - OAST: Jinja 2.10 WS report of CVE-2019-10906

lib/usd/translators/meshReader.cpp
When using PXRUSDMAYA_DEFINE_READER Macro it is a bit hard to follow the code logic and debug.
=> Replace PXRUSDMAYA_DEFINE_READER macro with class declaration/definition to make the code easier to read and debug.

lib/ufe/UsdHierarchy.cpp
See description of issue: https://github.com/Autodesk/maya-usd/issues/166
In usdview, the retrieval of children is always done with TraverseInstanceProxies enabled in appController.py, which has this comment:
Unless user experience indicates otherwise, we think we always want to show instance proxies
Add support for the same behavior in UsdHierarchy's children and getChildren.
=> MAYA-103370 - Traverse instance proxies

lib/usd/utils/CMakeLists.txt, test/lib/usd/utils/CMakeLists.txt
This PR is also another good example to show how target build/use requirement works.
=> Adopt to the new way of adding unit test.

plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/AnimationTranslator.cpp, plugin/al/mayatest/AL/maya/test/testHelpers.cpp, plugin/al/mayatest/AL/maya/test/testHelpers.h, plugin/al/plugin/AL_USDMayaTestPlugin/test_translators_CameraTranslator.cpp, plugin/al/translators/Camera.cpp, plugin/al/usdmayautils/AL/usdmaya/utils/AnimationTranslator.h, plugin/al/usdmayautils/AL/usdmaya/utils/DgNodeHelper.cpp, plugin/al/usdmayautils/AL/usdmaya/utils/DgNodeHelper.h
Added import and export support for animated near and far clipping planes.
=> [AL] Added support of animated near/far clipping planes

lib/ae/base/ae_template.py
* Display the transform attributes in xformOpOrder. Put any unused ones in new section.
=> MAYA-104008 - UFE AE : Transform Attributes in Several Sections

lib/mayaUsd/ufe/CMakeLists.txt, lib/mayaUsd/ufe/UsdHierarchy.cpp
Hi @ppt-adsk, I noticed accidentally some of the ufe header files are not promoted correctly according to the UFE version. 
Looking back in history I noticed this originated from one of my PRs. Je suis de soleil.
=> fix some of the ufe headers promoted incorrectly.

CMakeLists.txt, cmake/utils.cmake, lib/mayaUsd/CMakeLists.txt
- remove redundant call to add_dependencies
- fix a typo in the comment
=> minor cmake clean up

doc/build.md, lib/usd/hdMaya/adapters/proxyAdapter.h, lib/usd/hdMaya/delegates/sceneDelegate.cpp, lib/usd/hdMaya/delegates/sceneDelegate.h
This change corresponds to core USD commit
https://github.com/PixarAnimationStudios/USD/commit/ab424bc7528806164f758efd649faf5614deae5c
(Internal change: 2067892)
=> add instancerContext param for HdSceneDelegate::GetScenePrimPath()

plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/test_DiffPrimVar.cpp, plugin/al/plugin/AL_USDMayaTestPlugin/test_translators_NurbsCurveTranslator.cpp, plugin/al/translators/CommonTranslatorOptions.cpp, plugin/al/translators/CommonTranslatorOptions.h, plugin/al/translators/Mesh.cpp, plugin/al/translators/NurbsCurve.cpp, plugin/al/translators/tests/testMeshVariants.usda, plugin/al/translators/tests/testTranslators.py, plugin/al/usdmayautils/AL/usdmaya/utils/DiffPrimVar.cpp, plugin/al/usdmayautils/AL/usdmaya/utils/DiffPrimVar.h, plugin/al/usdmayautils/AL/usdmaya/utils/MeshUtils.cpp, plugin/al/usdmayautils/AL/usdmaya/utils/MeshUtils.h, plugin/al/usdmayautils/AL/usdmaya/utils/NurbsCurveUtils.cpp, plugin/al/usdmayautils/AL/usdmaya/utils/NurbsCurveUtils.h
Adding option to export extents when exporting mesh from Maya. This is enabled by default.
=> [al] Support option to write point based extents

plugin/adsk/plugin/plugin.cpp, plugin/adsk/scripts/CMakeLists.txt, plugin/adsk/scripts/mayaUsd_pluginBatchLoad.mel, plugin/adsk/scripts/mayaUsd_pluginBatchUnload.mel, plugin/adsk/scripts/mayaUsd_pluginUICreation.mel, plugin/adsk/scripts/mayaUsd_pluginUIDeletion.mel
Moving existing menu create/delete calls there and adding auto-load of the ufeSupport plugin.
=> MAYA-104964 Registering loaded/unloaded callbacks with the plugin.

lib/mayaUsd/fileio/utils/meshWriteUtils.cpp, lib/mayaUsd/fileio/utils/meshWriteUtils.h, lib/mayaUsd/utils/util.cpp, lib/mayaUsd/utils/util.h, lib/usd/translators/meshWriter.cpp, lib/usd/translators/meshWriter.h, lib/usd/translators/meshWriter_Primvars.cpp
- Create utility functions for writing out UVSets as Vec2f Primvars.
=> PART VI: Pixar Mesh write translator/utilities refactoring 

.github/workflows/maya-usd-preflight-launcher.yml
=> MAYA-104481 github actions launcher for branch preflight

lib/mayaUsd/render/mayaToHydra/renderGlobals.cpp, lib/mayaUsd/render/mayaToHydra/renderGlobals.h, lib/mayaUsd/render/mayaToHydra/utils.cpp
#481 left some settings in 20.05+, that no longer do anything.
=> [mtoh] Remove setting for SetColorQuantizationEnabled still hanging out after 44a03601.

lib/usd/hdMaya/CMakeLists.txt
-DWANT_UFE_BUILD isn't making it into the _mtoh_ build process.
=> [mtoh] Push WANT_UFE_BUILD definition into target_compile_definitions.

lib/mayaUsd/render/mayaToHydra/renderOverride.cpp
These parameters never make it to anyone but Storm, as a ShadowTask is only created when it is the renderer.
=> [mtoh] Move some Storm only task/params into the Storm block.

plugin/adsk/plugin/importTranslator.cpp
Removing unused map in UsdMayaImportTranslator::reader
=> Remove unused map

lib/mayaUsd/commands/layerEditorCommand.cpp, test/lib/testMayaUsdLayerEditorCommands.py
Didn't properly hold on to anon layer to be able to re-create them on redo() with the same layer identifier they were using, causing other commands down the roads to not find them
=> MAYA-106232 Crash with undo redo in USD Layer Editor

lib/mayaUsd/fileio/shading/shadingModeExporterContext.cpp, test/lib/usd/translators/CMakeLists.txt, test/lib/usd/translators/UsdExportGeomSubsetTest/UsdExportGeomSubsetTest.ma, test/lib/usd/translators/testUsdExportGeomSubset.py
If you connect one set of faces to a material, then later connect a second set of faces to the same material, there will be two separate sets in Maya. When exporting to USD we need to merge the faces into a single GeomSubset.
=> MAYA-106690 - Merge subsets connected to same material

lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp, lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
Prepare CPV buffer if either primvars:displayColor or primvars:displayOpacity is requested by USD material (through primvar readers).
=> MAYA-107785 Prepare CPV buffer if requested by USD material.

.clang-format
Address comments from https://github.com/Autodesk/maya-usd/pull/886#pullrequestreview-523664753
=> Include all mayaUsd targets in maya-usd repository category

.git-blame-ignore-revs
Suggestion from https://github.com/Autodesk/maya-usd/pull/890#issuecomment-722347918
=> Add blame ignore file with clang-format commit sha

lib/mayaUsd/ufe/Global.cpp
UFE has a minor API breaking change, this PR calls register_ in the new way.
=> Make the call to register_ using the new handlers struct.

lib/mayaUsd/ufe/Global.cpp
My original pull request #939 was slightly out of sync with the changes that were merged into UFE. Fix the variable names.
=> Fix variable names that got changed in UFE but not in MayaUSD.

lib/mayaUsd/render/vp2RenderDelegate/material.cpp
PR #950 caused a regression because _surfaceShaderId was skipped for
assignment when it could reuse a shader from the cache.
=> MAYA-108261 Fixed regression caused by PR950

lib/mayaUsd/ufe/UsdTransform3dHandler.cpp, lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
Minor error message string change.
=> MAYA-108545: update error message string.

lib/mayaUsd/ufe/UsdObject3d.cpp
Use UsdGeomImageable's GetVisibilityAttr, MakeVisible, MakeInvisible API directly.
=> Clean up Visibility Logics

lib/mayaUsd/utils/util.cpp
Thanks to @mattyjams for catching this typo with this specific frame rate. All the other drop frames look fine.
Apologies for that typo.
=> Fix 59.95FPS double conversion

test/lib/testMayaUsdCreateStageCommands.py, test/lib/testMayaUsdProxyAccessor.py, test/lib/ufe/testDuplicateCmd.py, test/lib/ufe/testGroupCmd.py, test/lib/ufe/testParentCmd.py, test/testUtils/mayaUtils.py, test/testUtils/testUtils.py, test/testUtils/ufeUtils.py, test/testUtils/usdUtils.py
Cleanup the test utils by ensuring proper separation between Maya, Ufe, Usd and general purpose.
=> Cleanup test utils

cmake/modules/FindUFE.cmake
Temporary setting of UFE_PREVIEW_VERSION_NUM while we transition to UFE v2.0.0.
=> UFE v2 transition

lib/mayaUsd/ufe/CMakeLists.txt, lib/mayaUsd/ufe/UsdTransform3dFallbackMayaXformStack.cpp, lib/mayaUsd/ufe/UsdTransform3dMatrixOp.cpp, lib/mayaUsd/ufe/XformOpUtils.cpp, lib/mayaUsd/ufe/XformOpUtils.h
Code originally written by Pierre Tremblay to refactor common code related to retrieving local transforms.
I slightly modified it since some code paths used prim + op, others already had the ops vector and iterator.
=> MAYA-108709 preliminary code refactor

plugin/adsk/scripts/mayaUsd_createStageFromFile.mel, plugin/adsk/scripts/mayaUsd_createStageWithNewLayer.py, test/lib/CMakeLists.txt, test/lib/mayaUsd/nodes/testProxyShapeBase.py, test/lib/testMayaUsdCreateStageCommands.py, test/lib/testMayaUsdDirtyScene.py, test/lib/testMayaUsdLayerEditorCommands.py, test/lib/ufe/testAttribute.py, test/lib/ufe/testComboCmd.py, test/lib/ufe/testContextOps.py, test/lib/ufe/testObject3d.py, test/lib/ufe/testPythonWrappers.py, test/lib/ufe/testSelection.py, test/lib/ufe/testTransform3dChainOfResponsibility.py
* New regression test for checking scene dirty.
=> MAYA-106780 - Editing USD should mark scene as dirty

lib/usd/ui/layerEditor/saveLayersDialog.cpp, lib/usd/ui/layerEditor/warningDialogs.cpp, lib/usd/ui/layerEditor/warningDialogs.h
Add warning icon in USD Save Overwrite section
=> MAYA-109969 - No warning icon in USD Save Overwrite section.

plugin/adsk/plugin/CMakeLists.txt, plugin/adsk/plugin/adskStageLoadUnloadCommands.cpp, plugin/adsk/plugin/adskStageLoadUnloadCommands.h, plugin/adsk/plugin/plugin.cpp, plugin/adsk/scripts/AETemplateHelpers.py, plugin/adsk/scripts/AEmayaUsdProxyShapeBaseTemplate.mel
MAYA-107380 - On the stage AE template I'd like to load and unload all payloads
* Reworked solution to avoid using UFE v2 and ufeSupport plugin as neither of these are present in Maya 2020. Created simple stage load/unload Maya commands.
=> MAYA-107380 - On the stage AE template I'd like to load/unload all payloads

cmake/modules/FindUFE.cmake, lib/mayaUsd/ufe/CMakeLists.txt, lib/mayaUsd/ufe/Global.cpp, lib/mayaUsd/ufe/StagesSubject.cpp, lib/mayaUsd/ufe/UsdContextOps.cpp, lib/mayaUsd/ufe/UsdObject3d.cpp, lib/mayaUsd/ufe/UsdObject3d.h, lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp, test/lib/mayaUsd/nodes/testProxyShapeBase.py, test/lib/ufe/testAttribute.py, test/lib/ufe/testComboCmd.py, test/lib/ufe/testDuplicateCmd.py, test/lib/ufe/testGroupCmd.py, test/lib/ufe/testMayaPickwalk.py, test/lib/ufe/testObject3d.py, test/lib/ufe/testParentCmd.py, test/lib/ufe/testRotatePivot.py, test/lib/ufe/testSelection.py, test/testUtils/mayaUtils.py
Remove/replace all UFE_PREVIEW_VERSION_NUM now that latest MayaPR has UFE v2.
=> Remove/replace all UFE_PREVIEW_VERSION_NUM

plugin/adsk/scripts/AEmayaUsdProxyShapeBaseTemplate.mel
=> MAYA-110566 - No tooltip for Prim Path in Attribute Editor

doc/build.md
Updating build.md with Maya 2022 and dropping Maya 2018.
=> Updating build.md with Maya 2022

lib/mayaUsd/ufe/XformOpUtils.cpp
* Fixing linux compilation error when building with USD v20.02.
=> MAYA-110361 - add PF jobs to cover what's currently tested manually

README.md
Adding a link to the Maya 2022 "Getting Started" Documentation for USD in Maya.
=> Added getting started docs link to Detailed Documentation section

test/lib/ufe/testSelection.py, test/testUtils/mayaUtils.py
- Add python test (The fix is in maya).
=> MAYA-110517 - Crash on redo of creation and manipulation of prim

lib/mayaUsd/ufe/Global.cpp, plugin/adsk/plugin/plugin.cpp
This fixes
https://github.com/Autodesk/maya-usd/issues/1399
The Transform3d chain of responsibility is now set up in the maya-usd core library, in UFE initialization.  In this way, when loading more than one plugin, it is predictable which Transform3d handler is obtained.
=> Move Transform3d handler creation into core.

lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
* New connections custom control for prims that have connections. Display attribute in similar manner as
Maya connected attribute (yellow background) with popup menu to follow connection.
* Modified the size of the array custom control to be same width as connected attribute control.
=> MAYA-104623 - As a user, I'd like to see connected attributes

lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
* Make sure to skip the suppressed attributes.
=> MAYA-111523 - Empty categories appear

lib/mayaUsd/fileio/jobs/readJob.cpp, plugin/adsk/scripts/mayaUsdTranslatorImport.mel
=> MAYA-111330 - USDZ Texture import Option should have a capital "I" on import

lib/mayaUsd/ufe/UsdUndoInsertChildCommand.cpp, test/lib/ufe/testParentCmd.py
**UFE Parent**
VS
**Maya Parent**
=> MAYA-112126: make sure parented object is added to selection list after it is moved.

.github/workflows/maya-usd-new-issues.yml
MAYA-112357 - USD Pipeline : investigate automatic insertion of new issues GitHub issues to a project
=> add action to move new triage

lib/mayaUsd/render/vp2RenderDelegate/material.cpp
The UsdUVTexture node has an attribute for source color space with values of raw/sRGB/auto which allows sending the information thru Hydra (since the metadata on the file attribute gets filtered).
When this attribute is set in a Hydra material network and the value is not "auto", we must explicitly set the isColorSpaceSRGB shader value with the information provided.
=> MAYA-112335 - Handle source color space in Vp2 render delegate

lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
* Original change integrated back to Maya 2022 update.
=> MAYA-111478 - [I] I'd like to see categories persist their expand/collapse state

plugin/adsk/scripts/mayaUsd_createStageFromFile.mel
* [GitHub] #1379
* Simple fix to remove the capitalization.
=> MAYA-112226 - Stage to be created without the proxyShape being capitalized

cmake/modules/FindMaya.cmake, lib/mayaUsd/CMakeLists.txt, lib/mayaUsd/render/vp2RenderDelegate/basisCurves.h, lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.h, lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp, lib/mayaUsd/render/vp2RenderDelegate/mesh.h, lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp, lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
be snapping to active objects.
=> MAYA-111686 Add kSelectPointsForGravity to all selected render items when we should

CMakeLists.txt, doc/build.md, lib/mayaUsd/fileio/utils/adaptor.cpp, lib/mayaUsd/fileio/utils/adaptor.h, lib/mayaUsd/nodes/proxyShapeBase.cpp, lib/mayaUsd/render/mayaToHydra/renderOverride.cpp, lib/mayaUsd/render/mayaToHydra/renderOverride.h, lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.cpp, lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.h, lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp, lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp, lib/mayaUsd/render/vp2RenderDelegate/meshViewportCompute.h, lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp, lib/mayaUsd/ufe/UsdAttribute.cpp, lib/mayaUsd/ufe/UsdAttributes.cpp
* Change min USD version to 20.05 (in CMakeLists.txt)
* Remove 20.02 from build.md
* Remove #if PXR_VERSION "2002" checks in code
=> MAYA-112336 - MayaUSD: bump USD min version to 20.05

plugin/adsk/scripts/mayaUsdMenu.mel
Disable Revert File for Readonly Files
=> MAYA-112793 - Disable Revert File for Readonly Files

plugin/al/mayautils/AL/maya/utils/MenuBuilder.cpp
=> Make USD menu tear-off-able.

lib/usd/hdMaya/delegates/sceneDelegate.cpp, lib/usd/hdMaya/delegates/sceneDelegate.h
This is in preparation for HdSceneIndex-based hydra emulation
This is for Pixar Jira HYD-2409
=> Implement HdMayaSceneDelegate::GetInstancerPrototypes

plugin/al/mayautils/AL/maya/utils/MenuBuilder.cpp
=> Clang format fix.

cmake/test.cmake, lib/mayaUsd/render/mayaToHydra/renderOverride.cpp, plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorContext.cpp, plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeSelection.cpp, plugin/pxr/maya/lib/usdMaya/CMakeLists.txt, test/lib/mayaUsd/render/pxrUsdMayaGL/CMakeLists.txt
Adding missing environment variable necessary for Debug builds
Fix asserts that were breaking the tests
=> MAYA-112867 MayaUSD : Fix unit tests to run in Debug builds

lib/mayaUsd/fileio/primWriter.cpp, lib/mayaUsd/fileio/primWriter.h, lib/mayaUsd/fileio/registryHelper.cpp, lib/mayaUsd/fileio/registryHelper.h, lib/mayaUsd/python/CMakeLists.txt, lib/mayaUsd/python/module.cpp, lib/mayaUsd/python/wrapExportChaser.cpp, lib/mayaUsd/python/wrapImportChaser.cpp, lib/mayaUsd/python/wrapOpenMaya.cpp, lib/mayaUsd/python/wrapPrimReader.cpp, lib/mayaUsd/python/wrapPrimWriter.cpp, test/lib/mayaUsd/fileio/CMakeLists.txt, test/lib/mayaUsd/fileio/testExportChaser.py, test/lib/mayaUsd/fileio/testImportChaser.py, test/lib/mayaUsd/fileio/testPrimReader.py, test/lib/mayaUsd/fileio/testPrimReader.usda, test/lib/mayaUsd/fileio/testPrimWriter.py, test/lib/mayaUsd/fileio/testShaderReader.py, test/lib/mayaUsd/fileio/testShaderWriter.py
Prim Reader and Writer python bindings + Sphere test
Skeleton python binding for Shader and Chaser + test
=> MAYA-113309 MayaUSD : Python bindings for prim translators

lib/mayaUsd/ufe/UsdStageMap.cpp, lib/mayaUsd/ufe/Utils.cpp
=> Verify that the DAG path of the returned proxy shape object matches

plugin/pxr/maya/lib/usdMaya/readJob_ImportWithProxies.cpp
All code should be using the UsdGeomPointInstancer schema instead
=> Removing references to the deprecated PxPointInstancer

lib/mayaUsd/commands/baseExportCommand.cpp, lib/mayaUsd/fileio/jobs/jobArgs.cpp, lib/mayaUsd/fileio/jobs/jobArgs.h, lib/mayaUsd/fileio/writeJobContext.cpp, plugin/adsk/plugin/exportTranslator.cpp, plugin/pxr/maya/lib/usdMaya/exportTranslator.cpp
It was one of the very remaining few non-const member.
=> Made filteredTypeIds const in export job arguments

test/lib/mayaUsd/fileio/testExportChaser.py, test/lib/mayaUsd/fileio/testPrimWriter.py
Validate that ExportChaser is working with a unittest.
=> MAYA-113464 MayaUSD : Python bindings for chasers

plugin/al/lib/AL_USDMaya/AL/usdmaya/Global.cpp, plugin/al/lib/AL_USDMaya/AL/usdmaya/cmds/ProxyShapePostLoadProcess.cpp, plugin/al/lib/AL_USDMaya/AL/usdmaya/cmds/ProxyShapePostLoadProcess.h, plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorBase.cpp, plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorBase.h, plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
This PR is related to loading nested proxyShape https://github.com/Autodesk/maya-usd/pull/1727 that the Python translator context can be maintained in nested proxyShape.
=> Fix translator context on nested proxy shapes

test/lib/usd/translators/testUsdExportUVSets.py
Fix the test to not expect hard-coded UV set sizes.
=> Fix UV export test

test/lib/ufe/testAttribute.py
* Added tests for new Ufe support of attributes using Maya getAttr command.
=> MAYA-114281 - Query a USD attributes locked state via getAttr

lib/mayaUsd/fileio/jobs/readJob.cpp
Fix node not being registered.
=> MAYA-120761 edit instance not found

lib/mayaUsd/render/vp2RenderDelegate/material.cpp
type from float3 to float4, causing the Maya shader to not compile.
=> MAYA-120864 Changing the primvar reader to a color reader can change the output

lib/mayaUsd/fileio/primUpdaterManager.cpp, test/lib/mayaUsd/fileio/testMergeToUsd.py
When targeting the session layer and a non-root prim, the hierarchy above the prim no longer existing by the time the data was being merged. Move the removal of the pull info to after the merge so that the hierarchy still exists in the session layer during the merge.
Add a unit test that filed without this fix.
=> MAYA-114109 fix merge-to-USD

lib/mayaUsd/ufe/StagesSubject.cpp
* Use the Usd notice flags to send proper Ufe notif.
=> MAYA-115171 - [GitHub #1808] Outliner not updating with new prim defined in python

lib/mayaUsd/fileio/primUpdaterManager.cpp
- The addition of the item to the pull set was not undone / redone.
- The import already has its own undo /redo but we were also using a UsdUndoBlock, which meant USD modifiaction were undone / redone twice.
=> MAYA-121074 fix assertion during edit-as-maya undo / redo

lib/mayaUsd/python/CMakeLists.txt, lib/mayaUsd/python/module.cpp, lib/mayaUsd/python/wrapPrimWriter.cpp, lib/mayaUsd/python/wrapUtil.cpp, test/lib/usd/translators/UsdExportMaterialXTest/MaterialX_decal.ma, test/lib/usd/translators/testUsdExportMaterialX.py
Fix issue accessing protected members, add missing APIs, make it export
something interesting.
=> MAYA-113462 - Revisit Python shader export unit test

lib/mayaUsd/utils/editRouter.cpp, lib/usd/utils/MergePrimsOptions.h
This fixes Pixar internal builds
=> Prefer to use the PXR namespace "using" directive

lib/mayaUsd/utils/plugRegistryHelper.cpp
=> Switch from runtime error to a warning

lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.mel, plugin/adsk/scripts/mayaUSDRegisterStrings.mel, plugin/adsk/scripts/mayaUsdMenu.mel
As requested in https://github.com/Autodesk/maya-usd/pull/2023
=> Register string resources

lib/mayaUsd/ufe/UsdUndoInsertChildCommand.cpp, lib/mayaUsd/ufe/UsdUndoInsertChildCommand.h, test/lib/ufe/testGroupCmd.py
Delays checking for name unicity until execution starts.
Adds unit test for the issue.
=> Fix group command not finding unique names

lib/mayaUsd/commands/PullPushCommands.cpp, lib/mayaUsd/fileio/jobs/jobArgs.cpp, lib/mayaUsd/fileio/jobs/jobArgs.h, plugin/adsk/plugin/exportTranslator.cpp, plugin/adsk/scripts/mayaUSDRegisterStrings.mel, plugin/adsk/scripts/mayaUsdMenu.mel, plugin/adsk/scripts/mayaUsdTranslatorExport.mel, plugin/pxr/maya/lib/usdMaya/exportTranslator.cpp, test/lib/mayaUsd/fileio/testDuplicateAs.py, test/lib/mayaUsd/fileio/testMergeToUsd.py
- Reworked the mayaUsdTranslatorExport function to support specifying the desired section names.
- Can include: specific section name to add it, "all", "none" or the section name prefixed with "!" to remove that section.
- Had to handle the UI updates too.
- Add unit test for export options.
=> T bailp/maya 114898/merge to usd export options

lib/mayaUsd/render/vp2RenderDelegate/extComputation.cpp
This fixes internal Pixar builds
=> Remove explicit use of pxr namespace

lib/mayaUsd/ufe/UsdContextOps.cpp, plugin/adsk/scripts/USDMenuProc.mel
* Removed temp env var hiding the EditAsMaya feature.
=> MAYA-121099: Env vars for push/pull and mayaRef features

lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
This reverts commit f814ca75764c8be1c5403bde541a941a485dda3c.
=> Revert "Skip updating MRenderItem's that we're not going to draw anyway."

lib/mayaUsd/render/vp2RenderDelegate/material.cpp
And extra parameter was added to HdMtlxCreateMtlxDocumentFromHdNetwork
=> USD 22.03 integration: API change for MaterialX

cmake/modules/FindMaya.cmake, lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
viewport to prevent thrashing display styles when multiple viewports are displayed.
=> MAYA-120659 Get the display style of all viewports rather than just the current

plugin/al/plugin/AL_USDMayaTestPlugin/py/testTranslators.py
Minor fix for unit test script to match the C++ flag.
=> [al] Fixed incorrect export flag for translator in test plugin

lib/mayaUsd/resources/scripts/mayaUsdMergeToUSDOptions.py
- Use the showHelp command.
- Use the content-ID UsdMergeMayaEditsToUsd
- Hide the menu if the content is not available.
=> MAYA-121886 Merge-to USD options help

plugin/adsk/scripts/mayaUsdMenu.mel
The callback that created the menus were not removed.
=> MAYA-121258 remove plugin menus

plugin/adsk/scripts/mayaUsdMenu.mel
Add the layer editor menu item to the context menu of edited-as-Maya objects.
=> MAYA-114716 add layer editor menu item

plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.cpp, plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_Transform.cpp, plugin/al/plugin/AL_USDMayaTestPlugin/test_data/animated_camera.usda
Fixed an uninitialized variable that caused NaN after decomposing the matrix.
The default or initial values for matrix should be an "identical" matrix instead of all "zero".
=> [al] Fixed uninitialized variable that caused NaN xform values after importing

plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
This PR added another validation on the transform node via lookup uuid, otherwise accessing non-exist node would cause Maya to crash during serialization.
=> [al] Add validation on custom transform node before accessing

.gitignore, cmake/compiler_config.cmake, cmake/googletest_download.txt.in, cmake/googletest_src.txt.in
* For VisualStudio make some warnings (unused variable) as errors.
* Don't need gmock.
* Added vscode files to ignore.
=> Build Updates:

test/lib/mayaUsd/render/mayaToHydra/testMtohVisibility.py, test/testUtils/imageUtils.py
for testMtohVisibility.py which for some reason needs an explicit call.
=> Set the default light intensity the new way. Also force it to be set 

lib/mayaUsd/render/MaterialXGenOgsXml/CMakeLists.txt, lib/mayaUsd/render/MaterialXGenOgsXml/GlslFragmentGenerator.cpp, lib/mayaUsd/render/MaterialXGenOgsXml/OgsFragment.cpp, lib/mayaUsd/render/MaterialXGenOgsXml/libraries/1.38.3/mx_lighting_maya_none.glsl, lib/mayaUsd/render/MaterialXGenOgsXml/libraries/1.38.3/mx_lighting_maya_v1.glsl, lib/mayaUsd/render/MaterialXGenOgsXml/libraries/1.38.3/mx_lighting_maya_v2.glsl, lib/mayaUsd/render/MaterialXGenOgsXml/libraries/1.38.3/mx_lighting_maya_v3.glsl, lib/mayaUsd/render/MaterialXGenOgsXml/libraries/1.38.3/mx_srgb_texture_to_aces_2065_1_color3.glsl, lib/mayaUsd/render/MaterialXGenOgsXml/libraries/1.38.3/mx_srgb_texture_to_aces_2065_1_color4.glsl, lib/mayaUsd/render/MaterialXGenOgsXml/libraries/1.38.3/mx_srgb_texture_to_acescg_color3.glsl, lib/mayaUsd/render/MaterialXGenOgsXml/libraries/1.38.3/mx_srgb_texture_to_acescg_color4.glsl, lib/mayaUsd/render/MaterialXGenOgsXml/libraries/1.38.3/mx_srgb_texture_to_lin_dci_p3_d65_color3.glsl, lib/mayaUsd/render/MaterialXGenOgsXml/libraries/1.38.3/mx_srgb_texture_to_lin_dci_p3_d65_color4.glsl, lib/mayaUsd/render/MaterialXGenOgsXml/libraries/1.38.3/mx_srgb_texture_to_linrec2020_color3.glsl, lib/mayaUsd/render/MaterialXGenOgsXml/libraries/1.38.3/mx_srgb_texture_to_linrec2020_color4.glsl, lib/mayaUsd/render/MaterialXGenOgsXml/libraries/1.38.3/usd_utilities_genglsl_impl.mtlx, lib/mayaUsd/render/MaterialXGenOgsXml/libraries/mx_lighting_maya_none.glsl, lib/mayaUsd/render/MaterialXGenOgsXml/libraries/mx_lighting_maya_v1.glsl, lib/mayaUsd/render/MaterialXGenOgsXml/libraries/usd_utilities_genglsl_impl.mtlx, lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp, lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp, lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.h, lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp, lib/mayaUsd/render/vp2RenderDelegate/points.cpp
Tested against an updated tip of USD dev. Follow Pixar's Github for the latest USD patch to MaterialX 1.38.4.
=> Update to MaterialX 1.38.4

plugin/adsk/scripts/USDMenuProc.mel
A way to easily inject menu items by the user, in line with this suggestion : https://github.com/Autodesk/maya-usd/issues/1773
=> MAYA-114501 added a user proc in USDMenuProc

cmake/modules/FindMaya.cmake, lib/mayaUsd/CMakeLists.txt, lib/mayaUsd/fileio/shading/shadingModeExporter.cpp, lib/mayaUsd/fileio/shading/shadingModeExporterContext.cpp
It correctly finds all the materials.
=> MAYA-122693 Use getMemberPaths for material export when it is available.

lib/mayaUsd/render/mayaToHydra/renderGlobals.cpp
Hi!
In our custom RenderSettings schema we have "asset" type for several fields.
We would like to add support to renderGlobals functionality to be able to get corresponding UI for these fields
=> Add SdfAssetPath support to renderGlobals

lib/mayaUsd/ufe/UsdContextOps.cpp
* Remove the env var hiding the menu item.
=> MAYA-122048: Turn on MayaRef for users

plugin/adsk/scripts/mayaUsdMenu.mel
* Make sure to set parent menu after creating submenu in callback.
=> MAYA-124088: USD breaks callback registration for addRMBBakingMenuItems

test/lib/ufe/testDisplayLayer.py
MAYA-124360 - Display Layers: changing a prim's metadata removes it from their current display layer
* Added unit test for testing fix in Maya.
=> MAYA-124360 - Display Layers: changing a prim's metadata removes it from display layer

lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp, lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp, lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.h, lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp, lib/mayaUsd/render/vp2RenderDelegate/points.cpp
- Set HideOnPlayback flag to all new render items
- Minor refactoring
=> MAYA-124578 - Hide on playback option doesn't work on re-open

test/lib/ufe/testComboCmd.py
Test for
https://git.autodesk.com/maya3d/maya/pull/22886
=> Add test for xform -cpc support.

test/lib/usd/translators/testUsdExportRfMLight.py, test/lib/usd/translators/testUsdImportRfMLight.py
Add a test for when Usd properties are suppressed
Test now run in separate test cases
Improved error messaging
=> RfM Translator Test Improvements

lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp, lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp, lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.h, lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp, lib/mayaUsd/render/vp2RenderDelegate/points.cpp, lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp, lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
Support for 'reference' attribute of display layers
=> MAYA-123160 - As a user, I'd like my prims to be referenced in a Display Layer

test/lib/ufe/testGroupCmd.py
Maya code being tested is here:
https://git.autodesk.com/maya3d/maya/pull/22712
=> Added test for group pivot options Maya fix.

lib/mayaUsd/utils/editRouter.cpp
This fixes internal Pixar build
=> Use the PXR namespace directive

lib/mayaUsd/render/vp2RenderDelegate/material.cpp
Some Hydra API has changed recently. Updating callsites and version
guarding.
=> Update callsite to use new Hydra API

lib/mayaUsd/resources/ae/usdschemabase/ae_template.py, lib/mayaUsd/ufe/UsdConnectionHandler.cpp, test/lib/ufe/testConnections.py
- Cleanup empty connection array when last connection is undone
- Cleanup transient attributes that no longer have any value in the USD
scene.
- Add notification handler to refresh AE when disconnecting ports
=> Disconnection code improvements

lib/mayaUsd/ufe/UsdAttributes.cpp, test/lib/ufe/testConnections.py
- Add unit test covering these specific issues.
=> Fix issues deleting attributes on NodeGraphs

lib/usd/utils/util.cpp, test/lib/ufe/testRename.py
When renaming a prim, all relationship targets and connection sources
that refer to that prim or any of its children must be updated with the
new name.
=> Update rels and cnx on prim rename

lib/mayaUsd/python/wrapExportChaser.cpp, test/lib/usd/translators/testUsdImportExportSiteSpecificConfig.py
Also access it in a python unit test.
=> MAYA-125142 add the python support for DagToUsdMap

lib/mayaUsd/ufe/UsdUndoRenameCommand.cpp, test/lib/ufe/testRename.py
- Transform the trailing # into a unique number.
- Add a unit test for it.
=> MAYA-124973 handle trailing # in rename

lib/mayaUsd/utils/utilDictionary.cpp, lib/mayaUsd/utils/utilDictionary.h
This fixes internal builds at Pixar
=> Use Pixar's namespace directive macro

test/lib/ufe/testParentCmd.py
Maya fixes were commited becore the fix that the test was expected. The fix level thus needs to be updated to one higher.
=> MAYA-121636 fix fixlevel check of parent test

plugin/adsk/scripts/mayaUSDRegisterStrings.mel, plugin/adsk/scripts/mayaUsdTranslatorExport.mel, test/lib/CMakeLists.txt, test/lib/testMayaUsdInteractiveMaterialsScopeName.py
of environment variable MAYAUSD_MATERIALS_SCOPE_NAME to override this default.
=> LOOKDEVX-761 | Defaults materials scope name to mtl and allows setting

lib/mayaUsd/render/vp2RenderDelegate/draw_item.cpp
In #1339 code was added to share the selection render item between reprs. The code did not track usage, so as soon as one of the reprs is removed, the render item was removed from the subscene as well, leaving dangling pointers in the remaining reprs.
In #1597 code was added that seem to indicate there was suspicion about render item issues, but sharing was not identified as the cause.
This PR adds use count tracking to the render item so they only get removed from the subscene once all reprs have stopped using the shared render item.
=> Properly track usage of shared render items

lib/mayaUsd/fileio/doc/Managing_export_options_via_JobContext_in_Python.md, plugin/adsk/scripts/mayaUsdTranslatorExport.mel
Only disable the Ui if there is actually a forced option for filter types.
=> MAYA-125816 fix nurbs curves UI when using export job context

lib/mayaUsd/fileio/jobs/readJob.cpp
- If the prim name, variant name or variant selection is invalid, issue an error.
- The import still proceeds.
=> MAYA-126367 issue error message for invalid variant selection

lib/mayaUsd/commands/Readme.md
Add documentation about the material scope env. var.
=> MAYA-126158 update documentation of the export command

lib/mayaUsd/ufe/wrapUtils.cpp, test/lib/ufe/testPythonWrappers.py, test/lib/ufe/testRename.py
* Fixed mayaUsd.ufe.stagePath() method to return Ufe pathString.
=> MAYA-126653 - mayaUsd.ufe.stagePath() returns incorrect value

lib/usd/translators/nurbsCurveWriter.cpp, test/lib/usd/translators/testUsdExportNurbsCurve.py
Detect some invalid bezier curves when exporting.
=> MAYA-124789 invalid beziers

lib/mayaUsd/utils/util.cpp, test/lib/ufe/testAttribute.py
Fixes incorrect prettification results for rotateXYZ.
=> Prettify: Add space on lower to upper transition

lib/mayaUsd/ufe/UsdUndoConnectionCommands.cpp, test/lib/ufe/testConnections.py, test/testSamples/MaterialX/compound_displacement_passthrough.usda
=> LOOKDEVX-1093 | Prevents a hang that can occur when forming certain

lib/mayaUsd/ufe/UsdMaterial.cpp
This PR fixes a bug where `getMaterials` would in certain cases return a shader instead of a material, which lead to inconsistent behaviour in LookdevX.
=> MAYA-127699 - Avoid diving into material when user selects "Show in LookdevX"

lib/mayaUsd/resources/ae/usdschemabase/ae_template.py, lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
* Cleaned up Xformable section as per design specs.
* Added AE template strings to resource.
=> MAYA-110702 - Prim AE template cleanup Xformable section

plugin/adsk/scripts/USDMenuProc.mel
Small addition that allows the user to remove the material assignment from the right-clicked object in the viewport.
=> MAYA-127975 - Add "Unassign Material" function to viewport context menu

lib/mayaUsd/utils/utilSerialization.cpp, lib/usd/ui/layerEditor/saveLayersDialog.cpp
The change in the order the layers are presented required to change the order the loop to do the saving should be executed.
=> MAYA-129332 fix batch saving of layers

lib/usd/ui/layerEditor/saveLayersDialog.cpp
- Refactoring SaveLayerPathRow class in preparation to future changes
- Display root layer path as only file name when saving as relative and Maya scene file doesn't exist
=> MAYA-129132 - As a user, I'd like my relative USD root file to appear as relative before my scene file is saved

lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
Also remove unnecessary Hd include
=> Update include paths for Hd files that have moved

test/lib/usd/translators/UsdImportSkeleton/skelCube.usda
UsdSkelBindingAPI is now an applied schema
=> Fix out-of-date UsdSkel assets

lib/mayaUsd/ufe/RotationUtils.h
Support both doubles and floats.
=> MAYA-000000 quick fix for conversion of rotations

test/lib/ufe/CMakeLists.txt, test/lib/ufe/testSelectionNotification.py
These demonstrate that some combination of ways to select, and listen to selections are not working correctly.
=> MAYA-129071 add UFE selection notification tests

lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.cpp
This should be a no-op for USD versions < 23.08
=> Use new HdMaterialBindings Schema and API

lib/mayaUsd/render/pxrUsdMayaGL/sceneDelegate.cpp
This should be a no-op for USD versions earlier than 23.08
=> Add new camera parameters to the pxr gl renderer

lib/usdUfe/ufe/UsdUndoAddRefOrPayloadCommand.cpp
This fixes internal Pixar builds
=> Use Pixar's directive for namespacing

lib/mayaUsd/nodes/proxyShapeBase.cpp, plugin/adsk/scripts/AEmayaUsdProxyShapeBaseTemplate.mel
- Add dependencies between file path attribute and the root layer, session layer and prim path attributes.
- Add a sript job to update the root layer and prim field in teh AE when the file path changes.
=> EMSUSD-261 fix root layer attribute in AE

plugin/adsk/scripts/mayaUSDRegisterStrings.mel, plugin/adsk/scripts/mayaUsdTranslatorImport.mel
- Add a drop-down to select the relative textures mode in the import and edit-as-Maya dialogs.
- Make sure the mode is remembered.
=> EMSUSD-280 import relative texture UI

plugin/adsk/scripts/mayaUsdTranslatorExport.mel
Change the annotation to lower case so it matches with the token string
=> EMSUSD-263 - Bug fix for export relative texture 

lib/mayaUsd/render/vp2RenderDelegate/instancer.cpp, lib/usd/hdMaya/adapters/dagAdapter.cpp
This allows usage of the most recent Hydra API
=> Renaming internal instancer primvars

plugin/adsk/scripts/mayaUSDRegisterStrings.mel, plugin/adsk/scripts/mayaUsd_preferenceTab.mel
=> EMSUSD-579 - Add Untextured mode selections to user pref

plugin/adsk/scripts/AETemplateHelpers.py, plugin/adsk/scripts/mayaUSDRegisterStrings.mel, plugin/adsk/scripts/mayaUsd_createStageFromFile.mel
Re-use the same UI functions as when initially creating the stage. Also, start the dialog in the path where the current file already is.
=> EMSUSD-686 better UI when selecting the proxy shape path

lib/mayaUsd/ufe/UsdAttributes.cpp
The code to handle it was off by one.
=> Fix errors when a USD object has an !invert! xform attribute.

plugin/adsk/scripts/mayaUSDRegisterStrings.mel, plugin/adsk/scripts/mayaUsd_pluginUICreation.mel, plugin/adsk/scripts/mayaUsd_preferenceTab.mel
* Reworded as per documentation suggestions.
=> EMSUSD-684 - Labeling of Relative settings may need reworded

plugin/adsk/scripts/mayaUsd_createStageFromFile.mel, plugin/adsk/scripts/mayaUsd_layerEditorFileDialogs.mel
This allows remembering the last loaded layer folder between Maya session.
=> EMSUSD-636 use the same saved folder location as when loading a stage.

test/lib/usd/translators/testUsdExportUVSetMappings.py
This overrides some studio-level options we have installed
=> Explicitly specify all required export options

lib/usd/ui/importDialog/TreeModel.h, lib/usd/ui/importDialog/USDImportDialog.cpp, lib/usd/ui/importDialog/USDImportDialogCmd.cpp
Also, remove the parent window warning that serves no purpose for the user.
=> EMS-764 properly reset the select prim dialog.

plugin/adsk/scripts/USDMenuProc.mel, plugin/adsk/scripts/mayaUsdTranslatorImport.mel
EMSUSD-614 - Fixes Edit As Maya Options Convert Instances Not Retaining
Also fixed the height issue on Edit As Maya Option Dialog
=> EMSUSD-614 - Fixes Edit As Maya Options Convert Instances Not Retaining From Session to Session

lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.cpp, lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.h, test/lib/mayaUsd/utils/materialx_test_data/topology_tests.mtlx, test/lib/mayaUsd/utils/test_ShaderGenUtils.cpp
Allows a notification handler to quickly know if a change is topological or not.
=> LOOKDEVX-2125 - Get watch list of traversed nodes

lib/mayaUsd/nodes/proxyShapeBase.cpp, plugin/adsk/plugin/plugin.cpp, test/lib/mayaUsd/nodes/testProxyShapeBase.py
https://github.com/Autodesk/maya-usd/issues/1337
Register usd files to file path editor
=> EMSUSD-599 - USD data is not registered on the Maya File Path Editor

lib/mayaUsd/render/vp2RenderDelegate/material.cpp, test/lib/mayaUsd/utils/test_ShaderGenUtils.cpp
This is version guarded since this API will be introduced with the next USD release
=> Use new Hd MtlxStdLibraries API

lib/mayaUsd/commands/baseExportCommand.cpp, lib/mayaUsd/fileio/jobs/jobArgs.cpp, lib/mayaUsd/fileio/jobs/jobArgs.h, lib/mayaUsd/python/wrapPrimWriter.cpp, plugin/adsk/plugin/exportTranslator.cpp, test/lib/mayaUsd/fileio/testExportChaser.py
I think we still need to add them into default dictionary because ultimately we want to access this variable in export chasers
=> EMSUSD-835 - Provide access to the Export Selected options

lib/mayaUsd/render/vp2RenderDelegate/material.cpp, test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateMaterialX.py, test/testSamples/MaterialX/color_management_USD.usda, test/testSamples/MaterialX/no-rule-studio-config-v1.0.0_aces-v1.3_ocio-v2.0.ocio
Update according to changes from Pixar commit [a8ec74c](https://github.com/PixarAnimationStudios/OpenUSD/commit/a8ec74c274da6d63ae964205c08e968f1642c5eb)
=> EMSUSD-765 - Update OCIO code to handle new Hydra colorspace info

lib/mayaUsd/commands/layerEditorCommand.cpp
When clearing a layer that had sub-layers and one of those sub-layer was the edit target, we would no longer have a valid edit target. Fix this by putting the target on a valid layer, for now the root (since it cannot be muted and thus is valid). Also, remember the edit target so that undo can restore it.
A the same time, split the functions in the command class to have each function do only one thing.
=> EMSUSD-848 fix edit target after layer clear

lib/usdUfe/utils/Utils.cpp, test/lib/ufe/testAttribute.py
EMSUSD-808 - Fixes an out of range crash that only occurs in Debug mode
=> EMSUSD-808 - Fixes an out of range crash that only occurs in Debug mode

test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateMaterialX.py
Since the latest USD has the OpenEXR fix.
=> EMSUSD-869 - Restore OpenEXR test

lib/mayaUsd/fileio/translators/translatorMaterial.cpp
Deprecate UsdGeomSubset::ValidateSubsets in favor of ValidateFamily
Update UsdGeomSubset::GetUnassignedIndices to accept a prim and family name instead of a list of subsets
=> Update usage of the Hydra API

lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
When using the universal manipulator, especially the scaling, many attributes would get added to the prim and one refresh per attribute were being queued. Fix the code to avoid queuing many AE refreshes.
=> EMSUSD-967 fix AE flashing when adding many attributes

lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
Doing as much work as possible instead of throwing the mesh entirely away.
=> EMSUSD-996 allowing meshes with insufficient primvars data size.

lib/mayaUsd/commands/abstractLayerEditorWindow.h, lib/mayaUsd/commands/layerEditorCommand.cpp, lib/mayaUsd/commands/layerEditorWindowCommand.cpp, lib/usd/ui/layerEditor/abstractCommandHook.h, lib/usd/ui/layerEditor/layerTreeItem.cpp, lib/usd/ui/layerEditor/layerTreeItem.h, lib/usd/ui/layerEditor/layerTreeItemDelegate.cpp, lib/usd/ui/layerEditor/layerTreeItemDelegate.h, lib/usd/ui/layerEditor/layerTreeModel.cpp, lib/usd/ui/layerEditor/layerTreeModel.h, lib/usd/ui/layerEditor/layerTreeView.cpp, lib/usd/ui/layerEditor/layerTreeView.h, lib/usd/ui/layerEditor/mayaCommandHook.cpp, lib/usd/ui/layerEditor/mayaCommandHook.h, lib/usd/ui/layerEditor/mayaLayerEditorWindow.cpp, lib/usd/ui/layerEditor/mayaLayerEditorWindow.h, lib/usd/ui/layerEditor/stringResources.h, lib/usdUfe/ufe/Utils.cpp, plugin/adsk/scripts/mayaUSDRegisterStrings.mel, plugin/adsk/scripts/mayaUsdMenu.mel, test/lib/testMayaUsdLayerEditorCommands.py
This change adds a locking action button as well as a context menu to USD Layer Editor to lock each layer individually.
=> EMSUSD-870 - Added Locking mechanism to layers

lib/mayaUsd/nodes/proxyShapeBase.cpp
Additional fix for https://github.com/Autodesk/maya-usd/pull/3418
=> EMSUSD-499 - Fix the bug that variant not saving to maya file

lib/mayaUsd/utils/copyLayerPrims.cpp
This fixes internal Pixar builds
=> Use the Using Directive macro

lib/usd/pxrUsdPreviewSurface/usdPreviewSurfaceWriter.cpp
With this PR, we make it so the UsdPreviewSurface writer understands that `Raw` and `Utility - Raw` are equivalent.
This is a sort of mirror to https://github.com/Autodesk/maya-usd/pull/2782 where we specifically handle `Utility - Raw` and just makes them consistent with each other.
This work was majorly done by Dan Knowlton on my team. I'll enable him to submit PRs directly on our behalf in the future.
=> Allow Raw colorspace aliases in file texture validation

lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
Fix reading past the end of the buffer causing incorrect rendering and crash later on.
=> EMS1056 vertex processing robustness

plugin/al/translators/pxrUsdTranslators/ProxyShapeTranslator.h
* Changes in preparation for USD v24.03
=> EMSUSD-1072 - Build USD v24.03 for Maya master (2026)

lib/usd/ui/layerEditor/layerTreeItemDelegate.cpp, lib/usd/ui/layerEditor/layerTreeItemDelegate.h
EMSUSD-1141 - Updates Layer Editor color visuals.
=> EMSUSD-1141 - Updates Layer Editor color visuals.

CMakeLists.txt, build.py
EMSUSD-1192 - UsdUfe: create standalone builds for MaxUsd
* Changes to build to allow building standalone usdUfe.
=> EMSUSD-1192 - UsdUfe: create standalone builds for MaxUsd

plugin/adsk/scripts/mayaUsd_exportHelpers.py
Filter items hidden in the outliner for the root prim drop-down when caching to USD.
=> EMSUSD-1173 filter items hidden in the outliner

lib/mayaUsd/render/pxrUsdMayaGL/proxyDrawOverride.cpp, lib/mayaUsd/render/pxrUsdMayaGL/proxyShapeUI.cpp
This fixes a potential loss of precision
=> Remove down cast of world space hit point in HdxPickHit

lib/mayaUsd/python/wrapUsdUndoManager.cpp, lib/mayaUsd/undo/MayaUsdUndoBlock.h, lib/mayaUsd/undo/README-USD-Undo.md, lib/usdUfe/undo/UsdUndoBlock.h, test/lib/mayaUsd/undo/testUsdUndoManager.py
While investigating another task, I had to re-read the docs I had written and found them unclear. I improved them and also improved the support to undo/redo in Python.
=> EMSUSD-000000 improve the undo/redo documentation

lib/usdUfe/ufe/UsdClipboardCommands.cpp
* Select only the normal pasted prims, ignoring shaders/nodegraph/materials for now.
=> EMSUSD-1121 - Pasted prims should be selected

lib/mayaUsd/fileio/translators/CMakeLists.txt, lib/mayaUsd/fileio/translators/translatorBlendShape.cpp, lib/mayaUsd/fileio/translators/translatorBlendShape.h, lib/mayaUsd/fileio/translators/translatorMesh.cpp, lib/mayaUsd/fileio/translators/translatorSkel.cpp, lib/mayaUsd/fileio/utils/meshReadUtils.cpp, lib/usd/translators/meshWriter_BlendShapes.cpp, lib/usd/translators/skelReader.cpp, test/lib/usd/translators/CMakeLists.txt, test/lib/usd/translators/UsdImportSkeleton/morpher_box.usd, test/lib/usd/translators/testUsdImportBlendShapes.py
This PR adds support to import UsdSkelBlendShapes into Maya BlendShapes
This PR solves #3101
=> Add support to import Usd Blendshape as Maya blendshapes

lib/mayaUsd/resources/scripts/mayaUsdDuplicateAsUsdDataOptions.py, plugin/adsk/scripts/mayaUsdTranslatorExport.mel
In duplicate-to-USD, disable materials if meshes are disabled.
=> EMSUSD-1343 disable material in sync with meshes when duplicating

test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateUsdCamera.py
Force the viewport to update by moving the camera.
=> EMSUSD-1358 fix blessing failure

lib/mayaUsd/commands/baseListJobContextsCommand.cpp, lib/mayaUsd/fileio/shading/shadingModeExporterContext.cpp, lib/mayaUsd/fileio/translators/translatorMayaReference.cpp, lib/mayaUsd/fileio/utils/meshWriteUtils.cpp, lib/mayaUsd/nodes/proxyAccessor.cpp, lib/mayaUsd/nodes/proxyShapePlugin.cpp, lib/mayaUsd/render/vp2RenderDelegate/renderDelegate.cpp, lib/mayaUsd/ufe/ProxyShapeHierarchy.cpp, lib/mayaUsd/ufe/UsdTransform3dFallbackMayaXformStack.cpp, lib/mayaUsd/utils/loadRulesAttribute.cpp, lib/mayaUsd/utils/targetLayer.cpp, lib/mayaUsd/utils/util.cpp, lib/mayaUsd/utils/util.h, lib/mayaUsd/utils/variantFallbacks.cpp, lib/usd/hdMaya/adapters/lightAdapter.cpp, lib/usd/hdMaya/adapters/materialAdapter.cpp, lib/usd/hdMaya/delegates/sceneDelegate.cpp, lib/usd/pxrUsdPreviewSurface/usdPreviewSurfaceShadingNodeOverride.cpp, lib/usd/translators/particleWriter.cpp, lib/usdUfe/ufe/UsdHierarchy.cpp, plugin/adsk/plugin/plugin.cpp
* As per our coding standard, constant name variables should be named with a leading k followed by UpperCamelCase.
=> EMSUSD-1351 - MayaUsd: Code cleanup

lib/mayaUsd/render/MaterialXGenOgsXml/OgsFragment.cpp, lib/mayaUsd/render/MaterialXGenOgsXml/OgsFragment.h, lib/mayaUsd/render/vp2RenderDelegate/material.cpp, lib/mayaUsd/utils/util.cpp, lib/usdUfe/utils/Utils.cpp, plugin/adsk/plugin/adskMaterialCommands.cpp
- Fix transparent detection on OpenPBR surface
- Fix transparent detection on glTf PBR
- Add OpenPBR to list of vetted materials
=> LOOKDEVX-3144 - Fix transmission issues

lib/mayaUsd/fileio/translators/translatorCurves.cpp, test/lib/usd/translators/UsdImportBasisCurvesTest/invalidNurbsCurves.usda, test/lib/usd/translators/testUsdImportNurbsCurves.py
=> EMSUSD-1444 improve curve import sanity checking

test/lib/CMakeLists.txt, test/lib/testMayaHydraPlugin.py, test/lib/testMayaUsdPlugVersionCheck.py, test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
EMSUSD-1442 - Update Maya Blessing so that the latest Hydra is picked up and used
* Added unit test to verify that MayaHydra plugin can be loaded.
=> EMSUSD-1442 - Update Maya Blessing so that the latest Hydra is picked up and used

cmake/modules/FindMaya.cmake, lib/mayaUsd/render/vp2RenderDelegate/meshViewportCompute.cpp, lib/mayaUsd/render/vp2RenderDelegate/meshViewportCompute.h, lib/mayaUsd/render/vp2RenderDelegate/renderDelegate.cpp, lib/mayaUsd/render/vp2RenderDelegate/taskCommit.h
* Support for OneTBB (from USD build).
=> EMSUSD-1550 - Build with USD v24.08

plugin/pxr/maya/lib/usdMaya/AEpxrUsdReferenceAssemblyTemplate.py
This provides a way to customize how variantSets are presented in the Attribute Editor for reference assemblies.
=> Update AE interface for Pxr Reference Assembly nodes

lib/mayaUsd/fileio/translators/translatorUtil.cpp, lib/mayaUsd/ufe/UsdUndoMaterialCommands.cpp, lib/usd/hdMaya/adapters/materialNetworkConverter.cpp, lib/usd/translators/shading/mtlxBaseWriter.cpp, lib/usd/translators/shading/usdFileTextureWriter.cpp, lib/usdUfe/ufe/UsdShaderAttributeDef.cpp, lib/usdUfe/ufe/UsdShaderAttributeHolder.cpp, lib/usdUfe/ufe/Utils.cpp
The class version of NdrSdfTypeIndicator will land in USD 2411. The callsites are version guarded
=> Updating callsites to use new NdrSdfTypeIndicator class

lib/usdUfe/utils/Utils.cpp
Update of User Interface node definitions names list
=> LOOKDEVX-3335 - Update MaterialX node UInames

lib/mayaUsd/render/vp2RenderDelegate/resourceRegistry.h
=> EMSUSD-1550 - Build USD v24.08 (with oneTBB) for Maya 2026

lib/usd/ui/layerEditor/layerEditorWidget.cpp
Add object names to three buttons: add layer, import layer, save all layers. The names are:
LayerEditorAddLayerButton
LayerEditorImportLayerButton
LayerEditorSaveAllButton
=> EMSUSD-1510 save-layer button's name

test/lib/mayaUsd/fileio/UsdExportMaterialScopeTest/one-group.ma, test/lib/mayaUsd/fileio/testDuplicateAs.py
Rather than have an external dependency in a mayaUsd test, copy the test file locally
=> Copy input file for test in separate location

lib/usdUfe/utils/editRouterContext.h
This fixes internal Pixar builds
=> Use macros for the pxr namespace

lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
Two different branches modified the same file in incompatible ways.
=> EMSUSD-0 fix bad merge in string resources

lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.cpp, lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.h, test/lib/mayaUsd/utils/materialx_test_data/DefaultGeomPropCase1.mtlx, test/lib/mayaUsd/utils/materialx_test_data/defaultgeomprop_topo.mtlx, test/lib/mayaUsd/utils/test_ShaderGenUtils.cpp
Copies nodegraph input defaultgeomprop values during TopoNeutralGraph construction.
=> Copies nodegraph input defaultgeomprop values during TopoNeutralGraph construction

lib/mayaUsd/CMakeLists.txt, lib/mayaUsdAPI/CMakeLists.txt, lib/usdUfe/CMakeLists.txt
* Revert mistake made in previous commit related to boost cmake flags.
=> EMSUSD-1770 - Initial support for USD v24.11

lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/expressionRulesMenu.py, lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/expressionWidget.py, lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/includeExcludeWidget.py
- The expression data changed callback was calling non-existing function on text string.
- Made label Python constants be all uppercase.
- Fix that clearing all include/exclude would not update the remove button.
=> EMSUSD-1996 Fix expression UI

lib/mayaUsd/undo/README-Nice-Undo.md, lib/mayaUsd/undo/README-Op-Undo.md, lib/mayaUsd/undo/README-USD-Undo.md, lib/mayaUsd/undo/README.md
Document how to get nice undo labels. Also adds a bit more info in the other docs about undo and redo.
=> Document how to get nice undo labels

lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/host.py, lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/data/stringListData.py, lib/mayaUsd/resources/ae/usdschemabase/collectionMayaHost.py
- Add a reportMessage function and MessageType to the Host class.
- Report about invalid items when dropping objects on the include or exclude lists.
- Implement the reportMessage function in the Maya host.
=> EMSUSD-2014 report error for invalid include and exclude

lib/mayaUsd/resources/ae/usdschemabase/collectionMayaHost.py
Implement the uiScaleFactor function in the Maya host.
=> EMSUSD-2012 implement theme scale in Maya Host

lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/includeExcludeWidget.py, lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/host.py, lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/usdData/usdCollectionStringListData.py, lib/mayaUsd/resources/ae/usdschemabase/collectionMayaHost.py
- Add a getSelectionAsText function to the host class.
- Add the "add selection..." actions to the add button.
- Enable the items only if a valid selection is present, outside of the collection itself.
- Add additional validation in the _isValidString USD implementation to avoid adding a prim to its own collection.
- Implement the getSelectionAsText in the Maya host.
=> EMSUSD-1646 add the selection to a collection

lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/persistentStorage.py, lib/mayaUsd/resources/ae/usdschemabase/collectionCustomControl.py, lib/mayaUsd/resources/ae/usdschemabase/collectionMayaHost.py
- Add documentation to the PersistentStorage class.
- Add a Maya implementation of the PersistenStorage class that uses option vars.
=> EMSUSD-2004 save collection list view size

lib/mayaUsd/resources/ae/CMakeLists.txt, lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/expressionWidget.py, lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/includeExcludeWidget.py, lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/warningWidget.py, lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/data/collectionData.py, lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/usdData/usdCollectionData.py
- Add a hasDataConflict function to the data class.
- Implement the function in the USD collection data class: detect conflict between membership and explicit inclusion or exclusion.
- Add a warning icon widget class to handle the warning icon.
- Add the warning icon to the UI and show it when conflicts are reported, hide it when conflicts go away.
- Report a log message when data becomes conflicted.
=> EMSUSD-1874 detect data conflicts

lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/filteredStringListView.py, lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/data/stringListData.py, lib/mayaUsd/resources/ae/usdschemabase/collectionMayaHost.py
Sync drag and drop elements from shared component
Added a new undoable command to replace strings when editing an element in the collection component
=> EMSUSD-1516 Sync drag and drop from max

lib/mayaUsd/resources/helpTable/helpTableMayaUSD, plugin/adsk/scripts/mayaUsd_createStageFromFile.mel
- Add help tag
- Change how the option box fills the help menu to be able to use MayaUSD tags.
=> EMSUSD-1598 add help for create stage option box

lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
The code was using a variable before it was initialized
=> EMSUSD-2185 fix schemas in AE

lib/mayaUsd/render/pxrUsdMayaGL/hdImagingShapeDrawOverride.h, lib/mayaUsd/render/pxrUsdMayaGL/proxyDrawOverride.cpp, lib/mayaUsd/render/pxrUsdMayaGL/proxyDrawOverride.h
This also uses a more current DrawOverride API
=> Selectable imaging node caused issues with XRay shading

plugin/adsk/plugin/gizmoGeometryOverride.cpp
updates the Object Type Exclusion Flag for gizmoGeometryOverride.
=> HYDRA-1519 - Fixes viewport filter for USD lights

lib/usd/translators/lightReader.cpp, lib/usd/translators/plugInfo.json, test/lib/usd/translators/UsdImportRfMLightTest/RfMLightsTest.usda, test/lib/usd/translators/testUsdImportRfMLight.py
Moved to an internal pxr plugin
=> Removing UsdLuxGeometryLight reader

doc/build.md
* Update docs with 24.11 tags & Maya 2026.
=> EMSUSD-2186 - Publish USD v24.11 branch

lib/mayaUsd/resources/ae/CMakeLists.txt, lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/expressionRulesMenu.py, lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/includeExcludeWidget.py, lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/filteredStringListView.py, lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/host.py, lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/usdData/usdCollectionData.py, lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/usdData/usdCollectionStringListData.py, lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/usdData/validator.py, lib/mayaUsd/resources/ae/usdschemabase/collectionMayaHost.py, lib/mayaUsd/resources/helpTable/helpTableMayaUSD
EMSUSD-2113 As an artist, I want a Help link to point me to training docs for Collections
+ Sync with Max
* Set case insensitive
=> EMSUSD-2113 As an artist, I want a Help link to point me to training docs for Collections

lib/mayaUsd/commands/Readme.md, lib/mayaUsd/commands/abstractLayerEditorWindow.h, lib/mayaUsd/commands/layerEditorWindowCommand.cpp, lib/usd/ui/layerEditor/layerEditorWidget.cpp, lib/usd/ui/layerEditor/mayaCommandHook.cpp, lib/usd/ui/layerEditor/mayaLayerEditorWindow.cpp, lib/usd/ui/layerEditor/mayaLayerEditorWindow.h, test/lib/testMayaUsdInteractiveLayerEditorCommands.py
* The LayerEditorWindowCommand proxyShape flag is query and create.
* Update command readme with flag modes.
* Fixed another bug when selecting layers to set the current index. The currentIndex is needed by many of the flags of this command.
* Fixed bug with selectPrimsWithSpec calling MGlobal from within a command. Call Ufe selection directly.
* proxyShape flag query needs full name.
* Wrote unit test for mayaUsdLayerEditorWindow command to test most of the flags.
=> EMSUSD-2301 - Layer Editor Won't Launch

lib/mayaUsd/fileio/jobs/readJob.cpp, plugin/pxr/maya/lib/usdMaya/testenv/testUsdExportPackage.py
=> Move deprecated Usd ZipFile-related codesites

lib/mayaUsd/fileio/translators/translatorCamera.cpp, lib/mayaUsd/fileio/translators/translatorLight.cpp, lib/mayaUsd/fileio/utils/readUtil.cpp, lib/mayaUsd/fileio/utils/splineUtils.cpp, lib/mayaUsd/fileio/utils/splineUtils.h, test/lib/usd/translators/testUsdExportLightAttrSplines.py
Fix bugs in light spline export.
Add support for light attribute spline import.
=> EMSUSD-2300 : Support Import for spline attribute of USD Lights.

lib/mayaUsd/fileio/transformWriter.cpp
Fix animated export transform for version bellow 2505
=> EMSUSD-2559 : Transforms are lost If objects contain transform data and Animation Curves is set on export

lib/mayaUsd/fileio/transformWriter.cpp, lib/mayaUsd/fileio/translators/translatorCamera.cpp, lib/mayaUsd/fileio/translators/translatorLight.cpp, lib/mayaUsd/fileio/translators/translatorXformable.cpp, lib/mayaUsd/fileio/utils/readUtil.cpp, lib/mayaUsd/fileio/utils/splineUtils.h, lib/mayaUsd/fileio/utils/xformStack.cpp, test/lib/usd/translators/testUsdExportSplineXforms.py, test/lib/usd/translators/testUsdImportXformAnim.py
Fix Rotation op order.
USD rotation should be in degree.
=> EMSUSD-2576 : Rotation is incorrectly written on export to USD when using splines.

lib/lookdevXUsd/CMakeLists.txt, lib/lookdevXUsd/LookdevXUsd.cpp, lib/lookdevXUsd/ProxyShapeLookdevHandler.cpp, lib/lookdevXUsd/ProxyShapeLookdevHandler.h, lib/lookdevXUsd/UsdMaterialHandler.cpp
=> LOOKDEVX-4467 - Move ProxyShapeLookdevHandler to MayaUSD.

lib/mayaUsd/fileio/translators/translatorXformable.cpp, lib/mayaUsd/fileio/utils/splineUtils.h, test/lib/usd/translators/testUsdImportXformAnim.py
Fix export tangents Y values. It was missing scaling.
Fix import of individual transforms.
=> EMSUSD-2577 : Some tangent usage are not translated correctly in 25.05 on Stage Creation

lib/usdUfe/ufe/StagesSubject.cpp, lib/usdUfe/ufe/Utils.cpp, lib/usdUfe/ufe/Utils.h
* Instead of sending out subtreeInvalidate to fix selection list just remove the items from selection list.
=> EMSUSD-2637 - Performance is slow with variants on certain Kitbash scene assets

lib/mayaUsd/utils/progressBarScope.cpp
This fixes runtime failures in our debug build
=> Define static class member in impl file

lib/mayaUsd/fileio/translators/translatorCamera.cpp, test/lib/usd/translators/testUsdImportCamera.py
Fix leave early condition on animated fstop with spline
Re-enable test
=> EMSUSD-2537 Animated F-stop attribute is not importing when using spline
