- CMakeLists.txt
- cmake/modules/FindUSD.cmake
- cmake/usd.cmake
- plugin/al/CMakeLists.txt
- plugin/pxr/CMakeLists.txt
FindUSD.cmake supports using an env var for PXR_USD_LOCATION, but
it never guarantees that the corresponding cmake-var is set... even though other
build files rely on it existing.
This ensures that the cmake-var for PXR_USD_LOCATION is set, which means you can safely use ENV{PXR_USD_LOCATION}.  (Also, ensuring PXR_USD_LOCATION is set before using is a good cmake practice in general.)
> support setting of PXR_USD_LOCATION hint via an env var

- lib/fileio/shading/shadingModeImporter.h
for consistency with rest of code base, fewer dependencies (because project
requires c++11), and because I got a build error becuase boost::function
had only been forward declared
> use std::function instead of boost::function

- plugin/pxr/maya/lib/pxrUsdMayaGL/shapeAdapter.h
> 'Always' from X.h conflicts with USD when maya/M3dView.h is included

- mayaUSD.mod.template
- plugin/al/lib/AL_USDMaya/CMakeLists.txt
Hi all,
I'm not sure if you had other plans for this file, but wanted to see what you thought of this.
The two main changes here are extracting the AL_USDMaya version from its Version.h (and including that header in the build), and then using that along with the other existing CMake variables in mayaUSD.mod.template for the fields that needs to be replaced.
With these changes, my builds end up producing a mayaUSD.mod file that looks like this:
```
+ USD 0.19.10 /pixar/ws/trees/mattjohnson/usd_open_source/build/inst
PYTHONPATH+:=lib/python
PATH+:=bin
PATH+:=lib
+ PXR_USDMAYA 0.19.10 /home/mattjohnson/local/open_source_projects/maya-usd/build/install/RelWithDebInfo/plugin/pxr
PYTHONPATH+:=lib/python
PATH+:=maya/lib
XBMLANGPATH+:=maya/lib/usd/usdMaya/resources …
```
> Use CMake variables to fully configure mayaUSD.mod

- plugin/al/lib/AL_USDMaya/AL/usdmaya/cmds/ProxyShapeCommands.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeSelection.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeUI.cpp
- Viewport selection problems when we have duplicate proxy names
- Sometimes shift-selecting several objects which have duplicate proxy names
in the viewport, then clicking somewhere else in the viewport, which should
clear the selection, clears the selection but leaves one or more of the
objects highlighted in the viewport. (The cause of this was ProxyDrawOverride
was setting m_pleaseIgnoreSelection - a temporary state - but then neglecting
to unset it.)
> Two bug fixes related to viewport selection

- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/wrapTranslatorBase.cpp
Happened to notice a few warnings about functions missing return values.
Longer term, I'd like to get PXR_STRICT_BUILD_MODE (or an equivalent) working, so we can error on all the warnings...
> some functions weren't returning a value

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeUI.cpp
This resolves a template deduction/substitution compilation error encountered
when building with gcc 4.8.3 on Linux.
> replace use of auto with full type name when getting Ufe::HierarchyHandler::Ptr

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/wrapProxyShape.cpp
Merge internal change to fix the compilation error on Windows with VS2017.
> Update dev 2

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.h
"collapsed" xforms - ie, a Mesh node with a transform directly applied on it, and no Xform parent - is technically not comatible with UsdGeom.Xform - just UsdGeom.Xformable.
This has mostly gone unnoticed because calls to methods on parent schemas still "work" - however, a check such as `if(m_xform)` will fail.
> [al] TransformMatrix should use xformable, not xform

- lib/render/vp2RenderDelegate/proxyRenderDelegate.cpp
When a proxy node lives inside a Maya namespace (as is the case when a `pxrUsdReferenceAssembly` node is loaded in its `Collapsed` representation), its name will include colon characters which are invalid in identifier names used in prim paths. This change ensures that the delegate name is a valid identifier before we try to create an `SdfPath` from it.
This fixes an issue where `pxrUsdReferenceAssembly` nodes would not draw correctly and Hydra errors would be spewed when `VP2_RENDER_DELEGATE_PROXY` was enabled.
> sanitize the proxy's UsdImagingDelegate name before using it to construct the delegateId

- plugin/al/CMakeLists.txt
...since it requires it, better to fail early
Note that I confirmed this change is not in PR91 yet; however, this is obviously low priority.  Just happened to notice this when doing a test build on windows...
> [al] Make AL's cmake confirm that date_time lib is available on windows

- plugin/al/translators/MayaReference.cpp
- plugin/al/translators/MayaReference.h
Changed the way reference nodes are named in order to fix the problem where
proxy nodes with duplicate names all created/attached to the same reference
node, making it impossible to save separate reference edits for them.
Also changed how code checks whether a reference has previously been created
for a prim (so it can be reused).  This allowed me to get rid of having to
create an attribute on the reference node, which wasn't serving a useful
purpose in the new scheme of things.
> Changed the way reference nodes are named to fix duplicate named proxy problem

- plugin/al/translators/pxrUsdTranslators/tests/CMakeLists.txt
- plugin/al/translators/pxrUsdTranslators/tests/testPxrTranslators.sh
- $USD_MAYA_ROOT not defined / needed (should always be part of this project)
- made sure that the pixar maya plugin's python dir is added to the
pythonpath before the main USD python dir; this is necessary because the
pixar maya plugin also defines a pxr/__init__.py, which needs to come
before the main USD pxr/__init__.py
- created / used explicit names in place of some $# variables (ie, $3 / $4),
for clarity
> misc fixes to paths to get AL pxrUsdTranslators tests running

- plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/commands/test_LayerManagerCommands.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/commands/test_ProxyShapeSelect.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyShape.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_TransformMatrix.cpp
...to make sure they get properly cleaned up when tests exit
> [al] ensure usage of buildTempPath in all tests

- lib/render/vp2ShaderFragments/shaderFragments.cpp
- plugin/pxr/maya/plugin/pxrUsdPreviewSurface/plugin.cpp
This resolves an issue where headless contexts of Maya would emit API errors during plugin registration because the renderer cannot be initialized. We now no longer force the renderer to initialize, and we bypass fragment registration/de-registration and return success if we cannot get a handle to the MRenderer or MFragmentManager.
More detail is available in the abandoned PR #128.
> skip fragment registration/de-registration when MRenderer or MFragmentManager are not available

- lib/usd/hdMaya/delegates/sceneDelegate.cpp
I came across this while looking into adapting mayaToHydra to recent Hydra API changes.
> fix incorrect function name in HdMayaSceneDelegate::GetMaterialId() debug message

- CMakeLists.txt
This fixes the issue described in #150 by increasing the minimum required CMake version.
_Note: I've just set the version number from the Issue - I haven't tested this myself._
@ryan-seymour could you check whether this captures the older compiler that failed correctly on your end?
> Fix #150: Bump minimum required CMake version to 3.12.0

- lib/render/vp2ShaderFragments/plugInfo.json
happens because the plugin is marked as a library, instead of a resource,
and specifies a LibraryPath (which it tries to load)
> fix an error on loading plugin, that mayaUsd_ShaderFragments is a folder

- cmake/defaults/Options.cmake
- cmake/modules/FindUSD.cmake
- plugin/pxr/cmake/macros/Public.cmake
- disable setting of custom output lib prefixes (for maya-usd outputs) via PXR_LIB_PREFIX
- enable finding of USD-core built with a custom PXR_LIB_PREFIX (via USD_LIB_PREFIX)
> Fixes issues with PXR_LIB_PREFIX

- doc/build.md
The master `/doc/build.md` file still mentioned the build was supposed to run against USD 0.19.05 yet as seen in #189 this actually doesn't work anymore. `/doc/DEVELOPER.md` instead describes the compatible source versions.
_**Warning**: This PR is deliberately set to merge against "master" for #189 to avoid confusion for new users_
This way it'll be more likely for newcomers to actually find the compatible versions to build against.
**Note:**
This same PR should also be cherry-picked for all other branches as it makes sense to have it consistent across the repository. Or, the other way to simplify would be to remove `/doc/DEVELOPER.md` and have the information available in `/doc/build.md`.
Remove old 0.19.05 USD version mention in `/doc/build.md` and link to `doc/DEVELOPER.md` instead.
> Remove old 0.19.05 USD version mention and link to doc/DEVELOPER.md

- plugin/al/mayautils/AL/maya/utils/NodeHelper.cpp
- plugin/al/mayautils/AL/maya/utils/NodeHelper.h
since old "addInheritedAttr" wasn't used, but there was a lot of repeated
code that COULD be using it, and addFrameAttr better describes it's
purpose
There's no functional difference with this code... but I wrote this while working on another change I was making, and decided the code unification / reduction was worth making a PR for on it's own.
> [al] replace NodeHelper::addInheritedAttr with addFrameAttr

- lib/CMakeLists.txt
* New python module need to have _d when compiled with debug python.
> MAYA-102389 - PyMayaUsd python bindings don't work with Maya Debug on Win

- plugin/pxr/maya/lib/usdMaya/__init__.py
Pull request #154 relocates a bunch of Python bindings from pxr.UsdMaya to mayaUsd.lib. To ease the transition for Python code that uses the bindings from the old package namespace, this change reintroduces the migrated names back into the pxr.UsdMaya namespace by importing them from mayaUsd.lib. It is wrapped in a try/except so that it will work both before and after PR #154 is merged.
> reintroduce migrated UsdMaya Python bindings back into the pxr.UsdMaya namespace

- cmake/defaults/msvcdefaults.cmake
This allows us now to build maya-usd in strict mode on all platforms.
> Disable deprecated warning on windows (matching gcc and clang)

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
This PR fixes issue #127 
It just makes sure that the stage is set in the data block (in ProxyShape::loadStage()) before sending any notifications or causing side effects.
Inside ProxyShape::loadStage() this call `m_stage->SetEditTarget(m_stage->GetSessionLayer());` causes other events to be triggered. If the stage data is not set in the datablock before this call we experience the error reported in issue #127
> make sure stage is set in datablock in ProxyShape::LoadStage

- CMakeLists.txt
- lib/CMakeLists.txt
- lib/python/__init__.py
- lib/python/moduleDeps.cpp
- test/lib/CMakeLists.txt
- test/lib/testMayaUsdPythonImport.py
This changes the name of the Python module shared object for the mayaUsd library to `_mayaUsd.so` to be more consistent with the way other Python modules are built. The capitalization of the first letter in the module name was a carry over from core USD which isn't relevant in maya-usd, and it wasn't even visible from Python anyway, since the module's contents gets imported under the `mayaUsd.lib` package path.
More importantly though, this adds a `TfScriptModuleLoader` registry function that ensures that when the mayaUsd library is loaded as a result of importing its Python module, the core USD libraries that it depends on also get loaded.
Without the changes in this PR, the test that was added fails with an error that looks like this:
``` …
```
> build mayaUsd Python bindings module consistently with other modules

- plugin/al/translators/pxrUsdTranslators/tests/CMakeLists.txt
- plugin/pxr/maya/plugin/pxrUsd/plugin.cpp
...if we find an operation failed, instead of printing a warning and continuing
I originally added this because to catch an error on an internal luma branch, but it has also exposed an error in the AL test TestPxrUsdTranslators (fixed in https://github.com/Autodesk/maya-usd/commit/2c78161eac9f5bd4baabb3f8abff6564f9ec0400)
> [pxr] when loading the pixar plugin, trigger an immediate fail

- test/lib/CMakeLists.txt
This prevents `unittest.main()` from exiting on test failures and ensures that `maya.standalone.uninitialize()` gets called before returning success or failure.
@HamedSabri-adsk previously made this fix for the UFE tests in #198.
> apply maya.standalone.uninitialize() fix from #198 to mayaUsd tests

- plugin/al/lib/AL_USDMaya/AL/usdmaya/PluginRegister.h
...a recent AL change (55e01cf9e52d14069f86763bf447a9c6ee7650a9) added
the ability to control the setting for pushToPrim for newly created
nodes via an optionVar, which is useful, but it also changed the default
from on to off.
In addition to being breaking behavior, this is also highly
non-intuitive for artists, who will be confused when they try to
transform the usd object, and it does nothing.  I would also argue that
the ability to pushToPrim is the primary thing which distinguishes this
plugin from the Pixar plugin, and as such, is probably why most people
are using it in the first place.
NOTE: I haven't yet run the tests for this, as the tests are still not fully functional on the dev branch.  Assuming we agree that this change should be made, we may wish to delay merging it in …
> [al] make pushToPrim default to On

- lib/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/render/vp2RenderDelegate/proxyRenderDelegate.h
GetListAdjustment is used iff WANT_UFE_BUILD is on, so added a guard
also, I noticed that the _globalListAdjustment is only used if WANT_UFE_BUILD
is on, so I also added a guard for that
now that PXR_STRICT_BUILD_MODE is on by default, this will cause the build to fail without this fix
> [vp2RenderDelegate] fix error/warning unused GetListAdjustment

- plugin/al/plugin/AL_USDMayaTestPlugin/py/CMakeLists.txt
- plugin/al/plugin/AL_USDMayaTestPlugin/py/examplecubetranslator.py
- plugin/al/plugin/AL_USDMayaTestPlugin/py/testLayerManager.py
- plugin/al/plugin/AL_USDMayaTestPlugin/py/testProxyShape.py
- plugin/al/plugin/AL_USDMayaTestPlugin/py/testTranslators.py
- plugin/al/plugin/AL_USDMayaTestPlugin/py/testUSDMayaPythonModuleOnly.py
also added a test to ensure that this module can be imported, even without
loading the plugin or even instantiating maya (mostly just to check that
the linking is set up correctly)
> add a test to ensure that the AL.usdmaya python lib links correctly

- lib/fileio/primUpdater.h
It seems the strict c++ spec used to state that a const class could only be constructed if it had an explicitly define constructor - even if there was an "obvious" default constructor, that wouldn't leave uninitialized items.
A defect was filed, and later accepted:
http://open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#253
...but it seems clang, as of Apple clang version 11.0.0, still warns if
you're using --std=c++11
(GCC lets this pass.)
The full error message I got when compiling (using OSX catalina, Apple clang version 11.0.0), was:
```
In file included from /System/Volumes/Data/Projects/Dev/USD/maya-usd/src/lib/fileio/primUpdater.cpp:17:
/System/Volumes/Data/Projects/Dev/USD/maya-usd/src/lib/fileio/primUpdater.h:40:5: error: explicitly defaulted default constructor is implicitly …
```
> [fileio] fix a clang warning about default ctor + const member

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/BasicTransformationMatrix.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/BasicTransformationMatrix.h
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Scope.h
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.h
Similar to the recent scope fixes (with shadowing of m_prim), I noticed that there were some oddities in the division between BasicTransformationMatrix and TransformationMatrix.
Specifically:
- `m_scope` never seemed to be used anywhere
- `m_transformNode` seemed to be unnecessarily shadowed; unshadowing also meant that `setMObject` didn't need to be virtual / repeated
- there seemed to be no need for `Scope::transform()` to be virtual - it's never overridden, and `Transform::getTransMatrix()` is already defined to get a `TransformationMatrix*`
> [al] clean up boundary of BasicTransformationMatrix and TransformationMatrix

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.cpp
We noticed when loading our very large sets into Maya that the time taken to select objects in the viewport was taking upto a minute. Running the code through vtune, we identified that the most significant bottleneck was simply a result of the call to UsdImagingEngine::SetSelected. Removing these two calls returned us to an interactive selection speed within the Maya viewport.
> [al] De-activate usdImaging selection in ProxyDrawOverride (#1008)

- plugin/al/lib/AL_USDMaya/AL/usdmaya/cmds/ProxyShapeCommands.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorBase.cpp
This is a crash fix for an edge case when using TranslatePrim non-recursively on a previously translated transform/scope. Also improved some of the TfDebug notices.
> [al] Fix an edge case within TranslatePrim  (#1009)

- cmake/utils.cmake
This fixes linking issues if you happen to have a symlink as part of your build path.
Previously, mayaUsd_add_rpath would use "realpaths" when comparing to origin, but mayaUsd_init_rpath would ONLY use a realpath if the argument was originally a relative path.  Thus, if you fed in an absolute path with a symlink, you would end up comparing a symlink path to a realpath.
> linux/rpath: fix relative path finding for symlinked dirs

- lib/CMakeLists.txt
- lib/nodes/proxyShapeBase.cpp
- lib/render/pxrUsdMayaGL/batchRenderer.cpp
- lib/render/pxrUsdMayaGL/batchRenderer.h
- lib/render/pxrUsdMayaGL/hdImagingShapeDrawOverride.cpp
- lib/render/pxrUsdMayaGL/hdImagingShapeUI.cpp
- lib/render/pxrUsdMayaGL/proxyDrawOverride.cpp
- lib/render/pxrUsdMayaGL/proxyShapeUI.cpp
- lib/render/pxrUsdMayaGL/usdProxyShapeAdapter.cpp
This takes a cue from recent work in the VP2.0 render delegate and adds some performance tracking to Pixar's batch renderer Hydra integration. This is proving to be helpful as we work to deprecate our usage of the legacy viewport, and also as we look towards eventually adopting the VP2.0 render delegate.
The MProfilerScopes added are good for tracking overall time spent in the batch renderer when using Maya's Profiler. The trace performance tracking is good for looking at the time spent in batch renderer setup and overhead versus the time spent in underlying Hydra and USD libraries, since those are also instrumented using trace.
The one change here that affects users **not** using the batch renderer is the addition of a `TRACE_FUNCTION()` call in `MayaUsdProxyShapeBase::boundingBox()`. A …
> add MProfiler/trace performance tracing when using Pixar's batch renderer

- cmake/plugin/AL_USDMayaTestPlugin/test_data/rig_bindings.usda
- plugin/al/lib/AL_USDMaya/AL/usdmaya/cmds/ProxyShapePostLoadProcess.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorBase.h
- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorContext.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorContext.h
- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/wrapTranslatorBase.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.h
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/proxy/PrimFilter.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/proxy/PrimFilter.h
- plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/proxy/test_PrimFilter.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/py/testTranslators.py
- plugin/al/plugin/AL_USDMayaTestPlugin/test_data/rig_bindings.usda
Typically when using a custom translator, the following action occurs on a variant switch:
If a prim that had previously been translated into Maya, remains in the stage after a variant switch, and that prim supports update, then the translator's update method will be called. In some cases this update step may be entirely superfluous _(because none of the data changed)_. 
For some of the translators we use internally, there are cases where the cost of updating can be very large, so this PR adds a way to optionally generate a hash for a translated prim, which can be used again later on to determine whether update should be called or not. 
Within a translator, you would override the generateUniqueKey method, to return a hashed value for a specific prim.
> [al] added generate unique key method for translators (#1005)

- lib/CMakeLists.txt
- lib/render/vp2RenderDelegate/basisCurves.cpp
- lib/render/vp2RenderDelegate/basisCurves.h
- lib/render/vp2RenderDelegate/draw_item.cpp
- lib/render/vp2RenderDelegate/draw_item.h
- lib/render/vp2RenderDelegate/material.cpp
- lib/render/vp2RenderDelegate/mesh.cpp
- lib/render/vp2RenderDelegate/mesh.h
- lib/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/render/vp2RenderDelegate/render_delegate.cpp
- lib/render/vp2RenderDelegate/render_delegate.h
- lib/render/vp2ShaderFragments/BasisCurvesCubicDomain_Cg.xml
- lib/render/vp2ShaderFragments/BasisCurvesCubicDomain_GLSL.xml
- lib/render/vp2ShaderFragments/BasisCurvesCubicDomain_HLSL.xml
- lib/render/vp2ShaderFragments/BasisCurvesCubicFallbackShader.xml
- lib/render/vp2ShaderFragments/BasisCurvesCubicHull.xml
- lib/render/vp2ShaderFragments/BasisCurvesLinearDomain_Cg.xml
- lib/render/vp2ShaderFragments/BasisCurvesLinearDomain_GLSL.xml
- lib/render/vp2ShaderFragments/BasisCurvesLinearDomain_HLSL.xml
- lib/render/vp2ShaderFragments/BasisCurvesLinearFallbackShader.xml
- lib/render/vp2ShaderFragments/BasisCurvesLinearHull.xml
- lib/render/vp2ShaderFragments/NwFaceCameraIfNAN.xml
- lib/render/vp2ShaderFragments/UsdPreviewSurface.xml
- lib/render/vp2ShaderFragments/UsdPrimvarReader_color.xml
- lib/render/vp2ShaderFragments/UsdPrimvarReader_vector.xml
- lib/render/vp2ShaderFragments/shaderFragments.cpp
This PR implements the VP2RenderDelegate support for USD curves, as well as some derisking work on tessellation shader approach for curve refinements.
* Refinement level 0 is fully implemented to get parity with USDView, which simply shows the curves as line list.
* Refinement level 1 is partially implemented as part of the work to derisk tessellation shader approach for curve refinement. For now it only interpolates widths and normals. The work is currently disabled until the new MRenderItem::setPrimitive() API is shipped.
* Refinement level 2 and 3 are not implemented, which I think is only about more complex algorithm than level 1 and I've already set up the code framework to host new algorithms.
The refactoring change to HdVP2Mesh and HdVP2DrawItem is necessary because the draw item …
> VP2RenderDelegate support for USD curves

- plugin/al/usdmayautils/AL/usdmaya/utils/MeshUtils.cpp
Previously the file import for AL_USDMaya would blindly create any float3/float4 primvar as a colour set. This would mean that any other vector based primvar _(e.g. tangents/binormals)_ would end up being imported as colours. 
This PR changes the exported colour set type to be Color3f/Color4f, and also checks the primvar role to see if the primvar is a Color type. If it is, it will be treated as a colour set.
> [al] import primvars as colour sets (#1029)

- CMakeLists.txt
- doc/build.md
The newly added import dialog functionality makes use of `QOverload` which was introduced in Qt 5.7, and `QSortFilterProxyModel::setRecursiveFilteringEnabled()` which was introduced in Qt 5.10. Some users may still be using VFX platform 2018 which specifies Qt 5.6.1 as the required version, so they may not be able to build the Qt-dependent features until they switch to VFX platform 2019+ which specifies Qt 5.12 instead.
This change adds CMake enforcement of Qt 5.10+ when building with Qt enabled, and adds a table of version numbers for the optional dependencies, of which Qt is currently the only one.
> identify Qt 5.12 as the minimum required version for Qt-dependent features

- plugin/adsk/scripts/mayaUsdTranslatorImport.mel
The import dialog UI is only available when compiling with the optional Qt features. So we need to protect the Import translator UI when this dialog/command is missing.
> MAYA-103070 - Minimal Import UI for PR112

- cmake/modules/FindUFE.cmake
Most of the other cmake vars also use an equivalent env var as a hint, but not the Maya devkit location.
> MAYA-103431 adding env var as a hint for the devkit location

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.h
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeSelection.cpp
**Compiler:** 
`XCode 11.3.1`
**Error:** 
```
format specifies type 'unsigned long long' but the argument has type 'int' [-Werror,-Wformat]
TF_DEBUG(ALUSDMAYA_SELECTION).Msg("ProxyShapeSelection::TransformReference::decRef %" PRIu64 " %" PRIu64 " %" PRIu64 "\n", m_selected, m_refCount, m_required);
.....
```
Hi @murphyeoin, 
I am trying to understand some of the logics in ProxyShape.h related to this issue:
So we have a bit field struct that is a size of 8bytes (16 bits * 4) 
```
// ref counting values
struct
{
uint64_t m_required:16; 
uint64_t m_selectedTemp:16;
uint64_t m_selected:16;
uint64_t m_refCount:16;
};
```
but then we have these getters that return them as 4 bytes.  Is there a reason for that? couldn't we return them as uint16_t.
```
uint32_t selected() const { return …
```
> Fix MacOSX build in strict mode:

- lib/CMakeLists.txt
touch fails when using DESTDIR install (non-existent target directory)
During our build process we do an internal staging install using `make DESTDIR=/path/to/staging install'. 
Unfortunately, the hard-coded touch command does not result in generated build files which can be redirected at 'make install' time. Using the CMake install() command creates all the proper boilerplate.
There were several other installations of empty `__init__.py` files in the same CMakeLists.txt file already using install().
> Use CMake install() instead of touch to install mayaUsd/__init__.py

- plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/testProxyShapeLiveSurface.py
I don't think anyone other than us is running this test, but this addresses an issue where we were seeing intermittent test failures. Execution of the test would sometimes barrel on through the assembly load and attempt to create new geometry using the proxy as a live surface before the geometry for the proxy was ready.
This adds a cmds.refresh() call immediately after creating the test window/viewport to ensure that the geometry that we're making live is present and will work as a live surface.
Note that this does **not** address #263. When the VP2.0 render delegate is enabled, the live surface functionality seems to be broken and this test fails.
> fix for Pixar testProxyShapeLiveSurface test

- cmake/CMakeLists_googletest_download.txt.in
- cmake/CMakeLists_googletest_src.txt.in
I also bumped the CMake Min version to 3.12.0 and removed CMAKE_MACOSX_RPATH flag as is no longer needed.
> - Enable C++11 for GoogleTest external project for sake of consistency with the project.

- lib/render/mayaToHydra/renderOverride.cpp
- lib/render/px_vp20/utils.cpp
- lib/render/px_vp20/utils.h
- lib/render/pxrUsdMayaGL/batchRenderer.cpp
This addresses an issue when running the [testProxyShapeSelectionPerformance](https://github.com/Autodesk/maya-usd/blob/dev/plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/testProxyShapeSelectionPerformance.py) test where only the first image would be drawn correctly and all images drawn after the first selection operation would be completely black.
This workaround was already being used during rendering, but this change applies it during selection as well.
> save and restore uniform buffer bindings during batch renderer selection

- cmake/defaults/CXXDefaults.cmake
- cmake/modules/FindUFE.cmake
This support will allow mayaUsd code to conditionally compile in UFE-dependent code according to the preview version of the UFE library.  UFE preview versions are identified with major version 0.  We intend that conditional compilation directives based on UFE_PREVIEW_VERSION_NUM be removed for the next Maya release, as they will have become obsolete, and since UFE_PREVIEW_VERSION_NUM would be no longer defined, would actually prevent code from being compiled.
> Added UFE_PREVIEW_VERSION_NUM pre-processor support.

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.cpp
Since the full pr/animationMissingAfterMayaFileSaveReopen was too controversial, breaking out some pieces. This piece has the part that everyone agreed was safe to merge in - approximate equality checks of new values against currently set values to determine whether or not new values need to be saved.  Plus a couple of changes that address what looked like small oversights.
(This change alone fixes the problem where we bring in a usd file with a sphere, turn on the Move To manipulator, and then, via python calls, select the sphere, set the sphere's rotateZ to 45 degrees, unselect the sphere, reselect the sphere and the rotation (and usd "over" that sets it) is inexplicably reset to 0,0,0.)
> A piece of PR183 - approximate equality checks

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/LayerManager.h
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/wrapLayerManager.cpp
Disable a couple warnings before including a couple boost headers.  Avoids "warning treated as errors" in a couple specific cases.
> MAYA-103572 Disable a couple warnings

- lib/nodes/proxyShapeBase.cpp
- lib/nodes/proxyShapeBase.h
- plugin/adsk/plugin/plugin.cpp
- plugin/adsk/scripts/CMakeLists.txt
- plugin/adsk/scripts/mayaUsdMenu.mel
- plugin/adsk/scripts/mayaUsd_createStagesFromExistingLayer.mel
A user currently can't create a USD stage using the UI. This UI will allow the user to create a stage using an existing USD layer.
In Maya's top level menu, under Create, a new entry 'Universal Scene Description (USD)' is underneath 'Scene Management' category.  Please have this in the What's New green highlight style.  On hover, the submenu appears with the following entry:
"Stage from Existing Layer..."
Please have this in the What's New green highlight style.   On click, the following file dialogue appears[...]
> MAYA-103409 Minimal Create USD Stage

- lib/fileio/jobs/jobArgs.h
Adding .usdz extension to the list of formats that can be read
> MAYA-103651 Enable import of .usdz

- plugin/adsk/plugin/CMakeLists.txt
- plugin/adsk/plugin/exportTranslator.cpp
- plugin/adsk/plugin/exportTranslator.h
- plugin/adsk/plugin/plugin.cpp
- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
Adding a new Export Translator for the MayaUSD plugin.  Contains a minimal set of export options plus the UI to set them.  For the most part this is a direct copy of the Pixar options with only minor adjustments to how they show up in the export options window, which was easy enough to do since we have based the current read/write jobs in the core library on the Pixar plugin.
> MAYA-102918 Adding a basic Export Translator to the MayaUSD plugin

- plugin/adsk/scripts/mayaUsdMenu.mel
- plugin/adsk/scripts/mayaUsd_createStagesFromExistingLayer.mel
Adding optionVars to store Create USD Stage options
Adding a proper Option Box menu item.
> MAYA-103673 update Create USD Stage menu

- lib/render/mayaToHydra/plugin.cpp
- lib/render/mayaToHydra/renderGlobals.cpp
- lib/render/mayaToHydra/renderGlobals.h
- lib/render/mayaToHydra/tokens.h
- lib/render/mayaToHydra/utils.cpp
- lib/render/mayaToHydra/utils.h
- lib/render/mayaToHydra/viewCommand.cpp
Initialization of the Hydra delegates is a bit awkward and can ultimately lead to invalid entries in the menu. Selecting an -invalid- delegate can wind up crashing depending on what & why they failed.
> Fix up mtoh initialization to not create entries for invalid delagates.

- lib/render/mayaToHydra/renderGlobals.cpp
- lib/render/mayaToHydra/utils.cpp
Requires:
https://github.com/PixarAnimationStudios/USD/pull/1122
Likely will conflict with: https://github.com/Autodesk/maya-usd/pull/292, but proof of concept that support outside usdview is trivial / worth it.
> [hdMaya] Build menu UI from TfEnum

- plugin/al/plugin/AL_USDMayaTestPlugin/CMakeLists.txt
- plugin/al/plugin/AL_USDMayaTestPlugin/py/CMakeLists.txt
- plugin/al/translators/pxrUsdTranslators/tests/CMakeLists.txt
- plugin/al/translators/tests/CMakeLists.txt
- test/lib/usd/schemas/CMakeLists.txt
Added missing paths to `${CMAKE_INSTALL_PREFIX}/lib/usd` and `${CMAKE_INSTALL_PREFIX}/plugin/al/lib/usd` in PXR_PLUGINPATH_NAME which caused some of the unit tests to fail:
```
5 - TestUSDMayaPython (Failed)
8 - TestAdditionalTranslators (Failed)
9 - TestPxrUsdTranslators (Child aborted)
```
These test failures were not visible if the `MAYA_MODULE_PATH` was set to `mayaUSD.mod` location.
> Add missing paths in "PXR_PLUGINPATH_NAME"

- plugin/adsk/plugin/exportTranslator.cpp
Clear frameSamples set so that we don't add in the default value when the flag is used.
> MAYA-103736 Clear frameSamples set

- lib/nodes/proxyShapeBase.cpp
- lib/nodes/proxyShapeBase.h
- lib/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- plugin/pxr/maya/lib/usdMaya/proxyShape.cpp
I wanted to float this change as a possible solution to #262. As we're testing the VP2.0 render delegate internally at Pixar, we're trying to ensure that the selection behavior of our proxy shapes is consistent when switching back and forth with our current batch renderer viewport integration. Our pxrUsdProxyShape node (and pxrUsdReferenceAssembly nodes which are the primary way our proxies are introduced) aren't really designed to support subpatch selection, so workflows aiming to expose more of the guts of a USD stage should favor one of the other proxy shape types.
> add a way for pxrUsdProxyShape to disable subpath selection with the VP2.0 render delegate

- lib/render/mayaToHydra/utils.cpp
- lib/render/mayaToHydra/utils.h
wasn't used anywhere - believe it was a holdover when we had a single maya renderOverride, and an option to switch between the various hydra renderDelegates; now that there is a 1-to-1 relationship between renderOverrides and renderDelegates, no need for this
Putting do-not-merge-yet on this, because it will create merge conflicts with https://github.com/Autodesk/maya-usd/pull/292, and I'd like to get that merged first.  I'll resolve conflicts here after that is merged - just wanted to create this now, as a bookmark for myself.
> [hdMaya] remove MtohGetDefaultRenderer

- doc/build.md
- lib/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/usd/hdMaya/adapters/proxyAdapter.cpp
With `USD_IMAGING_API_VERSION` 11, `UsdImagingDelegate::PopulateSelection()` expects to be given a USD path instead of a Hydra "index path". This helps to avoid some confusion about
the types of paths being passed around.
> adapt to UsdImagingDelegate::PopulateSelection param change

- plugin/pxr/maya/plugin/pxrUsdPreviewSurface/CMakeLists.txt
Hi @mattyjams,
Can you please confirm if `${TEST_INSTALL_PREFIX}/maya/plugin/pxrUsdPreviewSurface/resources` entry is needed ?
The separator for env variables on Windows is ";"  and It doesn't seem that testwrapper.py is currently supporting that?
I removed  `${TEST_INSTALL_PREFIX}/maya/plugin/pxrUsdPreviewSurface/resources` all together and the test passes on Linux.
> Fix testPxrUsdPreviewSurfaceExport failure on Windows

- lib/CMakeLists.txt
- lib/usd/translators/CMakeLists.txt
- plugin/al/CMakeLists.txt
- plugin/al/lib/AL_USDMaya/CMakeLists.txt
- plugin/al/schemas/AL/usd/schemas/maya/CMakeLists.txt
- plugin/al/schemas/AL/usd/schemas/mayatest/CMakeLists.txt
- plugin/al/translators/CMakeLists.txt
- plugin/al/translators/pxrUsdTranslators/CMakeLists.txt
- plugin/al/usdtransaction/CMakeLists.txt
- plugin/pxr/cmake/macros/Public.cmake
Any install(CODE ...) commands operating on CMAKE_INSTALL_PREFIX paths
break the CMake DESTDIR mechanism, and actually cause files to be
immediately created in the final install directory.
This makes it impossible to use a staging dir to receive an install
image via 'make DESTDIR=/path/to/staging/dir install' when using
packaging systems like RPM or rez
> Fixes for staging dir builds

- lib/render/vp2RenderDelegate/render_delegate.cpp
If the fallback shader map is not empty, clone any existing shader instance in the map instead of acquiring via `MShaderManager::getFragmentShader()`, which creates new shader fragment graph for each shader instance and causes expensive shader compilation and rebinding.
This change will speed up the first frame loading time considerably.
> Clone from existing shader instance to avoid extra cost.

- cmake/CMakeLists_googletest_download.txt.in
- cmake/Googletest.cmake
FindGTest.cmake is buggy when looking for only debug config (it expects both).
So when in debug we set the required gtest vars to the debug libs it would have found in the call to find_package(GTest). Then we find again. This will then properly set all the vars and import targets for just debug.
> Fix for find_package(GTest) when compiling in Debug

- lib/ufe/StagesSubject.cpp
- lib/ufe/UsdAttribute.cpp
- lib/ufe/UsdContextOps.cpp
- lib/ufe/UsdObject3d.cpp
- lib/ufe/UsdObject3d.h
- lib/ufe/UsdObject3dHandler.cpp
- test/lib/ufe/CMakeLists.txt
- test/lib/ufe/testObject3d.py
- test/lib/ufe/testRotateCmd.py
- test/lib/ufe/testScaleCmd.py
- test/lib/ufe/testTRSBase.py
- test/lib/ufe/testTransform3dTranslate.py
As a user, I would like to see the prim greyed out in the Outliner
when prim is set to invisible.
* Send new Ufe::VisibilityChanged notif when USD visibility attribute is modified.
* Added new Ufe:Object3d methods in UsdObject3d (protected by new UFE_PREVIEW_VERSION_NUM if test.
* Only create and return valid Ufe::Object3d interface for imageable prims.
* Re-enabled all UFE v2 tests. Gave them "ufe" test label for easy filtering. Had to fix some of the test as changes were made since they've been disabled.
* Added visibility test for Object3d. Only run for UFE >= v0.2.10.
> MAYA-103655 Object3d visibility

- lib/ufe/UsdTransform3d.cpp
When retrieving transform 3d data, we were not providing any time and relied on the default. This almost never is a good idea (as stated in [here](http://graphics.pixar.com/usd/docs/USD-Glossary.html#USDGlossary-ValueResolution), but as well when it comes to aligning manipulation behavior with the viewport display which doesn't use default time).
We will switch to leverage proxy shape time via already existing utility. This utility was created for the bounding box interface, which already respects current proxy time.
This change was as well proposed as part of bigger #299. This implementation leverages already existing utilities to retrieve proxy shape time.
> Support animated transform ops

- plugin/al/lib/AL_USDMaya/AL/usdmaya/Version.h
- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TransformTranslator.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.cpp
Removed the names from the end of the transform op attributes when exporting to usd from the AL plugin. 
Change the geom xform op names from, to.... 
* ```float3 xformOp:translate:translate ```` ---> ```double3 xformOp:translate``` (note type change!)
* ```float3 xformOp:scale:scale ```` ---> ```float3 xformOp:scale```
* ```float3 xformOp:rotate###:rotate ```` ---> ```float3 xformOp:rotate###```
* ```xformOp:translate:rotatePivotINV```` ---> ```!invert!xformOp:translate:rotatePivot``` 
* ```xformOp:translate:scalePivotINV```` ---> ```!invert!xformOp:translate:scalePivot``` 
This now uses the correct way to initialise inverse ops, and the TRS op names now match those found in the common transform API.
> [AL] Ensure UsdGeomXformOp names match Common API

- README.md
- doc/codingGuidelines.md
Add document to outline c++ coding guidelines for contributions to the maya-usd project. 
Clang-format, CMake and Python guidelines will follow.
> Add coding guidelines for maya-usd repository

- plugin/pxr/doc/README.md
The user-facing documentation for Pixar's Maya USD Plugins currently lives here:
https://graphics.pixar.com/usd/docs/Maya-USD-Plugins.html
This change adds a version of that page, cleaned up and translated to Markdown so that it can be added to the maya-usd repo. Since Pixar's Maya USD plugins are no longer delivered as part of the core USD distribution, the documentation is scheduled to be removed from the Pixar site in the near future. Adding this Markdown version to maya-usd preserves the information it provided in case anyone still finds it useful.
> add Markdown version of Pixar Maya USD Plugin Doc

- lib/ufe/Global.cpp
- test/lib/ufe/testDeleteCmd.py
This branch adds in support for UFE path strings in the mayaUsd plugin.  Most of the heavy lifting for path strings is done in the UFE library itself; UFE clients simply have to register their path component separator to the UFE library.  From the UFE Doxygen documentation:
In UFE, \ref Ufe::Path "paths" are full-fledged objects that are accessed and used through their object interfaces, in Python and C++.  To support scripting environments where such Python or C++ access is inconvenient or simply not possible, UFE provides an optional \ref Ufe::PathString "path string" service, which converts a parsable UFE path string to a UFE path.  A UFE path string has its segments separated by a path separator string, which by default is the single-character comma string ','.  In this way, UFE paths …
> Tremblp/maya 103295/ufe path string usd

- lib/ufe/UsdAttribute.cpp
- lib/ufe/UsdAttribute.h
Modified all the attribute Get calls to use current time.
If attribute has no time samples, the Get will automatically fallback to default time.
MAYA-103421 - UFE selecting certain USD objects will throw errors on the outliner and script editor
MAYA-103266 - USD Materials Erroring with USD attribute does not match created attribute class type
> MAYA-103421 - UFE selecting certain USD objects will throw errors

- plugin/adsk/plugin/importTranslator.cpp
- plugin/pxr/maya/lib/usdMaya/importTranslator.cpp
Add .usdz extension to the identifyFile function, which is used to determine if it is a supported file when doing a drag'n drop onto Maya.
> MAYA-104134 Add .usdz extension to the identifyFile function

- lib/usd/hdMaya/adapters/materialAdapter.cpp
- lib/usd/hdMaya/adapters/proxyAdapter.cpp
- lib/usd/hdMaya/delegates/delegate.h
- lib/usd/hdMaya/delegates/proxyDelegate.cpp
- lib/usd/hdMaya/delegates/proxyDelegate.h
- lib/usd/schemas/wrapALMayaReference.cpp
- lib/usd/translators/CMakeLists.txt
- lib/usd/translators/cameraWriter.h
- lib/usd/translators/fileTextureWriter.h
- lib/usd/translators/instancerWriter.h
- lib/usd/translators/jointWriter.h
- lib/usd/translators/locatorWriter.h
- lib/usd/translators/mayaReferenceUpdater.h
- lib/usd/translators/meshWriter.h
- lib/usd/translators/meshWriter_Primvars.cpp
- lib/usd/translators/meshWriter_Skin.cpp
- lib/usd/translators/meshWriter_Subdiv.cpp
- lib/usd/translators/nurbsCurveWriter.h
- lib/usd/translators/nurbsSurfaceWriter.h
- lib/usd/translators/particleWriter.h
- lib/usd/translators/plugin.cpp
- lib/usd/translators/strokeWriter.h
- plugin/adsk/plugin/plugin.cpp
Hey guys,
This PR fixes conditional orders in lib/usd and plugin/adsk.  
Only 6 files :)
> Address remaining feedback in lib/usd and plugin/adsk

- lib/mayaUsd/ufe/CMakeLists.txt
- lib/mayaUsd/ufe/__init__.py
- lib/mayaUsd/ufe/module.cpp
- lib/mayaUsd/ufe/moduleDeps.cpp
- lib/mayaUsd/ufe/wrapUtils.cpp
- test/lib/ufe/CMakeLists.txt
- test/lib/ufe/testUfePythonImport.py
This change is similar to #207 but applied to the ufe module. Instead of building the module as `mayaUsd/ufe.so` directly, we instead build it as `mayaUsd/ufe/_ufe.so` and bring its contents into the ufe namespace with an `__init__.py` that uses `Tf.PrepareModule()`.
Also similarly to #207, this adds a `TfScriptModuleLoader` registry function that ensures that when the ufe library is loaded as a result of importing its Python module, the core USD libraries that it depends on also get loaded.
Without the changes in this PR, the test that was added fails with an error that looks like this:
```
======================================================================
ERROR: testImportModule (testUfePythonImport.UfePythonImportTestCase) …
```
> build ufe Python bindings module consistently with other modules

- lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.h
- lib/mayaUsd/render/pxrUsdMayaGL/hdImagingShapeUI.h
- lib/mayaUsd/render/pxrUsdMayaGL/instancerShapeAdapter.h
- lib/mayaUsd/render/pxrUsdMayaGL/proxyShapeUI.h
- lib/mayaUsd/render/pxrUsdMayaGL/shapeAdapter.h
- lib/mayaUsd/render/pxrUsdMayaGL/usdProxyShapeAdapter.h
Following the merge of PRs #388 through #392, the header reorganization created some new sites where `M3dView.h` was being included earlier than `sdf/types.h`.
This change applies an existing pattern of including `sdf/types.h` early to work around this issue and fix compiling for Maya 2019 (and earlier).
> add pre-emptive includes of sdf/types.h before M3dView.h for Maya 2019

- plugin/adsk/scripts/CMakeLists.txt
- plugin/adsk/scripts/mayaUsdMenu.mel
- plugin/adsk/scripts/mayaUsd_createStageFromFile.mel
* Renamed menu/options/etc according to request from design.
* Renamed everything else (runtimecommands/procs/file/etc) to be consistent.
> MAYA-104219 - Rename 'Create Stage from Existing Layer'

- lib/mayaUsd/render/pxrUsdMayaGL/hdRenderer.h
Sorry all, but I missed one spot in #414 and only just now found it as I'm trying to reconcile the recent merges with our internal plugins.
> add one more pre-emptive include of sdf/types.h pxrUsdMayaGL/hdRenderer.h

- lib/mayaUsd/render/pxrUsdMayaGL/renderParams.h
This field was previously used for supporting custom intersection testing for live surface-type workflows, but it is no longer used or needed.
(Internal change: 2056384)
> [pxrUsdMayaGL] remove unused customBucketName from PxrMayaHdRenderParams

- test/lib/ufe/testMoveCmd.py
- test/lib/ufe/testRotateCmd.py
- test/lib/ufe/testScaleCmd.py
The workaround added to testScaleCmd.py and testRotateCmd.py
cannot work in batch mode, because manipulators can only be
created in GUI mode. Added further comments, and marked testMoveUsd in
testMoveCmd.py as an expected failure, due to an upcoming fix in the
underlying Maya code.
> MAYA-103876 - Update expected failing tests

- lib/mayaUsd/render/vp2RenderDelegate/CMakeLists.txt
- lib/mayaUsd/render/vp2RenderDelegate/analyticMayaUsdPerformance.py
This script measures time taken for key operations in Maya using Vp2RenderDelegate for the purpose of automated performance testing.
The script is measuring first frame time, consolidation time, tumble performance, playback performance, selection performance and file new performance.
An example of calling the script in Maya:
```
import mayaUsd.lib.analyticMayaUsdPerformance as analyticMayaUsdPerformance
cameraTranslate = [-13000, -2000, 6000]
cameraRotate = [60, 0, -90]
print( analyticMayaUsdPerformance.analyticMayaUsdPerformance().run('myFile.usd', cameraTranslate, cameraRotate, 1, 20) )
```
The script returns JSON data.  An example output looks like:
```
{
"select_all":{
"time":0.5999999999999943,
"memory":[
130956.921875,
2811.640625
]
},
"selected":{
"consolidate":{ …
```
> Add a script to measure key performance information for MayaUsd Vp2RenderDelegate.

- lib/mayaUsd/nodes/proxyShapePlugin.cpp
- lib/mayaUsd/render/vp2RenderDelegate/render_delegate.cpp
- lib/mayaUsd/render/vp2ShaderFragments/shaderFragments.cpp
- lib/mayaUsd/render/vp2ShaderFragments/shaderFragments.h
The failure to create shader instance when running command-line render was a regression caused by #130 and a block for us to deploy automated render tests.
When running command-line render, plugin loading happens before VP2 is initialized. Because fragment registration relies on the access to the fragment manager which is created during VP2 initialization, we will have to delay the fragment registration until when it is needed instead of doing it at plugin loading.
PS: The last time I tested #130 and the command-line render worked because there was some other plugin forcing VP2 initialization to be done earlier. We don't want to force initialization of VP2 during plugin load, for compatibility with headless config used by other partners.
> Failure to create shader instance when running command-line render

- cmake/defaults/msvcdefaults.cmake
- doc/build.md
- lib/mayaUsd/CMakeLists.txt
- lib/mayaUsd/render/mayaToHydra/renderOverride.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/hdRenderer.cpp
- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/usd/hdMaya/adapters/materialAdapter.cpp
- lib/usd/hdMaya/adapters/materialNetworkConverter.cpp
- lib/usd/hdMaya/adapters/materialNetworkConverter.h
- lib/usd/hdMaya/adapters/proxyAdapter.cpp
- lib/usd/hdMaya/adapters/proxyAdapter.h
- lib/usd/hdMaya/delegates/sceneDelegate.cpp
- lib/usd/hdMaya/delegates/sceneDelegate.h
- plugin/al/CMakeLists.txt
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Engine.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeUI.cpp
- plugin/al/lib/AL_USDMaya/CMakeLists.txt
- plugin/al/schemas/AL/usd/schemas/maya/tests/CMakeLists.txt
- plugin/al/usdmayautils/AL/usdmaya/utils/CMakeLists.txt
In particular, this PR absorbs the following core USD commits:
https://github.com/PixarAnimationStudios/USD/commit/82e343c42b730a3674a766aab6be1b4f1c0ca9ef
https://github.com/PixarAnimationStudios/USD/commit/310d9fbc2786b9ec5a3278c033b16ce713b92f49
https://github.com/PixarAnimationStudios/USD/commit/b0fc236ac695b6c66de50897356209ed7c21865a
https://github.com/PixarAnimationStudios/USD/commit/eff8cb850e44aab0d6afa89c80706e88984fefe6
I updated build.md to reflect that the most recent core USD commit supported by maya-usd is the one currently on the tip of the core USD dev branch (https://github.com/PixarAnimationStudios/USD/commit/8dcbcc9b46ce8f04d3ae330772b8936bef5cc9dd).
Note that #395 is also required if you want to build the maya-usd dev branch against the core USD dev branch.
> apply updates to comply with recent core USD dev branch commits

- cmake/defaults/CXXDefaults.cmake
- cmake/defaults/gccclangshareddefaults.cmake
- cmake/modules/FindUSD.cmake
Re-opening this from the original #395 pull request...
Conforming to VFX Reference Platform CY2018+ and following suit from core USD, this change sets the maya-usd project to use the C++14 standard if we're either building for Maya 2019 or later, or if we're building against USD 20.05 or later.
Core USD moved to C++14 with release 20.05 in this commit:
https://github.com/PixarAnimationStudios/USD/commit/afc0d5e3d45eeaf6579b9699250da37cd9149c6f
> upgrade maya-usd project to the C++14 standard

- lib/mayaUsd/listeners/notice.cpp
- plugin/adsk/plugin/plugin.cpp
This is a small change that reuses existing code that will reset the stage cache on New or Open, fixing some logged issues.  It is not a complete fix for how we deal with the cache though, e.g. deleting the proxy shape and re-importing the same USD file will still show you the cached version which is probably unexpected.  The listener here is only called on File -> New and Open.
We do plan on looking at how the Animal Logic plugin deals with this kind of thing and will most likely refactor some of that into the core lib to be shared by all plugins, but for right now this is an easy change that should help in a couple obvious workflows.
> MAYA-101454 Clear stage cach on file new/open.

- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
This commit is to fix the following compilation error with gcc 9.1:
‘void* memcpy(void*, const void*, size_t)’ copying an object
of type ‘class pxrInternal_v0_20__pxrReserved__::GfVec4f’ with
‘private’ member ‘pxrInternal_v0_20__pxrReserved__::GfVec4f::_data’
from an array of ‘const class pxrInternal_v0_20__pxrReserved__::GfVec3f’;
use assignment or copy-initialization instead [-Werror=class-memaccess]
> Fix compilation error on gcc 9.1

- CMakeLists.txt
- plugin/pxr/CMakeLists.txt
- plugin/pxr/cmake/macros/Private.cmake
- plugin/pxr/cmake/macros/Public.cmake
Following PR #412, plugin/pxr is now getting the compiler configuration by using mayaUsd_compile_config.
I didn't delete `defaults` sub-directory and left it there by itself for now.
> plugin/pxr is now adopting mayaUsd_compile_config routine

- lib/usd/hdMaya/adapters/lightAdapter.cpp
- lib/usd/hdMaya/utils.h
Two recent post-20.05 commits in core USD made some Hdx pointer types use std::shared_ptr instead of boost::shared_ptr, and a third commit moved some Hd enum values from hd/enums.h to hd/types.h.
The changes here update the maya-usd code to account for these core USD commits.
> updates from Hdx de-boostification and Hd reorganization

- lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.h
Native Viewport 2.0 selection is supported in the USD proxy shape for Maya 2018 Update 4 and later, so there should no longer be any need to set MAYA_VP2_USE_VP1_SELECTION=1. With the legacy viewport well down the road of deprecation, support for it in the batch renderer is being steadily removed as well.
> remove Pixar batch renderer's support of MAYA_VP2_USE_VP1_SELECTION env var

- lib/mayaUsd/render/pxrUsdMayaGL/instancerImager.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/instancerImager.h
- lib/mayaUsd/render/pxrUsdMayaGL/instancerShapeAdapter.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/instancerShapeAdapter.h
- lib/mayaUsd/render/pxrUsdMayaGL/proxyDrawOverride.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/proxyShapeUI.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/shapeAdapter.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/shapeAdapter.h
- lib/mayaUsd/render/pxrUsdMayaGL/usdProxyShapeAdapter.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/usdProxyShapeAdapter.h
- plugin/pxr/maya/lib/usdMaya/instancerShapeAdapterWithSceneAssembly.cpp
- plugin/pxr/maya/lib/usdMaya/instancerShapeAdapterWithSceneAssembly.h
- plugin/pxr/maya/lib/usdMaya/referenceAssembly.cpp
Following on from #450, we want to start being more explicit about the division between the legacy viewport and Viewport 2.0 so that it's easier to tear out the legacy stuff a little bit at a time.
There might also be a slight performance improvement here with `PxrMayaHdShapeAdapter::IsViewport2()` no longer dispatching virtually.
> remove virtual dispatch for PxrMayaHdShapeAdapter::IsViewport2()

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.h
If you have a transform that is a +270 rotation around the x axis, If this gets set as a quat the euler equivalents would be a -90 degree rotation in x. Previously the code would test to see if the rotations had changed by comparing euler values. This was leading to some pointless rotations being written as overs into the usd stage. By comparing the values as quats instead, the equivalence check now works correctly, and the pointless overs no longer get generated.
> [al] When updating a transform via a quat, test for equivalence in quat space

- cmake/compiler_config.cmake
- lib/mayaUsd/CMakeLists.txt
Full compiler support for the Standard C++exception handling model that safely unwinds stack objects requires /EHsc (recommended)
> Enable exception handling for VS compiler

- lib/mayaUsd/render/mayaToHydra/renderGlobals.cpp
- lib/mayaUsd/render/mayaToHydra/renderGlobals.h
- lib/mayaUsd/render/mayaToHydra/renderOverride.cpp
- lib/mayaUsd/render/mayaToHydra/utils.cpp
Outline hi-lighting was added in 22.05, and color-quantization can make things extremely slow.
> Add support for outline selection hilighting and disabling color-quantization

- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorBase.cpp
Previously the AL translator plugin code would first check to see if there was a C++ translator, and would then later check for a python translator. In order to allow the python translators to override the C++ translators, the order has been reversed.
> [al] flip translator order

- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/nodes/proxyShapeBase.h
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
The cached usdStage in the proxyRenderDelegate can change. If that happens delete everything cached in the ProxyRenderDelegate and clear the subscene container so VP2 draws correctly.
> MAYA-104544 Handle changing the USD stage

- lib/usd/ui/USDImportDialogCmd.cpp
- lib/usd/ui/USDImportDialogCmd.h
- plugin/adsk/scripts/CMakeLists.txt
- plugin/adsk/scripts/mayaUsd_createStageFromAsset.mel
Current code assumes an on-disk 'usd' file, which blocks possible ArAssetResolver from running.
Adds another `mayaUsd_createStageFromAsset` mel procedure to open the UI and apply settings to a proxy.
> Teach the import cmd ui how to import usd-assets and apply to proxy-shapes

- lib/mayaUsd/ufe/StagesSubject.cpp
If the **xformOpOrder** is swapped out entirely, UFE should be notified.
> Watch for full xformOpOrder changes.

- lib/mayaUsd/render/mayaToHydra/renderOverride.cpp
Following up on #469, the questionable `HdxTaskController::SetColorizeQuantizationEnabled()` was actually removed fairly soon after the release of core USD 20.05 in this commit:
https://github.com/PixarAnimationStudios/USD/commit/584c27d495047aa9a7231df64eec9e22396e5651
The change here ensures we stop using it for USD versions after 20.05.
> remove use of HdxTaskController::SetColorizeQuantizationEnabled() after USD 20.05

- lib/mayaUsd/listeners/proxyShapeNotice.cpp
- lib/mayaUsd/listeners/proxyShapeNotice.h
- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/ufe/StagesSubject.cpp
- lib/mayaUsd/ufe/StagesSubject.h
- lib/mayaUsd/ufe/UsdStageMap.cpp
- lib/mayaUsd/ufe/UsdStageMap.h
- lib/usd/hdMaya/adapters/proxyAdapter.cpp
- lib/usd/hdMaya/adapters/proxyAdapter.h
- plugin/adsk/scripts/CMakeLists.txt
- plugin/adsk/scripts/mayaUsdMenu.mel
- plugin/adsk/scripts/mayaUsd_createStageWithNewLayer.py
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
- test/lib/ufe/testObject3d.py
- test/lib/ufe/testTransform3dTranslate.py
* New USD notice type for stage invalidate. Send this notice when certain attributes (like filepath) are changed. From the StagesSubject receiver of this notice we also send the new Ufe::ObjectInvalidate() notification.
* When proxy shape compute is called if no filepath was attached, we create an in memory stage.
* Added dirty state to UsdStageMap. When dirty it will rebuild when a new request for stage info is made.
* Cleanup: renamed "UsdMayaProxyStageSetNotice" -> "MayaUsdProxyStageSetNotice".
* Added new menu item "Stage with New Layer".
> MAYA-104213 - add a new USD stage to an empty scene

- lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.h
This was previously used only by a Pixar-internal plugin, but the equivalent functionality is available using `HdSceneDelegate::GetScenePrimPath()`.
(Internal change: 2068351)
> remove unused PxrUsdMayaGLBatchRenderer::GetInstancerIndexForHit()

- test/lib/ufe/CMakeLists.txt
- test/lib/ufe/testComboCmd.py
- test/lib/ufe/testTRSBase.py
This test performs a sequence of move, rotate, and scale operations, and verifies that the position, rotation, and scale of the object has been modified according to how such operations should accumulate.
> MAYA-104273 - Add cmd combo test

- lib/usd/hdMaya/adapters/proxyAdapter.cpp
There's an issue with the following, when a viewport triggers a display before the second command is run:
```
string $proxy = `createNode mayaUsdProxyShape`;
setAttr ($proxy + ".filePath") <path>
```
> Fix leak of UsdImagingDelegate

- lib/mayaUsd/ufe/UsdContextOps.cpp
Added "Add Reference" and "Clear All References" menu items to the Outliner popup menu for UFE objects.  This is just a quick initial implementation, a separate Issue will be logged by Design to cover a more complete/advanced workflow.
> MAYA-104401 Add/Clear Reference menu op's

- plugin/al/docs/proxyShape.md
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.h
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/proxy/ProxyShapeVariantFallbacks.cpp
- plugin/al/lib/AL_USDMaya/CMakeLists.txt
- plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_VariantFallbacks.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/CMakeLists.txt
- plugin/al/plugin/AL_USDMayaTestPlugin/py/testProxyShape.py
- plugin/al/plugin/AL_USDMayaTestPlugin/test_data/variant_fallbacks.usda
Added '.variantFallbacks' attribute to store custom fallbacksThis PR is to add support of storing custom variant fallbacks inot ".variantFallbacks" ProxyShape node attribute.
Department might have different variant fallbacks request for different department / workflow apps, they can add overrides of global variant fallbacks before loading a stage then restore the global fallbacks after stage loaded, but previously there was no way to store this information, thus if user saves the Maya scene and reopen the scene file without using previous app, the variant fallbacks would be lost.
The proposed solution is to:
Before stage is loaded, check if the attribute ".variantFallbacks" has stored settings, use that as the fallbacks if foud;
If stageCacheId is provided, check if the session layer has …
> [al] Added '.variantFallbacks' attribute

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Scope.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Scope.h
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Transform.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Transform.h
Fix for including purposes during bounding box computations of USD data represented as Transform/Scope nodes. Viewport framing should work again.
Transform now delegates bounding box computations to parent Scope class
Scope now checks proxy shapes purpose draw state attributes before computing bounding boxes
Promoted Scope::boundingBox() virtual method from private to public.
> [al] Viewport Framing Fix

- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
**Issue**
Described in #430 
**Cause**
The crash occurred because it tried to compute smooth normals
from an empty point array due to missing support of USDSkel.
**Solution**
The change will fix the crash itself, and the real support
for USDSkel will be implemented at some other time.
> Fixing the crash when loading USDSkel

- cmake/utils.cmake
- test/lib/ufe/CMakeLists.txt
Rewrote mayaUsd_copyDirectory routine to allow more control over copying dir/files.
> Improved mayaUsd_copyDirectory routine to allow more control over copying dir/files.

- cmake/test.cmake
- test/lib/ufe/CMakeLists.txt
Added a new flag to allow overriding `WORKING_DIRECTORY`. If this flag is not set, ${CMAKE_CURRENT_SOURCE_DIR} is used hence the default behavior. 
UFE tests are supposed to run from build directory. We already copy all the python tests and resource to build directory and therefore WORKING_DIRECTORY needs to be set to ${CMAKE_CURRENT_BINARY_DIR}
> Add override flag for setting WORKING_DIRECTORY

- plugin/al/docs/layers.md
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/py/testProxyShape.py
Summary
This change allows ProxyShape to correctly load an anonymous root layer if the file path is set to an anonymous layer id. The anonymous root layer is serialised by the layer manager.
Note on file path
Note that the filePath on the ProxyShape is subject to change when an anonymous layer is used. This is necessary because an anonymous layer cannot be re-created with the same exact anon identitifier. This prevents the ProxyShape's file path from deviating from the layer manager serialisation records, and by doing so guarantees fetching the right layer when the Maya scene is reloaded.
Tests
A couple of Python tests are provided to verify this feature.
> [al] Handle anonymous layer in ProxyShape

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
**Problem**
Selection highlight will disappear when switching variant
**Cause**
When switching variant, a new Rprim will be created to replace
the original one, but the selection state of the new Rprim is
not set.
> Selection highlight disappears when switching variant

- lib/mayaUsd/fileio/jobs/readJob.cpp
- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/nodes/stageData.h
- lib/mayaUsd/nodes/stageNode.cpp
- lib/mayaUsd/python/wrapStageCache.cpp
- lib/mayaUsd/utils/stageCache.cpp
- lib/mayaUsd/utils/stageCache.h
- plugin/pxr/maya/lib/usdMaya/referenceAssembly.cpp
- plugin/pxr/maya/lib/usdMaya/translatorModelAssembly.cpp
- test/lib/testMayaUsdPythonImport.py
Rename forcePopulate to loadAll to match the enum name. Remove the default parameter value for loadAll so future callers have to make a choice, they will be more likely to choose correctly.
The stage cache does know about different session layers and so it won't hit the cache if the session layers don't match. The interesting code is at https://github.com/PixarAnimationStudios/USD/blob/master/pxr/usd/usd/stage.cpp#L975.
There you can see the call to the cache to FindOneMatching takes all the arguments except for the InitialLoadSet.
> Use separate UsdStageCache's for stages that loadAll or loadNone. 

- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/nodes/proxyShapeBase.h
- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
Trigger enough updates so that we can show/hide items whose visibility changes.
There is a big comment in ProxyRenderDelegate::_UpdateRenderTags() which explains the challenges and the approach taken.
https://github.com/Autodesk/maya-usd/issues/285
> Set the render tags on our dummy render task correctly.

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
The change will enable consolidation for instanced render items. It will take advantage of the MDI consolidation which is only available on OpenGL Core Profile mode in Maya.
> Enable consolidation for instanced render items

- lib/mayaUsd/fileio/translators/translatorMesh.cpp
- lib/mayaUsd/fileio/utils/CMakeLists.txt
- lib/mayaUsd/fileio/utils/meshReadUtils.cpp
- lib/mayaUsd/fileio/utils/meshReadUtils.h
- lib/mayaUsd/python/CMakeLists.txt
- lib/mayaUsd/python/module.cpp
- lib/mayaUsd/python/wrapMeshUtil.cpp
- lib/mayaUsd/python/wrapMeshWriteUtils.cpp
- lib/usd/translators/meshReader.cpp
- lib/usd/translators/meshWriter.cpp
- Rename meshUtil(`*.h,*.cpp`) to meshReadUtils(`*.h,*.cpp`).
- Follow coding guideline for function name ( lowerCamelCase ).
> PR II: Pixar Mesh write translator/utilities refactoring

- lib/mayaUsd/fileio/utils/meshReadUtils.cpp
- lib/mayaUsd/fileio/utils/meshWriteUtils.cpp
- lib/mayaUsd/fileio/utils/meshWriteUtils.h
- lib/mayaUsd/fileio/utils/writeUtil.cpp
- lib/usd/translators/meshWriter.cpp
Created 3 utility functions for writing Maya mesh data to USD:
- vertex positions
- face/vertex indices
- invisible faces
Removed the "TODO: Use memcpy()" and used memcpy to copy the data directly.
> PART V: Pixar Mesh write translator/utilities refactoring 

- lib/mayaUsd/commands/baseExportCommand.cpp
- lib/mayaUsd/commands/baseExportCommand.h
This is a small follow-up fix to #398 and accounts for the case when PXR_USE_NAMESPACES is disabled (which is how Pixar currently builds internally) or when USD is built with anything other than "pxr" as the namespace.
> remove hard-coded "pxr" namespace in favor of PXR_NS in baseExportCommand

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
When a prim switches modeling variant, the children of the prim can probably be changed to a different set of prims, with different hierarchy and paths. Thus the UFE selection observer will need to also listen to `Ufe::ObjectAdd` notification for Hydra selection update.
The other part of the commit will update the Hydra selection with respect to the UFE global selection  when creating a new stage or a new prim.
> MAYA-103697 selection update on new objects

- doc/build.md
- lib/mayaUsd/render/mayaToHydra/renderOverride.cpp
- lib/mayaUsd/render/mayaToHydra/renderOverride.h
- lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.h
- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Engine.cpp
This PR includes and replaces PRs #530 and #531.
> Updates to support core USD imaging-related changes in latest dev branch

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- lib/mayaUsd/render/vp2RenderDelegate/material.h
- lib/mayaUsd/render/vp2ShaderFragments/UsdUVTexture.xml
This change depends on a change in USD, commit [4e426565](https://github.com/PixarAnimationStudios/USD/commit/4e42656543f4e3a313ce31a81c27477d4dcb64b9), which isn't merged into the standard version of USD that we build against, so it won't actually work yet. But the source itself can compile fine without that change and the behavior isn't any worse, so I will commit the changes anyway.
This commit + 4e426565 fixes issue #89
> MAYA-101853 Changes necessary for UDIM texture support.

- build.py
- lib/mayaUsd/ufe/UsdUndoInsertChildCommand.cpp
- lib/mayaUsd/ufe/UsdUndoInsertChildCommand.h
- test/lib/ufe/testParentCmd.py
Improve parenting so that parenting between different layers will work.  There is an ongoing discussion with Will Telford about restrictions which should be enforced in the parenting workflows, but these can be implemented later.  Will this pull request, behaviors that users expect will work, and grouping will work reliably.
> Tremblp/maya 103815/ufe parenting usd 01

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.h
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.h
Currently due to missing support for UsdSkel, the mesh will have no points data, but it still has the topology data which will reference the points. This could cause corrupted geometry in the viewport.
The commit will disable all degenerated render items.
Along with the fix I clean up the code that determines the enable/disable state of the render item.
> MAYA-104981 Disable all degenerated render items.

- plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/testProxyShapeDrawPerformance.py
- plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/testProxyShapeDuplicatePerformance.py
- plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/testProxyShapeSelectionPerformance.py
These tests are still not being run through CMake/CTest, but we've been running them internally in our SCons-based build. This change makes them drop performance metrics generated using the Trace library to better determine where the time is being spent.
> add Trace profiling to pxr interactive performance tests

- lib/mayaUsd/render/mayaToHydra/renderOverrideUtils.h
> [mtoh] Split pre and post scene passes so camera guides go above Hydra.

- lib/mayaUsd/nodes/proxyShapeBase.cpp
The workflow that shows the problem here:
1. Create a new proxy shape.
2. Right click on the proxy shape and you will see the UFE/USD menu items, e.g. "Add new prim".
3. Create another new proxy shape.  Not from file, an empty one.
4. Right click the new proxy shape and you will not see the UFE/USD menu items.
This happens because we maintain a map of proxy shapes <-> USD stages that gets updated only when dirty.  The map currently only gets dirtied when the file path attribute on the proxy shape changes, which worked fine until we added a command to create a new empty stage + proxy shape.  In this case we were not notifying anyone that there was a new/dirty item so the map was not dirtied and we do not update the popup menu.
> MAYA-104776 send a notice that a newly created proxy shape is dirty

- .github/workflows/maya-usd-preflight-launcher.yml
The diff looks bad. The real change is only 2 lines:
` runs-on: ubuntu-latest`
`if: contains(toJson(github.event.pull_request.assignee), 'ecp-maya-devops-adsk')`
I took out the runs-on matrix for simplicity.
The if: condition makes the GitHub Actions build show as "skipped" instead of "failed", which is nice. You can see an example here: https://github.com/smithw-adsk/maya-usd/pull/16
> MAYA-105122 trigger only on assignment to ecp-maya-devops-adsk

- lib/mayaUsd/render/mayaToHydra/renderOverrideUtils.h
https://github.com/Autodesk/maya-usd/pull/526 broke curve rendering via Maya.
> [mtoh] Fix curve rendering broken in 4f4246a6.

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
As a part of setting up an instanced MRenderItem in Vp2RenderDelegate we'd set the prototype geometry on the item. At this point the MRenderItem looks to Maya like any other drawable item (with an identity transform matrix). Then we set the instance transforms and the MRenderItem changes to an instanced item and we handle the drawing differently.
The problem is when there is a USD instances with no instances we never do that second step, so the item stays a regular Maya item and we draw it normally, which is not what we want to happen.
The solution is detect that there is an instancer with zero instance transforms and hide the MRenderItem in those cases.
#404 #522
> MAYA-105120 Hide MRenderItems created for instancers with zero instances.

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
We were getting an **unused-function** error when building the current dev branch with USD 19.11. It's caused by the _LoadUdimTexture function. This is just a quick fix. This function does not seem to be used when we are building with USD versions earlier than 20.02, at least not with 19.11.
> fix unused-function compile error with USD versions earlier than 20.02

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
Only add each instance transform at most once.
> MAYA-104936 instanceIndices may contain duplicate indices.

- lib/mayaUsd/render/px_vp20/utils.cpp
- lib/mayaUsd/render/px_vp20/utils.h
- lib/mayaUsd/render/px_vp20/utils_legacy.h
- lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.h
- lib/mayaUsd/render/pxrUsdMayaGL/hdImagingShapeDrawOverride.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/hdImagingShapeUI.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/instancerImager.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/instancerShapeAdapter.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/instancerShapeAdapter.h
- lib/mayaUsd/render/pxrUsdMayaGL/proxyDrawOverride.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/proxyShapeDelegate.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/proxyShapeUI.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/renderParams.h
- lib/mayaUsd/render/pxrUsdMayaGL/sceneDelegate.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/sceneDelegate.h
- lib/mayaUsd/render/pxrUsdMayaGL/shapeAdapter.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/shapeAdapter.h
- lib/mayaUsd/render/pxrUsdMayaGL/softSelectHelper.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/softSelectHelper.h
- lib/mayaUsd/render/pxrUsdMayaGL/usdProxyShapeAdapter.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/usdProxyShapeAdapter.h
- lib/mayaUsd/render/pxrUsdMayaGL/userData.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/userData.h
To buy us some time with our production artists while we tackle adopting the VP2.0 render delegate, I took one final pass at improving and optimizing the Pixar batch renderer.
The biggest benefit for them here is a fix for a long-standing issue where the displayStyle of the viewport was only being considered at `prepareForDraw()` time. This caused draw issues when changing the style of a viewport where the display wouldn't update until another `prepareForDraw()` was issued (for example by performing a selection).
There is some marginal performance improvement here as well though as a result of avoiding ever dirtying the rprim collection or the repr for a given render task. The shape adapters now manage a collection for each repr that might be used by the Maya viewport, and a render task …
> Pixar batch renderer refactoring and performance improvements

- test/lib/ufe/testDeleteCmd.py
Maya has been changed (for the next preview release) to customize UFE path string output (path object to string) to avoid the leading "|world" prefix.  For single-segment Maya objects, having this prefix in the path is legal syntax, but does not match any objects when passed to Maya commands, and this was causing bugs when invoking Maya commands directly with UFE path string output as arguments (e.g. the parent command).  Changed the path string test to reflect this.
As before, the "|world" prefix on UFE path string input (string to path object) is optional, and can be omitted --- this is customization that Maya already does, and is unchanged.
> Fixed path string test.

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.h
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
> MAYA-105284 Track changes to render tags more carefully to avoid setting the tags

- test/lib/ufe/testSelection.py
- test/lib/ufe/ufeTestUtils/mayaUtils.py
This pull request updates the selection test to demonstrate a fix to the Maya selection undo / redo behavior.  The previous version of the test did not trigger the bug; this one does, and therefore demonstrates the fix, which will be in the next Maya preview release.  This pull request should not be merged before the corresponding Maya bug fix is merged.
The bug occurs when the select command replaces a non-Maya UFE selection.  On undo, the select command must restore the previous non-Maya UFE selection.  This test ensures it does.
> Demonstrate fix for Maya selection undo / redo.

- lib/usd/ui/USDImportDialogCmd.cpp
There can be a pause while building the hierarchy view dialog when importing a larger usd file, so here I add a wait cursor while building it.
The QApplication calls I'm making here are basically what the Maya waitCursor command does, so just calling them directly instead of bothering with a call to the command from c++.
Also thought about putting the calls right in the dialog itself, but I think the slower code in there is partly in the initializer list so it wasn't a good fit there.
> MAYA-103556 Display a wait cursor when building the hierarchy view

- build.py
I'm not sure what previously required the tests to be run serially, but I don't seem to be having any issues running them in parallel on Linux.
Was there something else we needed to follow up on here before we switched multiprocessing back on?
> do not hard-code the number of jobs to 1 when running ctest

- lib/mayaUsd/fileio/shading/CMakeLists.txt
- lib/mayaUsd/fileio/shading/shadingModePxrRis.cpp
I also organized the header includes in shadingModePxrRis.cpp while I was at it.
> Do not install shadingModePxrRis_rfm_map.h header publicly

- lib/mayaUsd/base/debugCodes.cpp
- lib/mayaUsd/listeners/stageNoticeListener.cpp
- lib/mayaUsd/listeners/stageNoticeListener.h
- lib/mayaUsd/nodes/CMakeLists.txt
- lib/mayaUsd/nodes/proxyAccessor.cpp
- lib/mayaUsd/nodes/proxyAccessor.h
- lib/mayaUsd/nodes/proxyAccessor.py
- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/nodes/proxyShapeBase.h
- lib/mayaUsd/nodes/proxyStageProvider.h
- plugin/adsk/plugin/ProxyShape.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.h
- test/lib/CMakeLists.txt
- test/lib/testMayaUsdProxyAccessor.py
This PR enables `mixed data model compute` between DG and USD, i.e. it allows DG connections to read and write to USD attributes. `ProxyAccessor` it the class responsible for providing this capability, which becomes the foundation to workflows like:
- parenting (e.g. DAG to Prim)
- animation (i.e. driving prim attributes with Maya animation curves)
- attribute level constraints
We decided to put `ProxyAccessor` capabilities on `ProxyShape` but the class itself can be used with any `MPxNode` with `ProxyStageProvider` interface for the querying stage and time. Centralizing all writes and reads from the USD stage allows deterministic evaluation order and avoids race conditions during parallel execution. 
The `ProxyAccessor` supports CachedPlayback, i.e. accelerated playback, proper cache …
> Mixed data model compute with proxy accessor

- plugin/adsk/scripts/mayaUsdTranslatorImport.mel
Minor change to adjust the column width of some text in the Import UI.  The chosen width is important for the animation details below the Hierarchy View button, but the text that is displayed when the button is invisible doesn't need the extra width.  The current width can effect other parts of the UI, minor problem but can be annoying.
> MAYA-105538 minor fix for column width of some text.

- test/lib/usd/translators/testUsdImportRfMLight.py
`fixturesUtils._setUpClass()` monkey patches the `cmds.usdExport` and `cmds.usdImport` names to `cmds.mayaUSDExport` and `cmds.mayaUSDImport`, respectively, so if we don't load `mayaUsdPlugin`, those commands will not exist.
This change fixes the `testUsdImportRfMLight` test, but `fixturesUtils` may need some reconsideration if we really want to support bypassing loading any plugins.
> do not bypass the mayaUsdPlugin load in the testUsdImportRfMLight test

- lib/mayaUsd/render/vp2RenderDelegate/render_delegate.cpp
- lib/mayaUsd/render/vp2ShaderFragments/FallbackShader.xml
api to enable multidraw consolidation.
The "API" (the XML attribute name) is still being finalized but I wanted this up to show an example of how it is used.
> Remove the call to the old multidraw API, and use the new xml based 

- test/lib/usd/translators/testUsdExportRenderLayerMode.py
Since we call `cmds.mayaHasRenderSetup()` in a decorator on the test class, we have to make sure that we call `maya.standalone.initialize()` *before* the class is defined, since `setUpClass()` when it would normally be called executes after that. Otherwise, the method called in the decorator will fail.
This is somewhat similar to #609 where because we're running this test outside of the usual CMake harness, we don't get the extra standalone initialization code injected.
> initialize Maya standalone mode when the testUsdExportRenderLayerMode module is loaded

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
The regression #153 was caused by not using instanced draw for single-instance objects and reproducible on Maya 2020 and before.
Recent Maya preview releases already support consolidation for instanced render items so the performance workaround has been removed, therefore the regression won't be reproduced for those preview releases.
> Fix the regression for selecting single instance objects.

- lib/mayaUsd/render/vp2ShaderFragments/CMakeLists.txt
- lib/mayaUsd/render/vp2ShaderFragments/UsdPreviewSurface.xml
- lib/mayaUsd/render/vp2ShaderFragments/UsdPreviewSurfaceCore.xml
- lib/mayaUsd/render/vp2ShaderFragments/shaderFragments.cpp
- lib/mayaUsd/render/vp2ShaderFragments/shaderFragments.h
- lib/usd/pxrUsdPreviewSurface/usdPreviewSurfaceShadingNodeOverride.cpp
These changes should address #607 which saw a breakage in the handling of the `opacity` control on `pxrUsdPreviewSurface`. They were written according to @HdC-adsk's proposal in that issue.
> fix opacity vs. transparency issues with UsdPreviewSurface and pxrUsdPreviewSurface

- lib/mayaUsd/commands/baseExportCommand.cpp
- lib/mayaUsd/commands/baseExportCommand.h
- lib/mayaUsd/fileio/jobs/jobArgs.cpp
- lib/mayaUsd/fileio/jobs/jobArgs.h
- lib/mayaUsd/fileio/jobs/readJob.cpp
- lib/mayaUsd/fileio/writeJobContext.cpp
- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
- test/lib/usd/translators/CMakeLists.txt
- test/lib/usd/translators/testUsdExportFileFormat.py
This branch is everything from https://github.com/Autodesk/maya-usd/pull/591 including some requested changes to use the file format id's, and a test added, but redone on the latest dev branch.  I had set this aside while there was some ongoing work on the tests and when coming back to it after everything else went in I ended up just cherry picking in the original changes I had into a new branch.
> MAYA-103187 Add option to save .usd files as binary or ascii

- lib/usd/ui/TreeModel.cpp
- lib/usd/ui/TreeModel.h
- lib/usd/ui/USDImportDialog.cpp
- lib/usd/ui/USDImportDialog.h
- lib/usd/ui/USDImportDialog.ui
New menu item in the Hierarchy View dialog that will reset all of the edited variant sets back to what is in the usd file, and sets the checked state back to the root selection
> Add menu in Hierarchy View to reset the model and variant selections

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
The pull request is to add a "UsdSelectionKind" option var to override selection
behavior (GUI support is coming separately).
The default behavior is to select the exact prim which is picked in the viewport.
If the option var is assigned with a non-empty string to indicate a Kind token,
the nearest ancestor that is assigned with that Kind or a subcategory of that
Kind will be selected when a prim is picked in the viewport. If the prim doesn't
have any qualified ancester, it falls back to the default behavior (but it can be
slower due to the cost of walking the scene hierarchy).
If the option var is undefined or empty, the default behavior will be used to
select the exact prim.
For details about Kind, please refer to [Kind : Extensible …
> Selection by kind

- lib/usd/utils/util.cpp
- lib/usd/utils/util.h
Often time I need to debug the queried composition arcs in C++ and this function helps to pretty-print them.
Same thing can also be achieved in python. See testUsdPrimCompositionQuery here :
https://github.com/PixarAnimationStudios/USD/blob/ebac0a8b6703f4fa1c27115f1f013bb9819662f4/pxr/usd/usd/testenv/testUsdPrimCompositionQuery.py#L28
> Convenience function for printing the list of queried composition arcs in order

- lib/mayaUsd/ufe/UsdUndoRenameCommand.cpp
- test/lib/ufe/testRename.py
- Spaces are replaced with "_"
- Names are not allowed to start with digits.
> MAYA-104778: Handle two more illegal cases:

- lib/usd/hdMaya/adapters/meshAdapter.cpp
- lib/usd/hdMaya/adapters/nurbsCurveAdapter.cpp
- lib/usd/hdMaya/delegates/delegateCtx.cpp
- lib/usd/hdMaya/delegates/delegateCtx.h
HdRenderIndex::InsertRprim will do this using HdRprim::GetInitialDirtyBitsMask().
Additionally, the previous use of HdChangeTracker::AllDirty could cause over-invalidation:
If the delegate doesn't have knowledge of those bits,  it won't necessarily clear them leading to `HdRprim::Sync` called on every `engine.Execute` invocation.
> [mtoh] Remove explicit call to HdChangeTracker::RprimInserted.

- lib/usd/hdMaya/adapters/proxyAdapter.cpp
When rendering via **mtoh**, changes to **UsdProxy.filepath** aren't working.
(If not always, at least when **VP_RENDER_DELEGATE=0**)
> [mtoh] Fix stage-repopulation.

- lib/mayaUsd/ufe/UsdUndoAddNewPrimCommand.cpp
- test/lib/ufe/testGroupCmd.py
Made a typo in my group command change.  Problem was that I used the variable for the name of the new object when defining the prim type.  Fixed that and added to the group test to make sure it's correct.
> MAYA-105743 Use the correct type when creating a new group

- lib/mayaUsd/ufe/StagesSubject.cpp
- test/lib/ufe/testRename.py
* Don't send UFE delete when in path change (rename).
> MAYA-104839 - Prim specs disappear from Outliner after rename

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
When picking instances from viewport, the non-UFE selection code path
wasn't able to select the proxy DAG path as expected because the default
VP2 selection logic cannot handle selection for non-DAG instances.
Thus in the plugin side we need to determine the selected DAG path to
avoid relying on the default VP2 selection logic.
Note: This fix is for Maya 2018 only. Besides, in the maya side we are fixing
a selection issue for transparent instances for all relevant Maya versions.
> MAYA-105608 Non-UFE selection code path couldn't work with instances

- lib/mayaUsd/render/mayaToHydra/renderGlobals.cpp
- lib/mayaUsd/render/mayaToHydra/renderGlobals.h
- lib/mayaUsd/render/mayaToHydra/renderOverride.cpp
- lib/mayaUsd/render/mayaToHydra/renderOverrideUtils.h
- lib/mayaUsd/render/mayaToHydra/tokens.h
- lib/mayaUsd/render/mayaToHydra/utils.cpp
There still seems to be a lot of things not drawn when in mtoh (Nurbs, SubdivSurf, GreasePencils).
This may or may not have been introduced in aeb87c46, but this simplifies the Pre & Post render passes to just not draw Meshes & PluginShapes (for UsdProxies) in the _PostRender_.
Additionally the HdSt menu for selection is removed, as I seem to be able to accomplish this with the other two checkboxes for wireframe & overlay.  And I haven't been able to get the menu to show what it's purpose is. (perhaps @pmolodo can shed some light on what it does or if the original intent is still valid).
> [mtoh] Draw all the things that mtoh will not in the post-render pass.

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.h
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.h
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
To be consistent with Maya's convention, lead selection and active selection should be highlighted with different colors.
> MAYA-102266 Selection highlight color for lead and active selection

- doc/build.md
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Engine.cpp
- test/lib/usd/translators/testUsdExportAsClip.py
The `_engine` property was made private starting with `USDIMAGINGGL_API_VERSION` 6 in core USD commit https://github.com/PixarAnimationStudios/USD/commit/c03508ba9850bccabcd4b84e217533bd909352a7. It can still be accessed using the protected `_GetHdEngine()` accessor.
These changes should continue to work before and after that version.
> Updates to support core USD release 20.08

- lib/mayaUsd/ufe/Global.cpp
- lib/mayaUsd/ufe/Global.h
- lib/mayaUsd/ufe/ProxyShapeHierarchy.cpp
- lib/mayaUsd/ufe/ProxyShapeHierarchy.h
- lib/mayaUsd/ufe/UsdHierarchy.cpp
- lib/mayaUsd/ufe/UsdHierarchy.h
- lib/mayaUsd/ufe/UsdUndoInsertChildCommand.cpp
- test/lib/ufe/testParentCmd.py
This pull request implements the Ufe::Hierarchy::defaultParent() method.  This is used when unparenting, a.k.a parent -world.  In this implementation, the default parent of USD nodes is their proxy shape, so that calling parent -w on them will place them as a child of the corresponding USD stage pseudo-root.
> Added implementation for new UFE unparent interface (MAYA-105276)

- lib/mayaUsd/ufe/Global.cpp
- lib/mayaUsd/ufe/StagesSubject.cpp
- lib/mayaUsd/ufe/UsdContextOps.cpp
- lib/mayaUsd/ufe/UsdHierarchy.cpp
- lib/mayaUsd/ufe/UsdUndoInsertChildCommand.cpp
- lib/mayaUsd/ufe/UsdUndoRenameCommand.cpp
- lib/mayaUsd/ufe/private/UfeNotifGuard.h
* New helper class to know when we are in an add or remove reference operation. Send UFE subtree invaliate notif for USD ObjectsChanged when we are in add/remove reference.
> MAYA-105442 - Add reference is not updated in the Outliner

- lib/mayaUsd/ufe/private/Utils.cpp
- lib/usd/utils/util.cpp
- lib/usd/utils/util.h
Updated the strings for re-parent/rename restriction rules. There are currently 3 rules in place:
**1.** Check if a particular node has any specs to contribute to the final composed prim. 
`Error Message: Cannot [reparent/rename] [prim_name]. It does not make any contributions in the current layer because its specs are in an external composition arc. Please open [filename.usd] to make direct edits.`
**2.** Check if we are in the correct edit target to make an edit.
`Error Message:  Cannot [reparent/rename] [prim_name]. It is defined on another layer. Please set [layername] as the target layer to proceed.
`
**3.** Check if we have more than 2 layers that contribute to the final composed prim. 
`Error Message: Cannot [reparent/rename] [prim_name]. It has definitions or opinions on other …
> MAYA-105977: Update restriction error reports based on latest design.

- build.py
- lib/mayaUsd/commands/CMakeLists.txt
- lib/mayaUsd/commands/editTargetCommand.cpp
- lib/mayaUsd/commands/editTargetCommand.h
- lib/mayaUsd/commands/layerEditorCommand.cpp
- lib/mayaUsd/commands/layerEditorCommand.h
- plugin/adsk/plugin/plugin.cpp
- test/lib/CMakeLists.txt
- test/lib/testMayaUsdLayerEditorCommands.py
MAYA-104967 Undo/Redo USD target change and sublayer edits for Maya USD Layer Editor
New MEL commands
```
Synopsis: mayaUsdEditTarget [flags] String 
Flags:
-e -edit
-q -query
-et -editTarget  String
Synopsis: mayaUsdLayerEditor [flags] String 
Flags:
-e -edit
-aa -addAnonymous    String (multi-use)
-cl -clear          
-de -discardEdits   
-is -insertSubPath   Int String (multi-use)
-rp -replaceSubPath  String String (multi-use)
-rs -removeSubPath   Int (multi-use)
```
> MAYA-104967 mel commands for Undo/Redo USD target change and sublayer edits

- lib/mayaUsd/fileio/importData.cpp
- lib/mayaUsd/fileio/importData.h
- lib/usd/ui/ItemDelegate.cpp
- lib/usd/ui/ItemDelegate.h
- lib/usd/ui/TreeItem.h
- lib/usd/ui/TreeModel.cpp
- lib/usd/ui/TreeModel.h
- lib/usd/ui/USDImportDialog.cpp
- lib/usd/ui/USDImportDialog.h
- lib/usd/ui/USDImportDialog.ui
- lib/usd/ui/USDImportDialogCmd.cpp
- plugin/adsk/scripts/mayaUsdTranslatorImport.mel
1. Help menu in the Hierarchy View dialog.
2. Might not be called from anywhere, but noticed a typo in ImportData::hasVariantSelections that I fixed.
3. I think we were leaking every ItemDelegate we created.  Qt docs say that QAbstractItemView::setItemDelegate does not take ownership of the delegate you pass to it but we were calling it like it would.
4. Made the checkbox column not resizable. 
5. Main part:
Adding UI to display a couple counts as information to the user.  One is the total number of prims that are checked, and the other is the number of variants that have been modified and are checked.  This info is displayed both in the Hierarchy View and also the file dialog import options after exiting the HV.
In the file dialog import options we also added a button to reset the import …
> MAYA-102330 Add UI to display the number of selected prims and changed variants

- build.py
- test/lib/testMayaUsdLayerEditorCommands.py
Build script was failing to run when executed with python3:
```
Traceback (most recent call last):
File "build.py", line 602, in <module>
BuildAndInstall(context, context.buildArgs, context.stagesArgs)
File "build.py", line 369, in BuildAndInstall
RunCMake(context, extraArgs, stagesArgs)
File "build.py", line 275, in RunCMake
extraArgs=(" ".join(extraArgs) if extraArgs else "")))
File "build.py", line 148, in Run
logfile.write(l.encode("utf8"))
TypeError: write() argument must be str, not bytes
```
Similarly, a new regression test `testMayaUsdLayerEditorCommands.MayaUsdLayerEditorCommandsTestCase` was failing: 
```
3: ======================================================================
3: ERROR: testSubLayerEditing (testMayaUsdLayerEditorCommands.MayaUsdLayerEditorCommandsTestCase)
3: …
```
> Fix build script and test failures with python3 build

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
fixed unused-but-set-variable on compiling with Maya 2018 earlier than 2018.7
> fixed unused-but-set-variable on compiling with Maya 2018 earlier than 2018.7

- plugin/adsk/scripts/mayaUsd_createStageWithNewLayer.py
- test/lib/ufe/testContextOps.py
MAYA-104770: When a new stage is created, it is named "stage" instead of "stage1" and the shape is named "stageShape" instead of "stageShape1" if multiple stages are created subsequent ones contain a number for instance the next one would be "stage1" which is correct however the shape is named "stage1Shape" instead of "stageShape1"
> MAYA-104770: Naming of stage and shape at creation are not inline with naming in Maya

- lib/mayaUsd/commands/editTargetCommand.h
The compiler generates following warning as an error when building on windows for Maya 2018 (or without UFE):
```
e:\maya-usd_pr\lib\mayausd\commands\editTargetCommand.h(53): error C2220: warning treated as error - no 'object' file generated
e:\maya-usd_pr\lib\mayausd\commands\editTargetCommand.h(53): warning C4251: 'MayaUsd::EditTargetCommand::_setEditTarget': class 'std::unique_ptr<MayaUsd::Impl::SetEditTarget,std::default_delete<_Ty>>' needs to have dll-interface to be used by clients of class 'MayaUsd::EditTargetCommand'
with
[
_Ty=MayaUsd::Impl::SetEditTarget
]
e:\maya-usd_pr\lib\mayausd\commands\editTargetCommand.h(53): note: see declaration of 'std::unique_ptr<MayaUsd::Impl::SetEditTarget,std::default_delete<_Ty>>'
with
[
_Ty=MayaUsd::Impl::SetEditTarget
]
```
There can't be any …
> Fix windows build when compiling for Maya 2018 or without UFE

- lib/mayaUsd/render/mayaToHydra/renderOverride.cpp
- lib/usd/hdMaya/adapters/proxyAdapter.cpp
- lib/usd/hdMaya/adapters/proxyAdapter.h
- lib/usd/hdMaya/delegates/proxyDelegate.cpp
- lib/usd/hdMaya/delegates/sceneDelegate.cpp
- lib/usd/hdMaya/delegates/sceneDelegate.h
This pushes Maya's "Use default material" toggle into Hydra.  Quick toggle to ignore all shaders is useful (particularly fo Storm and textures)
> [mtoh] Support USD enableSceneMaterials better.

- lib/mayaUsd/fileio/utils/meshReadUtils.cpp
The vertex color streams are sometimes hijacked to store custom
attribute values that are not representable as colors. This is the case
in the Kitchen_Set scene with pose information that show as black when
displayColors is turned on. Let the user manually turn that feature on
if he knows for sure there are colors to display.
> MAYA-105732 Do not auto turn on displayColors

- lib/mayaUsd/ufe/UsdUndoInsertChildCommand.cpp
- lib/mayaUsd/ufe/UsdUndoInsertChildCommand.h
Re-parenting creates cruft in the generated USD data model. This is mainly caused by the SetActive mechanism on undo/redo.
New mechanics doesn't use SetActive. Here are the steps during the undo/redo:
Redo:
1. Copy spec data at **srcPath** in **srcLayer** into **destPath** in **destLayer**
2. Remove **srcPath** in **srcLayer** by using "Stage::RemovePrim" 
3. Re-create **Ufe::SceneItem** and send data model change notification
Undo:
1. Copy spec data at **destPath** in **destLayer** into **srcPath** in **srcLayer**
2. Remove **destPath** in **destLayer** by using "Stage::RemovePrim" 
3. Re-create **Ufe::SceneItem** and send data model change notification
1. clean USD data model
2. undo/redo support
3. re-parenting support between multiple stages.
> MAYA-105764: Fix cruft in data model after re-parenting on undo/redo.

- test/lib/ufe/testParentCmd.py
Unparent functionality was initially planned to go into Maya with UFE 0.2.18.  Because of a change in priorities, it will go into Maya with UFE 0.2.20.  Disable the unparent test until that version of Maya.
> Do not test unparent functionality until Maya with UFE 0.2.20.

- test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
When I brought the changes from #686 down internally and attempted to run the tests, I was seeing the `testUsdExportImportRoundtripPreviewSurface` test fail on the final assertion that checks to make sure the texture file path in USD begins with a `..`:
https://github.com/Autodesk/maya-usd/blob/e15890ca2e4ddecfff7da95e4caf6bb9c425cca4/test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py#L146
Since we run the tests through a completely different infrastructure, it just so happened that the test run directory and the test data files are arranged on disk such that we end up with a relative file path authored that does **not** involve `..`.
I adjusted this final assertion to be more robust to this by verifying that when we join the directory that the USD file lives in with …
> adjust verification of texture path relative-ness in testUsdExportImportRoundtripPreviewSurface

- doc/build.md
- lib/mayaUsd/fileio/writeJobContext.cpp
- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- lib/mayaUsd/render/vp2RenderDelegate/material.h
- lib/usd/translators/skelReader.cpp
- test/lib/usd/translators/testUsdExportSkeleton.py
- test/lib/usd/translators/testUsdImportSkeleton.py
A handful of commits were pushed recently to core USD that require version-gated changes in maya-usd. This includes the `HdMaterial` change previously presented as #704 and replaces that PR.
With the changes here, maya-usd will continue to build against supported core USD releases 20.08 and earlier. For core USD at commits beyond the 20.08 release, commit https://github.com/PixarAnimationStudios/USD/commit/8a13d20062d14d486b7e130d252c4652aab0263e or later must be used. The build.md was updated accordingly.
> updates for building with latest post-20.08 commits of core USD

- lib/mayaUsd/fileio/jobs/jobArgs.cpp
- lib/mayaUsd/fileio/shading/shadingModeRegistry.h
- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
Added tooltips, updated some labels, reordered the entries and made useRegistry the new default.
> MAYA-103230 Cleaned-up export material UI

- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.h
The face vertex indices can jump drastically and cause cache hit rate
to be low when drawing. Thus we need to sort the vertices so it can be
more cache-friendly.
After sorting, a remapping table is populated and used to prepare vertex
buffers. This remapping table is updated only when topology is changed,
so it won't happen often in common workflows.
Previously we have had another remapping code path for vertex unsharing
when there is any uniform or face-varying primvar. The commit will unify
the two remapping processes with a single remapping table, making it
easier to maintain.
> MAYA-105263 Improve draw performance for dense mesh

- lib/mayaUsd/ufe/UsdSceneItem.cpp
- lib/mayaUsd/ufe/UsdSceneItem.h
- test/lib/ufe/CMakeLists.txt
- test/lib/ufe/testSceneItem.py
* Implement new ancestorNodeTypes() method on Ufe::SceneItem.
> MAYA-106190 - As a user, I would like see prim type icons

- lib/mayaUsd/ufe/Global.cpp
- lib/mayaUsd/ufe/StagesSubject.cpp
- lib/mayaUsd/ufe/UsdContextOps.cpp
- lib/mayaUsd/ufe/UsdUndoAddNewPrimCommand.cpp
- lib/mayaUsd/ufe/UsdUndoDeleteCommand.cpp
- lib/mayaUsd/ufe/private/UfeNotifGuard.h
- test/lib/ufe/testContextOps.py
- test/lib/ufe/testDeleteCmd.py
* Removed special case for add/remove reference and instead created special case for add or delete operations. In these cases we send the UFE add/delete notifs. Otherwise we fallback and send the UFE subtree invalidate notif.
* In the tests that add new prims and test delete, added a UFE observer to make sure we are getting the correct notifs.
> MAYA-103701 - UFE: Maya crashes after switching variant

- lib/mayaUsd/nodes/proxyShapeBase.cpp
Replacing std::bind with a simple lambda in here to avoid the unnecessary overheads that comes with std::bind.
> Prefer lambda over std::bind

- lib/mayaUsd/fileio/functorPrimReader.cpp
- lib/mayaUsd/fileio/functorPrimWriter.cpp
Favour lambda over std::bind to avoid the unnecessary overheads that comes with std::bind
> Eliminate any std::bind in favor of lambda

- CMakeLists.txt
- cmake/test.cmake
- modules/alUSD.mod.template
- modules/alUSD_Win.mod.template
- modules/mayaUSD.mod.template
- modules/mayaUSD_Win.mod.template
- modules/pxrUSD.mod.template
- modules/pxrUSD_Win.mod.template
- test/lib/usd/pxrUsdPreviewSurface/CMakeLists.txt
* Split mod file into three (one for each plugin).
* When running tests we only need PATH for Windows and not LD_LIBRARY_PATH.
> Split Maya module file into separate plugins

- plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/testBatchRendererIsolateSelection.py
A regression appears to have been introduced some time around the release of Maya 2020.
When using the "Show -> Isolate Select" feature in a particular viewport, if your isolated selection includes assemblies and you unload and reload those assemblies while "Isolate Select -> View Selected" is turned on, those assemblies will not be visible when they are reloaded, nor can they be selected. They continue to be visible and selectable in other viewports, and turning off "View Selected" will make them visible and selectable in the previously filtered viewport.
It's not quite clear whether this regression has to do specifically with the assembly framework or is instead more generally related to some set membership state being lost as nodes are created or destroyed while a viewport is being …
> workaround for testBatchRendererIsolateSelection test failure in Maya 2020+

- doc/build.md
- lib/mayaUsd/fileio/shading/shadingModeExporterContext.cpp
- lib/mayaUsd/render/mayaToHydra/renderOverride.cpp
- lib/mayaUsd/render/mayaToHydra/renderOverride.h
- lib/mayaUsd/render/mayaToHydra/utils.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/sceneDelegate.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/usdProxyShapeAdapter.cpp
- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- lib/usd/hdMaya/adapters/materialAdapter.cpp
- lib/usd/hdMaya/adapters/materialNetworkConverter.cpp
- lib/usd/hdMaya/adapters/materialNetworkConverter.h
- lib/usd/hdMaya/delegates/delegate.h
- lib/usd/schemas/CMakeLists.txt
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeUI.cpp
With recent support added for USD 20.08, we are dropping support for fairly old 19.07.
> Removing code blocks for USD 19.07

- lib/usd/translators/shading/usdFileTextureWriter.cpp
Boost filesystem will return an empty path when it can not find a
relative one. This will happen when the USD file and the textures are
not on the same Windows drive, or with UNC paths.
> MAYA-105604 Handle empty relative path

- plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/InstancerDrawTest/CubeModel.usda
- plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/RefAssemblyDrawRepresentationsTest/CubeModel.usda
In core USD, the test to determine whether a draw mode is used for a particular prim was updated to require that that prim has had the UsdGeomModelAPI schema applied to it. Most "modern" assets should have this already if they used the API schema to author draw mode, but these are some old test assets that were authored before the API schema applied itself when authoring the drawMode.
This change corresponds to core USD commit
https://github.com/PixarAnimationStudios/USD/commit/ccf9a3ddc8cdaf8ec9d5867418ebc947ca00d799
> apply UsdGeomModelAPI schema to test assets that exercise the drawMode adapter

- lib/mayaUsd/ufe/Utils.cpp
- test/lib/ufe/testContextOps.py
* When computing unique child name we need to also consider inactive prims.
> MAYA-106032 - add new prim fails after delete

- doc/build.md
- lib/mayaUsd/fileio/utils/adaptor.cpp
- lib/mayaUsd/fileio/utils/adaptor.h
These changes were made by the core USD team to allow some refactoring in the schema registry. They make use of API added in core USD version 20.05 so older APIs can be removed for later versions of USD. Support for older versions of USD is maintained as well.
The changes here are required to build against core USD at commit https://github.com/PixarAnimationStudios/USD/commit/0e3171a02b5b854c36d58c4ca74c7a8fa3ac2b8a or later.
> adapt to refactoring in core USD of registry handling of prim specs versus prim definitions

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
When the USD stage is set on proxyRenderDelegate we clear the change tracker and render index. At the same time we need to reset the dirty information that we use to track the state of the render index. Once the render index is cleared that old dirty information is meaningless, and sometimes causes us to do the wrong thing when the stage is replaced.
> Reset version ids and dirty information when the USD stage is cleared.

- lib/usd/ui/IMayaMQtUtil.h
- lib/usd/ui/IUSDImportView.h
- lib/usd/ui/ItemDelegate.h
- lib/usd/ui/TreeItem.h
- lib/usd/ui/TreeModel.h
- lib/usd/ui/TreeModelFactory.h
- lib/usd/ui/USDImportDialog.h
- lib/usd/ui/USDImportDialogCmd.h
- lib/usd/ui/USDQtUtil.h
We're finally getting our VFX platform 2019 and Maya 2020+ builds into a place where we're able to build the UI components of maya-usd, but I ended up tripping over the `#pragma once` directives being used there. I'm not sure exactly what the specific difference in setup is between our build internally and the CMake build, but since we landed on include guards being preferred to `#pragma once` in the coding guidelines, I just converted all of the headers in mayaUsdUI.
> [mayaUsdUI] replace #pragma once with #ifndef include guards

- lib/mayaUsd/ufe/CMakeLists.txt
- lib/mayaUsd/ufe/StagesSubject.cpp
- lib/mayaUsd/ufe/UsdTransform3d.h
- lib/mayaUsd/ufe/UsdTransform3d.md
- lib/mayaUsd/ufe/UsdTransform3dBase.cpp
- lib/mayaUsd/ufe/UsdTransform3dBase.h
- lib/mayaUsd/ufe/UsdTransform3dHandler.cpp
- lib/mayaUsd/ufe/UsdTransform3dMatrixOp.cpp
- lib/mayaUsd/ufe/UsdTransform3dMatrixOp.h
- lib/mayaUsd/ufe/Utils.cpp
- lib/mayaUsd/ufe/Utils.h
- plugin/adsk/plugin/plugin.cpp
This branch is a proof of concept for editing USD matrix transform ops
with maya-usd.  A more detailed architectural overview is given in
lib/mayaUsd/ufe/UsdTransform3d.md .
As per lib/mayaUsd/ufe/UsdTransform3d.md , the following two
requirements are the focus of this branch:
- 2 *Manipulation code will use an interface that takes care of transformation
operations management. Pipelines may choose to change this interface at runtime
to improve interop between DCCs.*  This is met by the existing customizable
Transform3dHandler system, which can create custom Transform3d interfaces.
Pipelines can leverage this mechanism to introduce studio-specific overrides
without modifying the default implementation or having to maintain and resolve
conflicts when the default implementation changes. In …
> Proof of concept for USD matrix transform op editing.

- lib/mayaUsd/utils/converter.cpp
- test/lib/testMayaUsdProxyAccessor.py
Matrix is stored as shared data, we have to use an appropriate function interface to allocate and maintain the lifetime of matrix objects when stored in the data block.
Added regression test to validate the fix and prevent regressions. Normally it would require a test only for the converter, but data block is not something we have easy access to from python.
> Use MFnMatrixData when storing/retriving MMatrix from data block

- lib/mayaUsd/fileio/shading/shadingModeDisplayColor.cpp
Prior to PR #707, the un-linearized transparency value was being used to compute a transparency "average", which was then used to author `displayOpacity` on the bound gprim if it did not already have an authored `displayOpacity`, as well as a `displayOpacity` input on the shader prim. It looks like an unintended side effect of #707 was that it was made to use the linearized transparency for this purpose instead. Note the use of the linearized `transparency` instead of the previously un-linearized `mayaTransparency` here:
https://github.com/Autodesk/maya-usd/pull/707/files#diff-5fe2e05011c04068f0f7249a36061532R138
Both of these behaviors seem somewhat dubious. It doesn't really seem like the shading mode exporter should be authoring `displayOpacity` of the bound gprim, since that is more a …
> use the un-linearized lambert transparency to author displayOpacity when using displayColors shading mode

- build.py
When running build.py with python3, each line starts with 'b and ends with \n' making it hard to read the log.
Using codec module fixes the problem: https://docs.python.org/3/library/codecs.html
It appears the same fix was also introduced in USD's build_usd.py few months ago:
```
Commit 4f0a1640
by sunyab, 25/03/2020 04:43 PM
committed by pixar-oss
parent 7f64522e
child a9c9786e
```
> Fix build script with python 3 where each line starting with 'b and ends with \n' making it hard to read the log.

- doc/build.md
- plugin/al/plugin/AL_USDMayaTestPlugin/test_translators_PythonBindings.cpp
- plugin/pxr/maya/lib/usdMaya/testenv/testUsdMayaXformStack.py
- test/lib/usd/translators/testUsdExportEulerFilter.py
- test/lib/usd/translators/testUsdExportFilterTypes.py
- test/lib/usd/translators/testUsdImportCamera.py
- test/lib/usd/translators/testUsdImportXforms.py
This removes the usage of `future`, `past`, and `builtin.zip` in tests. This simplifies the Python environment setup when attempting to run tests on currently released versions of Maya with Python 2, but should still support Python 3 as well.
Note that this is only part of the `future` removal. The other part of it takes place in #761 for the `pxrUsdMayaGL` tests.
No future. No past. Only now. :)
> remove test dependencies on Python future past, and builtin.zip

- lib/mayaUsd/ufe/UsdUndoInsertChildCommand.cpp
- lib/mayaUsd/ufe/UsdUndoInsertChildCommand.h
This PR addresses the random undo/redo crash after performing multiple re-parenting operations.
> MAYA-106376: fix undo/redo re-parenting crash due to accessing a stale prim.

- cmake/test.cmake
- test/lib/ufe/CMakeLists.txt
- test/lib/ufe/testRotatePivot.py
Add an automated test for setting the UFE rotate pivot through the Maya move command.
> Add test for setting rotate pivot through move command.

- lib/mayaUsd/ufe/CMakeLists.txt
- lib/mayaUsd/ufe/Global.cpp
- lib/mayaUsd/ufe/ProxyShapeHierarchy.cpp
- lib/mayaUsd/ufe/ProxyShapeHierarchy.h
- lib/mayaUsd/ufe/ProxyShapeHierarchyHandler.cpp
- lib/mayaUsd/ufe/ProxyShapeHierarchyHandler.h
- lib/mayaUsd/ufe/UsdContextOps.cpp
- lib/mayaUsd/ufe/UsdHierarchy.cpp
- lib/mayaUsd/ufe/UsdHierarchy.h
- lib/mayaUsd/ufe/UsdHierarchyHandler.cpp
- lib/mayaUsd/ufe/UsdHierarchyHandler.h
- lib/mayaUsd/ufe/UsdSceneItemOps.cpp
- lib/mayaUsd/ufe/UsdUIInfoHandler.cpp
- lib/mayaUsd/ufe/UsdUIInfoHandler.h
- test/lib/ufe/CMakeLists.txt
- test/lib/ufe/testChildFilter.py
- test/lib/ufe/testContextOps.py
- test/lib/ufe/testUIInfoHandler.py
* Implemented new UFE interface UIInfoHandler.
* Added support for child filtering with new Ufe::Hierarchy method "filteredChildren" and Ufe::HierarchyHandler method "childFilter". In USD we support a single child filter for "Inactive Prims".
* Added context menu for "{Active/Deactivate} Prim".
* Added test cases for new interface, new methods and new menu.
> MAYA-106188 - As a user, I would like to activate and deactivate prims

- doc/build.md
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
This function was a vestige of the legacy Hydra implementation and now no
longer does anything. It was removed in core USD commit https://github.com/PixarAnimationStudios/USD/commit/0c5c150e70c646226b9e6ffbb932c5187600efad.
`InvalidateBuffers()` hasn't done anything (for non-legacy Hydra) since at least USD 19.07, so this change should build against all supported earlier release of core USD as well. It is required for building with the current tip of the dev branch, https://github.com/PixarAnimationStudios/USD/commit/ac8f6d4be9bc20e7ff6ad98843d93e7a1cefca0b.
> [plugin/al] remove call to UsdImagingGLEngine::InvalidateBuffers()

- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawAndTransform.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawColorAccuracy.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawColors.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawLighting.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawPerformance.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawPurpose.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawTimeSampled.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawUsdChangeProcessing.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawVisibility.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDuplicatePerformance.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeLiveSurface.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeRendererSceneMessages.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeSelectionPerformance.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testPxrUsdMayaGL.py
- test/testUtils/fixturesUtils.py
I realized that the interactive tests I added were all dumping their output into the same directory where the tests live.
This change modifies `fixturesUtils` a bit so that the standalone initialization can be turned off, and then all of the pxrUsdMayaGL tests were updated to use `fixtureUtils`.
> use fixturesUtils for pxrUsdMayaGL tests

- plugin/adsk/scripts/CMakeLists.txt
- plugin/pxr/maya/plugin/pxrUsdPreviewSurface/CMakeLists.txt
Using CMAKE_SOURCE_DIR here breaks when the **maya-usd** project is included in another parent project
> [CMake] Use PROJECT_SOURCE_DIR for nested projects.

- plugin/pxr/maya/lib/usdMaya/testenv/testUsdMayaDiagnosticDelegate.py
- test/lib/usd/translators/testUsdExportStripNamespaces.py
Fix Python 3 warnings (also works in Python 2).
See https://docs.python.org/3.3/library/unittest.html#deprecated-aliases
> Fix Python 3 warnings

- lib/mayaUsd/ufe/UsdUndoInsertChildCommand.cpp
- lib/mayaUsd/ufe/private/Utils.cpp
- lib/usd/utils/util.cpp
- lib/usd/utils/util.h
- test/lib/ufe/testRename.py
This PR makes a major improvement in the way "Rename" restriction behaves in Maya.
> MAYA-105175: Rewrote the rename restriction algorithm from scratch to cover more edge cases.

- doc/build.md
- lib/mayaUsd/render/pxrUsdMayaGL/sceneDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
These changes will build against all supported earlier releases of core USD, but unfortunately one commit (https://github.com/Autodesk/maya-usd/commit/8f2708f5579ccaa6b6d8844acfe912d63b4366bc) will only build with core USD dev branch commits as of https://github.com/PixarAnimationStudios/USD/commit/37b4df75520c88fc464c6ae5a776fc8b4621dd15 or later.
I'll kick off a pre-flight anyway, but I expect that any builds using a core USD dev commit earlier than that may fail.
> more updates from recent Hydra changes

- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeLiveSurface.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeSelectionPerformance.py
I'm hoping this might help resolve the issue raised by @HamedSabri-adsk and @kxl-adsk in https://github.com/Autodesk/maya-usd/pull/761#discussion_r487392722.
This is unfortunately just a shot in the dark though since I'm not able to reproduce the failed assertions when Maya exits on my end.
> delete testing UI and resource handles in live surface and selection performance tests

- lib/mayaUsd/render/mayaToHydra/renderOverride.cpp
- lib/mayaUsd/render/mayaToHydra/renderOverride.h
- lib/usd/hdMaya/adapters/proxyAdapter.h
- lib/usd/hdMaya/delegates/delegate.h
- lib/usd/hdMaya/delegates/proxyDelegate.cpp
- lib/usd/hdMaya/delegates/proxyDelegate.h
- lib/usd/hdMaya/delegates/sceneDelegate.cpp
- lib/usd/hdMaya/delegates/sceneDelegate.h
The change requires new Maya APIs and needs to be merged after Maya PR119 is published.
> MAYA-106477 selection and point snapping support for mtoh

- cmake/modules/FindMaya.cmake
- cmake/test.cmake
This should address the issue raised in #805. Since the interactive tests launch the `maya` binary rather than `mayapy` or `mayapy2`, they were always running using Python 3 in Maya 2021/preview releases.
In addition to setting `MAYA_PY_EXECUTABLE` to either `mayapy` or `mayapy2` in `FindMaya.cmake`, we now also set `MAYA_PY_VERSION` to either `2` or `3` as appropriate. We then use that CMake variable to set `MAYA_PYTHON_VERSION` when setting up the environment for running the tests. Maya 2020 and earlier will simply ignore that environment variable.
I've verified that the interactive tests pass running Maya PR 119 and Python 2 on Linux. I'm not actually setup to build against Python 3 yet, so if someone is able to verify that configuration for me, that would be great. These tests get …
> fix Python version handling for interactive tests

- .clang-format
- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/ExportTranslator.h
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.h
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Scope.h
- plugin/al/translators/Mesh.h
- plugin/al/translators/NurbsCurve.h
Draft #690 applied clang-format for the entire repository. What we found out was that we no longer can build maya-usd. This PR makes necessary fixes to address it.
> Necessary fixes required before we can apply clang format

- lib/mayaUsd/render/mayaToHydra/plugin.cpp
- lib/mayaUsd/render/mayaToHydra/renderGlobals.cpp
- lib/mayaUsd/render/mayaToHydra/renderGlobals.h
- lib/mayaUsd/render/mayaToHydra/renderOverride.cpp
- lib/mayaUsd/render/mayaToHydra/renderOverride.h
- lib/mayaUsd/render/mayaToHydra/utils.cpp
- lib/mayaUsd/render/mayaToHydra/viewCommand.cpp
There are a few issues with the current render-settings / defaultRenderGlobals, that make it difficult for a delegate to merge _USDRenderSettings_ and _HdDelegate::SetRendererSetting_.  The larger goal of editing a USDRenderSettings and applying a delegates schema aren't dealt with here, as the PR seems large enough just to address the current issues:
- Largest issue is that if a delegate provides a USD-namespaced setting, **mtoh** will error out when trying to set it.
- If any two delegates have the same setting (because they can't namespace) then they will stomp one another.
- User state isn't honored when not saved into a scene, this is problematic for jumping between files as the user may have the delegate up in a specific way optimized for the task.
- Updates to a single setting …
> [mtoh] Refactor settings / defaultRenderGlobals storage

- doc/build.md
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Engine.cpp
This parameter was not actually being used by Hydra, so it should be fully compatible with older releases of USD. This change is *required* to build against the current tip of core USD dev branch.
This change corresponds to core USD commit https://github.com/PixarAnimationStudios/USD/commit/722bbab50b900ea2c1f9a75e975564cd16fb06c4.
> remove unused hitMode field from HdxPickTaskContextParams

- lib/mayaUsd/nodes/proxyShapePlugin.cpp
While the USD proxy shape classes included in the maya-usd repo all use either the (legacy) Pixar batch renderer *or* the Viewport 2.0 render delegate, there may be other custom node types that may or may not leverage USD but still want to take advantage of aggregated drawing using Hydra.
As an example, internally at Pixar we have a custom Maya shape node that is a severely stripped down approximation of a `UsdGeomPointInstancer`. This shape maintains its own data structures as a mix of USD and non-USD data, but it still uses the `PxrMayaHdImagingShape` and the Pixar batch renderer for drawing. I'm not sure whether other studios have custom shape nodes that leverage the Pixar batch renderer and its shape adapter system in this way, but it was definitely written with the intention of …
> always register and de-register the PxrMayaHdImagingShape and its draw override

- test/lib/mayaUsd/render/pxrUsdMayaGL/ProxyShapeDrawColorAccuracyTest/ProxyShapeDrawColorAccuracyTest.ma
This is intended to address #265.
The Storm-based Pixar batch renderer (poorly) supports depth map shadows but not ray-traced shadows, while the Viewport 2.0 render delegate supports both. The `directionalLight` in the Maya scene for the `testProxyShapeDrawColorAccuracy` test was set to use ray-traced shadows (which is the default). This meant that the "all_lights" image written by the test would not include shadows when run with the Pixar batch renderer, but it would include a very noisy shadow when run with the Viewport 2.0 render delegate, since the geometry is just a very simple cube.
Shadows are not important in the functionality being exercised by this test, so this change simply disables shadows on the `directionalLight`.
> disable shadows on the directionalLight in the Maya scene for the testProxyShapeDrawColorAccuracy test

- lib/mayaUsd/ufe/UsdHierarchy.cpp
- lib/mayaUsd/ufe/UsdUndoAddNewPrimCommand.cpp
- lib/mayaUsd/ufe/UsdUndoInsertChildCommand.cpp
- lib/mayaUsd/ufe/UsdUndoRenameCommand.cpp
- lib/mayaUsd/ufe/Utils.cpp
- lib/mayaUsd/ufe/Utils.h
- lib/mayaUsd/ufe/private/Utils.cpp
- lib/usd/utils/ForwardDeclares.h
- lib/usd/utils/util.cpp
- lib/usd/utils/util.h
The goal of this PR is to allow clients to be able to rename prims that are **internally referenced** by other prims and not worry about breaking them. The same workflow can also later be applied to other composition arcs ( e.g inherits or specializes ).
> MAYA-106755: Support automatic updating of internal references when the path they are referencing has changed.

- plugin/pxr/maya/lib/usdMaya/userExportedAttributesUI.py
Maya 2020 and later use Qt/PySide2 5.12.5, where `QStringListModel` is exported to Python with QtCore, which is also where it lives in C++. Maya 2019 and earlier use Qt 5.6.1 and PySide2 2.0.0-alpha, where `QStringListModel` was incorrectly exported with QtGui.
See this bug for more detail:
https://bugreports.qt.io/browse/PYSIDE-614
This change addresses #366. I also took this opportunity to remove support for Maya 2016 and earlier.
> handle namespace migration of QStringListModel between Maya 2019 and Maya 2020 in userExportedAttributesUI

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
from it and so we don't know to bring them back. The easy solution is to reset everything when excluded prims changes, that gives us the correct result slowly. We don't have any workflows built on top of this right now so leaving the performance issue in the backlog.
In addition to fixing the defect I also cleaned up how we understand changes to the proxy shape in the render delegate. I've tried to concentrate all the checks for invalid data into a new function _ClearInvalidData. Then the rest of the code after that (_InitRenderDelegate, _Populate, etc) doesn't directly check the _proxyShapeData for changes. Instead it looks at the data it is supposed to generate and does work based on that (similar to how it works on the first frame when we create the proxyRenderDelegate). I think that …
> MAYA-107249 When excluded prims changes we don't know if some prims were removed 

- test/lib/usd/translators/UsdExportSkeletonTest/baseline/UsdExportSkeletonWithoutBindPose.usda
Internally, we have a post-process to the `testUsdExportSkeleton` test that diffs the generated USD against this baseline. Following the merge of PR #822, the test began to fail since `displayColor` was no longer being exported with `shadingMode=none`.
> update baseline USD file for testUsdExportSkeleton test following #822

- test/lib/usd/translators/testUsdExportRenderLayerMode.py
Internally, we still run the `testUsdExportRenderLayerMode` test with `MAYA_ENABLE_LEGACY_RENDER_LAYERS` turned on. The test began failing following the merge of PR #822 since `displayColor` was no longer being exported. This change gets the test passing again by turning on the `exportDisplayColor` when calling `cmds.usdExport()`.
> enable exportDisplayColor in testUsdExportRenderLayerMode test following #822

- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawColors.py
Internally, we have a post-process to the `testProxyShapeDrawColors` test that diffs a render generated from the viewport against a baseline. Following the merge of PR #822, the test began to fail since `displayColor` was no longer being exported, so the color represented in the image was different. This change turns on the `exportDisplayColor` option to `cmds.usdExport()` so that `displayColor` is present in the exported USD, and the rendered image matches the baseline again.
> enable exportDisplayColor in testProxyShapeDrawColors test following #822

- lib/mayaUsd/ufe/UsdTransform3d.cpp
Previously, attempting to create an undoable command to set the scale pivot was an error, as Maya would never ask for such a capability.  With UFE 0.2.25 support, it does, and run-times that don't support a separate scale pivot must return a null command.
> Absence of scale pivot support is not an error.

- doc/build.md
This identifies core USD release 20.11 as a supported release of USD, as well as its corresponding core USD dev branch commit:
https://github.com/PixarAnimationStudios/USD/commit/edc7cde8c815dc560188f1281963b3091bbd6db4
> update build.md to reflect support for core USD release 20.11

- lib/usd/pxrUsdPreviewSurface/usdPreviewSurfaceReader.cpp
- test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
`useSpecularWorkflow` is an int-typed input attribute in USD, but it's a boolean attribute in Maya, so the value needs to be type-converted during import. The conversion was already being done for export.
> fix import of "useSpecularWorkflow" input on UsdPreviewSurface shaders

- lib/usd/translators/shading/usdLambertReader.cpp
- lib/usd/translators/shading/usdLambertReader.h
- lib/usd/translators/shading/usdLambertWriter.cpp
We have some internal test cases that were previously using the `displayColor` shadingMode, and in switching them over to use the new round robin-style shadingMode handling from #822 instead, I noticed that `lambert` shaders were not having their `transparency` attribute properly round-tripped out to USD as `opacity` and then back.
We could definitely use some better unit testing in this area, but I wanted to get the fix for this up sooner than later.
> add translation support between lambert transparency and UsdPreviewSurface opacity

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/render_delegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/render_delegate.h
- lib/mayaUsd/render/vp2ShaderFragments/BasisCurvesCubicCPVHull.xml
- lib/mayaUsd/render/vp2ShaderFragments/BasisCurvesCubicCPVPassing.xml
- lib/mayaUsd/render/vp2ShaderFragments/BasisCurvesCubicCPVShader.xml
- lib/mayaUsd/render/vp2ShaderFragments/BasisCurvesCubicColorDomain.xml
- lib/mayaUsd/render/vp2ShaderFragments/BasisCurvesCubicDomain_GLSL.xml
- lib/mayaUsd/render/vp2ShaderFragments/BasisCurvesCubicDomain_HLSL.xml
- lib/mayaUsd/render/vp2ShaderFragments/BasisCurvesLinearCPVHull.xml
- lib/mayaUsd/render/vp2ShaderFragments/BasisCurvesLinearCPVPassing.xml
- lib/mayaUsd/render/vp2ShaderFragments/BasisCurvesLinearCPVShader.xml
- lib/mayaUsd/render/vp2ShaderFragments/BasisCurvesLinearColorDomain.xml
- lib/mayaUsd/render/vp2ShaderFragments/BasisCurvesLinearDomain_GLSL.xml
- lib/mayaUsd/render/vp2ShaderFragments/BasisCurvesLinearDomain_HLSL.xml
- lib/mayaUsd/render/vp2ShaderFragments/CMakeLists.txt
- lib/mayaUsd/render/vp2ShaderFragments/UsdPrimvarColor.xml
- lib/mayaUsd/render/vp2ShaderFragments/shaderFragments.cpp
* Supported CPV for basisCurves complexity level 1
* Supported curve basis functions (including Bezier, BSpline and CatmullRom) for cubic basisCurves complexity level 1.
* Disabled complexity level 1 drawing for basisCurves on Maya 2018/2019/2020 because the necessary Maya API to allow plug-ins to build a complete tessellation shader graphs are not included in those releases.
> MAYA-105537 Add CPV support and curveBasis support for basiscurves complexity level 1

- lib/mayaUsd/fileio/utils/meshWriteUtils.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/test_translators_NurbsCurveTranslator.cpp
- plugin/al/usdmayautils/AL/usdmaya/utils/DgNodeHelper.cpp
- plugin/al/usdmayautils/AL/usdmaya/utils/DiffPrimVar.cpp
- plugin/al/usdmayautils/AL/usdmaya/utils/MeshUtils.cpp
GCC 9 will warn if using memcopy to overwrite the memory area of a non-POD class. The warning is correct, but in these cases, we know that these classes are POD so we can proceed and indicate the intent with a void* cast.
> Devtoolset-9 fixes

- lib/usd/translators/shading/usdLambertWriter.cpp
- lib/usd/translators/shading/usdMaterialWriter.cpp
- lib/usd/translators/shading/usdMaterialWriter.h
- lib/usd/translators/shading/usdStandardSurfaceWriter.cpp
These changes ensure that the `normal` shader input written by the lambert and standardSurface (and descendant) shader writers use the `Normal3f` type name when creating and authoring the input rather than just `Float3`. The existing call to `Converter::getUsdTypeName()` is not able to determine the role aspect of the type name from simply inspecting the Maya attribute plug, so an optional `inputTypeName` parameter was added to `AuthorShaderInputFromShadingNodeAttr()` and `AuthorShaderInputFromScaledShadingNodeAttr()` to handle cases like that.
> author UsdPreviewSurface "normal" input using Normal3f type name

- lib/mayaUsd/fileio/translators/translatorCamera.cpp
Some additional fallout following #822. This is a workaround specific to `ReadToCamera()`, but we may want to reconsider how/when the `UsdPreviewSurface` shading mode conversion is registered to fix this for all potential cases.
Code that links against mayaUsd but otherwise does not load any Maya plugins currently encounters an error that looks like this when it calls `ReadToCamera()`:
```
Error in '_shadingModesImportArgs' at line 244 in file ext/mayapkg/maya_open_source/maya-usd/lib/mayaUsd/fileio/jobs/jobArgs.cpp : 'Unknown material conversion 'UsdPreviewSurface''```
```
The issue is that the `UsdPreviewSurface` shading conversion is specified as the default in the default args dictionary in the mayaUsd core, but that conversion is only registered when one of the `mayaUsdPlugin`, …
```
> disable shading import in UsdMayaTranslatorCamera::ReadToCamera()

- lib/usd/translators/shading/usdLambertWriter.cpp
- lib/usd/translators/shading/usdMaterialWriter.cpp
- lib/usd/translators/shading/usdMaterialWriter.h
- lib/usd/translators/shading/usdStandardSurfaceWriter.cpp
This addresses some test failures we started seeing when adapting them to use the new cascading `shadingMode` setup. The tests do straight USD file diffs of an initial export from Maya versus a re-import and re-export of that initial export. Because the initial export uses the lambert shader writer, `emissiveColor` and `specularColor` were both getting exported as black, which is unnecessary since that's the default value for those inputs anyway:
https://github.com/PixarAnimationStudios/USD/blob/d8a405a1344480f859f025c4f97085143efacb53/pxr/usdImaging/plugin/usdShaders/shaders/shaderDefs.usda#L34
When re-imported, those shaders became usdPreviewSurface nodes in Maya instead of lambert nodes. The reader sets those attributes using the default values which has no effect. When the …
> export lambert and descendants more sparsely

- lib/mayaUsd/fileio/jobs/writeJob.cpp
- lib/mayaUsd/fileio/writeJobContext.cpp
- plugin/al/docs/importExport.md
- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/Export.cpp
- test/lib/usd/translators/UsdImportInstancesTest/ComplexScenario_optimized.usda
- test/lib/usd/translators/UsdImportInstancesTest/ComplexScenario_unoptimized.usda
- test/lib/usd/translators/UsdImportInstancesTest/SimpleScenario_optimized.usda
- test/lib/usd/translators/UsdImportInstancesTest/SimpleScenario_unoptimized.usda
- test/lib/usd/translators/UsdImportInstancesTest/UsdExportInstancesTest_optimized.usda
- test/lib/usd/translators/UsdImportInstancesTest/UsdExportInstancesTest_original.usda
- test/lib/usd/translators/UsdImportInstancesTest/UsdExportInstancesTest_unoptimized.usda
- test/lib/usd/translators/testUsdExportInstances.py
- test/lib/usd/translators/testUsdExportShadingInstanced.py
- test/lib/usd/translators/testUsdImportInstances.py
Split from [PR 856](https://github.com/Autodesk/maya-usd/pull/856) to keep diff smaller.
Global search and replace, as requested in [PR 794](https://github.com/Autodesk/maya-usd/pull/794)
> MAYA-106489 - Rename InstanceSources to be Maya-specific

- lib/usd/translators/shading/usdFileTextureWriter.cpp
- lib/usd/translators/shading/usdUVTextureReader.cpp
- test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
On export, if the color space of a file node was set (differs from the global rule) then we export it as a colorSpace metadata on the file UsdShadeInput.
On import, if there is a colorSpace on the USD file input, we set it in the Maya file node.
> MAYA-106892 - Export and import color space information on file nodes

- lib/mayaUsd/ufe/StagesSubject.cpp
This PR fixes the cases where subtree invalidation doesn't occur in the outliner where all the children are the descendant of stage proxy shape ( a.k.a pseudo-root).
This issue became obvious during the current ongoing work on reordering support where outliner stopped to refresh.
> MAYA-107591: Subtree invalidation support on StageProxy ( a.k.a pseudo-root ).

- test/lib/ufe/testParentCmd.py
- test/lib/ufe/testSelection.py
- test/testUtils/mayaUtils.py
Fixes relative paths to test-scenes copied to **${CMAKE_BINARY_DIR}** when compiled as a sub-project.
* testParentCmd.py, testSelection.py
Refactor duplicate **os.path.join** and **cmds.file** across other tests scenes into one place
* other tests
> [CMake] Add mayaUtils.openTestScene and mayaUtils.getTestScene

- lib/mayaUsd/ufe/CMakeLists.txt
- lib/mayaUsd/ufe/wrapGlobal.cpp
- test/testUtils/mayaUtils.py
- test/testUtils/usdUtils.py
We're starting to work more UFE awareness into some of our internal pipeline tools and having the UFE runtime IDs more readily accessible to client code would be handy.
> wrap UFE runtime ID getters for Maya and USD to Python

- plugin/pxr/maya/lib/usdMaya/usdTranslatorImport.mel
The existing call to `usdTranslatorImport_SetOptionMenuByAnnotation()` was replaced with a call to `usdTranslatorImport_SetShadingOptionMenuByAnnotation()` in #865, but the latter does not exist anywhere. This reverts that change.
> fix call to non-existent function in pxrUsd plugin's usdTranslatorImport

- lib/mayaUsd/ufe/CMakeLists.txt
- lib/mayaUsd/ufe/StagesSubject.cpp
- lib/mayaUsd/ufe/UsdRotateUndoableCommand.h
- lib/mayaUsd/ufe/UsdTransform3d.cpp
- lib/mayaUsd/ufe/UsdTransform3d.h
- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.h
- lib/mayaUsd/ufe/UsdTranslateUndoableCommand.h
- lib/mayaUsd/ufe/private/CMakeLists.txt
- lib/mayaUsd/ufe/private/UfeNotifGuard.cpp
- lib/mayaUsd/ufe/private/UfeNotifGuard.h
- plugin/adsk/plugin/plugin.cpp
- test/lib/ufe/testComboCmd.py
This pull request provides an initial implementation of the Maya transform stack in maya-usd.  As previously, creation of Ufe::Transform3d is structured as a chain of responsibility: in this pull request, creation of a Maya transform stack is the first link in the chain, and therefore will be considered first to determine a match.
The implementation is incomplete: undo / redo does not remove added transform ops in the ordered ops vector, single-axis rotations are buggy and move along two axes (!), and the rotate axis and shear components are unimplemented, though the UFE interface exists.  Additionally, a fair amount of undoable command code could be shared with the UsdTransform3dMatrixOp class, but this is not addressed in this pull request.
The core files in the review are …
> Tremblp/maya 106087/maya xform stack 01

- lib/mayaUsd/ufe/UsdUndoDuplicateCommand.cpp
* Outliner was being sent incorrect UFE notif (SubtreeInvalidate) when duplicating an item. It should get ObjectAdd.
> MAYA-107246 - USD: outliner does not update when duplicating items

- lib/usd/pxrUsdPreviewSurface/usdPreviewSurface.cpp
> Allow usdPreviewSurface to exist without input connections

- .gitignore
This adds some general setup exclusions to the Git repo. This should apply to all Jetbrains users and a few CLI editor folks.
Just putting this in to trial our process of getting PR's in. We're in the process of cleaning up some larger internal changes for submission as well.
For details:
- `.idea/cmake-build-*` are primarily for CLion users
- The remainder are primarily for vim/emacs folks with their completions and cmake integration setups.
> Organize Gitignore, and add more editor,platform and build specific patterns

- plugin/al/CMakeLists.txt
- plugin/al/lib/AL_USDMaya/CMakeLists.txt
- plugin/al/schemas/AL/usd/schemas/maya/tests/CMakeLists.txt
- plugin/al/usdmayautils/AL/usdmaya/utils/CMakeLists.txt
This PR is a reflection of our internal changes to support Boost_NO_BOOST_CMAKE=ON for using boost::python along custom paths. 
For a set of Boost Versions, the CMake setup made it difficult to use your own Boost library paths.
Prior to Boost 1.70, certain versions of CMake failed to find Boosts Python library due to the addition of version suffixes.
From Boost 1.70 onwards, it is possible for Boost to optionally support CMake files, but can also be problematic if you want to sub in your own paths. Occasionally without Boost_NO_BOOST_CMAKE, CMake will resolve to other versions of boost even if you specify an explicit boost root path. Hence the need for Boost_NO_BOOST_CMAKE.
See https://stackoverflow.com/a/63094072 for more details.
This doesn't appear to affect any other of the Boost …
> Add support for Boost_NO_BOOST_CMAKE=ON for Boost::python

- lib/mayaUsd/ufe/UsdSceneItemOps.cpp
- lib/mayaUsd/ufe/UsdUndoDuplicateCommand.cpp
- lib/mayaUsd/ufe/UsdUndoDuplicateCommand.h
- test/lib/ufe/testDuplicateCmd.py
There is a utility function in Utils that can be shared between some of the commands (e.g. duplicate and rename).  Using it to get the correct logic and proper error message.
There is still a question about what the exact logic/message should be for the commands, but if we want to change it then that will happen in a separate PR.
> MAYA-103547 Use the common utility function to check error conditions

- lib/mayaUsd/ufe/UsdAttributes.cpp
- plugin/al/mayautils/AL/maya/event/MayaEventManager.cpp
- plugin/al/mayautils/AL/maya/event/MayaEventManager.h
- plugin/al/mayautils/AL/maya/utils/FileTranslatorOptions.cpp
After PR #890 we still had few files that weren't fully formatted by clang-format
```
modified:   lib/mayaUsd/ufe/UsdAttributes.cpp
modified:   plugin/al/mayautils/AL/maya/event/MayaEventManager.cpp
modified:   plugin/al/mayautils/AL/maya/event/MayaEventManager.h
modified:   plugin/al/mayautils/AL/maya/utils/FileTranslatorOptions.cpp
```
For some reason, clang-format required to be applied twice to the above files (and to be precise, three times for lib/mayaUsd/ufe/UsdAttributes.cpp).
It's not something I was aware of, but luckily it's only these 4 files we missed.
> Apply clang-format two more times to make sure we have everything formatted

- lib/mayaUsd/fileio/jobs/writeJob.cpp
- lib/mayaUsd/utils/util.cpp
- lib/mayaUsd/utils/util.h
- test/lib/usd/translators/CMakeLists.txt
- test/lib/usd/translators/testUsdExportLayerAttributes.py
The current exporter behavior writes out frames as if the USD is a the current scenes uiUnits, but does not actually set the fps attributes in the exported layer. This causes downstream readers to treat it as 24fps as is default.
This change adds both TimeCodesPerSecond and FramesPerSecond, if the exporter is exporting animation. This will allow downstream readers to playback at the correct timing.
As a side note...it is surprising that MTimeUnit doesn't have an API method to convert to float values. Would be great in the future if that was exposed, rather than resorting to a hardcoded mapping here.
> Add FPS metadata to exported usd files if non static

- test/lib/ufe/testSelection.py
* Updated UFE Selection test now that Maya select command supports UFE.
> MAYA-107600 - UFE/MEL - make select command UFE aware

- lib/usd/pxrUsdPreviewSurface/AEusdPreviewSurfaceTemplate.mel
- lib/usd/pxrUsdPreviewSurface/usdPreviewSurface.cpp
- lib/usd/pxrUsdPreviewSurface/usdPreviewSurface.h
- lib/usd/pxrUsdPreviewSurface/usdPreviewSurfaceReader.cpp
- lib/usd/pxrUsdPreviewSurface/usdPreviewSurfaceWriter.cpp
- test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
Opacity Threshold is an attribute on the USD preview surface shader that wasn't previously exposed to Maya, however is useful for artists to define the cutoff level for their opacity maps.
This exposes it in the attribute editor, makes sure it serializes properly to USD and that it clips the opacity accordingly. 
There's a very minimal test included here that we used to check after merging upstream commits, but I hope we can add more material serialization tests in the future so I'm including it here.
> Add opacity threshold to USD Preview Surface Shader

- lib/mayaUsd/ufe/UsdSceneItem.cpp
USD method UsdSchemaRegistry::GetSchemaTypeName() was only added in v20.05.
> USD method GetSchemaTypeName() was added in v20.05

- plugin/adsk/scripts/AEmayaUsdProxyShapeTemplate.mel
* First pass at cleaning up the Proxy Shape AE template.
> MAYA-107239 - Proxy Shape AE template cleanup

- doc/build.md
- lib/mayaUsd/render/pxrUsdMayaGL/sceneDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- lib/usd/hdMaya/utils.cpp
Just a few minor changes to adapt to the following core USD commits recently pushed to the dev branch:
https://github.com/PixarAnimationStudios/USD/commit/bcc961554c3049a7546813efde7cc304a9d6a0d5
https://github.com/PixarAnimationStudios/USD/commit/84cacd09d1a0e0a1886b2a2494a16ad2625898ba
All supported releases of USD are still supported with these changes. The build.md was updated to reflect support up to the current dev branch commit.
> updates for building with latest post-20.11 dev branch of core USD

- cmake/compiler_config.cmake
- lib/mayaUsd/commands/baseListShadingModesCommand.cpp
- lib/mayaUsd/fileio/instancedNodeWriter.cpp
- lib/mayaUsd/fileio/registryHelper.cpp
- lib/mayaUsd/fileio/utils/readUtil.cpp
- lib/mayaUsd/utils/util.cpp
- lib/usd/hdMaya/adapters/materialNetworkConverter.cpp
- lib/usd/utils/util.cpp
There were several small warnings that were tripping up our compilation when trying to compile with -Wall
They're all errors like this:
```
/Users/dhruvgovil/Projects/maya-usd/lib/mayaUsd/commands/baseListShadingModesCommand.cpp:117:25: warning: loop variable 'c' of type 'const pxrInternal_v0_20__pxrReserved__::TfToken' creates a copy from type 'const pxrInternal_v0_20__pxrReserved__::TfToken' [-Wrange-loop-analysis]
for (const auto c : UsdMayaShadingModeRegistry::ListMaterialConversions()) {
```
> Fixed current compiler warnings

- cmake/compiler_config.cmake
Copied verbatim from https://github.com/PixarAnimationStudios/USD/commit/acf7c132affd6489b2f96c8b94d689e7508a90e6
> Fix missing ARCH_CONSTRUCTOR code with VS2019

- plugin/adsk/scripts/mayaUsd_createStageFromFile.mel
- plugin/adsk/scripts/mayaUsd_createStageWithNewLayer.py
- test/lib/CMakeLists.txt
- test/lib/testMayaUsdCreateStageCommands.py
* Connected time to proxy shape node
> MAYA-107484 - Time is not connected when creating a new empty USD stage

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/ufe/UsdStageMap.cpp
- lib/usd/hdMaya/delegates/proxyDelegate.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeUI.cpp
* Use new Ufe::NamedSelection "MayaSelectTool" for viewport selection, rather than modifying UFE global selection directly.
> MAYA-105322 - No undo support for viewport selections of USD objects

- lib/mayaUsd/commands/baseListShadingModesCommand.cpp
- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/ufe/Global.cpp
We are testing https://github.com/marketplace/actions/clang-format-lint and discovered that already some files got in without proper formatting. Fixing it in this PR.
> Some files got in without clang-format applied

- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/ufe/StagesSubject.cpp
- lib/mayaUsd/ufe/wrapUtils.cpp
- plugin/adsk/scripts/AETemplateHelpers.py
- plugin/adsk/scripts/AEmayaUsdProxyShapeTemplate.mel
- plugin/adsk/scripts/CMakeLists.txt
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.h
- test/lib/ufe/testAttribute.py
- test/lib/ufe/testAttributes.py
- test/lib/ufe/testComboCmd.py
- test/lib/ufe/testContextOps.py
- test/lib/ufe/testDeleteCmd.py
- test/lib/ufe/testDuplicateCmd.py
- test/lib/ufe/testGroupCmd.py
- test/lib/ufe/testMatrices.py
- test/lib/ufe/testMayaPickwalk.py
- test/lib/ufe/testMoveCmd.py
- test/lib/ufe/testObject3d.py
- test/lib/ufe/testParentCmd.py
- test/lib/ufe/testRename.py
- test/lib/ufe/testRotateCmd.py
- test/lib/ufe/testScaleCmd.py
- test/lib/ufe/testSceneItem.py
- test/lib/ufe/testTransform3dTranslate.py
- test/testUtils/mayaUtils.py
MAYA-107386 As a user, on the stage AE template I'd like to connect to time
MAYA-107350 As a user, on the stage AE template I'd like to see what my default prim is
MAYA-107338 As a user, on the stage AE template I'd like to see what my Root Layer is
MAYA-107273 As a user, on the stage AE template I'd like to toggle Purpose=Default
* Create new AETemplatesHelpers.py file which is used by the MEL templates to query USD (thru python API).
* Organized proxy shape template in sections: "Stage", "Stage Source" and "Stage Display".
* Suppressed 'Stage Cache ID' and 'Out Stage Cache ID'.
* Added new non-editable text fields (for display purposes only) for "Root Layer" and "Default Prim".
* Added tooltips to some controls.
> Proxy Shape AE Template - Part 2

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
If a Rprim has no extent, we will assign a null bounding box to its render item and
Maya will compute the bounding box from the position data. With the bounding box
the render item will be eligible for consolidation.
> MAYA-108270 Improve draw performance for Rprims without extent

- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
- Adjust UndoBlock to capture the opFunc functor that sets/adds to the transform op order.
- Clean up old logics around recreateOp, _prevOpValue, _attrName.
> More code clean up in UsdTransform3dMayaXformStack

- lib/mayaUsd/render/vp2RenderDelegate/CMakeLists.txt
- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- lib/mayaUsd/render/vp2RenderDelegate/material.h
- lib/mayaUsd/render/vp2RenderDelegate/render_delegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/render_delegate.h
- lib/mayaUsd/render/vp2RenderDelegate/shader.cpp
- lib/mayaUsd/render/vp2RenderDelegate/shader.h
Implemented a shader instance cache to allow reuse of shader effect for duplicate material networks.
* This avoids repetitive compilation of the same shader effect, and thus reduces the load time.
* This removes a blocker for material consolidation, and thus will reduce the playback time. Maya has some other blockers for material consolidation that should be fixed separately.
> Reuse shader effect for duplicate material networks.

- lib/mayaUsd/render/vp2ShaderFragments/usdPreviewSurfaceLighting.xml
The fragment used `#define` which leaked and broke other bragments.
> MAYA-105734 Fix broken lighting fragment

- lib/mayaUsd/resources/ae/CMakeLists.txt
- lib/mayaUsd/resources/ae/base/ae_template.py
- lib/mayaUsd/resources/ae/camera/ae_template.py
- lib/mayaUsd/resources/ae/capsule/ae_template.py
- lib/mayaUsd/resources/ae/cone/ae_template.py
- lib/mayaUsd/resources/ae/cube/ae_template.py
- lib/mayaUsd/resources/ae/cylinder/ae_template.py
- lib/mayaUsd/resources/ae/material/ae_template.py
- lib/mayaUsd/resources/ae/mesh/ae_template.py
- lib/mayaUsd/resources/ae/scope/ae_template.py
- lib/mayaUsd/resources/ae/shader/ae_template.py
- lib/mayaUsd/resources/ae/sphere/ae_template.py
- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
- lib/mayaUsd/resources/ae/xform/ae_template.py
- test/lib/ufe/testDuplicateCmd.py
- test/lib/ufe/testGroupCmd.py
* New "usdschemabase" template which is at top level of the schema inheritance scheme so all prim types will use it. All the node type templates are deprecated and will be removed in the future.
> MAYA-108214 - Attributes categorized by schema

- lib/mayaUsd/ufe/UsdTransform3dHandler.cpp
- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
According to USD docs, editing scene description via instance proxies and their properties is not allowed.
> MAYA-108545: Prevent the crash when authoring edits to instance proxies.

- plugin/al/usdtransaction/CMakeLists.txt
Just a small fix to eliminate cmake syntax errors when building on windows with a custom `Python_EXECUTABLE`
> [cmake] fix for windows if backslash in Python_EXECUTABLE

- lib/usd/hdMaya/adapters/aiSkydomeLightAdapter.cpp
- lib/usd/hdMaya/adapters/materialAdapter.cpp
- lib/usd/hdMaya/adapters/materialAdapter.h
- lib/usd/hdMaya/delegates/delegateDebugCodes.cpp
- lib/usd/hdMaya/delegates/delegateDebugCodes.h
- lib/usd/hdMaya/delegates/sceneDelegate.cpp
- lib/usd/hdMaya/delegates/sceneDelegate.h
- lib/usd/hdMaya/utils.cpp
- lib/usd/hdMaya/utils.h
Our Hydra team is working on removing parts of the old Hydra texture system for the next core USD release.
With Luma's recent work, it looks like all of the necessary support for the newer material network-based system is already in place, so the changes here mostly just pre-process the old code away for USD releases after 20.11.
> remove dependencies on old Hydra texture system from hdMaya for USD releases after 20.11

- CMakeLists.txt
This bakes runtime paths using RUNPATH instead of RPATH for linux plugins (i.e. modules) as well.
> Use RUNPATH instead of RPATH for linux plugins

- lib/mayaUsd/ufe/UsdTransform3dFallbackMayaXformStack.cpp
- test/lib/ufe/testComboCmd.py
Assertion in Maya fallback Transform3d interface was incorrect.
Fix was done using Test Driven Development (TDD).  Test was written, it failed, fix was done, test passes.
> Fixed incorrect Transform3d fallback assertion.

- lib/usd/translators/scopeReader.cpp
- test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
Skip importing non-empty UsdScope that only contains UsdShade items.
> MAYA-106079 Skip Looks scopes

- lib/mayaUsd/render/vp2ShaderFragments/UsdPreviewSurface.xml
- lib/mayaUsd/render/vp2ShaderFragments/UsdPrimvarReader_color.xml
The pull request needs to be merged after the required support is merged into Maya Preview Release 121.
> Use color consolidation support for UsdPreviewSurface and UsdPrimvarReader_color

- plugin/adsk/scripts/mayaUsd_createStageFromFile.mel
Adding a proc to figure out a good starting location for a file dialog that is going to read in a USD file.  Right now it just defaults to whatever the current working directory is, or whatever folder it was in last.
I do plan on eventually refactoring a few other places that open dialogs, but right now just keeping this one as a local proc.  We have some calls in c++, both in the plugin and in the Outliner in Maya, that I want to clean up but it's not a huge priority right now.
> MAYA-108519 Choose an appropriate location to open the file dialog.

- lib/usd/ui/layerEditor/abstractCommandHook.h
- lib/usd/ui/layerEditor/layerTreeItem.cpp
- lib/usd/ui/layerEditor/layerTreeItem.h
- lib/usd/ui/layerEditor/layerTreeModel.h
- lib/usd/ui/layerEditor/layerTreeView.cpp
- lib/usd/ui/layerEditor/mayaCommandHook.cpp
- lib/usd/ui/layerEditor/mayaSessionState.cpp
- lib/usd/ui/layerEditor/mayaSessionState.h
- lib/usd/ui/layerEditor/pathChecker.cpp
- lib/usd/ui/layerEditor/pathChecker.h
- lib/usd/ui/layerEditor/saveLayersDialog.cpp
- lib/usd/ui/layerEditor/sessionState.cpp
- lib/usd/ui/layerEditor/sessionState.h
- lib/usd/ui/layerEditor/stageSelectorWidget.cpp
- lib/usd/ui/layerEditor/stageSelectorWidget.h
Just a small follow-up from the merge of the layer editor work from #988:
The `PXR_NS` macro should be used rather than hard-coding `pxr` as the namespace when referring to symbols in USD in case the core USD build is configured to use a different namespace (or in our case, no namespace with `PXR_USE_NAMESPACES=0`).
> use the PXR_NS macro instead of pxr in the layer editor

- lib/mayaUsd/commands/editTargetCommand.cpp
- lib/mayaUsd/commands/layerEditorCommand.cpp
- lib/mayaUsd/commands/layerEditorWindowCommand.cpp
One more tiny bit of fallout from #988.
There was a single non-ASCII character in the file headers of a few cpp files that caused the whole file to be considered in UTF-8 encoding.
> remove a stray non-ASCII characters in copyright headers

- lib/mayaUsd/utils/diagnosticDelegate.cpp
- plugin/adsk/plugin/plugin.cpp
- test/lib/usd/translators/testUsdExportStripNamespaces.py
These changes make `mayaUsdPlugin` use `UsdMayaDiagnosticDelegate` in the same way that the `pxrUsd` plugin currently does. The delegate's install and remove functions were modified slightly to make this work, using a pattern similar to the one used for `MayaUsdProxyShapePlugin`.
The diagnostic delegate takes care of intercepting messages emitted by the `Tf` library in core USD and relaying them to the appropriate `MGlobal` functions (e.g. `displayWarning()`, `displayError()`, etc.).
This should address an issue @ysiewappl ran into in #952 where it was necessary to explicitly call both diagnostic functions with the same message:
https://github.com/Autodesk/maya-usd/pull/952/files#r539582025
It also turns out that this fixes an issue @ppt-adsk ran into where the full error message in …
> install and remove UsdMayaDiagnosticDelegate for adsk plugin load and unload

- lib/mayaUsd/commands/baseExportCommand.cpp
- lib/mayaUsd/commands/baseExportCommand.h
- lib/mayaUsd/fileio/jobs/jobArgs.cpp
- lib/mayaUsd/fileio/jobs/jobArgs.h
- lib/mayaUsd/fileio/primWriter.cpp
- lib/mayaUsd/fileio/primWriter.h
- lib/usd/translators/meshWriter.cpp
- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
- plugin/pxr/maya/lib/usdMaya/usdTranslatorExport.mel
- test/lib/usd/translators/testUsdExportAnimation.py
- test/lib/usd/translators/testUsdExportAsClip.py
This is a PR that adds an export optimization to convert attributes with single time samples to static values.
This is run by default for common mesh attributes as they have the benefit of reducing the complexity of the USD, especially for USD readers. For example, this will benefit round tripping USD files into maya since point cached meshes will be able to import their UVs if they're static.
For all other prim attributes, this is gated behind a new flag called staticSingleSamples. This is off by default to prevent any unwanted surprises if someone was expecting a single keyframe to persist through.
We find, with even the files generated by the included test, that a single attribute results in a 32 byte savings for usda file , and a 67 byte savings for a usdc file due to empty padding in …
> Added staticSingleSample flag, and optimize mesh attributes by default

- lib/mayaUsd/render/mayaToHydra/utils.cpp
I'm not sure how others aren't running into this, but we're seeing all of the newly added `mtoh` tests crashing because GL/GLEW isn't fully initialized at the point where it discovers the Storm renderer plugin and tries to call `GlfContextCaps::InitInstance()`.
Prior to core USD 21.02, this was handled by calling `GlfGlewInit()`, but from 21.02 on, the GLEW dependency has been removed, and `GarchGLApiLoad()` is  used instead.
The same pattern of calling `GlfGlewInit()`/`GarchGLApiLoad()` before calling `GlfContextCaps::InitInstance()` can be seen in some of the unit tests in core USD, for example:
https://github.com/PixarAnimationStudios/USD/blob/e9172af0ccea9896990f5ac093c3d6063ac7cab5/pxr/imaging/hdSt/unitTestGLDrawing.cpp#L94
> ensure that GL is initialized when mtoh creates the Storm render delegate

- test/lib/usd/translators/CMakeLists.txt
Thanks again for @mattyjams for catching the missing test in the CMakeLists in https://github.com/Autodesk/maya-usd/pull/989/files#r544716374.
> Add testUsdExportAnimation for staticSingleSamples flag to CMakeList

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeUI.cpp
On maya<=2019, maya ends up including Xlib.h, which does
```
#define Bool int
```
...which messes with SdfValueTypeNames->Bool. So on Linux with Maya<2020,
this just does an `#undef Bool`.
This may only be an issue on specific Linux distributions, since it's tied
to the system supplied GL/glx.h and Xlib.h headers.
> Fix a build issue on Linux with maya<2020

- cmake/modules/FindMaya.cmake
- lib/mayaUsd/render/CMakeLists.txt
- lib/mayaUsd/render/vp2ComputeShaders/CMakeLists.txt
- lib/mayaUsd/render/vp2ComputeShaders/computeNormals.cl
- lib/mayaUsd/render/vp2ComputeShaders/computeNormals.glsl
- lib/mayaUsd/render/vp2ComputeShaders/plugInfo.json
- lib/mayaUsd/render/vp2RenderDelegate/CMakeLists.txt
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.h
- lib/mayaUsd/render/vp2RenderDelegate/meshViewportCompute.cpp
- lib/mayaUsd/render/vp2RenderDelegate/meshViewportCompute.h
The code is disabled by default.
The GPU evaluation prototype is two separate parts, the normal calculation code and the OSD
code.
The normal calculation code is enabled by setting HDVP2_USE_GPU_NORMAL_COMPUTATION=1 at runtime.
The normal calculation code is close to being stable enough for general use, but hasn't had
enough polish to enable by default.
The OSD code requires the normal calculation code to be enabled to use. OSD is enabled
by compiling with HDVP2_ENABLE_GPU_OSD. The OSD code is much less stable then the normals
calculation code and comes with a number of huge.
OSD Limitations:
* No OSD adaptive support
* scenes with animation behave poorly
* selection in the viewport is very slow
* toggling VP2 consolidation world off and on will cause crashes
* some objects draw with …
> MAYA-106937 Prototype support for GPU Normals and OSD using glsl. 

- lib/mayaUsd/commands/layerEditorCommand.cpp
- test/lib/testMayaUsdLayerEditorCommands.py
When a layer in the Layer Editor is moved (drag & drop) under the last layer in a hierarchy it will disappear.
drag & drop a layer is a two steps operation. 
1- Removed the layer from it's original index position
2- Adding the layer to is new index location. 
The problem is we can't add a layer at the end of the layer list because of a wrong comparaison.
So, the layer is removed but never added at the new location.
> MAYA-107449 Layer disappears when moved under last layer.

- plugin/al/plugin/AL_USDMayaTestPlugin/py/testLayerManager.py
- plugin/al/plugin/AL_USDMayaTestPlugin/py/testProxyShape.py
- plugin/al/plugin/AL_USDMayaTestPlugin/py/testTranslators.py
- plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/testBatchRendererIsolateSelection.py
- plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/testPxrUsdMayaGLInstancerDraw.py
- plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/testRefAssemblyDrawRepresentations.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawAndTransform.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawColorAccuracy.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawColors.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawLighting.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawPerformance.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawPurpose.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawTimeSampled.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawUsdChangeProcessing.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawVisibility.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDuplicatePerformance.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeLiveSurface.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeRendererSceneMessages.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeSelectionPerformance.py
- test/lib/mayaUsd/render/pxrUsdMayaGL/testPxrUsdMayaGL.py
- test/lib/usd/pxrUsdPreviewSurface/testPxrUsdPreviewSurfaceDraw.py
When developing #915, we uncovered an issue where [output streams weren't being flushing before interactive maya tests quit](https://github.com/Autodesk/maya-usd/pull/915#issuecomment-738472429). 
This applies the fix developed in that PR to all interactive maya tests, so we can be sure to see all their output on stdout.
> [tests] interactive tests ensure output streams are flushed before quitting

- CMakeLists.txt
...but still allow user to force building
Disabled due to a problem with glew - if you force on with these versions,
you will probably need to LD_PRELOAD your glew lib.
See:
https://github.com/Autodesk/maya-usd/discussions/1017
> [mtoh] don't build Maya-To-Hydra if maya==2019 AND USD==(20.08||20.11)

- lib/mayaUsd/ufe/Utils.cpp
- lib/mayaUsd/ufe/private/Utils.h
- test/lib/usd/translators/CMakeLists.txt
* When asking for UsdPrim from Ufe Path we cannot assume the path is valid and therefore should not assert.
> MAYA-107303 - UFE: crash (debug only) with multiple UFE items in single string

- lib/mayaUsd/ufe/UsdTransform3d.cpp
Implement the 4x4 local affine transformation matrix for UsdTransform3d::matrix() accessor.
> MAYA-95543: implement the local affine transformation matrix 

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- lib/mayaUsd/render/vp2RenderDelegate/material.h
Replace the authored node paths with simplified paths in the form of "node#".
By doing so we will be able to reuse shader effects among material networks
which have the same node identifiers and relationships but different node
paths, reduce shader compilation overhead and enable material consolidation
for faster rendering.
> MAYA-108707 Share shader effect among similar-enough material networks

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
Replace "node" prefix with the actual identifier, to avoid ambiguity.
> MAYA-108707 Making shader reuse safer

- test/lib/mayaUsd/utils/testDiagnosticDelegate.py
This is a follow-up fix to a change I made in #1042 that replaced the `__main__` module name included as part of a coding error message with `testDiagnosticDelegate` instead. While this is correct for the way the test is run using the mayaUsd CMake testing infrastructure, it is not correct in all cases.
When the test is executed as a result of the `unittest.main()` call at the bottom of the file (e.g. when the script is executed directly via its shebang, when the script file is passed to a Python interpreter on the command-line, or when the script file's contents is read and executed through `compile()` and `exec()`, the module will be reported as `__main__`. Otherwise, when the file is imported as a module and then executed using `unittest.main(module=<module name>)`, the module name …
> fix regex in testDiagnosticDelegate to handle varying ways of executing the test

- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
- test/lib/ufe/testComboCmd.py
Direct manipulation failures on Linux were caused by a gcc 6.3.1 compiler problem.  This pull request implements an easy work-around for the issue.
> Work around gcc 6.3.1 bug, and re-enable test.

- lib/mayaUsd/fileio/shading/shadingModeExporterContext.cpp
Hi: 
This fixes an issue related to referenced Maya scenes being written out with the incorrect varname attribute for the UV set, as it is being determined incorrectly. You can reproduce the issue by attempting to export the cube in the Maya scene with the reference in it and looking at the resulting USDA (the correct file should have `map1` as its attribute name.)
Example:
```
def Material "usdPreviewSurface1SG"
{
token inputs:usd_scene_orig:file1:varname = "map1"
token outputs:surface.connect = </usd_scene_orig_pCube1/Looks/usdPreviewSurface1SG/usd_scene_orig_usdPreviewSurface1.outputs:surface>
```
This issue can be demonstrated with the following two scenes, which essentially amount to a single cube with a texture assigned, and then referenced in another scene: …
> Fix issue where referenced scenes have incorrect UV set attribute name written out.

- lib/mayaUsd/ufe/CMakeLists.txt
- lib/mayaUsd/ufe/UsdContextOps.cpp
- lib/mayaUsd/ufe/UsdObject3d.cpp
- lib/mayaUsd/ufe/UsdObject3d.h
- lib/mayaUsd/ufe/UsdUndoVisibleCommand.cpp
- lib/mayaUsd/ufe/UsdUndoVisibleCommand.h
- test/lib/ufe/testObject3d.py
This PR makes the "visibility" in USD data model Undo/Redo correct.
> Making visibility Undo/Redo correct.

- lib/mayaUsd/ufe/StagesSubject.cpp
- test/lib/ufe/testAttribute.py
* Added catch-all condition in response to USD stage changes. If no UFE notif is sent, but we were given paths, send a UFE subtreeInvalidate notif.
> MAYA-106780 - Editing USD should mark scene as dirty

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- lib/mayaUsd/render/vp2RenderDelegate/material.h
Skip creating a new shader instance if the token generated from the material
network is unchanged. There is no plan to implement fine-grain dirty bit in
Hydra for the same purpose:
https://groups.google.com/g/usd-interest/c/xytT2azlJec/m/22Tnw4yXAAAJ
> MAYA-108274 Skip creating shader instance for unchanged material network

- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
This PR fixes the regression with camera framing of instance proxies. The issue was related to the new conditional check that was added for "instance proxies" in UsdTransform3dMayaXformStackHandler::createTransform3d().  
This was a wrong place to have this condition since the original intention was to avoid "authoring edit transforms" for instance proxies. When the camera frame happens, we would end up calculating the ufe BBox which would go through transform3d() and eventually createTransform3d().
> MAYA-109190 : Fix camera frame for instance proxies.

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
The shader is transparent if the surface shader has its opacity attribute
connected to a node which isn't a USD primvar reader.
> MAYA-108272 fix false positive transparency

- test/lib/usd/translators/CMakeLists.txt
This repairs some minor damage from the merge of PR #1016 where the new `testUsdExportBlendshapes` test replaced `testUsdExportCamera` rather than just being added:
https://github.com/Autodesk/maya-usd/commit/138c4f99dce5388f0e0a10e4dd18d14ed0149fb6#diff-59ba898f87ae0237808269ee377b8b6cfd9adec3bc66f81455b72ab6b31cc33d
> re-add testUsdExportCamera translator test back to CMakeLists.txt

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
* If polygons are excluded from display, USD meshes will be filtered out.
* If NURBS curves are excluded from display, USD curves will be filtered out.
* If plugin shapes are excluded from display, all USD objects will be filtered out.
> MAYA-108814 Support viewport display filtering for meshes and basisCurves

- lib/mayaUsd/commands/baseImportCommand.cpp
- test/lib/usd/translators/CMakeLists.txt
- test/lib/usd/translators/testUsdImportAnonymousLayer.py
Reported in https://github.com/Autodesk/maya-usd/discussions/1069. We didn't have symmetry between import and export behavior for anonymous layers. 
It may be confusing that we are using a file path to feed layer identifier, but since the exporter and the underlying job already handles it we filter out anonymous layers when validating the path provided.
> Fixed anonymous layer import

- lib/mayaUsd/CMakeLists.txt
Adding dependency to usdRender. This change is mainly for Arnold team that rely on mayaUsd plugin to link against USD libraries.
> Added usdRender dependency.

- lib/mayaUsd/ufe/CMakeLists.txt
- lib/mayaUsd/ufe/UsdUndoCreateGroupCommand.cpp
- lib/mayaUsd/ufe/UsdUndoSetKindCommand.cpp
- lib/mayaUsd/ufe/UsdUndoSetKindCommand.h
- test/lib/ufe/testGroupCmd.py
Authoring the kind metadata on the group `Xform` prim ensures that the model hierarchy remains contiguous between the parent and children of the new group prim. Prims underneath the group prim may still be in the model hierarchy if they also have kind authored.
If the parent prim of the group prim is not part of the model hierarchy, no kind is authored on the group prim.
More info about model hierarchy can be found here:
https://graphics.pixar.com/usd/docs/USD-Glossary.html#USDGlossary-ModelHierarchy
> author kind=group on the UsdPrim created by the group command when its parent is in the model hierarchy

- lib/mayaUsd/fileio/shading/shadingModeRegistry.h
- lib/mayaUsd/render/mayaToHydra/renderGlobals.h
- lib/usd/ui/layerEditor/mayaSessionState.cpp
- plugin/al/mayautils/AL/maya/utils/PluginTranslatorOptions.cpp
We discovered that VS2015 wasn't well supported as part of https://github.com/Autodesk/maya-usd/issues/1087. This PR fixes the compilation error for Maya 2018 and some of the compilation errors when building with VS2015. The remaining compilation errors with VS2015 are related to `error C2872: 'uchar': ambiguous symbol` caused by:
```
\qt\5.6.1\14f946f\include\QtCore/qglobal.h(204): note: could be 'unsigned char uchar'
\Pixar_USD_VS2015\include\pxr/base/arch/inttypes.h(58): note: or       'pxrInternal_v0_21__pxrReserved__::uchar'
```
> Fix for Maya 2020 and compilation fixes for VS2015 when building without Qt

- doc/build.md
- lib/mayaUsd/fileio/shading/shadingModePxrRis.cpp
- lib/mayaUsd/fileio/utils/adaptor.cpp
- lib/mayaUsd/render/mayaToHydra/shadingModeExporter.cpp
- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/render_delegate.cpp
Just a handful of small changes to conform to recent, post-21.02 changes in core USD. These should all be backwards compatible with all previous releases of core USD supported by maya-usd.
This is the first such update since the release of 21.02, so I also took this opportunity to add it to `doc/build.md`, along with updating the dev branch commit SHA.
> updates for building with latest post-21.02 dev branch commit of core USD

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
when they are about to be redrawn after getting out of sync.
This fixes drawing multiple Repr in sequence after dirtying the RPrim.
The first draw will clean the RPrim and the Reprs that were selected
to be drawn. Reprs that were not drawn will stay stale and need to
signal the Sync engine that they need to be refreshed on the next
draw cycle that will draw them.
> MAYA-109316 Propagate state of dirty draw items

- test/lib/mayaUsd/render/mayaToHydra/testMtohCommand.py
...never noticed because it was in a command that's SUPPOSED to error
> fix typo in test - "mtoh" not "moth"

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- lib/mayaUsd/render/vp2RenderDelegate/material.h
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
Workaround for a material consolidation update issue in VP2. Before USD 0.20.11, a Rprim will be recreated if its material has any change, so everything gets refreshed and the update issue gets masked. Once the update issue is fixed in VP2 we will disable this workaround.
> MAYA-109414 workaround for material consolidation update issue

- lib/mayaUsd/ufe/StagesSubject.cpp
- lib/mayaUsd/ufe/StagesSubject.h
When using the `onStageInvalidate` notification, extra care has to be taken to NOT trigger any notification that would result in pulling on stage map. This notification is sent during dirty propagation, and we can't trigger compute from it (number one DG rule).
We didn't fully follow this rule and started to send `Ufe::SubtreeInvalidate`. One of the listeners, i.e. Outliner, was trying to refresh the tree by pulling on the list of stages. This caused a lack of refresh and what's more important, the potential use of released memory in future calls.
The fix is to delay this notification till later when we know the stage map has been already populated.
> Fixed crash caused by out of date stage map

- lib/mayaUsd/commands/baseExportCommand.cpp
- plugin/adsk/plugin/exportTranslator.cpp
- plugin/pxr/maya/lib/usdMaya/exportTranslator.cpp
We had a situation where shader exports were failing, but not being picked up as such, due to a mistyped shadingMode.
This will make the command error / fail if a bad shadingMode is requested
> [maya] error if unrecognized shadingMode on export

- lib/mayaUsd/commands/layerEditorCommand.cpp
Add a check for null pointer to avoid crash when removing invalid layer
> MAYA-109483 - Crash when removing an invalid layer

- CMakeLists.txt
- doc/build.md
- lib/mayaUsd/render/mayaToHydra/renderGlobals.cpp
- lib/mayaUsd/render/mayaToHydra/renderGlobals.h
- lib/mayaUsd/render/mayaToHydra/renderOverride.cpp
- lib/mayaUsd/render/mayaToHydra/tokens.h
- lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.cpp
- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- lib/mayaUsd/render/vp2RenderDelegate/meshViewportCompute.cpp
- lib/mayaUsd/render/vp2RenderDelegate/meshViewportCompute.h
- lib/usd/hdMaya/adapters/aiSkydomeLightAdapter.cpp
- lib/usd/hdMaya/adapters/materialAdapter.cpp
- lib/usd/hdMaya/adapters/materialAdapter.h
- lib/usd/hdMaya/adapters/materialNetworkConverter.cpp
- lib/usd/hdMaya/adapters/materialNetworkConverter.h
- lib/usd/hdMaya/adapters/nurbsCurveAdapter.cpp
- lib/usd/hdMaya/delegates/delegateDebugCodes.cpp
- lib/usd/hdMaya/delegates/delegateDebugCodes.h
- lib/usd/hdMaya/delegates/sceneDelegate.cpp
- lib/usd/hdMaya/delegates/sceneDelegate.h
- lib/usd/hdMaya/utils.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
- test/lib/mayaUsd/render/CMakeLists.txt
Following up on #1101, these changes set core USD version 20.02 as the minimum supported version of core USD. This version is specified as the minimum in the `find_package()` call in the top-level `CMakeLists.txt` so that the build will quickly bail out on any attempt to use an older USD version.
All conditionally compiled code that was active for versions of USD prior to 20.02 was removed. The bulk of the removed code was in `hdMaya`/`mayaToHydra`.
Our environment has moved on such that I can't actually build core USD 20.02 anymore, but I was able to verify this against 20.05 on Linux using Maya PR 121. A few minor adjustments were needed though (see 1281cbb374daba6ab96c38e7bdd6cd574e5ef045).
I also took this opportunity to mark the current USD dev branch commit …
> move minimum core usd version to v20.02

- lib/mayaUsd/ufe/UsdAttribute.cpp
- lib/mayaUsd/ufe/UsdAttribute.h
- test/lib/ufe/testAttribute.py
UsdAttribute derived classes were not overriding the Ufe::Attribute::setCmd() virtual.  This meant that we were using the implementation from UFE, rather than our new, data model correct undo system.  This was bad in two ways:
- The UFE implementation only does value undo, not data model undo
- It uses the Ufe::Attribute to set the previous value, and in our implementation this Ufe::Attribute stores a UsdPrim that can become stale, as per the Autodesk MAYA-109522 internal bug.
Now fixed, with an automated test to validate the fix.
> Use data model undo framework for attribute undo.

- lib/usd/translators/shading/usdFileTextureWriter.cpp
- lib/usd/translators/shading/usdUVTextureReader.cpp
...when exporting / importing.
Also does a bit of code unification for U+V cases
> support for UV mirroring on UsdUVTexture

- lib/usd/translators/jointWriter.cpp
- test/lib/usd/translators/UsdExportSkeletonTest/UsdExportSkeletonBindPoseMissingJoints.ma
- test/lib/usd/translators/UsdExportSkeletonTest/UsdExportSkeletonBindPoseSparseIndices.ma
- test/lib/usd/translators/UsdExportSkeletonTest/UsdExportSkeletonNoDagPose.ma
- test/lib/usd/translators/UsdExportSkeletonTest/UsdExportSkeletonWithIdentityBindPose.ma
- test/lib/usd/translators/testUsdExportSkeleton.py
Some bugfixes for edge cases, and made it so that we export restXforms whenever we export bindXforms (ie, the restXforms are calculated from the bindXforms if present).
We were getting some errors in other tools if rest xforms weren't present (as well as an annoying warning/error from usdview, IIRC).
> Fixes related to export of skeleton rest-xforms

- lib/mayaUsd/fileio/translators/translatorXformable.cpp
- test/lib/usd/translators/CMakeLists.txt
- test/lib/usd/translators/UsdImportXformAnimTest/Mesh.usda
- test/lib/usd/translators/testUsdImportXformAnim.py
There are two private functions that reads transforms: _pushUSDXformOpToMayaXform() and _pushUSDXformToMayaXform().
The first was using the earliest-time time code when no time interval were used for importing. The other was using default-time.
Using default-time prevented importing the transform since their time code did not match and the iimportaed mesh would have bad transform (they would all have identity matrix).
This change make both code paths use earliest-time. This fixes bad import of geometry when not importing animation data in Maya.
> MAYA105624 make xform reading more uniform

- lib/mayaUsd/fileio/translators/translatorGprim.cpp
- lib/mayaUsd/fileio/translators/translatorMesh.cpp
- lib/mayaUsd/fileio/translators/translatorMesh.h
- lib/mayaUsd/fileio/translators/translatorNurbsPatch.cpp
- test/lib/usd/translators/UsdImportMeshTest/Mesh.usda
- test/lib/usd/translators/testUsdImportMesh.py
The  main problem is that the 'leftHanded' orientation is USD changes the interpretation of the vertices order of faces *and* the direction of generated normals.
On the other hand, the 'opposite' flag in Maya flips the faces directions, but does not flip the normals.
So the behaviour differs. To better suport USD import of externally-generated USD files, we will no longer set the 'opposite' flag when importing ledftHanded USD files. We will instead change the vertices orders to be right-handed.
Note that we will still export 'opposite' geometries from Maya as by setting the 'leftHanded' flag. This is done for two reasons: first, to keep the code change minimal, second because USD does not support different handedness for faces and normasl anyway.
> MAYA-105623 better support for USD leftHanded mesh.

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
Maya PR 121 reports its API version as 20210000 while PR 122 reports its API version as 20220000. The newly added `MRenderItem::setObjectTypeExclusionFlag()` function whose use was added in pull request #1008 is only available in PR 122, not in PR 121. This means that compilation against PR 121 fails because the API version check guarding the function's usage is incorrect.
While I concede that we don't intend to support all previous preview/beta releases of Maya, this has been causing sufficient headache for us as we try to get PR 122 licensed that I was hoping taking these changes would be acceptable. The updated `MAYA_API_VERSION` also more accurately reflects the version in which the new API was added.
> use accurate MAYA_API_VERSION in guard for MRenderItem::setObjectTypeExclusionFlag()

- plugin/adsk/scripts/AEmayaUsdProxyShapeTemplate.mel
MAYA-109438 - Need to remove attributes from AE stage view
* Temp suppress two non-functional attributes.
> MAYA-109438 - Need to remove attributes from AE stage view

- test/lib/ufe/testAttribute.py
- test/lib/ufe/testAttributes.py
- test/lib/ufe/testChildFilter.py
- test/lib/ufe/testComboCmd.py
- test/lib/ufe/testContextOps.py
- test/lib/ufe/testDeleteCmd.py
- test/lib/ufe/testDuplicateCmd.py
- test/lib/ufe/testGroupCmd.py
- test/lib/ufe/testMatrices.py
- test/lib/ufe/testMayaPickwalk.py
- test/lib/ufe/testMoveCmd.py
- test/lib/ufe/testObject3d.py
- test/lib/ufe/testObservableScene.py
- test/lib/ufe/testParentCmd.py
- test/lib/ufe/testPointInstances.py
- test/lib/ufe/testPythonWrappers.py
- test/lib/ufe/testRename.py
- test/lib/ufe/testReorderCmd.py
- test/lib/ufe/testRotateCmd.py
- test/lib/ufe/testRotatePivot.py
- test/lib/ufe/testScaleCmd.py
- test/lib/ufe/testSceneItem.py
- test/lib/ufe/testSelection.py
- test/lib/ufe/testTransform3dChainOfResponsibility.py
- test/lib/ufe/testTransform3dTranslate.py
- test/lib/ufe/testUIInfoHandler.py
- test/lib/ufe/testUfePythonImport.py
This change syncs the tests in `test/lib/ufe` with tests elsewhere in the source tree so that the script files are directly runnable (with the addition of a `__name__ == "__main__"` block at the bottom) rather than only as a module. They also now use `fixturesUtils` to ensure that Maya standalone is initialized and uninitialized in that case.
I also cleaned up and reordered the module imports at the top of each test script.
> make tests in test/lib/ufe directly runnable and use fixturesUtils

- lib/usd/translators/meshWriter.cpp
- lib/usd/translators/meshWriter_BlendShapes.cpp
- test/lib/usd/translators/UsdExportBlendShapesTest/blendShapesExport.ma
- test/lib/usd/translators/testUsdExportBlendshapes.py
Hi:
This PR supplements the previous added support for exporting blendshapes with some minor changes to the names of the targets exported, and also adds support for exporting empty blendshape targets, gated by the `ignoreWarnings` flag.
> Support empty blendshape targets

- test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
- test/lib/mayaUsd/render/vp2RenderDelegate/CMakeLists.txt
We will have to detect if OCIOv2 is running and set it up differently. The CM default settings have changed, including the default render color space (instead of "scene-linear Rec 709/sRGB"), and the former view transform "sRGB gamma" is now a pair "ACES 1.0 SDR-video (sRGB). The end result is to see the viewport is a little bit darker.
Also, the outputTransformName "Raw" was renamed to "Raw (sRGB)".
Above will require changes, including new base images. For now, we switch back to legacy mode.
> We will need to adopt new OCIOv2 in mtoh tests, but for now switch it off

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- test/lib/mayaUsd/render/vp2RenderDelegate/CMakeLists.txt
Point instance selection depends on getting the `HdInstancerContext` from Hydra which was only exposed in `USD_IMAGING_API_VERSION` version 14. As a result, we can only support point instance selection for core USD 20.08, not 20.05 as previously thought.
> fix build breakage from PR #1119 due to missing Hydra API in USD 20.05

- test/lib/mayaUsd/render/vp2RenderDelegate/CMakeLists.txt
This was accidentally introduced by #1119 since that work spanned the transition from using `VP2_RENDER_DELEGATE_PROXY` to `MAYAUSD_DISABLE_VP2_RENDER_DELEGATE`.
> remove irrelevant setting of VP2_RENDER_DELEGATE_PROXY in vp2RenderDelegate tests

- lib/usd/ui/layerEditor/CMakeLists.txt
- lib/usd/ui/layerEditor/batchSaveLayersUIDelegate.cpp
- lib/usd/ui/layerEditor/mayaLayerEditorWindow.cpp
- lib/usd/ui/layerEditor/mayaQtUtils.cpp
- lib/usd/ui/layerEditor/mayaQtUtils.h
- plugin/adsk/plugin/plugin.cpp
* Moved the MayaQtUtils init to the plugin.
> MAYA-109948 - Crash saving USD without opening Layer Editor

- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
Maya move tool call sequence during point snapping manipulation causes repeated calls to undo, then redo, with new values set in the redone state.  Add support for this in the undo / redo state machine.
> Add set value support to redone state.

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Engine.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Engine.h
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeUI.cpp
I noticed that some bits of the AL selection code can be simplified / removed, some of which led to cascades of other bits being removed. In particular:
- I removed the custom code for getting nearest hit to camera, and instead rely on built-in resolveNearestToCamera
- Removed the need for `*SelectionHelper`, since we no longer use the hits we tracked with it
- Removed the need for custom `HitInfo` struct, as we never we no longer used the instanceIndex info, just the world space position
> Cleanup + simplify some of the selection logic in the AL plugin

- lib/mayaUsd/fileio/utils/meshReadUtils.cpp
- lib/mayaUsd/fileio/utils/meshWriteUtils.cpp
- test/lib/usd/translators/UsdExportUVSetsFloatTest/UsdExportUVSetsTest_Float.ma
- test/lib/usd/translators/UsdExportUVSetsTest/UsdExportUVSetsTest.ma
- test/lib/usd/translators/UsdImportUVSetsFloatTest/UsdImportUVSetsTest_Float.usda
- test/lib/usd/translators/UsdImportUVSetsTest/UsdImportUVSetsTest.usda
- test/lib/usd/translators/testUsdExportUVSets.py
- test/lib/usd/translators/testUsdImportUVSets.py
Some of our artists have discovered that the re-indexing and compression that we're doing when we export UV sets is actually messing with the connectivity information that Maya computes from the values and indices arrays. The result is that when they export Maya meshes to USD and then re-import them back into Maya, they're ending up with disconnected and hard to work with UV sets.
With the changes here, we now translate the Maya mesh's UV values and assignment indices more or less directly, and we no longer apply any compression. This offers the best chance of maintaining the UV set's connectivity across round-trips. The net result in USD is the same (i.e. the array of UVs produced by doing `primvar.ComputeFlattened()` is the same as before), but the array values for the UV set primvar …
> maintain UV connectivity across export and re-import round trips

- lib/usd/ui/layerEditor/layerTreeItem.cpp
- lib/usd/ui/layerEditor/mayaSessionState.cpp
- lib/usd/ui/layerEditor/mayaSessionState.h
- lib/usd/ui/layerEditor/saveLayersDialog.cpp
- lib/usd/ui/layerEditor/saveLayersDialog.h
- lib/usd/ui/layerEditor/sessionState.h
There was still one function call we were making that looked at the old binary/ascii option.  Fixing that was a one-liner, to just leave the function parameter as an empty string which gets the utils function to check the optionVar for us, but I went ahead and removed the member variable in the SaveLayerPathRow class that tracked the old option and any use of it.
All code should now use the option that is in the Layer Editor menu for ascii or binary when saving to a .usd file.
> Remove the old formatTag option and anything that might still call it

- test/lib/ufe/testComboCmd.py
Setting path martix dirty properly on Maya side fixes this issue.  See MAYA-17443
> MAYA-108067: Remove Z from fallback.

- lib/usd/ui/layerEditor/mayaSessionState.cpp
- lib/usd/ui/layerEditor/mayaSessionState.h
- lib/usd/ui/layerEditor/sessionState.h
- lib/usd/ui/layerEditor/stageSelectorWidget.cpp
- lib/usd/ui/layerEditor/stageSelectorWidget.h
I have some other changes to how we handle anonymous root layers, but this fixes an issue that showed up in a demo last week where a proxy that has a new stage set still has the old stage visible in the Layer Editor if it wasn't the visible proxy when the reset happens.
The easiest way to test this right now is to copy/paste in a path to a new .usd file for the filePath attribute of a proxy that is not being displayed in the Layer Editor.  Switching to that proxy after making the change to filePath will still show the old stage.  This defect can also be hit as part of File -> Save, but this change only deals with the Layer Editor.  Follow up changes are going to improve how we handle anonymous root layers as part of saving.
> new signal/slot to reset a stage/proxy in the Layer Editor

- lib/mayaUsd/fileio/shading/shadingModeExporterContext.cpp
Hi:
This PR accounts for the Maya behaviour described in https://github.com/Autodesk/maya-usd/issues/1079, where the UV set name is not correctly written out when there is a shape node that shares the exact same name as its parent transform. 
> Uvset names not written

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.h
Bugfix - in [line 2065](https://github.com/Autodesk/maya-usd/blob/21d410cf9cfcce4231b554cf715a5124f54c4b06/plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.cpp#L2065) we get the old transform, but then never use it... then when actually comparing the value, we [used to get the current value twice](https://github.com/Autodesk/maya-usd/pull/1192/files#diff-4918577650a36d85c51a468a604f5b99cf93dcd92521951e7dae78aeda422155L1722), and compare against each other (which is always equal).
> al: notifyProxyShapeOfRedraw: fix for check if xform has changed

- plugin/al/translators/pxrUsdTranslators/ProxyShapeTranslator.cpp
- plugin/al/translators/pxrUsdTranslators/tests/sphere2.usda
- plugin/al/translators/pxrUsdTranslators/tests/testPxrTranslators.py
If exporting a ProxyShape as a reference, make sure we export the timeScalar settings we've changed.
NOTE - the interpretation of the timeScalar is OPPOSITE that as used by USD.  Not sure if this was intentional, but I invert the values on export, to make it work in USD as it did in Maya.
> AL: fix proxy shape time-scalar export

- plugin/adsk/scripts/AETemplateHelpers.py
- plugin/adsk/scripts/AEmayaUsdProxyShapeBaseTemplate.mel
- plugin/adsk/scripts/mayaUSDRegisterStrings.mel
* Replaced loadPayloads checkbox with two buttons.
> MAYA-107380 - On stage AE template, load and unload all payloads

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
kSelectCurves includes kSelectSurfaceEdge which has a higher priority that causes issues.
This addresses https://github.com/Autodesk/maya-usd/issues/951
> Use the nurbs curve selection mask for basis curves. 

- doc/build.md
- test/lib/usd/translators/testUsdExportRfMShaders.py
- test/lib/usd/translators/testUsdExportShadingModePxrRis.py
Just one small tests-only change to go along with the most recently pushed core USD dev branch commits.
Starting with core USD 21.05, `GetInputs()` and `GetOutputs()` take an optional `onlyAuthored` argument that is `True` by default, which means that calling those functions without arguments will only return the authored terminals. For earlier USD releases, we still expect them to always return the built-in terminals for the universal renderContext in addition to any other authored terminals. See https://github.com/PixarAnimationStudios/USD/commit/53757699be3069a72842bf6b9781dfba017cd240 for more detail.
I also took the opportunity to update the `doc/build.md`.
> adapt tests to UsdShade GetInputs() and GetOutputs() API update with USD 21.05

- lib/mayaUsd/nodes/layerManager.cpp
- lib/mayaUsd/utils/utilSerialization.cpp
- lib/mayaUsd/utils/utilSerialization.h
- lib/usd/ui/layerEditor/batchSaveLayersUIDelegate.cpp
- lib/usd/ui/layerEditor/layerTreeItem.cpp
- lib/usd/ui/layerEditor/saveLayersDialog.cpp
We currently don't have a consistent namespace under "lib/mayaUsd" and in many places we are not respecting the namespaces at all making it hard to read and write code logic. This PR is the first of many to do this cleanup.
> MAYA-110155: consistent namespace across the project - Part 1

- lib/usd/translators/jointWriter.cpp
We are going to drop support for Maya 2018 as mentioned in https://github.com/Autodesk/maya-usd/discussions/1217. This PR fixes compilation before we officially remove the support from the https://github.com/Autodesk/maya-usd/blob/dev/doc/build.md documentation.
> Fix Maya 2018 compilation

- doc/codingGuidelines.md
I realized that we discussed this standardization offline but didn't actually have it documented anywhere.
> identify clang-format version 10.0.0 as the "standard" version for the project

- lib/mayaUsd/nodes/layerManager.cpp
The function that gathers the stages that might need to be written out has logic in it to check if we are doing Export vs. Export Selected, but the check for that state is incorrect.  The MFileIO::exportType check only tells us what option the last Export ran with and isn't changed when doing a Save.  We never want to check if something is selected during a Save, but it doesn't look like there is an explicit state kept by Maya so here we just create separate callbacks so we can keep track.
> Separate callbacks for Save and Export

- test/lib/mayaUsd/render/pxrUsdMayaGL/CMakeLists.txt
This mimics a similar fix that was applied to MayaToHydra and the
VP2RenderDelegate in https://github.com/Autodesk/maya-usd/pull/1160
> Revert pxrUsdMayaGL tests to old color management

- plugin/adsk/scripts/AETemplateHelpers.py
- plugin/adsk/scripts/AEmayaUsdProxyShapeBaseTemplate.mel
- plugin/adsk/scripts/CMakeLists.txt
- plugin/adsk/scripts/mayaUSDRegisterStrings.mel
- plugin/adsk/scripts/mayaUSDRegisterStrings.py
MAYA-107424 - On the stage AE template I'd like to load/reload a file as the stage source
* Added debugging messages to template helpers (controlled from var).
* New template helper method to deal with file path being changed from text field and file browser button.
* New template helper method to refresh file path attribute.
* Replace file path attribute with custom control containing: label, text field (for path), file browser button, file refresh button.
> MAYA-107424 - On stage AE template load/reload a file as stage source

- lib/mayaUsd/ufe/CMakeLists.txt
- lib/mayaUsd/ufe/UsdTransform3dMatrixOp.cpp
- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
- lib/mayaUsd/ufe/UsdUndoableCommand.h
- test/lib/ufe/testParentCmd.py
- Simple undoable command base class.
- Only handle the UsdUndoableItem.
- Only supports non-interactive commands.
- Used in the matrix non-interactive commands.
> MAYA-108709 undoable command base class.

- lib/usd/ui/layerEditor/layerTreeModel.cpp
- lib/usd/ui/layerEditor/mayaLayerEditorWindow.cpp
- lib/usd/ui/layerEditor/mayaSessionState.cpp
- lib/usd/ui/layerEditor/mayaSessionState.h
- lib/usd/ui/layerEditor/saveLayersDialog.cpp
- lib/usd/ui/layerEditor/sessionState.cpp
- lib/usd/ui/layerEditor/sessionState.h
- lib/usd/ui/layerEditor/stageSelectorWidget.cpp
- lib/usd/ui/layerEditor/stageSelectorWidget.h
We can have a situation where we have multiple proxy shapes that point to the same exact stage, using the InStageData port. Unfortunately this causes an issue in the layer editor since the combo-box is keeping track of the stage only, so two entries with the same stage is ambiguous. 
The fix was to move away from storing the Pixar Stage Reference as the data in the combo box and move to the StageEntry which encapsulates both stage and the proxy shape path.
> MAYA-110196 - Multiple ProxyShapes with Same Stage (InStageData) Bug

- lib/mayaUsd/render/mayaToHydra/renderOverride.cpp
- lib/mayaUsd/render/mayaToHydra/renderOverride.h
If a render-delegate fails to initialize itself **mtoh** will crash.
The checks here are a bit overly-cautious, but the function is called once (after switching renderers) so shouldn't affect perf.
> Fix crash on failure to initialize a renderer, and only try once.

- test/testUtils/ufeUtils.py
Attempting to import `ufeSelectCmd` before `maya.standalone.initialize()` has been called will raise an `ImportError` and cause tests to fail. For example, this would be the case for test cases that are decorated with the `unittest.skipUnless()` decorator and use `ufeUtils.ufeFeatureSetVersion()`, since the decorator will be executed before `setUpClass` has a chance to run and initialize `maya.standalone`.
This change addresses that by pushing the import of `ufeSelectCmd` into the `selectPath()` function where it is used rather than having it at the top of the file. This ensures that the `ufeUtils` module can be imported and `ufeUtils.ufeFeatureSetVersion()` can be called safely before `maya.standalone.initialize()`.
Note that this does not currently manifest as an issue when running the …
> move import of ufeSelectCmd inside selectPath() function in ufeUtils

- lib/usd/ui/layerEditor/mayaSessionState.cpp
With the addition of PXR_NAMESPACE_USING_DIRECTIVE there is no need to
specify the pxr namespace for USD types.
> Remove use of unnecessary pxr namespace

- lib/mayaUsd/fileio/jobs/writeJob.cpp
- lib/mayaUsd/fileio/writeJobContext.h
- lib/mayaUsd/utils/util.cpp
- lib/mayaUsd/utils/util.h
- lib/usd/translators/meshWriter.cpp
- lib/usd/translators/meshWriter.h
- lib/usd/translators/meshWriter_BlendShapes.cpp
- test/lib/usd/translators/UsdExportBlendShapesTest/blendShapesExport.ma
- test/lib/usd/translators/testUsdExportBlendshapes.py
Hi:
This PR fixes some bugs introduced with the newly-added blendshape export functionality, related to exporting multiple targets across multiple meshes.
The following are of significance in this PR:
- Previously, exporting multiple targets across multiple meshes resulted in some targets not having their animation written out at all.
- Exporting targets that share the same name across multiple meshes is now supported; we now namespace each target name (while leaving the prim name untouched to act as a "nice" name) to ensure that there is no risk of collision.
- We also now write out the default weights for blendshape targets, if they exist. This (unfortunately) only applies when animation export is enabled for now.
> Support duplicate blendshape target names

- lib/mayaUsd/ufe/CMakeLists.txt
- lib/mayaUsd/ufe/StagesSubject.cpp
- lib/mayaUsd/ufe/UsdPointInstanceModifierBase.h
- lib/mayaUsd/ufe/UsdPointInstanceOrientationModifier.cpp
- lib/mayaUsd/ufe/UsdPointInstanceOrientationModifier.h
- lib/mayaUsd/ufe/UsdPointInstancePositionModifier.cpp
- lib/mayaUsd/ufe/UsdPointInstancePositionModifier.h
- lib/mayaUsd/ufe/UsdPointInstanceScaleModifier.cpp
- lib/mayaUsd/ufe/UsdPointInstanceScaleModifier.h
- lib/mayaUsd/ufe/UsdPointInstanceUndoableCommands.h
- lib/mayaUsd/ufe/UsdTransform3dHandler.cpp
- lib/mayaUsd/ufe/UsdTransform3dPointInstance.cpp
- lib/mayaUsd/ufe/UsdTransform3dPointInstance.h
- plugin/adsk/plugin/plugin.cpp
- test/lib/ufe/testPointInstances.py
I've been having trouble finding the time to root out the remaining issues with point instance manipulation, so I wanted to just post what I've got so far. Feel free to review (read: ridicule) whenever you have a chance. :)
At a high level, this probably most closely aligns with the `XformCommonAPI` `Transform3d` implementation where instead of authoring translation, rotation, and scale values to xformOps dedicated to those operations, we author the values at the appropriate index in the `PointInstancer` prim's `positions`, `orientations`, and `scales` array attributes instead.
At the bottom, there is a `UsdPointInstanceModifierBase` class that handles most of the work of getting and setting individual element values in a `PointInstancer` prim's array attributes. This is then specialized …
> add support for manipulating point instances via UFE

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
Handle teh case where we receive a single-channel half-float texture. The support in Maya already existeed, only the correspondence in the switch/case was missing.
> MAYA-106484 add single-channel half-float EXR support.

- lib/mayaUsd/fileio/translators/translatorMesh.cpp
- test/lib/usd/translators/UsdImportMeshTest/Mesh.usda
- test/lib/usd/translators/testUsdImportMesh.py
Hello Autodesk, I am re-opening this pull request, I added the test.
Thanks,
Koen
> Adding support for indexed normals on import #1029

- CMakeLists.txt
- lib/mayaUsd/CMakeLists.txt
- lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
- lib/mayaUsd/render/mayaToHydra/utils.cpp
- lib/mayaUsd/render/mayaToHydra/utils.h
- lib/mayaUsd/render/pxrUsdMayaGL/proxyDrawOverride.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
These apparently still get called even when using MtoH's RenderOverride;
however, since MtoH has it's own proxyShape handling, they're unneeded, but
were still populating their own renderIndex.  Skip this to save time + memory.
> [mtoh] if using the VP2 MPxSubSceneOverride, don't update if we're also using mtoh

- lib/usd/translators/shading/usdUVTextureReader.cpp
Passing a path string to ArResolver::OpenAsset throws an error when built against the latest version of USD. This parameter is explicitly cast to ArResolvedPath elsewhere in the USD code, so updating this callsite to follow that pattern.
> Explicitly case Ar path string to ArResolvedPath

- lib/mayaUsd/ufe/UsdStageMap.cpp
- lib/mayaUsd/ufe/UsdStageMap.h
- lib/mayaUsd/ufe/Utils.cpp
The UsdStageMap was performing name-based lookup of proxy shape nodes on every access.  This has been replaced with a scheme that uses an unordered map index by Ufe::Path, which are hashable.
> Minimize name-based lookup of proxy shape nodes.

- cmake/compiler_config.cmake
- cmake/modules/FindUSD.cmake
This PR, enables `/permissive-` flag for Visual Studio compiler. Read more here:
https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=msvc-160
I recently wrote a code where I bind a non-const reference to a temporary which was rightfully detected as error with GCC but surprisingly not with either VS compiler 2017/2019.
```
void foo(std::string* errMsg)
{
std::string message{"potato_message"};
*errMsg = message;
}
int main()
{
// bad code: I am binding a temporary to a reference and by doing 
// so I am creating a reference to an object that will be 
// destroyed at the end of the expression.
foo(&std::string());
}
```
godbolt pseudo-code:
https://godbolt.org/z/3KzhnM
The "/permissive-" option is supported in Visual Studio 2017 and later and it would …
> Add "/permissive-" flag for VS compiler

- lib/mayaUsd/fileio/shading/shadingModeRegistry.h
Integrating Pixar change 2154753 by klucknav:
(HYD-2285) Updating comment since the mtlx protocol is added we no longer want to recommend using the universal render context for MaterialX networks.
> Update comment about using universalRenderContext

- lib/mayaUsd/ufe/StagesSubject.cpp
- test/lib/ufe/testComboCmd.py
* Send UFE Transform3d and AttributeValueChanged in response to USD "prim property path" notif.
* Added new test to verify these notifs.
> MAYA-108691 - USD: undoing transform will not update manipulator

- lib/usd/ui/layerEditor/layerTreeItem.cpp
- lib/usd/ui/layerEditor/mayaLayerEditorWindow.cpp
- lib/usd/ui/layerEditor/stringResources.h
- Remove warning comfirmation dialog box when clearing a layer. (That cause the Layer editor to refresh when clearing multiple layer which can cause a dangling pointer and crash)
- Suspend Usd Notices until all layers are cleared.
When clearing multiple layer at the same time, maya crash because of a dangling pointer. This happen when in the selected layers, there is a sub layer of another layer. When clearing layers, we are first getting a list of all selected layers than loop over the list and clear layer one by one (Same pattern as remove layer). The problem here is after the first clear, we are notified by USD that a layer changed and we are queuing a Layer Editor refresh on idle. On the next loop iteration, items can become a dangling pointer to an object that have been deleted if …
> Spinell/maya 110157/clearing mutiple layer crash

- lib/mayaUsd/ufe/UsdUndoVisibleCommand.cpp
This PR fixes visibility attribute not getting blocked when changed via outliner. I found this bug while testing some workflows.
> MAYA-110623: Fix visibility attribute not blocked via outliner

- lib/mayaUsd/fileio/jobs/jobArgs.cpp
- lib/mayaUsd/fileio/jobs/readJob.cpp
Hi:
This PR fixes #1273 and only shows the warning when the relevant `importUSDZTextures` flag is actually specified.
Update: I've also updated this PR to also fix #1272 as well since the code changes are minimal and they both relate to the same functionality.
> Fix spurious warning being raised about USDZ texture import and allow for user-defined sourceImages path

- lib/usd/hdMaya/adapters/lightAdapter.cpp
Lights translation/population doesn't occur when the light is invisible, so subsequent attempt to invalidate the prim issue errors as it doesn't exists.
> [mtoh] Fix Hydra prim invalidation for hidden lights that are never population

- lib/mayaUsd/utils/util.cpp
- lib/mayaUsd/utils/util.h
- lib/usd/pxrUsdPreviewSurface/usdPreviewSurfaceWriter.cpp
Hi:
This PR fixes #796, where referenced material attributes at non-default values were not getting exported to USD, causing a discrepancy in what was shown in Maya compared to what was getting exported.
> Fix referenced material non-default attributes not getting exported to USD

- lib/mayaUsd/ufe/UsdTransform3d.cpp
- test/lib/ufe/CMakeLists.txt
- test/lib/ufe/testAttributeBlock.py
This PR adds support for blocking attribute authoring in weaker layer in "legacy transform3d" via UFE1.0 && 2.0
> MAYA-110670: block attribute authoring in weaker layers in legacy transform3d

- cmake/gulark.cmake
This PR adds support for building Gulark via local source to avoid the need to pull directly from an external repo which requires an internet connectivity.
**Instruction:**
Set `GULARK_SOURCE_DIR` to the local directory where you have cloned gulark repo:
e.g
`--build-args=-DGULARK_SOURCE_DIR="path_to_your_gulark_local_source_directory"
`
Further discussion: https://github.com/Autodesk/maya-usd/discussions/1286 ,
> MAYA-110731:  Support Building Gulark library locally

- lib/mayaUsd/fileio/shading/shadingModeExporterContext.cpp
- lib/usd/translators/shading/usdFileTextureWriter.cpp
Hi:
This PR fixes a crash we're seeing on some exports where layered shaders are involved, leading to a mistaken assumption in array sizes and resulting in past-the-end-iterator invalidation.
> guard against past-end iterator invalidation

- lib/mayaUsd/ufe/UsdTransform3d.cpp
- lib/mayaUsd/ufe/UsdTransform3dCommonAPI.cpp
- lib/mayaUsd/ufe/UsdTransform3dMatrixOp.cpp
- lib/mayaUsd/ufe/Utils.cpp
- lib/mayaUsd/ufe/Utils.h
- test/lib/ufe/testAttributeBlock.py
This PR completes the blocking of attribute edits for the remaining transformation stacks ( UsdTransform3dCommonAPI, UsdTransform3dMatrixOp )
> MAYA-110706: Block attribute edits for the remaining transformation stacks (UsdTransform3dCommonAPI, UsdTransform3dMatrixOp)

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
This change will fix the bug when trying to point snap to a USD instance with camera-based selection off.
There is still another issue affecting point snapping with camera-based selection on. We will fix it separately.
> MAYA-110850 fix a point snapping issue on USD instances

- lib/mayaUsd/render/mayaToHydra/renderGlobals.cpp
- lib/mayaUsd/render/mayaToHydra/renderOverride.cpp
- lib/mayaUsd/render/mayaToHydra/renderOverride.h
- lib/usd/hdMaya/adapters/CMakeLists.txt
- lib/usd/hdMaya/adapters/adapterRegistry.cpp
- lib/usd/hdMaya/adapters/adapterRegistry.h
- lib/usd/hdMaya/adapters/cameraAdapter.cpp
- lib/usd/hdMaya/adapters/cameraAdapter.h
- lib/usd/hdMaya/adapters/dagAdapter.cpp
- lib/usd/hdMaya/adapters/dagAdapter.h
- lib/usd/hdMaya/adapters/meshAdapter.cpp
- lib/usd/hdMaya/delegates/delegate.cpp
- lib/usd/hdMaya/delegates/delegate.h
- lib/usd/hdMaya/delegates/delegateCtx.cpp
- lib/usd/hdMaya/delegates/delegateCtx.h
- lib/usd/hdMaya/delegates/params.h
- lib/usd/hdMaya/delegates/sceneDelegate.cpp
- lib/usd/hdMaya/delegates/sceneDelegate.h
- lib/usd/hdMaya/plugInfo.json
- lib/usd/hdMaya/utils.h
- test/lib/mayaUsd/render/mayaToHydra/testMtohCommand.py
_Running the test-suite locally to verify nothing has been broken, but as the change-set is quite large posting it now_
Currently mtoh does motion-blur with two hard-coded samples **t=frame** and **t=frame+1**. We'd like this to be configurable, as these values/ranges are rarely used by our camera's, which are usually centered around the current frame.  Additionally, reliance in the Hydra-projection matrix only for the camera means depth-of-field isn't currently supported.
These changes shouldn't affect Storm or other delegates that only use the Hydra render-pass view matrix.
- Removes **mtohEnableMotionSamples**, in favor of explicit shutter start and end settings. Setting **start=0**, **end=1** with a camera's **shutterAngle=360** is the equivalent of the old hard-coded mode.
- …
> [mtoh] Add camera adapter to support physical camera parameters and configurable motion blur and depth-of-field.

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
After turning on camera-based selection and zooming out far enough
to a USD object, we could only snap to silhouette points. After
zooming in closer, the issue will become better. This is a preexisting
depth priority issue in VP2RenderDelegate so it has nothing to do with
the recent point snapping refactoring inside Maya (MAYA-109518).
> MAYA-110917 Increase depth priority for point snapping items

- plugin/adsk/scripts/AEmayaUsdProxyShapeBaseTemplate.mel
* Special case for Maya 2020 (and below).
> MAYA-110727 - USD load/unload payloads does not update viewport

- plugin/adsk/scripts/mayaUsdMenu.mel
Plugin was creating runtimeCommands on load but not cleaning them up when unloading.  This change cleans those up on unload and also associates the commands with the plugin, which will mean Maya can load the plugin automatically if someone calls one of the commands when it's not yet loaded.
Few things for QA to check with this change:
1. Shut down Maya with the plugin loaded and set to autoload.  On restart the plugin shouldn't need to re-create the commands since they are stored in the pref's.  Just want to confirm that we don't spit out any errors about commands already existing.
2. Shut down Maya with the plugin loaded but NOT set to autoload.  On restart try calling one of the runtime commands, e.g. mayaUsdOpenUsdLayerEditor should load the plugin for you and open the Layer Editor.
3. …
> Clean up runtimeCommands created by the plugin

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.h
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.h
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
The component level is coarse-grain, causing Maya to produce selection hits with undesired selection levels, i.e. face/edge selection hits, as well as vertex selection hits that are required by point snapping. Switch to the new vertex selection level if available in order to produce vertex selection hits only.
> MAYA-110596 MAYA-110576 faster point snapping

- lib/mayaUsd/ufe/UsdTransform3dHandler.cpp
- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
- lib/mayaUsd/ufe/UsdUndoAddNewPrimCommand.cpp
- lib/mayaUsd/ufe/Utils.cpp
- lib/mayaUsd/ufe/Utils.h
- lib/mayaUsd/ufe/wrapUtils.cpp
- test/lib/ufe/CMakeLists.txt
- test/lib/ufe/testBlockedLayerEdit.py
Fixed the problem, also added a function to do this for both muted and locked layers (and possibly user locked layers in the future). Also added the block for adding and attribute changes. This probably doesn't cover all the cases, but its good enough for now.
> MAYA-110727 - Crash when editing Layer That has Permission to Edit false (locked)

- lib/mayaUsd/ufe/UsdContextOps.cpp
- lib/mayaUsd/ufe/UsdContextOps.h
This PR adds the ability to list and create all registered concrete prim types for creation in the UFE > Add Prim menu.
Concrete Prim types are listed dynamically under a `Registered` sub-menu, allowing for listing of new types if they're loaded by USD plugins at a later point.
I currently list them as a flat, sorted list. However I could group them by schema name if that is preferred, however I was unsure which would be more intuitive. I figure that this could be a mvp of the feature, and then could be refined as needed. I also do no filtering outside of listing only concrete types. For example, it may be desirable to filter the AL prim types, but I did not want to prematurely add filtering logic.
The motivation for this PR is that various teams we've spoken to have hit the issue of …
> List all registered Prim Types for Creation

- lib/mayaUsd/nodes/proxyShapeBase.cpp
- lib/mayaUsd/utils/utilFileSystem.cpp
Address issue reported by https://github.com/Autodesk/maya-usd/discussions/1236. FWIW. We are still planning on exploring Ar 2.0 so things may change here.
> Configure resolver to generate resolver context

- lib/usd/translators/shading/usdStandardSurfaceWriter.cpp
- test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
I also added support for testing metallic roundtrip and IOR roundtrip as well.
This addresses https://github.com/Autodesk/maya-usd/issues/1343
> Write correct IOR for metallic shaders

- lib/mayaUsd/fileio/jobs/readJob.cpp
This PR fixes the issue when none packaged usd files (e.g *.usd, *.usda ) fail to import when "USDX Texture import" option is enabled.
Steps to reproduce:
```
- Go to File > Import.
- Select a regular USD file.
- In the import options enable USDZ Texture import.
- Import the file and notice in the script editor is shows the results path line, but nothing comes in.
- Try the import again with the USDZ Texture import option disabled and notice that the file comes in.
```
> MAYA-111329: Fix echouer to import none Usdz ( *.usd, *.usda ) files  when "USDX Texture import" option was enabled.

- doc/build.md
- lib/mayaUsd/fileio/shading/shadingModeUseRegistry.cpp
The API for the Compute*Source functions in usdShade/material is changing. This change will future proof the callsites.
> Use new usdShade/material vector based API for USD versions beyond 21.05

- doc/codingGuidelines.md
- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- lib/mayaUsd/utils/diagnosticDelegate.cpp
- lib/mayaUsd/utils/stageCache.cpp
- test/lib/mayaUsd/utils/testDiagnosticDelegate.py
This PR keeps the TF_ERROR message format consistence with TF_WARN and TF_STATUS by displaying the by only displaying the **commentary** string.
Example below shows the case where an image resource is failed to created which results in a vague message to the user.
Before:
```
// Error: Failed verification: ' image ' -- Coding Error in _LoadTexture at line 422 of S:\jenkins\workspace\ecg-mayausd-full-2022-python3-windows\ecg-maya-usd\maya-usd\lib\mayaUsd\render\vp2RenderDelegate\material.cpp // 
// Error: Failed verification: ' image ' -- Coding Error in _LoadTexture at line 422 of S:\jenkins\workspace\ecg-mayausd-full-2022-python3-windows\ecg-maya-usd\maya-usd\lib\mayaUsd\render\vp2RenderDelegate\material.cpp // 
// Error: Failed verification: ' image ' -- Coding Error in _LoadTexture at …
```
> MAYA-108586: Keep the TF_ERROR message format consistence with TF_WARN and TF_STATUS 

- lib/usd/ui/layerEditor/layerEditorWidget.cpp
* We don't provide icons at 125% so make sure to account for that.
> MAYA-111084 - LE save icon missing when scaling is 125%

- lib/mayaUsd/ufe/UsdHierarchyHandler.cpp
- lib/mayaUsd/ufe/Utils.cpp
- lib/mayaUsd/ufe/Utils.h
Added optional argument to ufePathToPrimIndex to return the prim as well, thereby removing a duplicate call.  Provides a 7% gain in first point move performance in the 70k point instances test scene.
> Removed duplicate ufePathToPrim call.

- lib/mayaUsd/nodes/layerManager.cpp
The stage map we keep that maps between usd stages <-> ufe paths, does not currently remove stage entries when the object is deleted in Maya, even though the path no longer exists.  The stage does still exist in memory, at least until Maya's undo queue is flushed and the reference to the stage is removed, but until that happens the getAllStages function will return stages that will not return to you a valid path when you look it up in the map.
I know this code is currently being refactored a bit, and I believe this function will not longer be used by the layer manager code, so this is a nice easy fix to avoid trying to access an empty ufe path.
> Check for empty paths

- cmake/gulark.cmake
- lib/mayaUsd/utils/utilFileSystem.cpp
This PR fixes the issue with loading usd from mapped drivers.
```
Plugin and external drive or USB Drive to your computer.
Go to Disk Manager.
Right Click on your connected drive.
Select "Change Drive Letter and Path..."
Select "Add".
Use "Mount in the following empty NTFS folder:"
Locate the folder you want to mount to.
Extract the attached folder to that location.
Open Maya and then open the *.ma file that contains usd with relative path
Notice that the USD file doesn't load.
```
Note: Opening the same file if saved on a local drive or a network drive works without issues.
There is a bug in `gulark's filesystem::canonical` which fails to properly resolve relative path. C++17 std::filesystem::canonical doesn't have this issue and properly resolves the relative path. …
> MAYA-105710: fix USD files fail to load on mapped mounted volume.

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.h
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.h
Sync, so when a prim turns invisible make sure all reprs can draw correctly.
> MAYA-111760 Invisibile prims don't get notifications on _PropagateDirtyBits or

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
I didn't do a straight reversion of the change which enabled the new point snapping support in 2021 because I wanted to disable it in betas as well.
> MAYA-110972 Disable the new point snapping support for the time being.

- lib/mayaUsd/ufe/UsdAttributes.cpp
Accessing certain AE tabs (e.g Applied Schema, Cylinder Light ) results in "propName.IsEmpty()" error to spit out by USD. We currently allow creating attributes with an empty strings which are not accepted by USD. This doesn't only happen when accessing "Applied Schema" tabs but also in other attribute tabs "Cylinder Light". 
In USD land At Line 523 ,  the property name can't be empty. Hence the error reported.
https://github.com/PixarAnimationStudios/USD/blob/090ef0d849ced875b3b99a15e454b69148ccd8e1/pxr/usd/usd/stage.cpp#L4523
> MAYA-111521: Fix error messages showing up when opening the "Applied Schema" category

- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
* In Maya 2022.1 we need to hold onto the Ufe SceneItem to make sure it doesn't go stale. This is not needed in latest Maya.
> MAYA-112058 - AE Missing Information on Materials and texture

- lib/mayaUsd/ufe/UsdUndoCreateGroupCommand.cpp
- test/lib/ufe/testGroupCmd.py
This PR fixes the grouping crash and also makes sure that the group node ( a.k.a parent ) is selected which should match Maya's native behavior. 
https://user-images.githubusercontent.com/48299423/120524018-92cea080-c3a4-11eb-8ffa-08e2b3263e03.mp4
> MAYA-111835: Fix grouping a prim twice that crashed Maya.

- lib/mayaUsd/ufe/UsdUndoInsertChildCommand.cpp
- test/lib/ufe/testParentCmd.py
Reverts Autodesk/maya-usd#1449
> Revert "MAYA-112126: make sure parented object is added to selection list after it is moved."

- lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
Python 2 strings are ascii by default, whereas Python 2 strings as are unicode by default. This string had a unicode char (for apostrophe) that I replaced with the ascii one.
> Fix AE template invalid char

- lib/mayaUsd/utils/util.cpp
Hi all:
This small PR fixes an issue where if you have the Draw Overrides option enabled on a DAG node set to template instead of using the one in the Display rollout, the utility function in Maya-USD would report it to be renderable instead of not. This was causing issues for us internally in our own internal chaser plugins when determining visibility state.
> Fixed bug with visibility determination

- plugin/pxr/cmake/macros/Public.cmake
Result:
```
E:\Ws\UsdBuild\MayaUSD\build>ctest -V -R Package
...
163: Environment variables:
163:  TMP=E:/Ws/UsdBuild/MayaUSD/build/test/Temporary/testUsdExportPackage
163:  TEMP=E:/Ws/UsdBuild/MayaUSD/build/test/Temporary/testUsdExportPackage
...
163: Opening layer 'e:/Ws/UsdBuild/MayaUSD/build/test/Temporary/testUsdExportPackage/tmpdugxsng1/tmp-305918D1-45DE-C901-944D-D99D49A7FEB1.usdc' for writing
```
> MAYA-112050 - Pxr tests will use build area for temporary files.

- lib/mayaUsd/commands/Readme.md
- lib/mayaUsd/commands/baseExportCommand.cpp
- lib/mayaUsd/commands/baseExportCommand.h
- lib/mayaUsd/fileio/jobs/jobArgs.cpp
- lib/mayaUsd/fileio/jobs/jobArgs.h
- lib/mayaUsd/fileio/primWriter.cpp
- lib/mayaUsd/fileio/translators/translatorGprim.cpp
- lib/mayaUsd/fileio/translators/translatorGprim.h
- test/lib/usd/translators/testUsdExportMesh.py
This PR adds a new flag to the exporter to override the sidedness of the mesh.
Options are:
* **derived** : Same behaviour as right now where it's taken from the double Sided attribute
*  **single** : All gprims are exported as single sided
* **double** : All gprims are exported as double sided
I've also updated the mesh tests and updated the command documentation.
> Add geomSidedness flag to exporter

- plugin/pxr/maya/lib/usdMaya/referenceAssembly.cpp
Recursing into the inactivate function caused nested assembly nodes to end up in an
unstable state. Reparenting nested nodes prior to deleting works around
this problem.
> Deleting assembly nodes that contained child assemblies crashes Maya

- lib/mayaUsd/utils/utilSerialization.cpp
- lib/usd/ui/layerEditor/layerTreeItem.cpp
- lib/usd/ui/layerEditor/pathChecker.cpp
- lib/usd/ui/layerEditor/pathChecker.h
This replaces custom logic that tried to anchor sublayer
paths to the parent layer using direct calls to ArResolver.
USD uses the Sdf function during composition, so using
it will match USD's behavior. This also allows us to
remove the use of ArResolver API that is deprecated
under Ar 2.0.
> Use SdfComputeAssetPathRelativeToLayer to compute sublayer paths

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- lib/mayaUsd/render/vp2ShaderFragments/UsdUVTexture.xml
- lib/mayaUsd/render/vp2ShaderFragments/shaderFragments.cpp
- lib/mayaUsd/render/vp2ShaderFragments/shaderFragments.h
Maya versions before 2022 had a default color management rendering space of "scene-linear Rec 709/sRGB", which means converting a sRGB texture required only the gamma correction part,
With Maya 2022, we now use the "ACEScg" rendering color space, so an extra multiplication by a color correction matrix is required to move from linrec709 to ACEScg.
This is a user preference, though, and one that is saved with the scene. So we need to query the current rendering space and use the correct color correction.
This is the list of supported rendering color spaces:
- scene-linear Rec 709/sRGB
- ACEScg
- ACES2065-1
- scene-linear DCI-P3 D65
- scene-linear Rec.2020
Note that the VP2 render delegate does not register for notifications when the rendering color space is changed, so if you change the …
> MAYA-112059 - UsdUVTexture works with Maya color management prefs

- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.h
> MAYA-112073 Build a proper index buffer for the default material render item when

- lib/mayaUsd/ufe/CMakeLists.txt
- lib/mayaUsd/ufe/ProxyShapeHierarchy.cpp
- lib/mayaUsd/ufe/ProxyShapeHierarchy.h
- lib/mayaUsd/ufe/UsdHierarchy.cpp
- lib/mayaUsd/ufe/UsdHierarchy.h
- lib/mayaUsd/ufe/UsdUndoUngroupCommand.cpp
- lib/mayaUsd/ufe/UsdUndoUngroupCommand.h
- lib/mayaUsd/ufe/Utils.cpp
- lib/mayaUsd/ufe/Utils.h
- lib/mayaUsd/undo/UsdUndoStateDelegate.cpp
- test/lib/ufe/CMakeLists.txt
- test/lib/ufe/testUngroupCmd.py
This PR adds support for ungroup command.  See ungroup page:
https://download.autodesk.com/us/maya/2009help/Commands/ungroup.html
Known Issues:
- parent flag is not currently implemented. This shouldn't be a blocker since one can use the existing parent command. I will add this flag later if it is really requested. 
- Children are not selected after ungrouping.  **MAYA-112126**
- There is a bug in our selection where hierarchy item created from group item falsely report that children don't exist. See `testUngroupAfterUndoRedo` case in `testUngroup.py`  **MAYA-112510**
> MAYA-111943: Add support for ungroup command.

- lib/mayaUsd/ufe/StagesSubject.cpp
* Handle multiple deferred notifications for a single path (keeping the original notif order).
> MAYA-110878 - handle multiple deferred notifs for single path

- lib/mayaUsd/commands/Readme.md
- lib/mayaUsd/fileio/shading/shadingModeExporterContext.cpp
- lib/mayaUsd/fileio/translators/translatorMaterial.cpp
- lib/mayaUsd/fileio/utils/meshReadUtils.cpp
- lib/mayaUsd/fileio/utils/meshWriteUtils.cpp
- lib/mayaUsd/fileio/utils/readUtil.cpp
- lib/mayaUsd/fileio/utils/readUtil.h
- lib/mayaUsd/fileio/utils/roundTripUtil.cpp
- lib/mayaUsd/fileio/utils/roundTripUtil.h
- lib/mayaUsd/fileio/utils/writeUtil.cpp
- lib/mayaUsd/fileio/utils/writeUtil.h
- lib/mayaUsd/python/wrapReadUtil.cpp
- lib/mayaUsd/python/wrapRoundTripUtil.cpp
- lib/mayaUsd/python/wrapWriteUtil.cpp
- test/lib/usd/translators/CMakeLists.txt
- test/lib/usd/translators/UsdExportUVSetMappingsTest/UsdExportUVSetMappingsTest.ma
- test/lib/usd/translators/testUsdExportMaterialX.py
- test/lib/usd/translators/testUsdExportUVSetMappings.py
- test/lib/usd/translators/testUsdExportUVSets.py
- test/lib/usd/translators/testUsdExportUserTaggedAttributes.py
- test/lib/usd/translators/testUsdImportUVSets.py
Implements automatic UV set renaming.
- The sets will be renamed st, st1, st2, st3,... in the order they are found in the mesh.
- The original name will be stored in custom data for roundtripping
- On import, the names will always be restored if the roundtripping information is found
- On import, the UV sets are restored in the same order as found in the USD primitive
- The environment variables MAYAUSD_IMPORT_PRIMARY_UV_SET_AS_MAP1 and  MAYAUSD_EXPORT_MAP1_AS_PRIMARY_UV_SET were removed as their functionnality is subsumed in the global renaming.
Caveat:
If you have a mesh with multiple UV sets, and a UV set named "map1" is not the first UV set, then it will not automatically be renamed "st" as was previously the case using MAYAUSD_EXPORT_MAP1_AS_PRIMARY_UV_SET. We expect these cases to …
> MAYA-112227 - UV set renamed to st, st1, st2

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
ANY uv primvar reader to fix assertion.
> MAYA-112643 Detect and save a pointer to the cardsUv primvar reader rather than

- lib/mayaUsd/ufe/UsdUndoAddNewPrimCommand.cpp
- lib/mayaUsd/ufe/UsdUndoCreateGroupCommand.cpp
- test/lib/ufe/testGroupCmd.py
> MAYA-112372: Add restriction for grouping.

- lib/mayaUsd/render/vp2RenderDelegate/render_delegate.cpp
Now that support for USD 19.11 has been dropped, and hydra's GL material adapter is gone, this should be safe to restore.
This will allow the display of materials bound using the `preview` purpose.
> Restore preview purpose material binding

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
var for USD versions older then that.
> MAYA-111787 Pixar fixed the render tag issue in v0.20.08 so only enable the env

- lib/usd/translators/shading/mtlxStandardSurfaceWriter.cpp
And always export to MaterialX any attribute with a default value that changed since standard surface was first introduced.
> MAYA-111902 Review all standard surface default values

- lib/mayaUsd/render/vp2RenderDelegate/instancer.cpp
Various clients of UsdGeomPointInstancer were handling per-instance
rotation quaternions differently: some renderers would normalize while
others wouldn't, and extents were generally calculated from normalized
quaternions. In an effort to make this consistent, we now never
normalize these quaternions, relying on the incoming data being normal
instead.
Note: The mechanism of normalization was a bit sneaky: the GfRotation
constructor automatically normalizes quaternions, so by converting from
vec4 to rotation to quat we would normalize; in other situations where
we went straight to GfQuat, we wouldn't normalize.
> Don't normalize point instancer quaternions

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
When you create or modify an `AL_usdmaya_ProxyShape` node such that both:
- The `.filePath` attribute refers to a file that does not exist.
- The `.primPath` attribute has any value.
Maya will instantly hard crash. This request adds a guard against the null pointer when attempting to get the prim at the specified path.
Resolves [1571](https://github.com/Autodesk/maya-usd/issues/1571)
> Check that stage ptr is valid before getting prim path

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
The draw code path for default material in Maya has no idea on how to handle patch curve drawing, so whenever default material is active, these will be drawn as wireframe.
> MAYA-111438 - Show patch curves as wireframe in default material mode

- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.h
… stage
* Replaced TF_AXIOM (which abort when fail) with TF_VERIFY to allow Add{Scale/Translate/Rotate} calls that already exist to return without crashing.
> MAYA-111834 - Crash when transforming multiple objects with duplicate stage

- lib/mayaUsd/render/vp2RenderDelegate/CMakeLists.txt
- lib/mayaUsd/render/vp2RenderDelegate/draw_item.cpp
- lib/mayaUsd/render/vp2RenderDelegate/draw_item.h
- lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.h
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.h
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
- test/lib/ufe/testRotatePivot.py
The changes for MAYA-111889 also require the work done in https://github.com/Autodesk/maya-usd/pull/1502. That work is included in this PR for now. https://github.com/Autodesk/maya-usd/pull/1502 should be merged first, and then this pull request can be re-based on top of the new dev.
This change also requires more Maya API changes, so it can't be merged until that API is available.
> MAYA-111889 point snapping to similar instances

- lib/usd/ui/layerEditor/layerTreeItem.cpp
We had an issue where the root unshared layer could be saved, disabled it, had some code to do that but it wasn't working properly, cleaned it up.
> MAYA-112797 - Disable save for unshared layer root

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
Properly set the texture scale/offset attributes that adjust ST for
UDIM support.
> MAYA-111068 - Handle UDIM in MaterialX shaders

- test/lib/ufe/testUngroupCmd.py
MAYA PR19281 add support for item(s) selection after ungroup.
> MAYA-112732: unit test for item selection after ungroup command is performed.

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.h
Adds an attribute to the proxy shape to delay any costly updates to the maya viewport representation. This allows users or tools to make a series of usd edits efficiently and only pay once for the final result of all the changes.
We use this internally to pause evaluation as our users select variants from the available options and then only display the end result once the stage is fully configured. ( As a result, for now, this PR only pauses updates due to variant switches...)
Would like to make it pause updates due to other usd changes (not too hard) as well as changes in file path or prim path, too, but that is trickier. We'd be curious to know if Autodesk may have other methods for pausing evaluation that we can tap into to solve this problem. Otherwise, please consider the way we've …
> [al] ProxyShape: add pauseUpdate attr to pause evaluation

- lib/mayaUsd/ufe/CMakeLists.txt
- lib/mayaUsd/ufe/StagesSubject.cpp
- lib/mayaUsd/ufe/UsdSetXformOpUndoableCommandBase.cpp
- lib/mayaUsd/ufe/UsdSetXformOpUndoableCommandBase.h
- lib/mayaUsd/ufe/UsdTransform3dCommonAPI.cpp
- lib/mayaUsd/ufe/UsdTransform3dMatrixOp.cpp
- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
- lib/mayaUsd/ufe/UsdUndoableCommand.h
- test/lib/ufe/testMoveCmd.py
- test/lib/ufe/testTransform3dTranslate.py
The goal of this pull request is to bring matrix op and common API Transform3d interfaces to the new UndoManager undo / redo capability.  This will completely remove on undo any attrSpec's and primSpec's added during Transform3d edits.  This capability was already present in Maya transform stacks and Maya fallback transform stacks.
> Matrix op, common API undo / redo.

- lib/mayaUsd/fileio/jobs/jobArgs.cpp
- lib/mayaUsd/fileio/jobs/jobArgs.h
- test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
- test/lib/usd/translators/testUsdImportUSDZTextures.py
- Do not check folders if not importing USDZ textures
- Create sourceImages if no path was given, and there is an active project, and the sourceImage folder is not yet created in that project.
Fixes #1588
> MAYA-112854 - Fix warnings from USDZ texture import

- lib/mayaUsd/ufe/ProxyShapeHierarchy.cpp
- lib/mayaUsd/ufe/ProxyShapeHierarchy.h
- lib/mayaUsd/ufe/UsdHierarchy.cpp
- lib/mayaUsd/ufe/UsdHierarchy.h
- lib/mayaUsd/ufe/UsdUndoCreateGroupCommand.cpp
- lib/mayaUsd/ufe/UsdUndoCreateGroupCommand.h
- test/lib/ufe/testGroupCmd.py
> MAYA-112608: add grouping with absolute, relative, world flags.

- doc/MaterialX.md
- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- Updated MaterialX build how-to.
- Transparency support
- Updated list of topo nodes
> Maya 2022.1 has the Light loop API V2 and is compatible with MaterialX

- .github/run-clang-format.py
- cmake/compiler_config.cmake
- cmake/googletest_download.txt.in
- cmake/googletest_src.txt.in
Fix canonical path for script run-clang-format.py (fix only on Windows and when using Python 3.6 or higher).
- reported file paths reported by Git and paths inclusion had different case making the test fail finding any files.
Fix for forcing the use of old ABI on Linux same as done in Maya so that Maya-usd can be compiled with GCC 9.x or higher without error.
> MAYA-112871 MayaUSD: VS Code setup

- lib/mayaUsd/render/vp2ShaderFragments/shaderFragments.cpp
- test/lib/mayaUsd/render/vp2RenderDelegate/CMakeLists.txt
- The shading for V2 light API is still present and will be fixed shortly. It can be enabled using the MAYAUSD_VP2_ENABLE_V2_LIGHTING_SHADER env var.
Fixes a regression found with production scenes.
> MAYA-113212 - Revert to using shading with the V1 lighting API

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
When render tags change (or on file load) set the task controller render tags to the minimum set of tags rather than all tags. This saves time syncing rprims which are not drawn.
> MAYA-113230 Minor performance improvement for loading scenes into Vp2RenderDelegate

- lib/mayaUsd/render/vp2ShaderFragments/usdPreviewSurfaceLightingAPI2.xml
- Affects only Light API V2 (requires env var to activate)
For environment mapping, we assume symmetric reflection around the normal, which means the half vector H is actually equal to the normal N. The value of dot(E, H) then becomes equal to the value previously found and used for dot(N, E).
This fixes a highlight artifacts seen when looking at the Damaged Helmet asset from below as shown in this before and after image:
> Fixes incorrect Schlick Fresnel for IBL lighting

- lib/mayaUsd/ufe/UsdTransform3dCommonAPI.cpp
- lib/mayaUsd/ufe/UsdTransform3dFallbackMayaXformStack.cpp
- lib/mayaUsd/ufe/UsdTransform3dMatrixOp.cpp
- lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
- lib/mayaUsd/ufe/UsdTransform3dPointInstance.cpp
- test/lib/ufe/testMoveCmd.py
https://github.com/Autodesk/maya-usd/pull/1596
fixed crashing on improperly created scene items for UFE v1.  This pull request does more of the same, for UFE v2 this time.
> Improperly created scene item must not crash move tool.

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
Hydra is changing material tags to be per-drawitem rather than per-rprim
in order to allow meshes to support geom subsets with material bindings
using different material tags. This future-proofs the vp2 render
delegate callsite
> Support for Hydra's new per-draw-item material tag

- lib/mayaUsd/fileio/primReaderRegistry.h
- lib/mayaUsd/fileio/translators/translatorRfMLight.cpp
- lib/usd/translators/lightRfMReader.cpp
- test/lib/usd/translators/UsdImportRfMLightTest/RfMLightsTest.usda
- test/lib/usd/translators/testUsdExportRfMLight.py
Provide means of registering usd readers against usdTypeName to support
codeless schemas, which don't have an associated c++ class/type. Also
update the RfM lights to use ri property namespaces to differentiate
them from core usdLux schema properties.
> Update RfMLight translators to use codeless schemas

- lib/usd/ui/layerEditor/saveLayersDialog.cpp
- lib/usd/ui/layerEditor/stringResources.h
If one or more layers have identical file names, prevent saving and tell the user about the identical names.
> MAYA-113009 prevent saving layers with identical names.

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
sure we only sync rprims whose purpose is displayed when a stage is loaded.
> MAYA-113447 Make sure that any prims whose purpose changed get updated, and make

- lib/usd/translators/shading/usdStandardSurfaceWriter.cpp
- test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
Standard surface should never turn on useSpecularWorkflow. There are no
combinations of attributes on standard surface that can predict when
useSpecularWorkflow should be used.
> MAYA-113442 fix standard surface export

- plugin/adsk/scripts/mayaUSDRegisterStrings.mel
- plugin/adsk/scripts/mayaUsdMenu.mel
* Added new category for "Point Instances" to "USD Selection Mode" menu with options for Point Instances Selection.
> MAYA-112663 - I'd like to select by point instancers, instances and prototypes

- lib/usd/translators/meshWriter.cpp
Got "Unrecognized node" error on blendShape export. The node was the
fCurve driving the weight.
Looked in mayaFindOrigMeshFromBlendShapeTarget() and found out that the
traversal would start on a random plug in the checked branch. Sometimes
the input geom would be found first, sometimes the fCurve would be
traversed as well.
Fixed the code to make sure the traversal starts at the inputGeom plug
that would have been used to compute fnGeoFilter.inputShapeAtIndex(...)
in the ignoreWarning branch.
> MAYA-109415 Fix warning on blendShape export

- lib/mayaUsd/ufe/UsdAttribute.cpp
User (and ours) Python scripts can keep variable holding references to invalid USD attributes. Detect when an invalid USD attribute is accessed and prevent getting and setting its value rather than using invalid pointers and crash.
This was triggered in our own UI code when receiving notifications of attribute value change when two scenes with prim with identical UFE paths were manipulated in successsion in a Python script.
A typical example was a Python script that created a new Maya scene, a new USD stage, and a cone within that stage and setting a value on a property. Re-running the script within the same Maya session would crash.
> MAYA-113559 prevent crash when accessing a stale attribute from Python

- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/Import.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/fileio/import_playback_range.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/CMakeLists.txt
This PR ignores setting the playback range if the stage has no authored time-code.
> Ignored setting playback range if no time code found from USD

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- lib/mayaUsd/ufe/Utils.cpp
Also fix MStringArray not being 100% STL compatible for VS 2019.
> Fix MaterialX code generation

- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorContext.cpp
This PR adds a check for "duplicate" PrimLookups during serialisation of translator context after `postFileLoad`. This change assumes 1:1 mapping of prim path to translator.
> Add duplicate check during translator context deserialise based on prim path match

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.cpp
The `ProxyDrawOverride::userSelect` method can be called when snapping is active. The current implementation will try and update the current selection by building the `AL_usdmaya_ProxyShapeSelect` command, however this will cause a crash when called with the `-cl` flag.
Since we do not want to change the selection while snapping, this fix will bail out early in that scenario.
> Bail on proxyDrawOverride user select early if snapping is active

- plugin/al/lib/AL_USDMaya/AL/usdmaya/Global.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/Global.h
- plugin/al/usdtransaction/AL/usd/transaction/TransactionManager.cpp
- plugin/al/usdtransaction/AL/usd/transaction/TransactionManager.h
- plugin/al/usdtransaction/AL/usd/transaction/tests/testTransaction.py
- plugin/al/usdtransaction/AL/usd/transaction/tests/testTransactionManager.py
- plugin/al/usdtransaction/AL/usd/transaction/wrapTransactionManager.cpp
Makes sure it does not hold stale Python objects on exit.
> Fix python 3.9 AL TransactionManager crash

- lib/mayaUsd/ufe/CMakeLists.txt
- lib/mayaUsd/ufe/Global.cpp
- lib/mayaUsd/ufe/UsdUIUfeObserver.cpp
- lib/mayaUsd/ufe/UsdUIUfeObserver.h
- plugin/adsk/scripts/mayaUsd_pluginUICreation.mel
- test/lib/ufe/testAttribute.py
* Set default USD attribute display filter in Channel Box.
* Created new global UI Ufe Observer which connects to global attribute changes to update Channel Box.
> MAYA-112768 - Channel box for USD prims

- lib/mayaUsd/fileio/translators/translatorLight.cpp
- lib/mayaUsd/fileio/translators/translatorLight.h
- lib/mayaUsd/fileio/translators/translatorRfMLight.cpp
- lib/usd/translators/lightWriter.cpp
- lib/usd/translators/lightWriter.h
- test/lib/usd/translators/testUsdExportRfMLight.py
UsdLuxLight
Starting with release 21.11, a UsdLuxLight will be a USD prim that "has
a" UsdLuxLightAPI as opposed to a prim that "is a" UsdLuxLight.
UsdLuxLight will be deleted in 21.11
> Use the API schema class UsdLuxLightAPI in place of USD typed class

- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/wrapTranslatorBase.cpp
Python translator export never worked properly, but the mismatch between the wrapping and the Python implementation is causing errors that we would like to eliminate as a potential source of problems.
Where no export is supported, `canExport()` and `exportObject()` methods are not expected to be implemented in Python translators - leaving dummy methods which don't return the corret type will cause errors.
If implementing the method but return the incorrect type, you will get a runtime error like this:
```
TF_PYTHON_EXCEPTION: in TfPyConvertPythonExceptionToTfErrors at line 114 of ../pxr/base/lib/tf/pyError.cpp -- Tf Python Exception
TypeError: No registered converter was able to produce a C++ rvalue of type AL::usdmaya::fileio::translators::ExportFlag from this Python object of type bool …
```
> Fill in missing export translator implementation

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/proxy/ProxyShapeMetaData.cpp
Ensure excluded prims (that do not need to be rendered) handled properly so that we don't get double up geo on viewport.
> Fix excluded prim paths

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
This is to avoid duplicated usd stages on Maya scene reopen.
It happens in cases when we have nested proxyShapes, where the children proxyShapes got loaded twice:
- Reopen Maya file, postFileRead callback would be run;
- Root proxyShape starts to load the stage;
- Root proxyShape's outStageData plug would be computed, which will request the children proxysShapes' outStageData being computed as well;
- Children proxyShapes will be requested to load their stages, thus postFileRead callback would be triggered again.
> Avoid opening duplicated usd stages on Maya file load

- plugin/al/lib/AL_USDMaya/AL/usdmaya/PluginRegister.h
- plugin/al/lib/AL_USDMaya/AL/usdmaya/cmds/ProxyShapeCommands.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/cmds/ProxyShapeCommands.h
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.cpp
This PR adds the `AL_usdmaya_TestIntersection` command, which provides the world position of the closest USD prim matching a screen pick. This implementation is for the `ProxyDrawOverride` only. The command has been updated to comply with changes to `Engine::TestIntersectionBatch` introduced in upstream PR https://github.com/Autodesk/maya-usd/pull/1168.
> Added intersection test command for ProxyDrawOverride

- test/lib/ufe/testAttribute.py
In a random situation some of the tests in testAttribute are failing because the class loads the topLayer scene, but some
of the tests do a File|New.
> Fix testAttribute random failure

- plugin/al/lib/AL_USDMaya/AL/usdmaya/cmds/ProxyShapeCommands.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/proxy/ProxyShapeMetaData.cpp
This PR fixes tagged excluded prims not updating correctly when changing metadata values. It also makes sure to rebuild the `UsdImagingDelegate` used within the VP2 render delegate when those prims are modified.
> Fixed tagged excluded prims to update correctly when changed

- lib/mayaUsd/render/vp2ShaderFragments/usdPreviewSurfaceLightingAPI2.xml
The OS/X shader compilator support only literals for const initializers.
> Fix textures missing on OS/X with V2 Lighting

- cmake/test.cmake
Set Frameworks to force the test to take Python from the correct path.
> MAYA-114428 Compile mayapy on Linux and OSX to avoid search path issues.

- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
We can have HAS_DEFAULT_MATERIAL_SUPPORT_API true and HD_API_VERSION < 35 true, and in that case the code doesn't compile correctly.
> Compile MayaUSD correctly when mixing USD 20.05 and Maya 2022.

- test/lib/ufe/CMakeLists.txt
- test/lib/ufe/testSelectionByArray.py
Test passing array of Maya objects, UFE objects or a mix of both to Python `select` command and Mel `select` command.
Verified that the test fail in Maya 2022 and work with the new fix in Maya 2023.
> MAYA-114707 test passing array to Maya commands

- plugin/adsk/scripts/mayaUSDRegisterStrings.mel
- plugin/adsk/scripts/mayaUsd_createStageFromFile.mel
"kCreate" string definition is missing in mayaUSDRegisterStrings.mel file which causes the following runtime error upon click on "Universal Scene Descriptor(USD)" -> "Stage From File" menu item:
// Error: file: C:/Program Files/Autodesk/Maya2022/scripts/others/getPluginResource.mel line 66: Plug-in resource lookup failed, resource ("mayaUsdPlugin","kCreate") is not registered
> Adding definition for "kCreateStage" string constant

- test/lib/usd/translators/testUsdExportCustomConverter.template.py
- test/lib/usd/translators/testUsdImportCustomConverter.template.py
This allows users to run with cwd or relative paths to the cwd
> Use AbsPath for INPUT_PATH env var in converter tests

- lib/mayaUsd/render/mayaToHydra/renderOverride.cpp
- lib/mayaUsd/render/pxrUsdMayaGL/sceneDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/usd/hdMaya/adapters/cameraAdapter.cpp
- lib/usd/hdMaya/adapters/materialNetworkConverter.h
Hydra API continues to change in latest USD dev. This change updates
callsites to allow MayaUSD to work with latest USD.
Use Physical Attributes for HdCamera
Remove deprecated HdCamera dirty bits
Fix wrong member name usage for basisCurves
Prepare for future changes which will remove unneeded headers
> Update callsites to work with USD dev API changes

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
extra dirty bits to get held on some rprims, which causes an actual update later when some reprs ARE selected, and that hurts performance.
> MAYA-113723 If there are no reprs selected then don't call execute! It causes

- lib/mayaUsd/nodes/layerManager.cpp
- lib/mayaUsd/nodes/layerManager.h
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/LayerManager.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/LayerManager.h
- plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_LayerManager.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_TransformMatrix.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/py/testLayerManager.py
- plugin/al/plugin/AL_USDMayaTestPlugin/py/testProxyShape.py
- plugin/al/plugin/AL_USDMayaTestPlugin/py/testTranslators.py
- plugin/al/plugin/AL_USDMayaTestPlugin/py/testUSDMayaPythonModuleOnly.py
This PR allows for the extension to now be retrieved using USD's API instead of string parsing, and adds the layer's file format as a serialisation attribute (along with the current identifier and serialised content).
This is to help deserialisation in the case that the identifier does not resolve without a proper context (which is the case with the layer manager).
> Added file format attribute to LayerManager and improved format detection for serialised layers

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.h
- lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.h
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.h
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
- lib/mayaUsd/render/vp2RenderDelegate/tokens.h
This change also removes the selected repr from proxyRenderDelegate because nothing actually needs it, and adds more Maya profiler events in mesh::Sync.
> When selection changes mark the prims which are added/removed from the list dirty.

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeSelection.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.cpp
This PR locks transform manipulators in the scenario that an instance proxy is allowed through, and adds a helper method for safely obtaining current time code on xform ops.
> Added locking for instance proxy xforms and updated code for time sampled xform ops

- lib/mayaUsd/fileio/translators/translatorCurves.cpp
This fix #1852.
The new deleteNode method (`MStatus MDGModifier::deleteNode( const MObject & node, bool includeParents )`) was added in 2020.3, so we better use API version to check that instead of App version.
Reference:
https://help.autodesk.com/view/MAYAUL/2020/ENU/?guid=__developer_Maya_SDK_MERGED_What_s_New_What_s_Changed_2020_3_Whats_New_in_API_html
> fix #1852 - Maya 2020 picked wrong MDGModifier.deleteNode

- lib/mayaUsd/ufe/Global.cpp
This PR fixes an issue introduced in PR https://github.com/Autodesk/maya-usd/pull/1789, causing the exit callback in `lib/mayaUsd/ufe/Global.cpp` to be run multiple times as it would not get deregistered correctly, producing the following `TF_VERIFY` failure in `lib/mayaUsd/ufe/UsdUIUfeObserver.cpp` throughout tests:
```console
Coding Error: in destroy at line 60 of /fast/the_lot/maya-usd/lib/mayaUsd/ufe/UsdUIUfeObserver.cpp -- Failed verification: ' ufeObserver '
```
> Fixed exiting callback failing to deregister on UFE global

- lib/mayaUsd/render/mayaToHydra/renderOverride.cpp
- lib/mayaUsd/render/mayaToHydra/renderOverride.h
- lib/mayaUsd/render/mayaToHydra/renderOverrideUtils.h
* https://github.com/PixarAnimationStudios/USD/commit/fc63eaef29 removed backing, and restoring of GL_FRAMEBUFFER state.
* At the same time HdxColorizeSelectionTask modifies the frame buffer state
* HdxColorizeSelectionTask is used by the Arnold hydra plugin, unlike maya-usd default hydra plugin.
* Manually backup and restore the state of the frame buffer for now.
> MAYA-114630: Insert backup restore gl state render task around colorize-select-task

- lib/mayaUsd/commands/baseExportCommand.cpp
- lib/mayaUsd/commands/baseImportCommand.cpp
- lib/mayaUsd/fileio/jobs/jobArgs.cpp
- lib/mayaUsd/fileio/jobs/jobArgs.h
- lib/mayaUsd/utils/util.cpp
- plugin/adsk/plugin/exportTranslator.cpp
- plugin/adsk/plugin/importTranslator.cpp
- plugin/adsk/scripts/mayaUSDRegisterStrings.mel
- plugin/adsk/scripts/mayaUsdTranslatorExport.mel
- plugin/adsk/scripts/mayaUsdTranslatorImport.mel
- plugin/pxr/maya/lib/usdMaya/exportTranslator.cpp
- plugin/pxr/maya/lib/usdMaya/importTranslator.cpp
- test/lib/usd/plugin/nullApiExporter.cpp
- test/lib/usd/translators/testUsdExportSchemaApi.py
Add a job context dropdown called "Plug-in Configuration:" in both
import and export dialogs when in USD mode.
This dropdown will be populated with the available job contexts.
Selecting on the the job context will populate the UI with the settings
provided by the job context, and these settings will be made read-only.
> MAYA-114297 MAYA-114300 Job context UI

- lib/mayaUsd/ufe/UsdContextOps.cpp
- test/lib/ufe/testContextOps.py
This PR adds an action to the Outliner's context menu to toggle the instanceable state of a prim. 
Following the design, it provides the options to "Mark as Instanceable" if the prim is not an instance and "Unmark as Instanceable" if the prim is an instance.
> Add action in the outliner's context menu to toggle the instanceable state of a prim

- lib/mayaUsd/ufe/UsdAttribute.cpp
* Adapt to changes made to Ufe::Value class.
> MAYA-114507 - Ufe: Investigate testValue.cpp failure on OSX

- lib/mayaUsd/ufe/ProxyShapeHierarchy.cpp
- lib/mayaUsd/ufe/UsdHierarchy.cpp
- test/lib/ufe/testChildFilter.py
* In default prim predicate remove IsLoaded (so we will always display both loaded and unloaded prims).
> MAYA-113820: [Github 1543] Unloaded prims should appear in the outliner

- lib/mayaUsd/render/vp2RenderDelegate/render_delegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/render_delegate.h
Small change to make sure materials connected to "glslfx:surface" will show up as well as the unqualified "surface" port in viewport 2.0.
This fix makes sure the glslfx ports are also displayed when maya_usd is not built with "materialX" support.
(This matches the Storm implementation used by Usdview)
> [base] fix for proxyShapes in vp2 to display shaders bound to "glslfx:surface" material output

- CMakeLists.txt
- cmake/python.cmake
- cmake/utils.cmake
This PR adds a workaround to compilation issues on Macs where the Python binary included with Maya points to a nonexistent path. See https://github.com/Autodesk/maya-usd/issues/1351 
I'd forgotten to clean up and update our internal workaround, so here it is.
This changes it so the CMake script will try and find Maya earlier in the generation, which then allows the `mayapy` path to be used as the Python interpreter directly.
This also seems to work fine with our Maya 2020 builds as well, so I've only left this behind a platform check and not a version check.
> Use mayapy as Python interpreter on Mac

- test/lib/mayaUsd/nodes/testLayerManagerSerialization.py
As requested by @kxl-adsk in PR https://github.com/Autodesk/maya-usd/pull/1792#discussion_r754490345, I've gone ahead and added a test for the updated `LayerManager` to test multi-format serialisation, similar to the one added [here](https://github.com/AnimalLogic/maya-usd/blob/f485f4b1a43c36d4d8d584d62c0988f2609fafcc/plugin/al/plugin/AL_USDMayaTestPlugin/py/testLayerManager.py#L143).
> Added multi-format serialisation test for shared LayerManager

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/LayerManager.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyShape.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/py/testLayerManager.py
- plugin/al/plugin/AL_USDMayaTestPlugin/test_data/layer1.usda
- plugin/al/plugin/AL_USDMayaTestPlugin/test_data/layer2.usda
- plugin/al/plugin/AL_USDMayaTestPlugin/test_data/multiple_layers.usda
This PR incorporates two changes:
The proxy shape has been updated to make all dirty layers serialisable regardless of whether they have ever been set as an edit target or not when saving Maya scenes. As a result anonymous sublayer content can be serialised.
Loading a scene serialised with anonymous sublayers results in stale references to previous sublayers' IDs. Although they exist in the registry on load, their IDs no longer match those referenced. Support has been added for the serialisation and deserialisation of anonymous sublayers to Maya files by the layer manager.
> Made all dirty layers and anonymous sublayers serialisable

- lib/mayaUsd/utils/converter.cpp
- test/lib/testMayaUsdConverter.py
Addressing issue reported in https://github.com/Autodesk/maya-usd/discussions/1881 discussion.
> Add support for float and double types to the converter (and proxy accessor)

- plugin/al/plugin/AL_USDMayaTestPlugin/py/CMakeLists.txt
- plugin/al/plugin/AL_USDMayaTestPlugin/py/testLayerManager.py
FAIL: test_anonymousLayerSerialisation (testLayerManager.TestLayerManagerSerialisation)
09:37:31     Tests multiple anonymous sublayers can be saved and restored.
09:37:31     ----------------------------------------------------------------------
09:37:31     Traceback (most recent call last):
09:37:31       File "/local/S/jenkins/workspace/ecg-mayausd-branch-preflight-python3-osx/ecg-maya-usd/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/py/testLayerManager.py", line 262, in test_anonymousLayerSerialisation
09:37:31         self.assertIsNotNone(sublayer01)
09:37:31     AssertionError: unexpectedly None
> Test fix for random failing test: TestALUSDMayaPython_LayerManager

- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
Adds DirtyNormals to the initial set of dirty bits.
Vital for USD 21.11 due to USD commit [6c89bf90](https://github.com/PixarAnimationStudios/USD/commit/6c89bf909c42a5a4b32177ca2693a0c349999334).
Works with previous versions.
> Fix exported normals not being used by VP2

- lib/usd/translators/shading/usdFileTextureWriter.cpp
- test/lib/mayaUsd/fileio/testShaderWriter.py
- test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
First item in to fix in Issue #1834
- The UsdUVTexture and UsdTransform2d are no longer nested under the
file node
- Shared place2dTexture nodes result in shared UsdUVTexture
- If a file node does not have a place2DTexture node, then is shares a
common UsdUVTexture
More to follow.
> Unnest UV reader and optimize

- lib/usd/pxrUsdPreviewSurface/usdPreviewSurface.cpp
- lib/usd/pxrUsdPreviewSurface/usdPreviewSurface.h
- lib/usd/pxrUsdPreviewSurface/usdPreviewSurfaceWriter.cpp
- test/lib/usd/translators/testUsdExportUsdPreviewSurface.py
Also check monochromatic inputs.
Connecting a file texture node interactively or by script will
automatically set the color attributes on the file node according to the
destination of the connection.
@dgovil : Added an env var for automatic fixups on load.
Second PR for issue #1834
> MAYA-114979 - Validate normal maps for correctness

- cmake/modules/FindUFE.cmake
* Temporary setting of UFE_PREVIEW_VERSION_NUM while we transition to UFE v3.0.0.
> MAYA-115168 - MayaUSD : Bump UFE version to 3.0

- lib/usd/pxrUsdPreviewSurface/usdPreviewSurface.cpp
- test/lib/usd/translators/testUsdExportUsdPreviewSurface.py
As discussed in https://github.com/Autodesk/maya-usd/pull/1918 , the color space values are only set when the ignoreColorSpaceFileRules is set to false
> Support for ignoreColorSpaceFileRules when setting scalar textures

- lib/mayaUsd/fileio/utils/writeUtil.cpp
- test/lib/usd/translators/testUsdExportAnimation.py
> MAYA-114695 Properly detect animated compound plug

- lib/mayaUsd/fileio/jobs/jobArgs.cpp
- plugin/adsk/plugin/importTranslator.cpp
Especially on a clean set of user prefs. The correct default is *nothing* and this allows properly merging the list of shading modes later at import time if none was specified.
> MAYA-114729 Use correct default for shading mode

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- test/testSamples/instances/billboard.usda
vertex buffers. Fix test so I can run it in debug mode.
This should address the missing normal requirement from #1532.
> MAYA-112624 Add required primvars corresponding to the Maya shader's required

- lib/mayaUsd/fileio/shading/shadingModeExporterContext.cpp
- lib/mayaUsd/fileio/shading/shadingModeUseRegistry.cpp
- lib/mayaUsd/fileio/translators/translatorMaterial.cpp
- lib/mayaUsd/fileio/utils/shadingUtil.cpp
- lib/usd/translators/shading/mtlxFileTextureWriter.cpp
- lib/usd/translators/shading/mtlxPreviewSurfaceWriter.cpp
- lib/usd/translators/shading/mtlxStandardSurfaceWriter.cpp
- lib/usd/translators/shading/shadingTokens.h
- lib/usd/translators/shading/usdFileTextureWriter.cpp
- test/lib/mayaUsd/fileio/UsdImportMaterialX/UsdImportMaterialX.usda
- test/lib/usd/translators/UsdImportMaterialX/UsdImportMaterialX.usda
- test/lib/usd/translators/testUsdExportMaterialX.py
- test/lib/usd/translators/testUsdExportMultiMaterial.py
This fixes #1834 for the last correctness problems mentioned
- Use a separate varnameStr for MaterialX since the type is not compatible with the varname used in UsdPreviewSurface
- Shared place2dTexture nodes are now shared on MaterialX export
- NodeGraph is used instead of Scope to isolate shaders by type in multi-material export
- NodeGraph boundaries are not skipped anymore by shader connections
- Cleaned-up code producing empty NodeGraphs
> MAYA-114979 MAYA-114731 Fix correctness issues

- lib/mayaUsd/render/vp2RenderDelegate/material.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
If 100 materials refer to the same image file, only load it once and ask the MTextureManager for cached copies for the 99 other materials.
Also fixes a crash if a GeomSubset faceId is greater than the number of faces on the mesh.
> MAYA-115091 Use cached textures

- cmake/test.cmake
Set TEMP and TMP environment variables for each tests registered with mayaUsd_add_test.
> MAYA-120860 Fix TestALUSDMayaPython_LayerManager random fails

- lib/usd/translators/shading/mtlxBaseWriter.cpp
- lib/usd/translators/shading/mtlxFileTextureWriter.cpp
- lib/usd/translators/shading/usdFileTextureWriter.cpp
- test/lib/usd/translators/testUsdExportMultiMaterial.py
- test/lib/usd/translators/testUsdExportStripNamespaces.py
Some recent code was not sanitizing the names of auxillary nodes,
causing failures when namespaces are in use.
> Make sure material export sanitizes names

- lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.h
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
This fixes the issue Grace found with https://github.com/Autodesk/maya-usd/issues/1752.
MayaUSD skips updating render items whose repr is not currently in use, instead saving dirty bits about the unused items so that when they are used they can be correctly updating. With the update to USD 21.11 we're not getting a sync call for these rprims which have some dirty reprs. We clean all the dirty bits off the rprim, so it makes sense that USD skips syncing them.
I don't want to leave the rprims dirty, because then we'll have to call sync on them every frame. Instead, when the reprs in use change mark every rprim "dirty" with a flag that will cause sync to be called, but which won't trigger any actual work to occur. This way any dirty reprs get a chance to update themselves.
> MAYA-114247 Mark everything dirty when display modes change.

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
must be updated before that happens.
https://github.com/Autodesk/maya-usd/issues/1955
> MAYA-120891 _UpdateSelectionStates may trigger an execute. The wireframe color

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.h
Description
------------
This PR comes down to some memory corruption within the proxy shape class.
The WANT_UFE_BUILD define might not be correctly defined within projects that use pointers to the ProxyShape node, which can cause memory misalignments (as can additional variables that are added to the Autodesk base class).
We have removed those issues, and have simply exported all ProxyShape methods rather than using the inline methods.
> Export all inline functions from the proxyshape, and remove the WANT_UFE_BUILD conditional compiles from the headers

- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/Export.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/Export.h
- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/ExportParams.h
- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TransformTranslator.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TransformTranslator.h
- plugin/al/plugin/AL_USDMayaTestPlugin/test_translators_TransformTranslator.cpp
This PR fixed tow problems:
- The `worldspace` flag for exporter to only bake xform at the top level prim, children prims xforms would be remained unchanged
- The logic to handle selection objects has also been modified to match `mayaUsdPlugin` that when selecting parent node and one of the children, unselected siblings would be excluded, for example:
```
- parent            * selected
- child_A       * selected
- child_B
```
`child _B` object would be excluded when exporting.
> Fixed worldspace export flag behaviour to only bake xform at the top level prim

- lib/mayaUsd/python/CMakeLists.txt
- lib/mayaUsd/python/module.cpp
- lib/mayaUsd/python/wrapOpUndoItem.cpp
- lib/mayaUsd/undo/OpUndoItemList.cpp
- test/lib/mayaUsd/fileio/testDiscardEdits.py
- test/lib/mayaUsd/fileio/testDuplicateAs.py
- test/lib/mayaUsd/fileio/testEditAsMaya.py
- test/lib/mayaUsd/fileio/testMergeToUsd.py
- test/lib/mayaUsd/fileio/testPrimUpdater.py
When using the direct python API to edit-as-Maya and merge-to-USD, the calls have to be wrapped in a OpUndoItemList block to capture the undo info, otherwise it will linger on. This is not a problem, except when Maya exit, the order of cleanup makes Maya assert that some deleted nodes are still present.
Fix the tests by using a block.
Also do a best effort to clean up the undo information that may have been left behind due to not using a OpUndoInfoList block in Python. On scene reset the undo info is cleared, although currently the assertions are hit before the scene-reset callback is triggered, so we still get assertions.
> MAYA-114898 fix unit test assertions related to pull/push

- lib/usd/utils/CMakeLists.txt
- lib/usd/utils/MergePrims.cpp
- test/lib/mayaUsd/fileio/testMergeToUsd.py
- test/testUtils/mayaUtils.py
Compare the full local transform when deciding to merge transform-related properties to avoid authoring transforms when they did not change but their representation changed.
Get the union of all time codes of all transform properties and compre the value at all time codes.
Add a unit test. Confirmed that the test fails when the new code is disabled.
> MAYA-114995 avoid merging equivalent transforms.

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- plugin/adsk/scripts/USDMenuProc.mel
- test/lib/mayaUsd/fileio/testDuplicateAs.py
- Add code to make target of the copy have a unique name.
- Add a unit test that failed without the fix and now works.
> MAYA-115074 Ensure duplicate-as-USD creates unique prim names.

- lib/mayaUsd/resources/scripts/mayaUsdAddMayaReference.mel
- lib/mayaUsd/resources/scripts/mayaUsdAddMayaReference.py
- lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.mel
- test/lib/mayaUsd/fileio/testAddMayaReference.py
* Set Maya Reference Prim Name to initial (unique) value.
* Sanitize and make unique the Maya Reference Prim Name after user enters something.
> MAYA-115053: Name the MayaReference prim/transform node on creation

- lib/usd/utils/MergePrims.cpp
- lib/usd/utils/MergePrimsOptions.cpp
- lib/usd/utils/MergePrimsOptions.h
- test/lib/mayaUsd/fileio/testMergeToUsd.py
- Correctly detect that metadata is not present at all in the source or destination of comparison.
- Add merge option for handling missing data for property metadata and prim metadata.
- They both default to preserve missing and create newly added.
- Added code for metadata we know we always want to preserve.
- Added a unit test. It fails without the fix, passes with the fix.
> MAYA-121208 fix references metadata lost

- lib/mayaUsd/resources/scripts/mayaUsdAddMayaReference.mel
* Make the "Use namespaces" always true.
> MAYA-120831: Always use Namespaces when creating a Maya Reference

- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TransformTranslator.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/test_translators_TransformTranslator.cpp
Updated `TransformTranslator` to only export rotation order if the transform's `rotateOrder` attribute is not default (`0`).
> Only export transform rotate order if not default

- lib/mayaUsd/render/vp2RenderDelegate/CMakeLists.txt
- lib/mayaUsd/render/vp2RenderDelegate/extComputation.cpp
- lib/mayaUsd/render/vp2RenderDelegate/extComputation.h
- lib/mayaUsd/render/vp2RenderDelegate/render_delegate.cpp
inputs are computed serially from sprim sync instead of in parallel in rprim sync.
> MAYA-106930 Pre-evaluate all the compute inputs so that any lazy-evaluated shared

- lib/mayaUsd/fileio/utils/meshWriteUtils.cpp
- lib/usd/utils/MergePrims.cpp
- lib/usd/utils/MergePrimsOptions.cpp
- lib/usd/utils/MergePrimsOptions.h
Maya did not write the USD "orientation" attribute. In addition, Maya flipped the vertices order when editing a USD mesh with "leftHanded" orientation. On merge-to-USD, Maya would write right-handed vertices but not write the "orientation" property.
The result would be righ-handed verticeswith left-handed orientation attribute.
See: MAYA-105623 for the original reason we flip vertices orders. It has to do with the way "leftHanded" affect vertices order and normals in USD.
The fix is to explicitly write the "orientation" attribute on export.
A few improvements in the verbosity options and simplification of some code were also made whilte investigating the problem and are included.
> MAYA-121242 fix flipped normals.

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
some string operations, and waiting for them all to finish is adding significant overhead.
This helps with issue #1991 but it does not fix the whole problem.
> MAYA-121225 reating the events from the commit task is too slow. The events do

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- plugin/adsk/scripts/mayaUsdMenu.mel
Renamed set containing pulled objects.
Improved handling of the context menu for items under the set (it has a special logic when creating the menu)
Added traversal to allow merging and discarding changes on the entire hierarchy.
> Improve edit as maya context menu

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
Leverage render index to check for validity. This prevents ugly warnings like `// Error: Failed verification: ' it != _rprimState.end() ' – /Proxy_Kitchen_setShape_000001C81675F860/Kitchen_set/Props_grp/DiningTable_grp/ChairB_2.proto_polySurface32_id6`
> Don't dirty invalid paths

- lib/mayaUsd/commands/PullPushCommands.cpp
- lib/mayaUsd/fileio/primUpdaterManager.cpp
Properly undo semi-successful edit-as-Maya command and other related commands. Also provide helpful error messages when a command fails mid-way.
> MAYA-121245 fix failed edit-as-maya commands

- lib/mayaUsd/resources/scripts/mayaUsdAddMayaReference.mel
- lib/mayaUsd/resources/scripts/mayaUsdAddMayaReference.py
- lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
- lib/mayaUsd/ufe/Utils.cpp
- test/lib/mayaUsd/fileio/testAddMayaReference.py
* Implement the "Group" section with optionMenu's for the type and kind and optionVar's (to remember values) for checkbox/type/kind.
* Update the variant preview field with group prim name (including logic when name field is empty).
* Added error checking for DefinePrim.
* Added documentation for createMayaReferencePrim() function and input group params for creating a group prim.
* Fixed adding MayaReference directly under the ProxyShape.
* Enhanced testAddMayaReference with error cases and separate test functions for each feature.
> MAYA-115056: Group my Maya Reference on creation

- lib/mayaUsd/fileio/schemaApiAdaptor.cpp
- lib/mayaUsd/fileio/utils/readUtil.cpp
- lib/mayaUsd/python/CMakeLists.txt
- lib/mayaUsd/python/module.cpp
- lib/mayaUsd/python/wrapAdaptor.cpp
- lib/mayaUsd/python/wrapPrimReader.cpp
- lib/mayaUsd/python/wrapPrimWriter.cpp
- lib/mayaUsd/python/wrapReadUtil.cpp
- lib/mayaUsd/python/wrapSchemaApiAdaptor.cpp
- lib/mayaUsd/python/wrapSparseValueWriter.cpp
- lib/mayaUsd/python/wrapSparseValueWriter.h
- lib/mayaUsd/python/wrapWriteUtil.cpp
- test/lib/mayaUsd/fileio/testExportChaser.py
- test/lib/mayaUsd/fileio/testSchemaApiAdaptor.py
- test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
- test/lib/usd/translators/testUsdExportMaterialX.py
Goal was to reach unit test parity with C++. The Python wrappers can now implement the full Bullet simulation unit test originally implemented as a C++ USD plugin.
> MAYA-114335 - Extended Python schema API wrappers

- plugin/adsk/scripts/CMakeLists.txt
- plugin/adsk/scripts/USDMenuProc.mel
- plugin/adsk/scripts/mayaUsd_selectionUtils.py
Use the entire selection instead of the item under the mouse when right-clicking in the viewport to edit-as-Maya or duplicate-as-Maya.
> MAYA-121247 edit-as-maya whole selected object - not sub-part

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- lib/mayaUsd/ufe/ProxyShapeHierarchy.cpp
- lib/mayaUsd/ufe/ProxyShapeHierarchy.h
- test/lib/mayaUsd/fileio/testMergeToUsd.py
Exclude prim is way too expensive for complex scenes since it repopulates the entire render index. We decided to switch to deactivation which reduces the cost to what changed.
> MAYA-115117 Deactivate prim on pull instead of using exclude feature

- lib/mayaUsd/python/wrapOpUndoItem.cpp
- lib/mayaUsd/python/wrapPrimUpdaterManager.cpp
- Add undo/redo to Python binding of OpUndoItemList.
- Add user args options to mergeToUsd and duplicate Python bindings.
> MAYA-114898 Improve Python bindings

- lib/mayaUsd/fileio/translators/translatorMayaReference.cpp
- lib/mayaUsd/fileio/translators/translatorMayaReference.h
- test/lib/usd/translators/UsdImportMayaReferenceTest/MayaReference.usda
- test/lib/usd/translators/testUsdImportMayaReference.py
As explained in issue #640, the MayaReference prim is incompatible with a multi-proxy workflow where the proxy and a MayaReference in the proxy's stage (eg, a rig) share the same namespace.
Add support for a `mergeNamespacesOnClash` boolean attribute on a MayaReference prim that controls the same flag on the Maya `file` MEL command.
- Added a test case to `testUsdImportMayaReference`
- Tested in Maya under a mayaUsdProxyShape node(1). 
----
(1) Note that AutoPull was disabled for the MayaReference schema on 13/12/2021 by PPT - this behavior must be re-enabled to test the behavior under a mayaUsdProxyShape node.
> Support mergeNamespacesOnClash attribute on MayaReference prim

- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
This helps with the selection / de-selection performance issue mentioned in https://github.com/Autodesk/maya-usd/issues/1991. This change doesn't fully fix that issue.
> MAYA-121316 Skip updating MRenderItem's that we're not going to draw anyway.

- lib/mayaUsd/python/CMakeLists.txt
- lib/mayaUsd/python/pythonObjectRegistry.cpp
- lib/mayaUsd/python/pythonObjectRegistry.h
- lib/mayaUsd/python/wrapExportChaser.cpp
- lib/mayaUsd/python/wrapImportChaser.cpp
- lib/mayaUsd/python/wrapPrimReader.cpp
- lib/mayaUsd/python/wrapPrimUpdater.cpp
- lib/mayaUsd/python/wrapPrimWriter.cpp
- lib/mayaUsd/python/wrapSchemaApiAdaptor.cpp
Allow updating class registrations while actively implementing prim reader/writer/updaters and all other
class-based MayaUSD Python workflows.
> MAYA-113541 Allow updating registered Python class

- lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
- lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
Get up-to-date selection color settings from Maya. This includes 'lead' color as well as curve and surface active colors.
> MAYA-106075 - USD selection highlighting doesn't take Color Settings into consideration

- lib/mayaUsd/fileio/utils/meshWriteUtils.cpp
Don't explicitly write mesh orientation attributes if they are set to
the default value (rightHanded)
> Write Sparsely when exporting mesh orientation

- lib/mayaUsd/fileio/primUpdaterManager.cpp
- plugin/adsk/scripts/mayaUsdMenu.mel
Also moved the re-activation of the edited prim before the merge in case deactivated prim would cause problems. (I'm frankly surprised it works when it was deactivated... it thought USD would ignore it.)
> MAYA-114898 fix merge UI option defaults.

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Transform.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Transform.h
- plugin/al/lib/AL_USDMaya/CMakeLists.txt
- plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/fileio/export_misc.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/test_DiffPrimVar.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/CMakeLists.txt
- plugin/al/plugin/AL_USDMayaTestPlugin/test_translators_MeshTranslator.cpp
- plugin/al/schemas/AL/usd/schemas/maya/CMakeLists.txt
- plugin/al/schemas/AL/usd/schemas/mayatest/CMakeLists.txt
- plugin/al/translators/CommonTranslatorOptions.cpp
- plugin/al/translators/CommonTranslatorOptions.h
- plugin/al/translators/Mesh.cpp
- plugin/al/usdmayautils/AL/usdmaya/utils/DiffPrimVar.cpp
- plugin/al/usdmayautils/AL/usdmaya/utils/MeshUtils.cpp
- plugin/al/usdmayautils/AL/usdmaya/utils/MeshUtils.h
- plugin/al/usdtransaction/CMakeLists.txt
Here are another batch of changes in AL's plugin.
The changes made around normals were aimed at restoring some coherence between the type of mesh (poly vs subdiv) and normals handling. Prior to this there was zero coupling between the which means that exporting subdiv with custom normals was perfectly valid.
> Medley of normals and a few other fixes

- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
- lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
Introducing color cache to improve performance of ProxyRenderDelegate::GetSelectionHighlightColor and ProxyRenderDelegate::GetCurveDefaultColor.
Make sure the cache is accessed from inside the mutex to prevent races.
> MAYA106075 - Introducing color cache to improve performance

- lib/mayaUsd/fileio/doc/Managing_export_options_via_JobContext_in_Python.md
- lib/mayaUsd/fileio/doc/SchemaAPI_Import_Export_in_Python.md
- test/lib/mayaUsd/fileio/testSchemaApiAdaptor.py
Also includes Job Context registration documentation.
> MAYA-114268 - Schema adaptor documentation

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/BasicTransformationMatrix.h
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.h
- plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_TransformMatrix.cpp
The PR changed the rotation comparison to use quaternion instead of raw value (rx, ry, rz) in Euler space.
In USD, rotation ops, "xformOp:rotateXYZ" etc. are in Euler space, we had an issue in production that the rotation was twisted but in fact they should be treated as the same, e.g. `(180, -2.3171844, 180) == (0, 182.31718, 0)`, thus converting to quaternion for comparison.
> [al] Use quaternion form to compare rotation angles

- lib/mayaUsd/resources/scripts/CMakeLists.txt
- lib/mayaUsd/resources/scripts/cacheToUsd.py
- lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
- test/lib/mayaUsd/fileio/CMakeLists.txt
- test/lib/mayaUsd/fileio/testAddMayaReference.py
- test/lib/mayaUsd/fileio/testCacheToUsd.py
- test/testUtils/mayaUtils.py
- test/testUtils/ufeUtils.py
Cache to USD unit test.  Only testing sibling prim with payload for now.  No discard edits test yet.
> Initial cache to USD test.

- lib/mayaUsd/fileio/translators/translatorMayaReference.cpp
- test/lib/mayaUsd/fileio/CMakeLists.txt
- test/lib/mayaUsd/fileio/testAddMayaReference.py
- test/lib/mayaUsd/fileio/testSchemaApiAdaptor.py
- test/lib/usd/translators/CMakeLists.txt
- test/lib/usd/translators/testUsdExportSchemaApi.py
* Code + test fixes for Usd compiled with AssetResolver v2.
* Minor test fixes when missing Pixar plugin.
> MAYA-115079: USD: MayaUsd test failures with USD built with AssetResolver 2

- lib/mayaUsd/listeners/notice.cpp
- lib/mayaUsd/listeners/notice.h
- lib/mayaUsd/undo/OpUndoItemList.cpp
- plugin/adsk/plugin/plugin.cpp
- plugin/al/lib/AL_USDMaya/AL/usdmaya/Global.cpp
- plugin/pxr/maya/plugin/pxrUsd/plugin.cpp
- test/lib/mayaUsd/fileio/testCustomRig.py
- Use an OpUndoItemList to capture the undo items of mergeToUsd in the test.
- Add a new notice sent before scene change, including Maya exit.
- Clear the recorded global undo items that were not picked up by any command on exit.
> MAYA-121514 fix leaking node due to undo items being left behind.

- plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/wrapTranslatorBase.cpp
- plugin/al/plugin/AL_USDMayaTestPlugin/py/testTranslators.py
Maya was spitting out `RecursionError`s when enabling or disabling certain Python translated objects. It was also noted that similar `RecursionError`s would be generated from a handful of other operations concerning the Python translators. It was later identified that the error would only occur in Python 3.
It was found that the fallback method (to be called in the event no Python override existed for it) was not properly wired up in such a way that it would short the method and still technically function correctly under Python 2:
```cpp
std::size_t generateUniqueKey(const UsdPrim& prim) const override
{
if (Override o = GetOverride("generateUniqueKey")) {
auto res = std::function<boost::python::object(const UsdPrim&)>(
TfPyCall<boost::python::object>(o))(prim);
if (!res) {
return 0;
} …
```
> Fixed recursive calls to bound Python translators under Python 3

- plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
During some updates to the proxy shape I noticed `pathsToNuke` wasn't doing anything so I removed it and cleaned up the method. Tests are all green.
> Removed redundant code in proxy shape transform validation
